### ISSUE TITLE
Resource Type subclasses

### ISSUE THREAD

**Issue by bhaugen** [valueflows/valueflows#10]
As discussed in issue #8, Lynn and I have not subclassed Resource and Resource Type in our existing NRP software because we are using a relational database and the available subclassing options are all ugly.

However, openvocab/ovn does not have the same constraints, and subclassing is an easy option.

In that other issue, we also discussed subclasses of Resource and Resource Type that have very different behaviors, such as money, human labor and energy.

So what subclasses of Resource Type would be useful? And would they also require subclassing Resource, or would Resources be handled sufficiently by subclassing Resource Types?

[@elf-pavlik](https://github.com/elf-pavlik) had a bunch of ideas about subclassing money. I have some ideas about subclassing human labor. I also have some ideas about subclassing stuff like tools.

This issue is focused on discussing all of those questions.

**Comment by ahdinosaur** [comment]
closing in favor of https://github.com/valueflows/resource/issues/4.
