### ISSUE TITLE
update labels to names

### ISSUE THREAD

**Issue by ahdinosaur** [valueflows/valueflows#101]
from https://github.com/valueflows/agent/pull/57#discussion_r48389285,

i propose we:
- rename `vf:label` (based on `skos:prefLabel`) to `vf:name` (as in [Activity Streams](http://www.w3.org/TR/activitystreams-vocabulary/#dfn-name) and [schema.org](http://schema.org/name))
- create `vf:alternateName` (as in [schema.org](http://schema.org/alternateName)) based on `skos:altLabel`

**Comment by fosterlynn** [comment]
I like it!  I'll start changing it in the various doc, but probably tomorrow.

**Comment by fosterlynn** [comment]
P.S. I have a hard time thinking about all nodes right now, but seems like it probably will work.

**Comment by gcassel** [comment]
Looks like a great idea!
