### ISSUE TITLE
Subclasses and renaming

### ISSUE THREAD

**Issue by bhaugen** [valueflows/valueflows#11]
I'm thinking about renaming Commitment to Plan (which might communicate better with more people) and subclassing for inputs and outputs as in the diagram on the ovn homepage, so for example:
![o vn_subclasses](https://cloud.githubusercontent.com/assets/117439/5780720/659572d8-9d72-11e4-9411-dac7755a912b.png)

Same for Events, we'd have:
- EconomicEvent
  - InputEvent
  - OuputEvent

I think those subclasses will align better with (for example) IPOTables.

Opinions?

Then we will still need to subclass for different input and output behaviors, e.g. consume, use, cite, etc.

This is related to #8 and #10 and [visual language](https://docs.google.com/presentation/d/1N81Q0uDjA7OMEZTLNig6O-MLuWHgb5TL0IxPZ2U8qDU/edit?usp=sharing).

**Comment by ahdinosaur** [comment]
:+1:
