### ISSUE TITLE
Versioning systems for informational resources 

### ISSUE THREAD

**Issue by gcassel** [valueflows/valueflows#112]
I did a quick repo search and couldn't find anything relevant, so I'm making a quick Issue.

I'm interested in the potential value of versioning systems to value flows accounting for the *collaborative development* and (when applicable) the *use rights* for any type of informational resource.  

For example, it could theoretically be relevant to specify that someone contributed code to App X version 1.11.03  instead of simply specifying that they contributed code to App X.   I doubt that that info would typically be used in calculations (such as determining compensation), but it'd be really good IMO for the info to be available for future reference.   (And in theory,  the info could be automatically mined from a codebase in version control, such as on github.)

My overall interest in version control is more personal: i.e., I'd like clear version control for all collaborative creative projects.    

With that in mind:  Semantic Versioning 2.0.0 http://semver.org/  is rigorous.   Any opinions?
@elf-pavlik this may be particularly up your alley?   I'd appreciate any feedback!

**Comment by ahdinosaur** [comment]
++ [semver ftw](https://web.archive.org/web/20160304140715/http://semver-ftw.org/)

**Comment by elf-pavlik** [comment]
relevant
* https://www.w3.org/2011/rdf-wg/wiki/Graph_Terminology
* https://tools.ietf.org/html/rfc7089
 * https://github.com/LinkedDataFragments/Server.js/wiki/Configuring-Memento

**Comment by elf-pavlik** [comment]
> My overall interest in version control is more personal: i.e., I'd like clear version control for all collaborative creative projects.

somehow relevant
* https://www.w3.org/2011/rdf-wg/wiki/Graph_Terminology#Visual_Diagram
* http://mementoweb.org/about/
 * https://github.com/LinkedDataFragments/Server.js/wiki/Configuring-Memento
