### ISSUE TITLE
Currencies, especially MonetaryCurrencies

### ISSUE THREAD

**Issue by elf-pavlik** [valueflows/valueflows#117]
I would like to propose a dedicated repository `valueflows/currency` where we would give currencies special treatment. In issue [MonetaryCurrency a 'transfer only' resource](https://github.com/valueflows/resource/issues/12) I pointed our various peculiarities of monetary currencies.

Also in our distinction between actual resource and rights to that resource. Monetary currencies seem more of a rights to a resource, often without any clear 'underlying resource'. We will also need to deal with 'vf:Transportation' of monetary currencies. Possibly defining 'connectors' to legacy interfaces like bank transfers (I would ask friends from https://openbankproject.com/ for feedback). We also may need to [deal with 'cash payments'](https://github.com/valueflows/exchange/issues/14#issuecomment-217152732).

I find cash payments very tricky, since we use paper bills (often with tracking number specific for particular [ISO 4217](https://en.wikipedia.org/wiki/ISO_4217) code). But those bills don't act as actual resource but more as analogue proofs of right to that virtual/digital resource (monetary currency).

Projects like IPO Tables most likely will not want to deal with all the mess around currencies. I would prefer to keep `valueflows/resource` focused on 'Products & Services` and avoid blurring it with many discussions about modelling all kinds of modern and archaic monetary currencies.

Also `valueflows/exchange` shouldn't deal with defining the 'underlying resource' when we need to describe vf:Transfer of ownership for some monetary currency.

Last but not least, while we should incorporate use of monetary currencies, the whole system MUST NOT depend on their presence and allow handling all economic interactions without use of them.

**Comment by elf-pavlik** [comment]
Regarding paper bills (cash), AFAIK if one brings partially destroyed bills to the bank, they should replace them with bills in better shape. In such operation one not change resource or ownership, only gets new analogue proof of that ownership.

I believe we will find many more nuances in a process or trying to position monetary currencies as a resource or rights to a resource. Timebanks also will come interesting, especially that @bhaugen discourages rights to human services, which I can understand.

**Comment by bhaugen** [comment]
I'm good with a currency repo. Let's please avoid arguments about everybody's theories about what money is etc. and stick to observable behaviors of currencies.

**Comment by elf-pavlik** [comment]
Sure, I'll make mentioned replacement of damage bills a use case to drive with other use cases modelling of cash.

**Comment by bhaugen** [comment]
Will the replacement of damaged bills that anybody would ever want to record ever appear in a real life economic network use case? And do you also want to document the toilet use case?

If you think these use cases will teach us something useful, that's ok, but when we get into wiping your butt use cases I think we might have gone overboard...and I think replacing damaged bills is pretty close to the overboard mark.

**Comment by elf-pavlik** [comment]
> If you think these use cases will teach us something useful, that's ok

I think we need to stay very careful with considering cash a physical resource. Paper bills in most cases can fit same inputs as newspaper if we focus on their physical properties. They mostly act as legal proof, similar like paper contracts when someone buys a car or a house. For coins, I often drilled a hole in them and used it as a [washer](https://en.wikipedia.org/wiki/Washer_%28hardware%29). Of course people often use them in other way in legal context.

**Comment by bhaugen** [comment]
It totally works to have an economic event with a resource type and a quantity + unit but no resource. That is what I would do with cash money.

We do this all the time. We do not instantiate work as a resource, for example. And lots of resources, like nuts and bolts, are not worth inventorying.

**Comment by elf-pavlik** [comment]
I have impression that what you call *'no resource'* I call [indirectly identified resource](https://github.com/valueflows/resource/issues/13)

If you have 'no resource' than what has attributes: *(resource) type*, *unit*, *quantity*, sometimes *location*. I see it as a resource but without `@id` / IRI, we can't directly identify it so we use indirect identification.

**Comment by bhaugen** [comment]
Could be. Ok with me, I think, until some testing...

**Comment by ahdinosaur** [comment]
> I would like to propose a dedicated repository valueflows/currency where we would give currencies special treatment.

:-1: i don't think currency deserves a special treatment from other resources, nor would i find adding another repository help when we have a dedicated repository for all resources. currency is already a topic of strong opinions, i would prefer to not put currency on a pedestal and instead treat it as a resource with everything else.

the peculiarities mentioned are also not unique to currencies. as Bob mentioned, being able to consider a currency resource type as being "swappable" is also true of nuts and bolts. being able to exchange damaged bills could be described as a standing commitment to exchange some physical currency resources for other physical currency resources, i feel it's almost like a warranty program by the state.

**Comment by elf-pavlik** [comment]
I `valueflows/currency` to my personal github space. I'll continue working on that topic over there for now. Everyone can join it there or work on currencies in other repositories which you find fit to host such workstreams.
