### ISSUE TITLE
relating Intent to a Process, and to other resources via its inputs/outputs

### ISSUE THREAD

**Issue by elf-pavlik** [valueflows/valueflows#118]
In https://github.com/valueflows/intent/pull/3 I already mentioned that 
- requested resource may go as input into a process
- offered resource may come as output from a process

I see utility of creating such relations **fundamental** for conscious decision making. For example:
- I have 2 tons of steel available, which I attach to an offer
- I get match with 2 requests
  - First one declaring requested resource as input into a process which outputs weapons
  - Second one declaring requested resource as input into a process which outputs farming tools

Without a context of what requesting agent plans to do with requested resource, I might unintentionally contribute to production of weapons. I want to have possibility to practice _conscious contribution_ (requirement)

Example 2:
- I publish a request for a pair of shorts
- I get match with two offers, both declare offered resource as output from a process with input of human labour
  - First one has that work used as input marked by many people as _child slavery_
  - Second one has that work used as input marked by many people as _fair_

Without a context of from which process offering agent created that resource, I might unintentionally create demand for child slavery.  I want to have possibility to practice _conscious consumption_ (requirement)

**Comment by fosterlynn** [comment]
@elf-pavlik this is very interesting, and also triggered a thought for me related to some of our transfer discussion.  Intents (offers and requests) are desires for transfers I think.  

> requested resource may go as input into a process
> offered resource may come as output from a process

This is exactly where I was trying to go with thinking of transfers as facilitating coordination and setting the conditions for a resource to continue on its flow.  But hadn't related it to intents.

**Comment by elf-pavlik** [comment]
> Intents (offers and requests) are desires for transfers I think

makes sense, I'll add it to **relationships** section of Intent.md

> This is exactly where I was trying to go with thinking of transfers as facilitating coordination and setting the conditions for a resource to continue on its flow. But hadn't related it to intents.

I see indeed relevance to https://github.com/valueflows/exchange/issues/17 . In case of intents we also deal with existing as well as planned resources (https://github.com/valueflows/resource/issues/14). Especially requested resources can only become inputs to planned resources and yield planned resources. Also offered resources don't always exist, sometimes process which outputs them starts after making commitments on offers.

When it comes to Services (https://github.com/valueflows/resource/issues/15) Intents always have planned services attached.

**Comment by ahdinosaur** [comment]
> Intents (offers and requests) are desires for transfers I think. 

yep, this is why i've been thinking about Intents in the same way as Commitments and Observations (Economic Events), they all reference Actions (Transfers, Transformations, Transportations). seems to work in my own conceptual model so far, but really need to test it more.

usually it seems Intents have a bunch of open variables, as in i might want a transfer with me giving some coffee to another agent in exchange for a reciprocal transfer with another agent receiving some money, the other agent is an open variable but as said up above maybe i want to filter them to only agents who are known to be "fair".

**Comment by bhaugen** [comment]
There is another intent, which is a proposal for a process: to do something together.

**Comment by fosterlynn** [comment]
Maybe we need a 4 layer picture, with Recipe, Intent, Plan/Commitment, Observations/Reality?  Well, I was wanting to work on pictures, will do so in the next week or so, hopefully....

**Comment by gcassel** [comment]
This is super interesting and (literally) deeply important.  

Intent is a transitional phase IMO between goals/ objectives/ desires and Plan/Commitment.  An Intent may iterate and become more specific before a Plan/Commitment emerges from it.  

Intent certainly may or may not have anything to do with an existing Recipe.  Both Intent and Plan may emerge from described Offers and Wants, *or* from brand new conversations. 

Really, I think that Intent is transitional phase (or more accurately, element/agent) in a Conversation, and especially in a Conversation for Agreement.  Conversation for Agreement is not *part of* the potentially bidirectional or circular flow of Recipe/ Plan/ Observation.     Conversation for Agreement can touch any existing structure or process at any point   It's parallel or, dare I say, "meta".   It's con-text.   

I love the term Signal... well, we can send Signals any time to describe our Observations,  and we can also send Signals when we want to talk about our experiences or ideas, including potential changes to our Recipes and Plans.  

Maybe personal Signals are generally either Observations **or** Conversation?   BTW, IMO, Observations/Reports are always declarative, although they may derive from exclamatory statements.   Interrogative and imperative statements have no valid place *within* Observations, but are frequently part of Conversation.

Anyway, now I'm thinking of Conversation as operating entirely in parallel to almost everything else we discuss in VF.   Conversation for Agreement is personally key for me, regardless.

**Comment by elf-pavlik** [comment]
Actually intents should always relate agent with particular input or output of a process. Resources flow between processes (IPO) and intents model the will of agents for influencing that flow. I can also cast intent "Someone please give a laptop to this organization (as input to one of it's processes)", it doesn't always need to deal with "someone give something to me or i give something to someone". Once again, in practice resources don't flow between agents but between processes. Agents influence that flow and have various relationships with those resources and processes. Relevant to [Transfer of agent-resource-relationship](https://github.com/valueflows/exchange/issues/29)

**Comment by fosterlynn** [comment]
>Anyway, now I'm thinking of Conversation as operating entirely in parallel to almost everything else we discuss in VF. 

@gcassel this makes a lot of sense to me.  (Sorry, just came back upon this thread.)

**Comment by elf-pavlik** [comment]
I see many advantages in modeling intents around IPO and not exclusively focusing on transfer of ownership between agents. It relates to [Exchange definitions oriented towards coordination](https://github.com/valueflows/exchange/issues/17) and [open intent and intent specific to audience (even single agent)](https://github.com/valueflows/intent/issues/9) (even single planed process, not agent in this case).

When many different agents, cast *vf:Request* to provide needed input to the same planned process. Those who can match that request with *vf:Offer* can suggest an exchange based on aggregation of all offers from agents who support particular process. Similar situation to [agent can benefit from keeping intended Transactions not coupled into intended Exchanges](https://github.com/valueflows/intent/issues/5) . The offer can even propose [Exchange chains / Network (Multi-Party) barter](https://github.com/valueflows/exchange/issues/19). For material resources and currency resources, all the agents could transfer all the requested resources to 'context agent' of a process, which in turn could could do 1-on-1 exchange. But for services (including work) we still don't have clear way to transfer them to someone beforehand, and even more to someone who will not receive the service in the end. Example:

* Community Learning Center needs construction services (work) for repair process of meetings hall, they already have all the material resources and tools allocated
* All the supporters cast intent referencing 'planed service resource' needed for that input
* All the supporters also have various *vf:Offer* requests public, they don't specify particular exchange but just intent of proving some resource (including work/service)
* People who can offer their construction work/service respond to those intents with proposals for exchanges. e.g.
  * Sam offers 10h of construction work if Julie provides him 2h of percussion class, Daniel 1h of shiatsu massage and Bruce 3h of mentoring in JavaScript
   * Lucy offers 6h of constrution work if Daniel provides her 1h of shiatsu massage and Irena 2h of electric guitar class
  * etc.

Making intents utility to relate agents (who have other intents) to resources needed in particular processes, provides interesting potential for coordination based economy and not just ownership based focus.

**Comment by elf-pavlik** [comment]
currently Offer | Request != Intent but Intent represents Input | Output on Plan layer

![copy of process-oriented flow](https://cloud.githubusercontent.com/assets/876431/23593171/e18bdbc4-01d0-11e7-9f74-baf04fc94a09.png)

**Comment by bhaugen** [comment]
> currently Offer | Request != Intent but Intent represents Input | Output on Plan layer

I think that deviates from common usage of Intent, where Intents include Offers, Requests and sometimes Proposals.

**Comment by elf-pavlik** [comment]
If we look at this diagram, just Plan & Observation, should we use more specific
* IoIntent
* IoCommitment
* IoEvent

or `vf:` prefix will work just fine? if we ever get to stuck on picking english words for terms we can always just take Wikidata approach with opaque identifiers - https://www.wikidata.org/wiki/Wikidata:List_of_properties

the precise meaning (semantic) matters and english names mostly for developers which will write code which implements VF. people who use that software will use labels in many languages, and often domain specific terminology.

**Comment by fosterlynn** [comment]
I think EconomicIntent, EconomicCommitment, and EconomicEvent would help more conceptually.

And I don't know how to think about vf: doing the trick, I still feel like it could get lost in the syntax, but don't have enough experience in LOD to know.  Event in particular seems problematic.

**Comment by bhaugen** [comment]
> the precise meaning (semantic) matters and english names mostly for developers which will write code which implements VF. people who use that software will use labels in many languages, and often domain specific terminology.

While it is true that developers will rename everything, I disagree that the names in the vocabulary do not matter. For the developers, the semantics matter too, or they will screw them up. We've already had people complaining they can't understand what we are talking about.

And when we are talking Linked Open Data, we are talking about data that will live on the Web, where people can "follow their nose", as you like to say, and often the vocabulary names will be exposed: that's what LOD browsers will see.

I think we will see LOD vocabs used raw, on the Web, unmediated by other software. I can always be wrong about any prediction, but the importance of the names for developer understanding will remain important.

**Comment by fosterlynn** [comment]
>While it is true that developers will rename everything, I disagree that the names in the vocabulary do not matter. For the developers, the semantics matter too, or they will screw them up. We've already had people complaining they can't understand what we are talking about.

That makes sense actually.  That happened with when we changed type/whatever to template, then when someone needed a template, they tried to make what started as a type/whatever into a template, which was different.  And led to a bunch of confusion.

**Comment by djodjoni** [comment]
> While it is true that developers will rename everything, I disagree that the names in the vocabulary do not matter. For the developers, the semantics matter too, or they will screw them up. We've already had people complaining they can't understand what we are talking about.

I cannot agree more with that I had experience in this as well and the way you explain your specs/domain does matter a lot how the code will be written. this is why I love so much DDD and BDD as this helps move in that direction a lot.

**Comment by fosterlynn** [comment]
Resolved for v.3, please re-open if needed.
