### ISSUE TITLE
IRI's

### ISSUE THREAD

**Issue by fosterlynn** [valueflows/valueflows#126]
@elf-pavlik provided this link: https://tools.ietf.org/html/rfc3987. 

My understanding from a skim of the spec: IRI's were created to expand URI's to be international by expanding the character set.  There is an algorithm to create a URI from an IRI.  A URI can be considered an IRI.

So, seems to me we should use IRI for all our current and future references to URI's.  What do you all think?  Especially Pavlik.

**Comment by elf-pavlik** [comment]
> A URI can be considered an IRI.

:+1:

[RDF 1.1 Primer](https://www.w3.org/TR/rdf11-primer/) and other RDF 1.1 specs use IRI and I think it slowly starts replacing URI term in other specs.

**Comment by fosterlynn** [comment]
@elf-pavlik do you know offhand if there is a vocab that defines it and people tend to use, so we can just use it from there?

**Comment by elf-pavlik** [comment]
We should add statement about https://en.wikipedia.org/wiki/HTTPRange-14 and recommend using # fragments.

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/valueflows/-/issues/126.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
