### ISSUE TITLE
Transfer works with Currency (The Map) while Process with Resource (The Territory)

### ISSUE THREAD

**Issue by elf-pavlik** [valueflows/valueflows#128]
After many long chats with @fosterlynn and @bhaugen and looking at Processes, Transfers, Intents and Resources, Agents involved in all of them, I think I start seeing possibly elegant approach to how we can model it

Piggybacking on terms used in already mentioned https://github.com/valueflows/valueflows/pull/115#issuecomment-217550404 **"The map is not the territory"** we can distinguish.
## The map
- Transfer
- Currency
- conceptual/logical/legal/agreement (perceptions)
## The territory
- Process
- Resource
- physical/analogue (matter) or virtual/digital (data)

Currencies correspond in various ways to Resources, some examples:

| Currency | Resource |
| --- | --- |
| 100% ownership of particular device, model Fairphone2 ([as discussed yesterday](https://gitter.im/valueflows?at=573a56a3e2996a5a42c8f0b6) | the physical Fairphone2 device |
| Ticket (vf:Claim) for a play in theatre | Inclusion in audience of that play |
| Gift Card (vf:Claim) for a 1h shiatsu massage | The health care service - actual 1h shiatsu massage |
| ownership/allocation for 20L of natural gas in a grid | 20L of gas used in daily [Porridge preparation](https://github.com/valueflows/valueflows/blob/master/use-cases/porridge-preparation.md) |
| ownership/allocation for 2week usage of a flat | staying in that flat for 2 weeks |
| agreement to use a particular car on one particular day | using that car on that day |

I will work on drawing such distinction for each of the [use cases](https://github.com/rdfjs/representation-task-force/wiki/Use-Cases). I recall @bhaugen that he can consider rights to resources themselves as resources. I find calling them Currency a useful distinction which keeps clear separation between the map and the territory. We also [discussed yesterday](https://gitter.im/valueflows?at=573a504664dbdadc7deca231) that one can vf:Transfer a vf:Claim which seems to support that approach.

[The Treachery of Images](https://en.wikipedia.org/wiki/The_Treachery_of_Images) "This is not a pipe"
![not a pipe](https://upload.wikimedia.org/wikipedia/en/b/b9/MagrittePipe.jpg)

**Comment by bhaugen** [comment]
@elf-pavlik sorry,  I have not had headspace and time to digest this fully. This is a placeholder comment; more to come.

I think the currency ~= rights analog has a lot of possibilities. Tickets are similar to currencies, for example. 

The map-territory analogy works partially for me. Mental interference comes in when I think of vf:Process, which is map, vs real-life process, which is territory. I.e. VF vocab concepts are all map, pointing we hope to territories.

**Comment by elf-pavlik** [comment]
> The map-territory analogy works partially for me. Mental interference comes in when I think of vf:Process, which is map, vs real-life process, which is territory. I.e. VF vocab concepts are all map, pointing we hope to territories.

Sure, all the data we generate makes a map. But than we have a map the territory and map of the map. Please read it in this way
* Currency - map of the map
* Resource - map of the territory

**Comment by bhaugen** [comment]
Uh-oh: a metamap...
