### ISSUE TITLE
use case: retrospective review of purchase

### ISSUE THREAD

**Issue by ahdinosaur** [valueflows/valueflows#129]
from https://github.com/valueflows/valueflows/pull/115#discussion_r63798449:

on any buy / sell website ever (eBay, TradeMe, AliExpress, etc), after you've received the order you receive a message telling you to give a review to the person you purchased from regarding the order. in some websites (TradeMe) it happens at the same time as signifying that you've received the order, in other websites (AliExpress) it's done separately at a later time.

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/valueflows/-/issues/129.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
