### ISSUE TITLE
Sensorica example about reciprocal responsibilities

### ISSUE THREAD

**Issue by bhaugen** [valueflows/valueflows#136]
We've talking about reciprocity and the combinations of rights and responsibilities a lot in VF. Here's a very clear example.
https://groups.google.com/forum/?hl=en?hl%3Den#!topic/Sensorica/h6XBWVyCkZM

**Comment by elf-pavlik** [comment]
> You must be a member of this group to view and participate in it. Membership is by invitation only.

> This group is invite only, so you may not apply for membership.

**Comment by bhaugen** [comment]
Ah, too bad. I'll copy some highlights when the discussion settles down.

**Comment by elf-pavlik** [comment]
@bhaugen I think we should close this issue in next days unless you have some more details you would like to provide.

**Comment by bhaugen** [comment]
@elf-pavlik I'll close the issue, but here's a bit more from that Sensorica thread. The thread itself went in many directions and dealt with many issues, but this is the one I had in mind:
> We've had this discussion before, about not raising the bar to what is expected from Sensoricans. My argument was why not enforce a minimum amount of time and monetary contribution for use of the lab. The rebutle was that this might limit newcomers and lower participation. I don't think this "bait and switch" tactic is sustainable, nor does it foster a sense of community building, where everyone joins in and contributes to the general upkeep of the lab.

> As an open environment, I believe it needs stricter abidance to rules than anything else, as these rules of engagement and infrastructure are all we have that define us as a community.
