### ISSUE TITLE
VF vocab terms gathered into one place

### ISSUE THREAD

**Issue by fosterlynn** [valueflows/valueflows#145]
I'm starting this issue to have a place to gather the status of VF terms into one place, at this point in the evolution of our work, as an aid to @serapath and others, who can easily become confused by our plentitude of discussion!  I'm going to take off from #142, which is morphing this direction, and make this more generic than that use case.

I'll start with a list of concepts / terms next post (although maybe not today).  I wasn't going to include relationships to start with, such as is happening starting [here](https://github.com/valueflows/valueflows/issues/142#issuecomment-231514311).  But if people want to include those, we certainly can.

**Comment by serapath** [comment]
:+1:

**Comment by fosterlynn** [comment]
OK here goes the first draft, wish me luck. :)  VF old-timers, please feel free to make corrections, I'm going to do this a lot from memory rather than combing the multitude of discussions.  I'll try to use vf: when either we have decided, or we have sort of informally settled on usage of a term.  In the latter case, the concept is probably valid but the term could change.  Otherwise I'll try to indicate other sources and ideas.

* vf:Agent (foaf:Agent, rea:EconomicAgent)
 *  vf:Person (foaf:Person)
 *  vf:Group (foaf:Group)
* vf:Relationship (between agents, also like as:Relationship)
* vf:relationship 
 * (there are and will be lots of defined relationship properties, such as member, child, mentor, etc., and groups will be able to define their own)
* vf:Resource (rea:EconomicResource)
 * vf:MaterialResource
 * vf:WorkResource
 * vf:ServiceResource
 * vf:CurrencyResource
* rea:ResourceType
 * (this will be any taxonomy of types of resources, and there are many, from industry standards to individual group lists to generic resource descriptions like prodont:)
 * (we have had several names to reference this, no conclusions as of now)
* vf:Location (we want to use another standard for Location, but need something to reference)
* vf:Action (vf:EconomicInteraction, some other suggestions)
 * vf:Process
    * vf:Transformation
    * vf:Transportation
 * vf:Transfer
* vf: Exchange
* rea:EconomicEvent (vf:Flow or vf:Action or ??)
* nrp:EventType (may be handled as properties? and may be more than this?)
 * vf:consume (related to process)
 * vf:use (related to process)
 * vf:cite (related to process)
 * vf:produce (related to process)
 * vf:work (usually related to process, but can happen anywhere)
 * rea:give (related to transfer)
 * nrp:receive (related to transfer; is rea:take but we changed the name)
 * vf:load (related to transportation)
 * vf:unload (related to transportation)
 * vf:accept (related to workflow type process)
 * vf:improve (related to workflow type process)
* rea:Commitment (plan, commitment, ??)
* vf:Intent
  * vf:Offer
  * vf:Want (need, request, desire)
  * vf:Proposal (to do something, as opposed to offer and want for goods or services)

*TODO
I did not include agreements or contracts or conversations for agreement/action yet, since we have not talked much about them until very recently, and others have more experience there.  I expect between @serapath and @stevebosserman and @gcassel and others, there will be more use cases and discussion on this.

**Comment by serapath** [comment]
Thx, that helps. I think I will need some time to restructure/rethink our current approach in refugeeswork a bit and formalize how we do things and how we want to do things and then draw inspiration from your vocabulary :-)
Guess it might take some more days until i can contribute.
The part which is most unclear to me is how the **conversation** part connects into the **process/transfer** network chains from **recipes**

* The latter is usually thought as something that follows a strict and well defined flow.
* The former is spontaneously on-the-fly woven and might lead to custom one-time-used solutions.
 
...not even sure how to express it, but to connect those "two worlds" in well defined ways is where i see the most trouble and it feels it's connected to contracts and breaking down vision and brainstorming into one-time-projects/actions and then maybe into repeated ongoing business processes that are executed over and over again until changed...   ¯\_(ツ)_/¯

**Comment by bhaugen** [comment]
> The part which is most unclear to me is how the conversation part connects into the process/transfer network chains from recipes

See [exchange protocols](https://github.com/valueflows/exchange#exchange-protocols) for some ideas on formal methods. I can give you more to read about those, too, if you get interested. Both the ISO and the CfA approaches have been documented profusely and implemented many times. 

However, in real life, people can conduct meandering conversations via many unstructured methods and then come to some kind of agreement on what to do via any means necessary. The only thing really necessary for a VF economic interaction is to record the economic events. The commitments are nice, too, though...

**Comment by fosterlynn** [comment]
this is getting out of date, superceded by 0.1 doc
