### ISSUE TITLE
Core vf model

### ISSUE THREAD

**Issue by fosterlynn** [valueflows/valueflows#147]
This is to help us converge on a "final" core model for vf.  I think we have worked out most of the core issues (probably not all - will post one on processes and agents).  Note that a lot of the names are very much up in the air, so nobody should take offense at my names, trying to represent how it works in the core model.  This issue can help resolve names as well as see if we are close on the core model.

Will post pictures.....

**Comment by fosterlynn** [comment]
First picture, an attempt at a UML diagram.  It is right now a bit mixed on object vs data focus, and possibly confusing, I'm thinking....  In any case, it is meant to be something that can be implemented for a VF vocabulary that could be but is not necessarily LOD based.  So, there are elements that won't necessarily be in the LOD version.
![core-observation](https://cloud.githubusercontent.com/assets/3776081/17638597/c2a60ffc-60b0-11e6-9743-8a4e28c7de8e.png)

**Comment by fosterlynn** [comment]
OK, another version of the UML above, but focused on relational persistent data structures.  Resolved arrow directions vs names, I think, although now I have names that probably won't appear in LOD land.
![core-observation-erd](https://cloud.githubusercontent.com/assets/3776081/17638812/6e77ee3a-60b2-11e6-9fb6-42668905bf43.png)

**Comment by fosterlynn** [comment]
And a version more focused on the OO perspective:
![core-observation-oo](https://cloud.githubusercontent.com/assets/3776081/17639110/e29d3b92-60b4-11e6-95f4-7a4611caae83.png)

OK, enough of that fun.... next a VOWL picture (gulp!).

**Comment by elf-pavlik** [comment]
Thank you @fosterlynn !

Can you imagine making PR to `valueflows/process` which explains in .md file implications of *vf:context* relationship? I also see that both *vf:Process* and *vf:EconomicEvent* can relate to *foaf:Agent* via *vf:context*, example of events having different 'context agent' than the process could help with clarifying it.

**Comment by fosterlynn** [comment]
>example of events having different 'context agent' than the process could help with clarifying it.

That is more because events (although process-type events) do not always have a process.  I don't think events would have a different context agent than the process.

**Comment by fosterlynn** [comment]
Done - to valueflows repo since it covers more than process.  Diagram next.

**Comment by elf-pavlik** [comment]
*vf:EconomicEvent* recommends use of property *vf:eventQuantity*, it seems to me that we talk more about *vf:resourceQuantity*. The event references that resource (I would say stock) and does some action on certain quantity of that resource(stock). If we have for example `'vf:action': vf:consume` we can think of it "This event consumed a quantity of that resource(stock)"

**Comment by bhaugen** [comment]
@elf-pavlik:
> it seems to me that we talk more about vf:resourceQuantity

I certainly don't talk that way. It's an event, not a resource. The event may affect a resource, but it is not a resource, and there is no resource that is living on the event.

Moreover, how would that deal with events which are not measured in a quantity that could be interpreted as a quantity of a resource: citations, for example, where the event quantity is a percentage of the value of the other inputs to the process?

**Comment by fosterlynn** [comment]
Actually in rea, the event is primary in general - it's the movement, the flow, it's what's happening economically.  You can derive the resource from event history if you want, at any point in time.

**Comment by elf-pavlik** [comment]
> Moreover, how would that deal with events which are not measured in a quantity that could be interpreted as a quantity of a resource: citations, for example, where the event quantity is a percentage of the value of the other inputs to the process?

Why in NRP you only allow 'cite' inputs to have '% share of the output' assigned but not 'consume' or 'work' and other input events? I consider mentioned use of 'quantity' as 'data model smell', possibly result of inflexibility of relational databases. IMO such 'cite' event *or any other input event* should use dedicated property for such 'value equation' purposes e.g *nrp:shareOfOutputResource*.

**Comment by bhaugen** [comment]
> Why in NRP you only allow cite inputs to have '% share of the output' assigned but not consume or work and other input events?

That's the only case where anybody has wanted anything like that. Citations and the percentage option arose from a long discussion between us, Sensorica, and Enspiral about how to treat intellectual resources. The exemplar was academic citations. The percentage idea came from Enspiral.

Consume, work and other input events already get a percentage of the income distributed to that process based on their natural quantities. Citations do not have a natural quantity. So the options for valuing them include both percentage of the value of the other inputs as well as a direct quantity of the unit of value of the value equation, which in Sensorica is always money, but does not need to be logically in NRP or VF.

> I consider mentioned use of 'quantity' as 'data model smell', possibly result of inflexibility of relational databases.

That could very well be.

**Comment by fosterlynn** [comment]
Closing, we have specific issues for anything left in this one.
