### ISSUE TITLE
Agents in relation to process events

### ISSUE THREAD

**Issue by fosterlynn** [valueflows/valueflows#148]
We have a general question on if agents should have a place in processes, or do they just relate to transfers, i.e. which agent has which role (rights and responsibilities) in relation to a resource.  From a gitter chat, too hard to find it now. :disappointed:   But I think this is maybe the biggest conceptual hurdle left in the core model after our marathon discussions.....??

I think there is a lot of agency involved in processes, and several kinds of process related events require one or possibly two agents to have complete information.  For example work, load, unload. 

@elf-pavlik please add your thoughts or objections to this, I don't think I can do it justice and don't want to mis-represent.

**Comment by bhaugen** [comment]
Unless you got some robotic agents, your process will need some human agents.

**Comment by elf-pavlik** [comment]
> I think there is a lot of agency involved in processes, and several kinds of process related events require one or possibly two agents to have complete information. For example work, load, unload. 

If we model work as *vf:ServiceResource*, than we can reference agent as provider (owner doesn't seem to fit services well). For scheduled services (possibly modeled as [planned resources](https://github.com/valueflows/resource/issues/14#issuecomment-239677311)) we also need provider and recipient information.

If we want to capture the actual work of loading and unloading... again we have work which we can represent as *vf:ServiceResource* which in turn also can reference *load* and *unload* events (we would need to define property for it, but we will also need something like that for referencing *load* and *unload* from the transportation service - output of transportation process)

Maybe for each YAML snippet where you reference agent directly from a process event I will try to write alternative where we have a resource with a relationship to an agent? If you paste couple of links to existing YAML from other issues I could give it a try.

**Comment by fosterlynn** [comment]
>If we want to capture the actual work of loading and unloading... again we have work which we can represent as vf:ServiceResource

I was thinking more about this too. I think you are right about load and unload - creation of value all comes down to work in the end.  It also takes work to create a service (and sometimes other inputs too).  

Load and unload provider, carrier, receiver might be just context agents?  Would need to do some examples to be sure, because different viewpoints might impact this, I'm not sure.  Context agents have agency too, but I think you are .

Then again some people might not want to record work, but only record what was created/produced.  Could be a service or a material item.

>If we model work as vf:ServiceResource

I'd like to understand better why you don't like vf:work?  Seems to me to clearly and directly describe what is actually happening.  Which is what I think rea:EconomicEvents should do.

I think if some people would rather log their work as a service, that's fine too.  That would be for situations where they think their actual work is not anyone's business (can be valid), or people are working very independently, or isn't useful to log for whatever reason.

But vf:work events can also be used in collaborative situations to coordinate the work among several people in a process, make it clear what everyone is doing so others can see it. That transparency is a useful part of an open collective process.  As a more edge example, in Sensorica, they have also used work events to log results and thoughts while doing R&D, keeping running scientific lab notes so everyone can see results as they go along, see what has been tried already, etc.

**Comment by elf-pavlik** [comment]
@fosterlynn in https://github.com/valueflows/process/issues/21#issuecomment-238099929 you wrote (I copied only the *vf:work* input)
 
>
```yaml
'@context': https://w3id.org/valueflows/v1
'@id': https://fablab.example/818f30f4-c119#process
'@type': vf:Transformation
'skos:note': making a 3d printed part
'vf:contextAgent': https://fablab.example/OhioFabLab#agent
'vf:io':
- '@id': '#input-4'
    '@type': vf:ResourceEvent
    'vf:action': vf:work
    'vf:eventDate': 2016-08-10
    'vf:resource':  '@id': https://fablab.example/3d-printing#typeOfWork
    'vf:fromAgent': '@id': https://fablab.example/FredFlintstone#agent
    'vf:eventQuantity':
        '@type': qudt:QuantityValue
        'qudt:unit': unit:Hours
        'qudt:numericValue': 2.5
```

We could rewrite that work event as 

```yaml
'vf:io':
- '@id': '#input-4'
    '@type': vf:ResourceEvent
    'vf:action': vf:input
    'vf:resource':  
      '@id': https://fablab.example/3d-printing-by-fred-on-aug-10#work
      '@type': vf:WorkResource
      'vf:model': https://fablab.example/3d-printing#typeOfWork
      'vf:location': https://fablab.example/main-hall#place
      'vf:provider':
        '@id': https://fablab.example/FredFlintstone#agent
        '@type': vf:Person
      'vf:date': 2016-08-10
      'vf:quantity': 
        '@type': qudt:QuantityValue
        'qudt:unit': unit:Hours
        'qudt:numericValue': 2.5
```

We would need a way to capture that 'one person working for 2.5 hours' vs. 'n persons working for 2.5 hour' If for example we would have *vf:WorkResource* sub class of *vf:ServiceResource* which implies just one person working. Now when we cast an intent, we can create planned service and reference input of a process which we want to use (following [relating Intent to a Process, and to other resources via its inputs/outputs](https://github.com/valueflows/valueflows/issues/118)

```yaml
'@context': https://w3id.org/valueflows/v1
'@id': https://fablab.example/818f30f4-c119#process
'@type': vf:Transformation
'skos:note': making a 3d printed part
'vf:contextAgent': https://fablab.example/OhioFabLab#agent
'vf:io':
- '@id': '#input-4'
    '@type': vf:ResourceEvent
    'vf:action': vf:input
    'vf:resource':  
      '@id': https://fablab.example/3d-printing-on-aug-10#work
      '@type': vf:WorkResource
      'vf:model': https://fablab.example/3d-printing#typeOfWork
      'vf:location': https://fablab.example/main-hall#place
      'vf:date': 2016-08-10
      'vf:quantity': 
        '@type': qudt:QuantityValue
        'qudt:unit': unit:Hours
        'qudt:numericValue': 0
      'vf:expectedQuantity': 
        '@type': qudt:QuantityValue
        'qudt:unit': unit:Hours
        'qudt:numericValue': 0
```

Having above, we could reference that particular instance of planned *vf:WorkResource* from *vf:Request*.

```yaml
'@context': https://w3id.org/valueflows/v1
'@id': https://fablab.example/intent-2342#request
'@type': vf:Request
'@id': https://fablab.example/3d-printing-on-aug-10#work
```

I find it **fundamental** for making conscious decisions that intents have requested resource placed in IPO chain. I consider nowadays practice of 'what i can in return for my work' much inferior to approach 'what impact my contribution will make, and how i can benefit from doing that work'.

@fosterlynn how do you imagine casting an intent for work contribution to particular process which has particular planned output (very likely already 'earmarked' as input to another process in IPO chain)

**Comment by bhaugen** [comment]
Some examples of process work that do not involve loading or unloading:
* carpentry and other kinds of woodwork
* metalworking
* turning pots on a wheel
* working dough in many ways: kneading, forming loaves, toppings, fills, etc.
* cleaning
* medical and other kinds of diagnosis
* repair work

I am sure several hundred others exist.

**Comment by bhaugen** [comment]
>  I consider nowadays practice of 'what i can in return for my work' much inferior to approach 'what impact my contribution will make, and how i can benefit from doing that work'.

Would be good to develop that thought more precisely.

However, as I have explained a few times in VF issues, reciprocity, however indirect, will be required to keep communal mutual coordination for-benefit economies alive. Including your ability to continue to work.

**Comment by fosterlynn** [comment]
>I find it fundamental for making conscious decisions that intents have requested resource placed in IPO chain.

Thinking about work resources - 

If there is a vf:Resource, I see the resource not as the vf:Agent, but more as the labor power of the person.  So maybe the "Pavlik can work max 21 hours per week" is a resource.  Of course the agent has as much control over his/her work resource as possible - not much in slavery, more but not enough in capitalism, hopefully more in the future.  (Although I do agree with @bhaugen that a community can't function without some notions of reciprocity.)

The event consumes some of that resource.

If people do calendar scheduling or need max time for planning, then the resource is useful.  On a calendar, not sure of the granularity people would need for a vf:Resource, but in any case it would always be some time period.  Or I could see that if you need to schedule a particular person but don't do calendar related scheduling, there could be a non-time-specific vf:Resource of a person's labor power.  Otherwise there really isn't a vf:Resource yet, just a vf:model I think.  And an event could reference the vf:model and the person doing the work as a vf:Resource.  Not a proposal yet, but trying it out, and moving it back to the event structure we agreed on for other types of events:

```yaml
'vf:io':
- '@id': '#input-4'
    '@type': vf:ResourceEvent
    'vf:action': vf:work
    'vf:resource':  
      '@id': https://fablab.example/3d-printing-by-fred-on-aug-10#work
      '@type': vf:WorkResource
      'vf:model': https://fablab.example/3d-printing#typeOfWork
      'vf:provider': 
        '@id': https://fablab.example/FredFlintstone#agent
        '@type': vf:Person
    'vf:location': https://fablab.example/main-hall#place
    'vf:date': 2016-08-10
    'vf:quantity': 
        '@type': qudt:QuantityValue
        'qudt:unit': unit:Hours
        'qudt:numericValue': 2.5
```

I do think we need to know an event type of work, as it has specific behavior.

>@fosterlynn how do you imagine casting an intent for work contribution to particular planned process which has particular planned output (very likely already 'earmarked' as input to another process in IPO chain)

Do you mean how does a person commit to doing some work already scheduled?  Or how does a person request some work or service from another person?

>I consider nowadays common practice of basing our choices on thinking: 'what i can get in return for my work' much inferior to approach of making choice based on reflection: 'what impact my contribution will make, and how i can benefit from doing that work'.

I completely agree.  I don't see how the vf:work approach is not that.  It is all about a person contributing to a process or a context, in its most direct representation.  If the person gets something in exchange for the work, OK.  A service also can be generated directly to create an exchange at the same time it provides something useful, in fact we have had to do that in other use cases.  Or we can think of them as work being direct contribution to creating something and service being something which is useful to a process but buries its internals either in a previous process of creating the service or as something not useful to log, more as the results of the work than the work itself.

**Comment by bhaugen** [comment]
The [Quick Response Engine](https://en.wikipedia.org/wiki/Quick_Response_Engine) (QRE)  was a skunkworks project for an ERP software company I worked for in the 1990's, and was also my first implementation of the set of ideas that fed into VF.  

We did shift scheduling for people and equipment in that project. The inventory of such time-based resources was a shift calendar composed of 15-minute slots. It was implemented as sparse array composed only of slots where the resource was scheduled to be available: for a person, the shifts they were scheduled to work. Each time-based resource had a shift calendar. A process could reserve as many of these 15-minute slots as it needed, assuming they were not already taken by some other process.

**Comment by fosterlynn** [comment]
Wondering if vf:UsageResource should become vf:TimeBasedResource?  Could handle equipment and space, plus work....

**Comment by fosterlynn** [comment]
oops, putting the above comment in the new timeline based stocks issue.....

**Comment by elf-pavlik** [comment]
another example of *vf:WorkResource* in https://github.com/valueflows/process/issues/22

**Comment by elf-pavlik** [comment]
how do you model in NRP a person making commitment to planned work input of planned process? how does it relate to that planned work input before someone committed to it?

**Comment by bhaugen** [comment]
> how do you model in NRP a person making commitment to planned work input of planned process? how does it relate to that planned work input before someone committed to it?

The planned work input before someone committed to it is a work requirement for the process. It appears in on the process and on the My Work pages of people whose skills it fits with a description and a button that says "Take this task". Once somebody takes it, it goes in their "What I am working on now" section and disappears as a task that other people can take.

**Comment by fosterlynn** [comment]
And in terms of the model, the planned work is a Commitment without a from_agent, and then when someone takes the task, we just put that agent in the Commitment.from_agent.  (Not making any VF recommendations particularly.)

**Comment by elf-pavlik** [comment]
As discussed during today's call, illustration of IPO with *vf:ServiceResource* and agents acting as *provider* and *recipient*

![vf_serviceresource 3](https://cloud.githubusercontent.com/assets/876431/17840887/cc280710-67d6-11e6-946c-18956dfeecd8.png)

[source](https://docs.google.com/drawings/d/1hCZ7GFHeUYBMLyPZjqlgh3apmmKpTKax9mZCmY8Yd3E/edit) - please make copy (fork) to edit!!! 

```yaml
'@context': https://w3id.org/valueflows/v1
'@id': https://fixme.example/#agent
'@type': foaf:Agent
```
```yaml
'@context': https://w3id.org/valueflows/v1
'@id': https://fablab.example/#agent
'@type': foaf:Agent
```
```yaml
'@context': https://w3id.org/valueflows/v1
'@id': https://fixme.example/wer09rew07e#process
'@type': vf:Transformation
'vf:io':
  - '@id': '#output-1'
     '@type': vf:InputOrOutput
     'vf:action': vf:create
     'vf:resource': https://fablab.example/fsdfs90sdf8#service
```
```yaml
'@context': https://w3id.org/valueflows/v1
'@id': https://fablab.example/fsdfs90sdf8#service
'@type': vf:ServiceResource
'vf:provider': https://fixme.example/#agent
'vf:recipient': https://fablab.example/#agent
```
```yaml
'@context': https://w3id.org/valueflows/v1
'@id': https://fablab.example/adliaf9a0f89a0#process
'@type': vf:Transformation
'vf:io':
  - '@id': '#input-1'
     '@type': vf:InputOrOutput
     'vf:action': vf:consume
     'vf:resource': https://fablab.example/fsdfs90sdf8#service
```

**Comment by fosterlynn** [comment]
@elf-pavlik thanks for getting this out here!

Initial comment: Referring to the provider and recipient agents on the resource itself will only work for the very simplest cases.  What if there are more than one provider of a service (like if more than one person worked on the repair), and what if there are more than one recipient (like if the provider is giving a class)?  And it only works for something like services, where they are provided and consumed at the same time, so there is very tight coupling.

Any reason not to move those references to the events? 

Also not clear to me: Who is the provider and who is the recipient in this? Are they the fablab and fixme groups, or specific people within those groups?

**Comment by elf-pavlik** [comment]
> Also not clear to me: Who is the provider and who is the recipient in this? Are they the fablab and fixme groups, or specific people within those groups?

The service only references the fablab and fixme groups. If specific people do some work, they would have it connected as inputs to relevant processes.

> What if there are more than one provider of a service (like if more than one person worked on the repair)

The process which outputs the repair service would have work resources as inputs to it.

> and what if there are more than one recipient (like if the provider is giving a class)?

Just as in transportation I would see one output service per package / passenger. I would also consider creating one service per recipient for class like scenarios.

> Any reason not to move those references to the events?

Could you please modify YAML I provided to reflect your suggestion?

**Comment by fosterlynn** [comment]
In this example I'm not sure what a repair service would be input to.  While we are discussing that possibility, I'll just put out this comment so there is more to discuss.

```yaml
'@context': https://w3id.org/valueflows/v1
'@id': https://fixme.example/#agent
'@type': foaf:Agent
```
```yaml
'@context': https://w3id.org/valueflows/v1
'@id': https://fablab.example/#agent
'@type': foaf:Agent
```
```yaml
'@context': https://w3id.org/valueflows/v1
'@id': https://fixme.example/wer09rew07e#process
'@type': vf:Transformation
'vf:io':
  - '@id': '#output-1'
    '@type': vf:InputOrOutput
    'vf:action': vf:create
    'vf:resource': https://fablab.example/7e831985-1ad5-49d0-867a-9dec9e13c44e#service
    'vf:provider': https://fixme.example/#agent
    'vf:recipient': https://fablab.example/#agent
```
```yaml
'@context': https://w3id.org/valueflows/v1
'@id': https://fablab.example/7e831985-1ad5-49d0-867a-9dec9e13c44e#service
'@type': vf:ServiceResource
'vf:uuid': urn:uuid:7e831985-1ad5-49d0-867a-9dec9e13c44e
```

**Comment by elf-pavlik** [comment]
More details on possible process that would take this *vf:ServiceResource* as input:

```yaml
'@context': https://w3id.org/valueflows/v1
'@id': https://fablab.example/adliaf9a0f89a0#process
'@type': vf:Transformation
'vf:io':
  - '@id': '#input-1'
    '@type': vf:InputOrOutput
    'vf:action': vf:consume
    'vf:resource': https://fablab.example/7e831985-1ad5-49d0-867a-9dec9e13c44e#service
  - '@id': '#input-2'
    '@type': vf:InputOrOutput
    'vf:action': vf:work
    'vf:resource':
      '@id': https://fablab.example/bab044c5-b3fc-4f87-b0ef-232c470007c0#work
      '@type': vf:WorkResource
      'vf:uuid': urn:uuid:bab044c5-b3fc-4f87-b0ef-232c470007c0
      'vf:performer': https://amanda.example/#person
  - '@id': '#input-3'
    '@type': vf:InputOrOutput
    'vf:action': vf:use
    'vf:resource':
      '@id': https://fablab.example/a31572d2-e144-4567-9302-5315a40b8622#usage
      '@type': vf:UsageResource
      'vf:uuid': urn:uuid:a31572d2-e144-4567-9302-5315a40b8622
      'vf:underlyingResource': https://fablab.exmple/lab-5#resource
  - '@id': '#input-4'
    '@type': vf:InputOrOutput
    'vf:action': vf:accept
    'vf:resource': https://fablab.example/inventory/ORD-FDM-3D-printer-34242#resource
  - '@id': '#output-1'
    '@type': vf:InputOrOutput
    'vf:action': vf:improve
    'vf:resource': https://fablab.example/inventory/ORD-FDM-3D-printer-34242#resource
```

**Comment by fosterlynn** [comment]
OK, going with your example:

```yaml
'@context': https://w3id.org/valueflows/v1
'@id': https://fablab.example/adliaf9a0f89a0#process
'@type': vf:Transformation
'vf:io':
  - '@id': '#input-1'
    '@type': vf:InputOrOutput
    'vf:action': vf:consume
    'vf:resource': https://fablab.example/7e831985-1ad5-49d0-867a-9dec9e13c44e#service
    'vf:provider': https://fixme.example/#agent
    'vf:recipient': https://fablab.example/#agent
  - '@id': '#input-2'
    '@type': vf:InputOrOutput
    'vf:action': vf:work
    'vf:resource':
      '@id': https://fablab.example/bab044c5-b3fc-4f87-b0ef-232c470007c0#work
      '@type': vf:WorkResource
      'vf:uuid': urn:uuid:bab044c5-b3fc-4f87-b0ef-232c470007c0
    'vf:provider': https://amanda.example/#person
  - '@id': '#input-3'
    '@type': vf:InputOrOutput
    'vf:action': vf:use
    'vf:resource':
      '@id': https://fablab.example/a31572d2-e144-4567-9302-5315a40b8622#usage
      '@type': vf:UsageResource
      'vf:uuid': urn:uuid:a31572d2-e144-4567-9302-5315a40b8622
      'vf:underlyingResource': https://fablab.exmple/lab-5#resource
  - '@id': '#input-4'
    '@type': vf:InputOrOutput
    'vf:action': vf:accept
    'vf:resource': https://fablab.example/inventory/ORD-FDM-3D-printer-34242#resource
  - '@id': '#output-1'
    '@type': vf:InputOrOutput
    'vf:action': vf:improve
    'vf:resource': https://fablab.example/inventory/ORD-FDM-3D-printer-34242#resource
```

On the work resource, could we also say the following?  (removed identification of the vf:WorkResource but kept it a resource)
```yaml
  - '@id': '#input-2'
    '@type': vf:InputOrOutput
    'vf:action': vf:work
    'vf:resource':
      '@type': vf:WorkResource
    'vf:provider': https://amanda.example/#person
```

I have a vague desire to add an output action verb for services like vf:provide, because vf:create seems a bit too concrete.  Do you think this would help clarify for people?

**Comment by fosterlynn** [comment]
Another specific above: I changed the agent on the work event to a vf:provider rather than vf:performer, to try to move to consistency on the event model/vocab.  What do you think?

**Comment by elf-pavlik** [comment]
For v0.1 we can simply leave out the 'provider' and 'recipient' of *vf:ServiceResource*, it doesn't affect tracking the observable state of resources. I will make comment about usage and work in #150

**Comment by fosterlynn** [comment]
I'm getting back to this issue, since we are doing more publishing out to people about VF model (had a discussion today with people working on an Odoo implementation for Coopaname in France who want to use REA and will be looking at VF documentation).  And how agents fit in with IPO (and exchanges) is the biggest missing hole from publishing anything at all.

So....  For starters, lets ignore 'context agent' with the goal of getting something we can agree on.    But let's explore the 'provider' and 'receiver' concepts we have discussed before.  Who knows, maybe we discover we don't need context agent concept? :smile:   And I think we can publish without context agent, but not without other involved agents directly involved.

So, in IPO, we have resource > input event > process > output event > resource.  Starting with observation layer.  I think where the 'provider' and 'receiver' agents belong is on the events.  We may not need both on all events.  Initial thoughts by action:

vf:work - provider is the person who did the work

vf:consume - provider would be the agent who owns, controls, manages, etc. the resource consumed

vf:use - provider would be the agent who owns, controls, manages, etc. the resource used (or maybe this action will go away in favor of a usage resource with underlying resource of the tool or equipment?)

vf:accept - provider would be the agent who owns, controls, manages, etc. the input resource

vf:load - provider would be the agent who owns, controls, manages, etc. the loaded resource

For all these input actions, the receiver seems to me to be the agent who 'has' the process, probably the same as the nrp:contextAgent.  So, the group or project or person who is implementing the process. For load it is probably the carrier.

vf:produce - for situation where work is not recorded, but deliverables are recorded, the provider could be the person who delivered the output resource; but I think we can ignore this for the first pass?  I think the provider would be the same as the receiver of the above input events, and the receiver would be the same.  Or if an item is being produced specifically for another agent, maybe they would be the receiver, that would feed into the exchange model.

vf:provideService (name tbd) - provider as above; receiver the agent whom the service was done for/to.

vf:change (or vf:improve, where did we end up on this?) - provider as above; receiver of final output of a workflow same as vf:produce, if intermediate output, receiver same as provider?

vf:unload - provider as above, the carrier; receiver the agent who received the unloaded item.

OK, enough to I hope revive the discussion....  :blush:

**Comment by elf-pavlik** [comment]
Thansk @fosterlynn 

I think while we look at Observation layer, we should also keep Plan in mind, where we have Commitment and Intent as 'Event Image'. It looks that for example in *work* and *use* you suggest only 'provider', do we need on Commitment for *work* and *use* both agents referenced or other element of agreement will make those references. Just as we need to know who makes commitment to who, we need to know who can assess the event to approve (or not) that it fulfilled the commitment.

When it comes to Intents, we should thing how requesting particular work would look (as input to particular planned process, which one event can satisfy/fulfill). Possibly some kind of other construct (maybe Request distinct from Intent) would reference that intent and requesting agent. Later agent who wants to 'provide' that work would make Commitment with agent who requested it. Again, possibly Commitment wouldn't have to reference the 'committed to' agent but only 'committing' agent as 'provider'. Still Agreement which references that Commitment would need to provide way to interpret in not ambiguous way who made commitment to who.

**Comment by fosterlynn** [comment]
>It looks that for example in work and use you suggest only 'provider',

For these, I thought this:
>For all these input actions, the receiver seems to me to be the agent who 'has' the process, probably the same as the nrp:contextAgent. So, the group or project or person who is implementing the process. For load it is probably the carrier.

But in any case, yes we do need to see how it will work for Intents and Commitments.  Even more yaml.....

**Comment by elf-pavlik** [comment]
We may also need to touch again Agent - Process relationships. For example something like admin/maintainer/manager - agent(s) who coordinates the process, who make commitments etc.

Case of *nrp:contextAgent* seems like situation with only one agent having that admin/maintainer/manager relationship to a process. I'd also like to support cases of 'collaborative' processes where more than one independent agent can have such admin/maintainer/manager relationship to a process. So any one of them could make commitments for that process. Once again they wouldn't have to create single group agent to manage that process while they could do that if they have such preference.

**Comment by fosterlynn** [comment]
>Case of nrp:contextAgent seems like situation with only one agent having that admin/maintainer/manager relationship to a process. I'd also like to support cases of 'collaborative' processes where more than one independent agent can have such admin/maintainer/manager relationship to a process. So any one of them could make commitments for that process. Once again they wouldn't have to create single group agent to manage that process while they could do that if they have such preference.

Context agents are exactly that.  They are the group.  Anyone in the context can manage a process, make commitments, etc.  They can do it all together if they want, in discussion as peers.  Context agents by their nature give you opportunity for collaborative process.

**Comment by bhaugen** [comment]
The Scuttlebutt crowd, including @ahdinosaur , has been thinking about how groups can act together in a decentralized protocol.

**Comment by elf-pavlik** [comment]
> Anyone in the context can manage a process, make commitments, etc. 

So agent used as 'context' uses some kind of 'inContext' property to specify other agents 'in its context'? IMO just because someone has some kind of 'member' or 'affiliated' relation to agent used as 'context' it shouldn't imply that they can admin/manage all the processes.

I do not want to force that process has to have one and only one agent with a special 'context' relation to it. I would prefer to have such special relation admin/manager/maintainer which can reference any number of agents. Which still allows some groups to choose to create group agent and mark that agent as 'admin/manager/maintainer'. In terms of agent <-> agent relationship we still may need some common relationship which allows to verify that agent referenced with it can make commitments on behalf of agent referencing.

**Comment by bhaugen** [comment]
A long time ago, I wrote something about this set of topics in the Sensorica wiki. Which nobody ever paid any attention to. But i still think it is relevant.
http://valuenetwork.referata.com/wiki/How_internal_exchanges_and_schedules_must_work_in_a_value_network

**Comment by elf-pavlik** [comment]
Based on today's chat with @fosterlynn, we may take Commitment as reference
* *provider* - agent that makes the commitment
* *receiver* - agent to whom commitment gets made

and project it to Intent and Event, so for Intent
* *provider* - agent who makes the offer
* *receiver* - agent who makes the request

**Comment by elf-pavlik** [comment]
I think we can follow up here on @bhaugen comment in https://github.com/valueflows/vf-apps-traversing-the-flows/issues/4#issuecomment-451732026

In one of the recent chats with @fosterlynn we touched on 'rights and responsibilities' and I mentioned that we may need to consider in what way agents **exercise** those rights. Since future events which will represent such 'exercising of rights and responsibilities' need to have some actions, at lest for the 'rights' part it should map somehow to those actions.

Currently we have *provider* and *receiver* relations on flows and they still mean pretty much what more than a year old comment above states. In events I would interpret is as agent referenced as *provider* causes agent referenced as *receiver* to 'benefit' from that event. But this interpretation may not work with 'responsibilities' related interactions like picking up recycling which inspired my attempt in #276 

I would propose that we pick couple of use cases with variants to define scope for the next step in defining 'rights and responsibilities' and how they relate to flows with different actions.

**Comment by fosterlynn** [comment]
Here is a "napkin doodle", thinking about a PR...  trying to clear up some of the ambiguities of transfer.

The top 3 entities are derived, and could be stored or not.  I'm not sure we need the defined relationships to allowed actions (possibly beyond VF), but it was mentioned so it is on the "napkin".
![arrr](https://user-images.githubusercontent.com/3776081/50776095-b46fe000-125d-11e9-95a0-b6f2d0c395c5.png)

**Comment by elf-pavlik** [comment]
> [edit] It is also possibly we might want some defined behaviors for people to start with in Agent Resource Relationship Role - ownership, custody, rental, lending, that kind of thing.

Could you please write down which rights/actions you think of assigning for each of the roles above?

> I'm not sure we need the defined relationships to allowed actions (possibly beyond VF)

If we don't tie it to actions, then we don't really have clarity in data what 'rights' agent can exercise on the resource. Since we also expect that `vf:Agreement` can include some non machine readable information (besides it grouping machine readable flows), flow can also reference some agreement with `vf:under` and it can capture any non machine readable details.

**Comment by elf-pavlik** [comment]
> * ownership: use, give, consume, load

what about: receive, produce, unload ?

>  * custody: use, give, load ?

what about: receive, produce, unload ?

>  * rental: use
>  * lending: use

what about: give, receive, load, unload? - non of them *change existence*

**Comment by fosterlynn** [comment]
well....

produce is the first action for a produced resource, so there can't be any rules about what came before

yes, more work to be done on different kinds of transfer of rights, to see how they can be overlapped - like would an agent receive something they already own?

rental and lending are very different rights and expect different kinds of reciprocity, or not - there is more to economic life than if something changes existence

yes, more rights could allow load and unload (moving stuff around)

but i'm not sold on having pre-defined behaviors at all, really - although it is at least useful as an exercise in sifting through what are the important semantic differences we are dealing with

**Comment by elf-pavlik** [comment]
> produce is the first action for a produced resource, so there can't be any rules about what came before

We have a lot of examples with *produce* that affects resource with *currentQuantity* >= 0

> rental and lending are very different rights and expect different kinds of reciprocity, or not - there is more to economic life than if something changes existence

Flows on their own should have no notion of reciprocity, Agreements stay responsible for that and most likely Proposals.

> yes, more rights could allow load and unload (moving stuff around)

I see it as another point in favor of having unified *split* and *merge* which don't change existance

BTW I like approach of defining orthogonal to `vf:action` constructs to capture how flows impact 'rights and responsibilities', so actions themselves should take no responsibility for that.

If we go with something like proposed here `vf:affectsRole` it should simply work with any action and we shouldn't need to try leak any 'rights and responsibilities' responsibility into actions themselves.

Another approach we could consider:

```yaml
`@id`: example:a52d18c8-aeeb-479b-a755-2c907555707e
`@type`: EconomicEvent # or any other flow
observedQuantity: ...
affects: ...
transfers:
  '@type': Transfer
  rights:
    - use
    - split
    - merge
  providedBy: alice
  receivedBy: bob
```

If people want to define some 'roles' and map them to actions, they can do it but flows use those actions directly and later application can map it back to whatever 'roles' they match.

This also should interoperate better for situations where different agents map same set of actions to different roles or same roles to different set of actions. We should rely on what VF vocab defines and let people build all the extra constructs around that. We can't rely on what vocab does not define.

**Comment by fosterlynn** [comment]
>We have a lot of examples with produce that affects resource with currentQuantity >= 0

True indeed.

>Flows on their own should have no notion of reciprocity

OK, agree.  Lending and Renting have essentially the same flows. 

>BTW I like approach of defining orthogonal to vf:action constructs to capture how flows impact 'rights and responsibilities', so actions themselves should take no responsibility for that.

I'm good with that in general.  Although I'm thinking about the concepts of transferring "ownership" and transferring "possession" that some of the REA gang are working with.  They seem too limited in post-capitalism thinking.  And they don't seem to include responsibilities with their implied rights.  But the possession thing has some possibilities to solve some of the current confusion over teleportation. :)  Although I don't know how these guys are modelling that.  I also think we should be careful to not be too rigid about flows - they are "edges" so can't really exist by themselves.

In terms of connecting transfers to the actions that are given as rights to - I feel like that also ignores responsibilities.  Some transfers I think are heavier on responsibility, some heavier on rights.  I think about the example @bhaugen cites sometimes of the air traffic controller "plan-o-spheres", which define at all times which planes they are responsible for, and which require an explicit transfer or handoff when a plane leaves one and enters another.  So I have some hesitations about trying to define transfers as bundles of rights to actions.

**Comment by fosterlynn** [comment]
Some potential issues with transfer-related events clearly changing the data on an agent-resource-relationship.

Need to support many instances of the same role for a resource.  Need to support many instances of the same agent and resource with different roles.  Sometimes transferring a role imply that you don't have that role any more for that resource; sometimes not.

Still thinking....

**Comment by fosterlynn** [comment]
Resolved for v.3, please re-open if needed.
