### ISSUE TITLE
How should we go about this?

### ISSUE THREAD

**Issue by bhaugen** [valueflows/valueflows#15]
Spinoff from #13 

@fosterlynn starts with models in something like (but not necessarily) UML. @ahdinosaur started with json-schema code. @bshambaugh in an email suggested starting with "the Ontology builder Protege", but aiming for json-ld. I said I was also aiming for json-ld. 

The [conversations in Loomio](https://www.loomio.org/d/5WOvZfEq/linked-open-data) that this project emerged from wanted Linked Open Data. But I am a noob in linked open data land. Lynn is studying the [Working Ontologist book] (http://workingontologist.org/) via a recommendation from @elf-pavlik.

So can we come to some rough consensus on an approach? Or maybe everybody take their own approach and try to converge?

**Comment by fosterlynn** [comment]
@bhaugen  There is a PLP meeting on Wednesday with this on the agenda.  Also I will try a newbie draft of the @context definitions for agent relationship types and agent relationships, to get something out there for feedback.  Others feel free to add....

**Comment by bshambaugh** [comment]
So, I've been playing around and I put my stuff up. It is a work in progress. You can see that I made some things up to fit to the graph such as the RelationshipTypeName and RelationStatusType classes. I also renamed name as agentName and symmetric as symmetrichasRelationship. I tried to infer what made sense to be a correct structure. I looked at http://www.w3.org/TR/swbp-n-aryRelations/ for help, and it seemed that some logic of this sort had been considered.  I posted to my blog about it: http://adistributedeconomy.blogspot.com/2015/03/structure-of-ontology-for-agent.html . Here you will also have a link to the ontology I made on GitHub. If you'd like to use the tool I used to help create it see Protege (http://protege.stanford.edu/). Also see a text editor. I might be kind of quiet, pushing updates as I get them, while pushing through this.

**Comment by bshambaugh** [comment]
You can load the ontology from GitHub in Protege to see a different view of it.

**Comment by bshambaugh** [comment]
It is in turtle, and not JSON-LD (http://www.w3.org/TR/turtle/). But I do plan on some conversion later after I look at the other files at https://github.com/openvocab/ovn. Eventually I plan to ingest other issues as I gain some confidence and understanding.

**Comment by ahdinosaur** [comment]
@bshambaugh wow, that's awesome! :sunny:

if you happen to wander over to https://github.com/openvocab/holodex/issues/1, there's a recent discussion diving more into the vocabulary you played with, and i'd be really grateful for your input. :smile_cat:

**Comment by ahdinosaur** [comment]
closing, seems stale given that we're currently *going about this*?

**Comment by elf-pavlik** [comment]
@bshambaugh we picked up this work and now build up some momentum, maybe you would like to join for [the next call](https://github.com/valueflows/valueflows/issues/42#issuecomment-149747934)? You can see recording from last one in https://www.youtube.com/watch?v=Uk7aa4MXjmw

**Comment by bshambaugh** [comment]
Elf,

Thanks for being in touch with me I think I get off of work at 3, so this
will give me a chance to join.


-Brent Shambaugh

Website: bshambaugh.org

**Comment by bshambaugh** [comment]
Is this call going on right now?

-Brent Shambaugh

Website: bshambaugh.org

On Fri, Oct 23, 2015 at 11:08 AM, Brent Shambaugh <brent.shambaugh@gmail.com

**Comment by elf-pavlik** [comment]
@bshambaugh we will have next call on 20th, please also feel invited to jump on https://gitter.im/valueflows at any time!
