### ISSUE TITLE
Who is the vocabulary for?

### ISSUE THREAD

**Issue by bhaugen** [valueflows/valueflows#151]
Recent chatter in gitter discusses if the VF vocabulary is for software developers and can be too complicated for end users to understand because software developers will give them friendly interfaces to it.

I think we should keep in mind one of the [principles we agreed to up front](https://github.com/openvocab/ovn/wiki/Principles-for-this-vocabulary): 

> The model must enable collaboration between different people in different organizations using different software on different platforms using different human and programming languages.

What I meant when I wrote that, as I think I explained in various settings, is that it should be usable using any software or almost no software: that is, via email, using hashtags, text messages, command lines, csv files (which is where the action is now in the various resource flow mapping conversations we have been involved in), etc etc.

If how to do this kind of thing using hashtags is not clear, I can bring in several examples from the wild.

I also think that a direction that is possible using linked open data and Solid is to allow anybody to post their own economic profile and intents and broadcast the intents and enter into conversations for action using any of the channels I mentioned, as well as purpose-built software.

What do you all think?

**Comment by fosterlynn** [comment]
there is a section in the 0.1 release, closing
