### ISSUE TITLE
Proposal for representing units of time and their relationships

### ISSUE THREAD

**Issue by bhaugen** [valueflows/valueflows#152]
This issue came up when discussing time-based resources, but I am putting it here in the main VF repo because it may have broader implications.

I suggest to represent units of time and their relationships, we use [owl-time](https://www.w3.org/TR/owl-time/) instead of [qudt time units](http://qudt.org/vocab/unit/units-space-and-time.html), although we are using qudt for physical units.

Qudt focuses on scientific uses of time, for astronomy etc, with a lot of emphasis on velocities.

Owl-time is based on temporal relations, which is what we will need. As they say on the owl-time doc, "The basic structure of the ontology is based on an algebra of binary relations on intervals (e.g., meets, overlaps) developed by Allen and Ferguson for representing qualitative temporal information, and to address the problem of reasoning about such information."

Allen and Ferguson is the source for every good temporal relations library I have ever seen.

To represent availability of time-based resources, I think we will want to use [time:DateTimeInterval](https://www.w3.org/TR/owl-time/#time:DateTimeInterval)~~, which has a beginning and ending [time:DateTimeDescription](https://www.w3.org/TR/owl-time/#time:DateTimeDescription) and a [time:Duration](https://www.w3.org/TR/owl-time/#time:Duration)~~. 
_[edit] See @dr-shorthair 's comment below and this diagram:_
![owl-time classes](https://www.w3.org/TR/owl-time/images/TemporalDuration.png)

_TemporalUnit is based on TemporalDuration, so my statement that I crossed out was incorrect._

The availability of time-based resources can be represented by a calendar, a collection of vf:Commitments where the unit is a time:DateTimeInterval. The intervals can have any required granularity (days, hours, minutes, whatever) and can have gaps in between them where the time-based resource is not available.

In the recently cited use cases where some equipment is being repaired, the interval of the expected repair would be removed from the availability calendar.

**Comment by bhaugen** [comment]
> In the recently cited use cases where some equipment is being repaired, the interval of the expected repair would be removed from the availability calendar.

One way to "remove" those intervals semi-automatically would be for the repair process to reserve them. Then they would no longer be available for other uses, plus other prospective users could see what is happening on the resource calendar.

**Comment by bhaugen** [comment]
Example of a resource calendar: https://help.xmatters.com/ondemand/groups/groups-calendar.htm

**Comment by bhaugen** [comment]
See also https://plus.google.com/u/0/+SimonCox1959/posts/XiFNP59VU1m
> Compiliing a usage report https://www.w3.org/2015/spatial/wiki/OWL_Time_Ontology_adoption to help OWL-Time https://www.w3.org/TR/owl-time/ transition from W3C Candidate status. LOV is helping, but there is plenty more out there. Anyone who uses OWL-Time, particularly in datasets, please let me know.

**Comment by dr-shorthair** [comment]
Actually TemporalUnit is based on Duration

**Comment by bhaugen** [comment]
@dr-shorthair - thanks a lot for dropping in and correcting my error! I'll do some re-reading and strikethrough the error above (so your comment will remain valid) and correct the statement.

**Comment by bhaugen** [comment]
See also https://www.w3.org/TR/owl-time/#time-prov
> 5.7 Alignment of PROV-O with OWL-Time

> PROV is a process-flow model. The base class Activity denotes things that occur over a period of time, and act upon or with entities. Activities are ordered within a provenance trace. Thus, an alignment with OWL-Time is natural.

We (VF) include a process-flow model.

**Comment by elf-pavlik** [comment]
Last version uses OWL-Time
