### ISSUE TITLE
How to model Usage?

### ISSUE THREAD

**Issue by fosterlynn** [valueflows/valueflows#156]
Starting a dedicated issue for this. 

I'm doing examples for 0.0, I'm not liking my vf:UsageResource so much.  It's not horrible, but it's not that intuitive either.  So, here are the options I know about for handling usage, thinking about equipment, tools, space here.
- Create a vf:MaterialResource for the base resource, create a vf:UsageResource for the usage resource, with vf:underlyingResource of the base resource.  This is where I was going with it.  Each resource has its own vf:quantity (number + unit).
- Create a vf:MaterialResource for the base resource, support unit and unitOfUse.  NRP does this, I never liked it and it confused users initially, but I may dislike the usage resource as much in terms of potential confusion.  Actually, NRP has this in the nrp:ResourceType, not in the resource itself, so it is just unit, has no quantity.  But we can't do that in VF because we won't have control over a lot of the resource types.
- Create a vf:MaterialResource for the base resource, link the resource's possible units with the vf:action verb, like vf:consume - Each, vf:use - Hour.  Cleaner and more flexible model, but also forces resources that need only one unit to still use this more complex model.  (credit @bhaugen )  I think this applies more to the resource type too though.  For the resource, I suppose it could have more than one vf:quantity, which includes both number and unit.
- I suppose we could combine them - the vf:MaterialResource could have its main quantity in its main unit, and then add for usage related to vf:action verb.

So, some complicating factors:
- How we want to plan for usage will affect this - for both calendared and not calendared scenarios.
- We can't count on having a resource type that defines any units at all.
- We should consider citations along with this, if we can use the dualing units of whatever model we like best to also support a way to have a different unit of citing a document or design, that would be great.  (We have a requirement to have some way to quantify credit for a citation, but @elf-pavlik rightly objected to using the main vf:quantity for recording a percentage, as it skews the meaning of vf:quantity.)

I'll continue to think about this....

**Comment by elf-pavlik** [comment]
> We can't count on having a resource type that defines any units at all.

Each inventory can have a way to provide some defaults for resources with particular 'resoruce type'. Since different inventories can handle resources of the same type differently. As I understand NRP doesn't support same resource type used across independent inventories and it uses the type record of the resource to store inventory specific preferences for handling resources of that type.

**Comment by bhaugen** [comment]
>  As I understand NRP doesn't support same resource type used across independent inventories and it uses the type record of the resource to store inventory specific preferences for handling resources of that type.

Not true. Every network that we have ever worked with has needed to agree on resource types for anything that went across independent inventories. It's the same with any collaborative system of independent agents. That's also why GTINs (global trade identification numbers) evolved.

**Comment by elf-pavlik** [comment]
Do you expect everyone to agree if they will measure usage of resources of same type. Eg. some open source model of a cargo bike in the same way? I think different inventories may prefer to measure it in time or in kilometers etc. Even when usage of same type of resource gets measured in time across different inventories, they all may still have different preferences if they make commitments per hour, per day etc. https://listings.cycle.land/

**Comment by bhaugen** [comment]
> Do you expect everyone to agree if they will measure usage of resources of same type.

Depends on whether they need to agree or not. For most resource types, every network we have known agrees on some basics, and allows for some variations (like growing method for carrots, e.g. organic or not, and sometimes price, or sometimes prices are uniform). One driveby affiliate of Sensorica wanted to develop a resource-sharing app, where some of the time-based resource rules might have been fleshed out. So the rules vary.

**Comment by elf-pavlik** [comment]
> and sometimes price, or sometimes prices are uniform

Just a reminder 'price' has nothing to do directly with a resource or its type but it always has an intent 'in between' - https://github.com/valueflows/resource/blob/master/ResourceType.md#what-about-prices

**Comment by bhaugen** [comment]
I'm reporting actual practices, not specifying what VF should do.

**Comment by fosterlynn** [comment]
Resolved for v.3, please re-open if needed.
