### ISSUE TITLE
Assembly and disassembly

### ISSUE THREAD

**Issue by bhaugen** [valueflows/valueflows#158]
I think we should create a new vf:action for assemble and another for disassemble.

Could be other names, like attach and detach.

They might go with a Assembly ProcessType.

An assemble event would be an input to an Assembly process. It could specify a serialized or lot controlled resource (or not). The event would decrement the source resource.

The Assembly process would know all of the assembled inputs by their vf:action, and to disassemble, you could ask the output resource for all of the components that were assembled into it. You could disassemble one selected assembled component, or a function to disassembleAll could be created.

If you had a series of Assembly processes, you might want to identify the end output resource as early as possible, and that resource would basically be both an input and an output from each of the processes after it was identified. This would be useful, for example, where an end user wanted specific components for their end product. 

For example, if Lynn specifies some particular components for her semi-custom-built computer, before the process chain or assembly line gets to the optional components, the "stream resource" would be identified as "Lynn's computer", and it would go through the next set of processes and get the selected components.

It would also be possible to recursively follow the IPO tree from the output resource as root and find all of the various assembled components along the tree. That treatment would not require identifying the output resource until the end.

I think anything like this, where you want to identify the particular inputs for a particular option, requires one process = one output. So if you had an assembly line, each station on the line could be one process for one output. The next output at the same station could come out of a different process.

Alternatively, the whole assembly line could be modeled as one process for each output product.

Which process scope to choose would depend on where in the line the end product could be identified, and whether after that it's worth defining a separate process for each station on the line.

Please suggest improvements.

**Comment by bhaugen** [comment]
More on assembly, after rethinking some gitter conversations about bike frames. I think this might be a good use case to refine our understanding of what is a resource and what is not a resource.

REA defines a resource as something that has value for an agent. I don't think we should care about why people value their resources, or what is their definition or theory of value. I think we should focus in VF mostly on use value, although exchange value will raise its hands now and then, too. Clearly in capitalism exchange value dominates use value. But even then, a resource needs to have _some_ use value (although sometimes you wonder...).

In the bike frame use case, a bike frame before it becomes part of a bike has the use value of being a component that _could be used_ to make a bike. Once it becomes part of a bike, the frame is no longer a resource, it is part of the bike, and the bike is a resource that has the use value of providing transportation or exercise or possibly pedal power for light machinery. If the bike is disassembled, and the frame is separated from the other components, it might become a component resource again.

What I am trying to point out here is that a resource is defined by its use value, not that fact of its physical existence or non-existence. The bike frame, when it is part of the bike, clearly still exists. It might even have a serial number. But it is no longer a resource in its own right.

In this sense, assembly decrements the bike frame as a resource.  Even if we posit separate issue and assemble events, as in a controlled inventory environment, the issue just takes the bike frame out of a controlled component inventory, but it is still a component resource (now possibly part of work-in-process inventory). When the frame becomes part of the bike, it is no longer a component resource anymore. 

So if we had a process of repetitively manufacturing bikes, we might want to stage 10 frames in work-in-process in front of the workstation where bikes were being assembled. Each of those frames, before becoming part of the bike, would still be a component resource.  When the first one becomes part of a bike, we would have 9 frames in work-in-process inventory. And one bike.

I hope this is clear. I think this is the clearest way that I have explained this stuff yet, which seems to be conceptually difficult. And it will apply to several other use cases where we are still arguing about what a resource is and ain't.

**Comment by elf-pavlik** [comment]
Thank you for further clarifications @bhaugen !

I would like to stay very careful about making assumptions about how agents (mostly people) value resources. Continuing example of the bike frame. Knew in the past couple of people who I would consider obsessed with MTB. If someone would assemble bike frame which they really like into a bike with various other components which they don't like, they would still finde the frame as something useful (we get disassemble it and assemble with another configuration of components), while they wouldn't see the whole bike as something useful - "I can't ride with those breaks... Why would anyone use this suspensions???" etc.

Other scenario relates to generic components eg. engines, wheels etc. which could stay assembled into some 'war machines'. While many people would not consider them useful, they would still consider particular components useful as potential parts for 'farming machines' or 'building machines'...

Also often bike frames have warranty independent from the bike they stay assembled in. If we don't allow representing assembled bike frame as *vf:Resource*, modelling various agreements about resources (like warranty) may not work with cases like such bike frames.

**Comment by bhaugen** [comment]
And thanks for responding, @elf-pavlik !

An assembled bike could still reference each of its components. But I don't think they are independent resources when assembled into the bike. I recognize that somebody could do that (not consider the bike to be a resource, but instead to represent each of its components), but I would think that would be an odd edge case. vf:Resource would allow them to do it, but I wouldn't put it in a how-to-do-it example.

And if I were one of those odd people, I would probably find it annoying that the assemble action decremented the assembled resources, and I would create my own action that didn't. And I would also need to figure out how to represent the whole bike as a collection of resources instead of a bike. But as always, edge cases make good tests but bad designs.

> Also often bike frames have warranty independent from the bike they stay assembled in. 

I'd like to see one of those warranties to see how they represent it. Seems doable without representing the frame as an independent resource once assembled into the bike. As I wrote above, the frame exists, and has its own history from when it was an independent resource, which was also where its warranty most likely came from.

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/valueflows/-/issues/158.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
