### ISSUE TITLE
Add foaf:Organization to UML model?

### ISSUE THREAD

**Issue by pmackay** [valueflows/valueflows#159]
As its part of foaf, and a useful way to represent other types of Agents, could it be added?

cc @fosterlynn

**Comment by fosterlynn** [comment]
My opinion would be to definitely add it, we need the concept, which can be different than "group".  There has been quite a bit of discussion, and we haven't come to consensus yet.  (A lot of the earlier objection I think was focused around org:Organization rather than foaf.  I am totally fine with foaf.)

**Comment by pmackay** [comment]
Having scanned org:Organization, it seems to have more capability (fields, etc), so perhaps that would be a better option?

**Comment by fosterlynn** [comment]
Yes, org:Organization is a much more developed model; at the same time it is probably more "corporate".  And I don't want to speak for @elf-pavlik on this, since I can't remember all of the details, and I'm not sure I ever understood his main objection.

References I could find:
https://github.com/valueflows/agent/issues/68
https://github.com/valueflows/agent/pull/66 (part of this)

@pmackay what are your needs?  Let's make sure you have them met!

**Comment by pmackay** [comment]
Might it actually be better to define `vf:Agent` and sub-models, which can heavily reuse the fields from `foaf`? Currently the Agent model includes fields for `url`, `primaryLocation` and `note` which I dont see as part of `foaf`, so is that a bit confusing in itself?

My main need currently is just to add the model, the basic fields on Agent are enough.

On that, Im just wondering though, why does Agent have `primaryLocation`? What if an Agent has multiple locations? Could it be one-to-many?

**Comment by fosterlynn** [comment]
>Might it actually be better to define vf:Agent and sub-models, which can heavily reuse the fields from foaf? Currently the Agent model includes fields for url, primaryLocation and note which I dont see as part of foaf, so is that a bit confusing in itself?

Either is fine with me, I've been confused about that, and we've been back and forth.  I think it is a question of what is more or less standard for LOD.  Seems like most (but not all) vocabs define their own agent classes, and then will sometimes define them as owl:equivalentClass of foaf or schema.org classes.  Can @pmackay or @elf-pavlik speak to what would be the most standard and least confusing thing to do in this case?  And the most respectful to re-using existing work?

>On that, Im just wondering though, why does Agent have primaryLocation? What if an Agent has multiple locations? Could it be one-to-many? 

I imagine there will be a need for multiple locations for an agent.  In fact, wouldn't it really be a many-to-many? There also I expect will be a need to have more information on the relationship to qualify it.  We haven't spent much time on that, partly hoping to piggy back on TransforMap or others who have agents related to locations as part of their core.

One thing we did talk about was changing the name vf:Location to vf:Place (assuming it is vf:).  Should we do that?

Paul, let's minimally do what you need; and if we want to really nail it down now, I'd be willing to do some research on standard models for agent - location relationships.  And see if @almereyda can help us out with at least the requirements from his side, understanding it has been hard to standardize on the actual model.

**Comment by gcassel** [comment]
Continuing the tangent on vf:Location, which probably deserves its own thread:

Agents may have a primary personal physical mailing address, where they receive physical mail (less important than it used to be).  That may or may not be their residential address, and their residential address may or may not be one of the main centers (or regions) of their activity.  

Agents also may have one or more physical offices, often (but not always) associated with specific roles/positions they have in a network or organization, 

Ultimately, I think that *physical addresses* (and any sub-types) need to be distinguished from any other *locations* or (preferably IMO) *regions/areas* which an agent desires to list for their general or specific activities.

**Comment by pmackay** [comment]
Keeping this issue to the Organisation point:

>speak to what would be the most standard and least confusing thing to do in this case? And the most respectful to re-using existing work?

I really like the Popolo project approach to this, e.g. look at [section 3 for Person](http://www.popoloproject.com/specs/person.html). Or the same for [Organisation](http://www.popoloproject.com/specs/organization.html). They cherry pick the best properties from existing specs that offer the best equivalence.

**Comment by fosterlynn** [comment]
@pmackay the Popolo stuff looks well thought out, I will study it more, both for specifics and how they approach their cherry-picking.  Unfortunately probably not in the next few days, unless we want to bump the priority....  :)

**Comment by fosterlynn** [comment]
we added org:Organization
