### ISSUE TITLE
How to model work

### ISSUE THREAD

**Issue by bhaugen** [valueflows/valueflows#174]
Split off from https://github.com/valueflows/valueflows/issues/173

If we measure work by timespan, then work (as for example a process input) has two different aspects:
* For the worker, it is a section of their life, for example, from 8-10am on 2017-02-06. I have in fact modeled work that way in a previous system, as time slots on a calendar, where the worker commits to be available for some set of time slots, and processes may allocate some them for their use. When the worker does some actual work, the work events, those time slots in the worker's life are consumed, and they are gone, never to return.
* But the process input cannot actually use those 2 hours in the worker's life. They need the actual work, the exertion of effort and skill of the worker, to provide some desired effect on the materials of the process.

The worker's life and skill requires all of the elements of daily life mentioned in #173 - plus a lifetime of child rearing, education, training, and practice.

The process might not care about any of that, only the effect on the materials. But if those responsible for the nested contexts in which the process happens do not care, then the workers and the process and the contexts and all of their citizens will suffer.

Of course, we live in a system that does not care, or cares only the absolute minimum. But we also want to generate something better.

It would be possible to use the VF vocab to model only the work input to the process, without getting into all that was required to provide the span of the worker's life and the worker's abilities. But for an economic ecosystem, that all comes into play.

**Comment by elf-pavlik** [comment]
>* For the worker, it is a section of their life, for example, from 8-10am on 2017-02-06. I have in fact modeled work that way in a previous system, as time slots on a calendar, where the worker commits to be available for some set of time slots, and processes may allocate some them for their use. When the worker does some actual work, the work events, those time slots in the worker's life are consumed, and they are gone, never to return.
>* But the process input cannot actually use those 2 hours in the worker's life. They need the actual work, the exertion of effort and skill of the worker, to provide some desired effect on the materials of the process.

I thinks commitments can happen for both, 'actual work' (IPO events) as well as availability. For example Bob may commit to stay available for 3 hours at particular time to help Alice. Even if Alice fails to coordinate processes in a way that Bob can actually work, he still have fulfilled his commitment to stay available.

**Comment by stevebosserman** [comment]
@bhaugen wrote:

> Of course, we live in a system that does not care, or cares only the absolute minimum. But we also want to generate something better.

In my opinion, this "something better" would be economic systems that produce what John Boik terms "economies of meaning."  Dr. Bork recently posted [An Economy of Meaning, or Bust](https://medium.com/@JohnBoik/an-economy-of-meaning-or-bust-2aa46457b649#.9tflykt75) on Medium.  In it he emphasizes the importance of time:

> A human has only so many minutes in life. Time is the bedrock scarcity. If a person isn’t doing something meaningful in a given moment, he’s doing something less than meaningful. He’s wasting at least some of his potential. By meaningful, I don’t mean productive, in an economic sense. I mean important to the person, to her own wellbeing.

He goes further to state:

> Work doesn’t count as a real human need. It’s only a vehicle by which some needs can be (but for most people aren’t) met. Work doesn’t meet our needs because economic systems, as they exist, didn’t evolve to fulfill the real needs of ordinary people. They evolved largely under pressures exerted by powerful people and groups who wanted to maintain and expand their own privileges.

He then asks:

> What economic system designs, out of all conceivable ones, might be among the best at helping us meet real needs?

Again, in my opinion you're addressing this question in a very fundamental way with the design critieria you're developing.  Collectively, we're on the brink of acknowledging the value in human systems by spending our time simply being with one another in the spirit of companionship and advocacy.  Such work can be imbued with REAL meaning.  And it doesn't necessarily require training, skill and experience as much as it does presence - just being there.  But if this type of "work" is important, we have to account for the time spent doing it and assign an exchange value to it or it gets dismissed as inconsequential.  Conceivably, the system you're developing could give anyone using it a way to find value for everything they do.  And that is a big WOW!

**Comment by elf-pavlik** [comment]
from @fosterlynn 
> what if a group wants to commit that someone (don't know yet who) will do some work?

**Comment by elf-pavlik** [comment]
from: https://github.com/valueflows/exchange/issues/34#issuecomment-280735845
> I also consider modeling each skill as a resource which only person having that skill can own, then work becomes more of a process bound to the individual in which person use those skills ('improving' them like cite) and this process provides service as input to other processes (instead of simple work event).

**Comment by elf-pavlik** [comment]
> what if a group wants to commit that someone (don't know yet who) will do some work?

I think that could happen at stage of commitments, I have a real world use case where organization providing nursing would make commitments that someone will give care in specific place for specific time. One could express one's preference for some of the nurses to come, still the organization would only commit that 'one of certified nurses will come'. Also when someone just starts receiving services, one would probably not express any preferences until getting to know some of the nurses.

Composition could help since organization could make commitment on a service output by a process which takes *work* as the input. They would still need to get commitment for that *work* from one of the people. 

> If we measure work by timespan, then work (as for example a process input) has two different aspects

@fosterlynn I would like to include one or two examples of work where person *works* by staying available at workplace for specific time. As well as processes will have more specific *work* events included in that shift based work. With use of equipment we might hope to do it with 'transfers of rights and responsibilities` but it also has to work with *work* use cases an maybe composition will make more sense if we also consider it for *work*.

**Comment by fosterlynn** [comment]
> I have a real world use case where organization providing nursing would make commitments that someone will give care in specific place for specific time.

Seems like the organization is making the commitment, and is also probably the provider in your real-world example?  If you pay for the nursing services, who do you pay?

>I would like to include one or two examples of work where person _works_ by staying available at workplace for specific time. As well as processes will have more specific _work_ events included in that shift based work.

Good idea.

**Comment by elf-pavlik** [comment]
> Seems like the organization is making the commitment, and is also probably the provider in your real-world example? If you pay for the nursing services, who do you pay?

I think person pays to the organization for the service which includes scheduling and making sure that someone will come even if specific nurse calls sick on the same day. Then very likely nurse who does the nursing work gets paid for this specific work. I think that process which outputs the service, would take work of the nurse on site as well as some coordination work or service input from a coordination process.

**Comment by fosterlynn** [comment]
>> I would like to include one or two examples of work where person _works_ by staying available at workplace for specific time. As well as processes will have more specific _work_ events included in that shift based work.

>Good idea.

Although if you want to use vf:includedIn for that scenario, I think we need to wait for composition milestone.

**Comment by elf-pavlik** [comment]
Here we might not need `vf:includedIn`, just:
* a process (A) that outputs *service* (X) (organization provider, patient receiver)
* work input to that process (A) (nurse provider, organization: receiver)
* *service* (Y) input to that process (A) (organization both provides and receives)
* a process (B) that outputs *service* (Y) and also *service* to other smaller processes
* work input that process (B) takes as input (some admin person: provider, organization: receiver)

We can take this UC in composition milestone, here we can just keep in mind that some flows can go as input to another process that outputs a service. So organization can commit to provide service, process that should provide can have work input and then a person has to commit to that work input.

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/valueflows/-/issues/174.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
