### ISSUE TITLE
Process vs Exchange Fulfillment

### ISSUE THREAD

**Issue by fosterlynn** [valueflows/valueflows#177]
In combining the process and exchange models that we have more or less agreed on, it became clear that we have different ways of modeling event fulfillment of commitment in process vs exchange. 

Exchange here: https://github.com/valueflows/exchange/issues/32#issuecomment-267834962

Process: We have events directly fulfilling commitments.  1:M, commitment to event.  (For exchanges, M:M.)

This issue is to take some specific use cases and work them through in detail to see how this should work.

For example, someone commits to do some work for a process.  They also commit to trade this work for a bushel of apples.  They do the work, recording an event. The work fulfills the commitment to do work.  The work also fulfills the commitment to "transfer" (little t) the work as part of the exchange......

**Comment by elf-pavlik** [comment]
> The work fulfills the commitment to do work. The work also fulfills the commitment to "transfer" (little t) the work as part of the exchange......

I don't see 2 commitments here but only one, to do some work.

**Comment by fosterlynn** [comment]
So I suppose the commitment belongs to both a process and an exchange then?  Could work.

**Comment by elf-pavlik** [comment]
When it comes to work, the only case where we would see *provider* & *receiver* the same would happen when someone just tracks work requested by oneself and committed to oneself. In any case where we have work with different agents referenced as *provider* and *receiver* one can consider it implying transfer between those agents.

**Comment by fosterlynn** [comment]
>In any case where we have work with different agents referenced as provider and receiver one can consider it implying transfer between those agents.

That makes sense when the work will actually be involved in a direct exchange with another agent.

But what about the cases where people are working on a process together?  Let's say an open source project for the commons.  Or in Sensorica working on an R&D process.

**Comment by elf-pavlik** [comment]
> But what about the cases where people are working on a process together? Let's say an open source project for the commons. Or in Sensorica working on an R&D process.

I don't see why this changes anything, as long as we have event with different agent referenced as *provider* and *receiver* I think one can interpret that as 'transfer'. It may or may not stay included in some Agreement or at some point have Appreciation but I don't see why this would matter.

If we look at VF, work events could have *provider* but wouldn't have any agent referenced as *receiver*.

**Comment by fosterlynn** [comment]
> In any case where we have work with different agents referenced as provider and receiver one can consider it implying transfer between those agents.

I think this makes sense.  Let's see how it plays out as we make yaml with provider and receiver.

**Comment by fosterlynn** [comment]
Have discussed with @elf-pavlik in gitter, and also thought about it some more.  (We took it out of release 0.1, couldn't get to a consensus solution fast enough.)

There are various use cases here.  From gitter chat, what if agent A promised to do 10 hours of work this month in exchange for something from agent B.  Then 3 hours of that gets actually scheduled for agent A as input to a process for agent B.  Then maybe 2 work events are recorded, 1 hour and 2 hours against the 3 hour commitment.

Then there is the already modeled difference between process and exchange fulfillment of commitments.  I.e. for a process, an event directly fulfills a commitment, and many events can fulfill a commitment, but not vice versa.  We don't want to create a m:m situation for processes because processes mediate any of the m:m issues.  We don't want to add the complexity of an event being split as input to 2 processes, since processes themselves handle the m:m requirement.  Exchanges are different by nature - there arise m:m situations all the time, due to partial payments and payment for multiple deliveries.  (This is the same for money and non-money transfers.)  So for exchange we modeled a Fulfillment class in between event and commitment to manage that.  But then we have 2 different paths from event to fulfill commitment, and it is confusing and a little messy.  And what if the events fulfill commitments for processes, and also commitments for exchanges?  And can a commitment for a process be the same as a commitment for an exchange?

Here is a proposal, to be validated with some yaml soon.  I think we need 2 kinds of commitment, and not try to use the same instance of commitment for process and exchange, even though one event can fulfill both.  Sometimes it would work, sometimes it wouldn't.  And conceptually it is a bit different: "I commit to do some work on this process", "I commit to exchanging this work for some apples.".

How about TransferCommitment, and ScheduledCommitment (or ProcessCommitment, or PlannedCommitment) ?  And we would need a superclass of Commitment.

Then work or other action event on a process would tie directly into a ScheduledCommitment.  Some action event as part of an exchange would tie to the TransferCommitment through Filfillment.  Or it could be OK to tie directly to Commitment and support both process related and transfer related to make it simpler when there would be no m:m.  Something like:

![fulfillment](https://cloud.githubusercontent.com/assets/3776081/24518125/61ce65c6-1546-11e7-8c51-09f2fcff6ffd.png)

**Comment by elf-pavlik** [comment]
> And can a commitment for a process be the same as a commitment for an exchange?
[...]
>  I think we need 2 kinds of commitment, and not try to use the same instance of commitment for process and exchange, even though one event can fulfill both. Sometimes it would work, sometimes it wouldn't. And conceptually it is a bit different: "I commit to do some work on this process", "I commit to exchanging this work for some apples.".

I see no problem with "I commit to do some work on this process in exchange for some apples" and currently don't see need to create 2 commitments for that which would pretty much say the same.

> How about TransferCommitment, and ScheduledCommitment (or ProcessCommitment, or PlannedCommitment) ? And we would need a superclass of Commitment.

If we do that, we need a way for 'ScheduledCommitment' to reference 'TransferCommitment' from which some particular quantity should get deducted.

**Comment by fosterlynn** [comment]
@elf-pavlik The way I am thinking about it is:

1. Pavlik agrees to do 10 hours of work this month for Jane in exchange for 5 bushels of apples.  This creates an Exchange Agreement with 2 TransferCommitments.

2. Pavlik schedules himself for 3 hours work for Jane on one of Jane's processes.  This creates a ScheduledCommitment for 3 hours related to the process.

Since the exchange agreement happened first, you can't just hook the process commitments to the exchange.  The first one is your "promise", the second is your "commitment", if I recall the chat.

We shouldn't need to hook the two commitments together, because you can find their connections through provider:Pavilk, receiver:Jane, action:work.  And probably type of work too.  They would hook together because one is related to an exchange, one to a process (you wouldn't relate 2 exchange commitments or 2 process commitments.)  There is no need to actually subtract, rather handle it like any ongoing planning logic, which already looks at onhand, commitments, etc. when planning.

Anyhow, I'll do some yaml, I think that will make it more clear and we'll find those devils in the details.

**Comment by elf-pavlik** [comment]
> We shouldn't need to hook the two commitments together, because you can find their connections through provider:Pavilk, receiver:Jane, action:work. And probably type of work too.

I could 'promise/pledge' some more general 'type of work' and then make commitment on more precise 'type of work'. I would prefer not to rely those 'types of work' need to stay connected as broader/narrower using a taxonomy. Do you see a problem with 'scheduled commitment' referencing that 'promise'.

>1. Pavlik agrees to do 10 hours of work this month for Jane in exchange for 5 bushels of apples.  This creates an Exchange Agreement with 2 TransferCommitments.

> 2. Pavlik schedules himself for 3 hours work for Jane on one of Jane's processes.  This creates a ScheduledCommitment for 3 hours related to the process.

What about just

"Pavlik schedules himself for 3 hours work for Jane on one of Jane's processes in exchange for 10kg of apples."

Do we need an extra 'promise' if we already have clear commitment?

**Comment by fosterlynn** [comment]
>"Pavlik schedules himself for 3 hours work for Jane on one of Jane's processes in exchange for 10kg of apples."

What is that if not a commitment?  Would have to see your model.

And what if you do that first, then agree on that being part of 10 hours for the month?

I did try to get it to be just one commitment, couldn't make it happen....

**Comment by fosterlynn** [comment]
And the commitments do get hooked up explicitly when the event(s) occur.  That is the time when either software or a person can hook them up, like Pavlik logs his 3 hours of work on Jane's process, says this work is part of those commitments, which he probably knows, having made them.

This kind of thing happens all the time when we are talking about outputs instead of inputs - like someone orders 10 items, there are 5 in stock, a process is scheduled for the rest, but the recipe calls for batches of 20, so 20 are produced.  

I'll try yaml for this kind of use case too.

**Comment by elf-pavlik** [comment]
> And what if you do that first, then agree on that being part of 10 hours for the month?

This 3h commitment could still reference that 10h promise. Either by editing it or if we keep them immutable superseding it with updated one. 

> And the commitments do get hooked up explicitly when the event(s) occur. That is the time when either software or a person can hook them up, like Pavlik logs his 3 hours of work on Jane's process, says this work is part of those commitments, which he probably knows, having made them.

I still see no problems for those 'promises' (TransferCommitments) and 'commitments' (ScheduledCommitments) to reference each other. For example 'commitment' -- *vf:promissedIn* --> 'promise'.

**Comment by fosterlynn** [comment]
>I still see no problems for those 'promises' (TransferCommitments) and 'commitments' (ScheduledCommitments) to reference each other.

We could try it with the direct references, I suppose it would be a m:m?  Or could we get away with 1:m, and just create more process commitments if needed?

**Comment by bhaugen** [comment]
Consider also what it will mean to code that needs to follow resource flows. I'll think about that more when I see some of those yaml examples...but I'm concerned about exceptions in the logic.

**Comment by elf-pavlik** [comment]
m:m e.g two pledges 10h & 6h, first has 2h left and one makes 4h commitment which takes 2h from second pledge. pretty much whenever we can have pledge m:m event we can have scheduled commitments before events... somehow it looks like allocation but for use, work, service we don't have stocks to allocate from so we allocate from those pledges.

**Comment by bhaugen** [comment]
Please define pledge.

**Comment by fosterlynn** [comment]
>m:m e.g two pledges 10h & 6h, first has 2h left and one makes 4h commitment which takes 2h from second pledge.

I don't see these as something where something can be "taken away".  They are simply commitments to different things - a process vs an exchange.  One contributes to getting some bigger thing accomplished; the other is something to exchange.  Nothing is taken away, just part of the exchange is fulfilled by the event.

**Comment by elf-pavlik** [comment]
I don't see them as "Commitments to different things". I also don't think one needs two kinds of commitments to represent
> "Pavlik schedules himself for 3 hours work for Jane on one of Jane's processes in exchange for 10kg of apples."

I don't like naming *vf:TransferCommitment* and *vf:ScheduledCommitment* since in case above we will get instance `"@type": [ "vf:ScheduledCommitment", "vf:TransferCommitment"]`. If we define *vf:ScheduledCommitment* as one which has date defined, and *vf:TransferCommitment* as one that has *vf:provider* and *vf:receiver* defined and those two differ. Any instance having all above defined will fit both definitions and we can classify it as belonging to both of those classes.

When it comes to allocating *usage*, *work*, *services*, agent which will *receive* them and have as input to various processes can not use stocks as kind of a 'buffer' and this way have full control over the availability. One of specific requirements here comes for representing something like 'quota' agreed on between agents. Scheduling reception of those services (seeing *usage* as rental/lending service) may still require coordination between those agents, even if one providing uses automated scheduling system.

> We don't want to add the complexity of an event being split as input to 2 processes, since processes themselves handle the m:m requirement.

In cases where one allocated parts of resources in stock to processes, making two different commitments for two processes which reference same resource in stock doesn't make problem. When one has pledge from someone to work for 6h (already scheduled so also scheduled commitment). In those 6h that work can get allocated to multiple processes. Since we don't have WorkResource which we can manage as stock, we can not create a dedicated commitment for each process which would reference the same stock. If we do create dedicated commitments for each process, they don't have stock/resource to reference so they only can reference that initial commitment for 6h. And sum of hours in all per process work commitments shouldn't exceed those 6h. Just like sum of all *consume* commitments for today on particular stock (material resource) shouldn't exceed its current quantity (or current + expected to receive before process starts).


For material items and currencies, which can get managed as stocks and allow buffering their flows. One may still have agreement with commitment to provide certain quantity, which later before *issue* or *receive* events happen can have prior commitments that schedule them.

**Comment by fosterlynn** [comment]
At some point I think we will want to differentiate between commitments that are "mirrors" of events (1:m) and commitments that are more general.   There are many levels of agreement outside of the scope of REA commitments.

**Comment by fosterlynn** [comment]
>I don't like naming vf:TransferCommitment and vf:ScheduledCommitment since in case above we will get instance "@type": [ "vf:ScheduledCommitment", "vf:TransferCommitment"].

Well, if we don't need separate commitments for the process and the transfer, then we don't need the 2 names, and we go back to just vf:Commitment. :)

**Comment by elf-pavlik** [comment]
>> We shouldn't need to hook the two commitments together, because you can find their connections through provider:Pavilk, receiver:Jane, action:work. And probably type of work too.

> I could 'promise/pledge' some more general 'type of work' and then make commitment on more precise 'type of work'. I would prefer not to rely those 'types of work' need to stay connected as broader/narrower using a taxonomy. Do you see a problem with 'scheduled commitment' referencing that 'promise'.

I think we hit here again the nuances related to different meaning for 'type of work' if meant as reference to some shared taxonomy or meant more local reference to [Stock keeping unit](https://en.wikipedia.org/wiki/Stock_keeping_unit). Using internal SKU could very likely take care of:

> Since we don't have WorkResource which we can manage as stock, we can not create a dedicated commitment for each process which would reference the same stock. If we do create dedicated commitments for each process, they don't have stock/resource to reference so they only can reference that initial commitment for 6h. And sum of hours in all per process work commitments shouldn't exceed those 6h. Just like sum of all consume commitments for today on particular stock (material resource) shouldn't exceed its current quantity (or current + expected to receive before process starts).

Commitments between agents for various services (including usage and work), would most likely use references to common taxonomies. At the same time those agents may also want to use they internal SKU references to keep track of their stocks (even that we don't represent services as resources).

**Comment by fosterlynn** [comment]
Here is a yaml snippet with a picture (otherwise too much yaml).  Its purpose is to help think about this issue.  https://github.com/valueflows/valueflows/blob/master/snippets/order-fulfillment.md

**Comment by elf-pavlik** [comment]
If before events that will fulfill a promise we have scheduled commitments, in similar way as we use *Fulfillment* we can use something like *Scheduling* 

![copy of order-fulfillment](https://cloud.githubusercontent.com/assets/876431/24624816/a28f8df4-1872-11e7-9c4d-3b66ad1c8c66.png)

This way for each promise one can keep track on scheduled commitments vie *Scheduling*, just like we can keep track on events via *Fulfillment*

**Comment by fosterlynn** [comment]
Resolved.

**Comment by elf-pavlik** [comment]
`vf:includedIn` discussed in #290 also seems relevant for this issue
