### ISSUE TITLE
Where / how to publish VF doc?

### ISSUE THREAD

**Issue by fosterlynn** [valueflows/valueflows#184]
From gitter:

Paul Mackay
@pmackay
11:58
that would be cool. I was also wondering whether (if this is of interest) it might be worth starting a Readthedocs project and building up docs that can be viewed there? Doesnt preclude iteration and rework, etc.
elf Pavlik
@elf-pavlik
12:05
I've seen some nice docs published with https://www.gitbook.com/ eg. https://redux-saga.github.io/redux-saga/
people also use Readthedocs for non software projects ?
Paul Mackay
@pmackay
12:06
do you prefer gitbook? Also very good, I'm easy either way. Gitbook is very clean.
elf Pavlik
@elf-pavlik
12:08
i just haven't looked into Readthedocs and had impression that people mostly use it for software projects
while we have more of a spec + some tutorials / cookbook

**Comment by pmackay** [comment]
I've spent a bit of time reviewing Gitbook as a tool. I agree with @elf-pavlik that it's used for a wider range of topics than software (perhaps ReadTheDocs is quite focussed on SW). Also the toolset is very good, including an editor app for local content writing.

@fosterlynn @bhaugen would you see the docs being part of this project? That feels logical to me, in which case a `/docs` directory could be used to contain all the Gitbook content. The simplest approach might to start the creation of a Gitbook structure in this repo and then import it into Gitbook.

**Comment by bhaugen** [comment]
> @fosterlynn @bhaugen would you see the docs being part of this project? 

Yes. I don't care where they go, gitbook or readthedocs. I've met Eric Holscher a couple of times, and know that this is a labor of love, and think the support team would welcome VF, but I can go happily along with gitbook if that is the rough consensus.

**Comment by fosterlynn** [comment]
I don't know enough about either to have an opinion.

I started some doc last year which we can use as a starter - probably needs reformatting and reorganizing - https://github.com/valueflows/valueflows/tree/master/release-doc-in-process.  The new UML and VOWL was intended to go in there, and will need definitions for the added things.

**Comment by pmackay** [comment]
Would you like me to have a go at setting something up in Gitbook? I'd be happy to test it out.

**Comment by fosterlynn** [comment]
>Would you like me to have a go at setting something up in Gitbook? I'd be happy to test it out.

That would be awesome @pmackay !

**Comment by pmackay** [comment]
Have setup https://valueflows.gitbooks.io/valueflows/content/ as a starting point with a couple of pages copied from release-doc-in-progress README.

**Comment by pmackay** [comment]
For reference check https://toolchain.gitbook.com/pages.html for info on how the pages and summary index are setup. And other pages in that guide for details on the formatting, etc. 

Suspect you will have a better understanding of how might be best to define the structure :)

**Comment by fosterlynn** [comment]
Thanks @pmackay !  I will get familiar and move the other doc over there so we can iterate.  (But probably not this weekend.)

**Comment by fosterlynn** [comment]
I need some help understanding what our workflow and data structure should be for this documentation.

For example: The principles got updated earlier today (PR and merge), but that was in our regular repo doc copy, not the gitbook copy in docs.  So I just updated it there too, but it would be good if we settled on one main copy for this stuff, realizing that some of the content needs to go in the gitbook and some in the readme's and a lot in both.  

As another wrinkle, I'm looking where should I start a more disciplined approach to a first release (0.1) of core elements where we have agreed or are very close, and using PRs to get it done.   (Done for an early release of course, not cast in cement for all time.)

Should I use the gitbook docs directory for that?  And/or do we want to version the releases in some way vs the gitbook doc?  And how would this fit in with the RFC process mentioned by @enricostano .

And yet another wrinkle, there is a script written by @ahdinosaur early on that takes doc (readme's?) and puts it into valueflo.ws website.  So all of this should get coordinated in some way.

Help! :)  Anyone got experience with a good way projects manage all of this?

**Comment by pmackay** [comment]
>but that was in our regular repo doc copy

Do you mean the `release-doc-in-progress`? I was assuming the gitbook docs folder would replace that, as its a format that will publish to gitbook.

How much needs to go in the README from now on? I almost wonder if the README needs trimming down to just be an intro to the project so the actual docs are in one place.

> I'm looking where should I start a more disciplined approach to a first release (0.1) 

Would this happen by updating master until 0.1 is reached and then tagging it? Gitbook should be able to do versions (need to check how that works).

> there is a script written by @ahdinosaur early on that takes doc (readme's?) and puts it into valueflo.ws website.

Again I wonder if that site should be slimmer and a general project intro rather than having tech detail of the vocab, just to avoid repetition. What is that site built on? Something like Jekyll?

All this just my thoughts, your call of course :)

**Comment by fosterlynn** [comment]
@pmackay thanks for responding! :)

>Do you mean the release-doc-in-progress? I was assuming the gitbook docs folder would replace that, as its a format that will publish to gitbook

No, I agree with ditching that.  And I'll take that doc and get it all into gitbook.

>How much needs to go in the README from now on? I almost wonder if the README needs trimming down to just be an intro to the project so the actual docs are in one place.

This would solve it.  And that sounds good to me just in general, I think it is not that great having the doc split by repo.

>Again I wonder if that site should be slimmer and a general project intro rather than having tech detail of the vocab, just to avoid repetition. What is that site built on? Something like Jekyll?

Actually, it doesn't have all the detail, although I think it may have all of the valueflows/valueflows/readme.md - probably too much detail.  Maybe we can tailor that readme to feed the website, at least while investigating how it works and thinking about what we want there.

**Comment by fosterlynn** [comment]
>What is that site built on? Something like Jekyll?

It is built periodically using a script that @ahdinosaur put together, which I would need to dig around to find.  Might be in the "magic happens here" directory... just kidding... :)

**Comment by elf-pavlik** [comment]
I think we could simply use the gitbook as the homepage and just configure domain name as explained on https://help.gitbook.com/books/can-i-use-custom-domain.html

**Comment by pmackay** [comment]
>I think we could simply use the gitbook as the homepage

This makes things even simpler so worth considering IMHO.

**Comment by fosterlynn** [comment]
>I think we could simply use the gitbook as the homepage

makes sense to me also :+1:

**Comment by elf-pavlik** [comment]
AFAIK only @ahdinosaur has access to configure valueflo.ws DNS records

**Comment by pmackay** [comment]
Reckon ok to close this @fosterlynn ?

**Comment by fosterlynn** [comment]
Yup, closing.  Thanks a bunch @pmackay ! :+1: :heart:
