### ISSUE TITLE
vf:Category or not?

### ISSUE THREAD

**Issue by fosterlynn** [valueflows/valueflows#186]
I have a question on category.  My original thinking was that there would be no vf:Category class defined in VF.  There would be a vf:category property that would reference some place in the existing taxonomies of resource categories.

But several people have referenced vf:Category in different discussions in the last few days, and the ofd model subclasses from it. 

I realize that we will get different things back, depending on what the taxonomies provide.  On the other hand, wikidata etc. are not going to just provide VF vocabulary on demand.

What is the best way to think about this, LOD fans?

**Comment by pmackay** [comment]
>vf:category property that would reference some place in the existing taxonomies of resource categories.

I'd see this as logical, which is what I'm (perhaps badly) trying to explore in https://github.com/valueflows/valueflows/issues/183#issuecomment-282659640.

**Comment by fosterlynn** [comment]
>I'd see this as logical, which is what I'm (perhaps badly) trying to explore in #183 (comment).

Ah yes, that is one of the places I saw vf:Category. :)  Sorry I may not have picked up where you were going.  Does this mean you think there isn't a vf:Category?

**Comment by pmackay** [comment]
>On the other hand, wikidata etc. are not going to just provide VF vocabulary on demand.

No, but if we're reusing, perhaps VF's goal is to document best practice and how to create and maintain interoperable taxonomies, using existing ones as much as possible? Im not sure how constrained ones such as the food one @djodjoni needs could be published but there are various ways.

BTW, I noticed that its possible that more "equivalent classes" could be added to Wikidata (I added the Agrovoc class to [beer](https://www.wikidata.org/wiki/Q44)). @elf-pavlik have you thought about whether that might be useful?

**Comment by djodjoni** [comment]
:) btw its probably only me who wrongly interpreted that :)
 vf:Category I wrongly assumed form UML. 
The whole thing about Category in general is that VF may not need it at all but for specific applications you may need various 'trees' of categories. meaning category for Actors, Resources of different types etc, which cannot be satisfied always by the commons?

So we say we don't introduce Category class in VF just category property ?
btw @elf-pavlik is on the same opinion as I can see 
https://github.com/valueflows/valueflows/issues/183#issuecomment-282602902
> We don't have to define rdfs:range for vf:category which would allow anything (all instances of owl:Thing which includes any possible instance), this way vocab supports using any URI as category.

**Comment by elf-pavlik** [comment]
:-1: defining *vf:Category* (*owl:Class*)
:+1: just the property *vf:category* possibly with open *rdfs:range* (*owl:Thing*) or *skos:Concept* if that helps with anything.

BTW even if we define *rdfs:range* with *vf:category* as *skos:Concept*, it *does NOT restrict* anyone to just reference entities which already have *rdf:type* *skos:Concept*. One can reference any instance except those which have some *rdf:type* **disjoint** with *skos:Concept*. Referencing instance of *wikibase:Item* would just use RDFS inference to add to it one more *rdf:type* - *skos:Concept*.

**Comment by djodjoni** [comment]
One extra thought just o clarify (which does not change anything :)
This includes several discussions on the topic.

Shall we agree that there is only the vf:category property  which has unbound range. and this is where its stops with the VF.

when it is used/extended one can/should use any of the common Ontologies or create custom categories which can be anything but preferably link to the commons (this is what I am trying to do in OFD) 

so example as I see it:
Level 0; VF - basics
Level 1: OFD - add specific category root for food resources - FoodType
Level 2.1: farmer A - Create ResourceTemplates using Wikidata Items and with software OFN
Level 2.1: farmer B - Create ResourceTemplates using Agrovoc concepts and with software Drupal
Level 2.2: webshop X -  Create custom concepts using FoodType Root referencing Agrovoc and create ResourceTemplates using those concepts with software WP+WooCommerce
Level 2.2: webshop Y -  Create custom concepts using FoodType Root referencing Agrovoc and Wikidata, and create ResourceTemplates using those concepts with software Prestashop
Level 2.2.1 webshop Z - Create custom concepts on top of the ones of Y

so : 
A does not  understand B
X  understand A via Y
X  understand B, Y via agrovoc
Z, Y understand A and B

**Comment by djodjoni** [comment]
> BTW even if we define rdfs:range with vf:category as skos:Concept, it does NOT restrict anyone to just reference entities which already have rdf:type skos:Concept. One can reference any instance except those which have some rdf:type disjoint with skos:Concept. Referencing instance of wikibase:Item would just use RDFS inference to add to it one more rdf:type - skos:Concept.

Im just giving examples with SKOS because for me is easier to use that to build custom taxonomy :)

**Comment by fosterlynn** [comment]
Decision: There is no actual vf:Category class.  Closing.  Please re-open if you think this is premature!

**Comment by djodjoni** [comment]
ill make changes to the ttl in a PR and ill push it also as jsonld :)
