### ISSUE TITLE
DatatypeProperty limitations

### ISSUE THREAD

**Issue by fosterlynn** [valueflows/valueflows#202]
Harvesting from the last PR related to the ttl file, before it gets merged, between @djodjoni and me.  

>>>>> +vf:trackingIdentifier a owl:DatatypeProperty ;

>>>>DatatypeProperty could limit future uses, as ID could be represented by an individual resource. something like skos labels had suffered from and skos-xl emerged to solve this.

>>>This is interesting, I'm not sure how to think about it. In that case should we use owl:Thing?

>>Rather ObjectProperty

>But for our known use cases, it is a string - a lot number or serial number....

I need to study up on owl:DatatypeProperty and how to best use it in any case. :)

**Comment by djodjoni** [comment]
> But for our known use cases, it is a string - a lot number or serial number....
simple example lot number might be the same string but different instance if it is issued from different agents or just have different meaning. In the past I have dealt with stock control systems where you need to store different numbers for the same item depending on the issuer and the actors in the chain. There could be many examples like this. In GR or schema org they have SKU, GTIN, MPN etc. In VF it is not clear what is that and in practice can be anything.

**Comment by fosterlynn** [comment]
If we make it an ObjectProperty, can it be a string?

I'm thinking about your other example identifiers.... we may need something else for them, for example a lot number has to carry through any number of stages in flows, and be clearly accessible; but a SKU might be only an identifier to one agent, etc....  more thought needed.... @bhaugen may be able to help with this too.....

**Comment by djodjoni** [comment]
you can wrap a string in an individual value or use owl:AnnotationProperty as well which then can have both individual and data values.

**Comment by fosterlynn** [comment]
Actually, thinking about it, GTIN and SKU are for resource types/models rather than resources themselves.  Don't know about MPN.  Will need to address that when we do the top layer.

I like owl:AnnotationProperty though, just in case, from what I read about it.  I'll change it.

**Comment by djodjoni** [comment]
> GTIN and SKU are for resource types/models rather than resources themselves. Don't know about MPN

indeed they are, having as a datatype property for example id string or any other property that might be useful. Individuals of those can actually be a tracking identifier. there are different ways to do it as mentined above having different properties for each type. I think i prefer on single propery accepting different types but have no particular objections to the multiple properies option.

**Comment by fosterlynn** [comment]
Changed to owl:AnnotationProperty for trackingIdentifier.  Left a comment in the ttl file for GTIN etc., closing issue.
