### ISSUE TITLE
Get gitbook working with lode

### ISSUE THREAD

**Issue by fosterlynn** [valueflows/valueflows#207]
Ref. #184 -- this is a detail of that one.

@djodjoni introduced [LODE](http://www.essepuntato.it/lode) for formatting our class and property specs from the .ttl file, and it works great, is open source, love it.  @pmackay set up Gitbook for us to move all the VF doc into, works great, open source, love it.

I'm having trouble getting my generated LODE page to work inside Gitbook.  @djodjoni is this something you would like to put some time into while (or instead of) working on the .ttl validation on PRs?  It would be really helpful.

So far: I tried just calling our generated LODE page from a gitbook side bar in SUMMARY.md, and it generates the page, but as a new tab, maybe OK but not the best.  So then I saved the source from our generated page, made it a .md file, and connected it like any other page on the side bar in SUMMARY.md.  It stays in the gitbook structure fine, but lost its style.  I thought maybe it was just a matter of css relative references, but all of them are full path.  I think the problem is that the stylesheets are referenced hidden inside whatever div is created by gitbook?

One possible solution I found: https://github.com/chudaol/gitbook-plugin-addcssjs.  But maybe there is something much easier and more obvious, I don't know.

Anyhow, I'd love to hand over this task to someone a bit more techy than me. :)

**Comment by djodjoni** [comment]
Just back from a few busy days and seeing lots going on 👍  
I'll try to make this work

**Comment by fosterlynn** [comment]
hi @djodjoni thanks!  

I put it back to where it just opens the LODE spec in another tab, with its styling intact.  I'm actually getting used to that - well a little used to it. :)  Why don't you take a look and see what you think is worth spending time on. 

Another option is to create a front page which links into the gitbook (with spec removed) and the spec separately.  If we do that, we could do a prettier front page.

What direction do you think we should go?

**Comment by djodjoni** [comment]
I took a look and it can work also if we put the styles in the book, however I think I like the LODE specs as a separate page indeed. 
In fact I would point https://w3id.org/valueflows/ to the LODE specs if the browser requests text/html or the .ttl in the case of text/turtle, .jsonld file in case of browser accepting "application/ld+json" etc. 

> Another option is to create a front page which links into the gitbook (with spec removed) and the spec separately. If we do that, we could do a prettier front page.

I personally like the gitbook generated site. it is simple and clear I don't think there is a need of 'prettier' page :)

**Comment by fosterlynn** [comment]
OK let's go with your call @djodjoni unless others disagree....  :)

>In fact I would point https://w3id.org/valueflows/ to the LODE specs if the browser requests text/html or the .ttl in the case of text/turtle, .jsonld file in case of browser accepting "application/ld+json" etc.

So we would need to create a json-ld file then, right?  And do we know how to do that at w3id.org?

I also noticed we need to do something about the individual element links to IRIs in w3id.org site, which are links on the LODE spec and currently don't go anywhere.  All in good time, of course.

**Comment by elf-pavlik** [comment]
@djodjoni I haven't used Apache for ages, maybe you can figure out how to add content negotiation to https://github.com/perma-id/w3id.org/blob/master/valueflows/.htaccess
If you do, please make PR to w3id.org and mention me in it

**Comment by djodjoni** [comment]
Sure, ill do this later tonight

**Comment by djodjoni** [comment]
ok w3id is updated and works I need to fix the css and js of the LODE to put it local but this I will include as part of auto-generator, which then will push the onto files to hg-pages branch.

@elf-pavlik do mind if I setup travis for that?

**Comment by elf-pavlik** [comment]
please go ahead @djodjoni :+1:

**Comment by fosterlynn** [comment]
closing

**Comment by djodjoni** [comment]
ill open a new one to complete the build automation :)
