### ISSUE TITLE
Switch to gitbook for valueflo.ws

### ISSUE THREAD

**Issue by fosterlynn** [valueflows/valueflows#208]
Probably any time after this current PR is merged we could switch to gitbook for our website - although it is not final for release 0.1, it is a lot better than our .md files, which are what is being pulled now.  Every day I either post or see more references to VF (CTA, Commons Transition, FairCoop, etc), it sure would be good to upgrade the website!

Anyone know how to hook it up?

Also, @ahdinosaur wrote a script way back in the day :heart:  that pulls the readme.md file in to the website.  I wonder if that is what the codeship check on PRs is about??  (I am completely guessing.)  So that would need to be removed, wherever it is.

Another thought: We would want to version it so that ongoing changes don't affect the website, until we're ready to commit it there, maybe on new releases?  Ideas?

**Comment by ahdinosaur** [comment]
:+1: yeah this is a great idea. happy for someone to setup a GitBook, at which point i'll point the domain to that instead of my server.

> Another thought: We would want to version it so that ongoing changes don't affect the website, until we're ready to commit it there, maybe on new releases? Ideas?

i believe GitBook supports versioning, probably as branches or something. happy if we had a "stable" branch that is our latest release. we could also tag versions to be extra legit.

**Comment by pmackay** [comment]
I added `valueflo.ws` to the Domains section of https://www.gitbook.com/book/valueflows/valueflows/details. However then I realised it immediately redirects, so removed it again (otherwise cannot see the gitbook at all).

It did show this message though:
```
valueflo.ws: Domain has no CNAME value
```

@ahdinosaur would you be able to update the registrar as per [these steps](https://help.gitbook.com/books/can-i-use-custom-domain.html)? Maybe that should happen first?

There is a [versions plugin](https://www.npmjs.com/package/gitbook-plugin-versions) which could be tried but it would be helpful to have a tagged version first. Specific versions can be accessed [via URL](https://help.gitbook.com/content/how-can-i-access-a-specific-version.html)

**Comment by pmackay** [comment]
Tried a quick local test and versions can be explicitly defined and they show up like this (as example):

![screen shot 2017-03-26 at 12 24 33](https://cloud.githubusercontent.com/assets/115115/24330837/4ba8e64c-121f-11e7-80d7-14206cde3256.png)

**Comment by fosterlynn** [comment]
@pmackay thanks! :1st_place_medal: 

>There is a versions plugin which could be tried but it would be helpful to have a tagged version first. Specific versions can be accessed via URL

I'll tag it in github after one final look-through after the merge.  And it sounds like we should tag it in gitbooks directly too, I'll take a look at the doc.

**Comment by ahdinosaur** [comment]
@pmackay okay, i think i updated the registrar.

**Comment by fosterlynn** [comment]
It is good to switch now; although the most recent commit is not tagged.

**Comment by elf-pavlik** [comment]
@ahdinosaur did you configure CNAME record as suggested in https://help.gitbook.com/books/can-i-use-custom-domain.html ? gitbook complains that `valueflo.ws` doesn't have that CNAME record

**Comment by ahdinosaur** [comment]
> [EDIT] I see now that you have it only for www subdomain, I guess we can't use the main domain with gitbook.com ?

yep! iwantmyname.com (my registrar) only supports normal CNAME, not fancy ALIAS or naked domain CNAME. i setup a redirect from valueflo.ws to www.valueflo.ws, so should be all good. (it's the same as what i've done for both rootsystems.nz and scuttlebutt.nz.)

**Comment by fosterlynn** [comment]
I'm pretty sure that https://valueflo.ws/ used to work, and that we have spread that link around in various posts though.....  :worried:

**Comment by ahdinosaur** [comment]
ah true. hmm..

**Comment by ahdinosaur** [comment]
will update [the server](https://github.com/valueflows/valueflo.ws) we were using before to handle this redirect correctly.

**Comment by ahdinosaur** [comment]
okay, i think it works. once the DNS propagates can someone double check?

**Comment by ahdinosaur** [comment]
also great website folks! :tada:

**Comment by elf-pavlik** [comment]
It works, thanks @ahdinosaur 

> also great website folks! :tada:

@pmackay got us started with gitbook and @fosterlynn did most of the work in putting all the docs together :tada:  with some help from @djodjoni on LODE and the .ttl

**Comment by pmackay** [comment]
@fosterlynn did you want to use the tagging plugin and fix the tag that the Gitbook is pointing at?

**Comment by fosterlynn** [comment]
@pmackay Yes, but let's give it a day, Bob is doing some fixes, then I'll tag it in github and we can point to that?  Does this make sense to you?

**Comment by fosterlynn** [comment]
@pmackay ok tagged 0.1 and pushed, I hope the tag went up.... if not, feel free to tag as 0.1.    And thanks!!

I'll close the issue again when this is working....

**Comment by fosterlynn** [comment]
@pmackay my tag didn't get pushed, but Pavlik created a tag, so if you want to set this up, awesome.  If not, no worries, let us know. :blush:

**Comment by pmackay** [comment]
Will try to take a look soon. I've been away for a few days....
