### ISSUE TITLE
Units: How to deal with units not defined in QUDT?

### ISSUE THREAD

**Issue by fosterlynn** [valueflows/valueflows#215]
[QUDT](http://qudt.org/), which we decided to use early on for our quantities, is a very complete set of units of measure, with conversion capabilities, for the scientific community.  They even have complex units, like GallonUSPerDay.  Here is our initial definition: https://github.com/valueflows/valueflows/pull/5/files

QUDT also is adding other kinds of units, like Currency, but as far as I can tell, this is not ready yet.  And it will never have Faircoin. :)

Here also is an older issue #152 with suggestion for units of time.

But.... Here is a group extending QUDT: http://www.openphacts.org/specs/2013/WD-units-20130913/.

And here is a discussion in schema.org about how to map to qudt - they have a lot of units defined also. https://github.com/schemaorg/schemaorg/issues/1390

So, this issue is to nail down how we will define quantities and units, since it affects our core entities.  Should we:
* Show how to define new units in QUDT, even define some we know are needed?  And define our vf:quantity to only be defined in QUDT?
* Allow a vf:quantity property to reference different vocabulary definitions of instances of units?

**Comment by elf-pavlik** [comment]
I think we need https://en.wikipedia.org/wiki/Dimensionless_quantity

http://qudt.org/doc/2017/DOC_VOCAB-UNITS-BASE.html

has `unit:NUM` and `unit:UNITLESS`

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/valueflows/-/issues/215.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
