### ISSUE TITLE
lend/borrow - P2P, tools library ...

### ISSUE THREAD

**Issue by elf-pavlik** [valueflows/valueflows#220]
As discussed during our last call, I'd like to start looking at how to model lend/borrow which includes changing possession A->B and B->A (return) but no ownership.

#### P2P

* Bob borrows a photo camera from Alice (S/N 1234) at given place and at given time
* Bob agreed (while picking it up) to return it to Alice at the same place exactly one week later
* During the time that Bob stays in possession of that camera, he uses it 4 times
* At agreed time Bob returns the camera to Alice

#### Tools library

TODO

#### P2P

* The camera (serial resource) stays denoted by IRI https://alice.example/stuff/photo-camera-1234
* When Bob picks it up, we have EconomicEvent (eg. *issue*) and Commitment made by Bob that he stays responsible to return it exactly one week later (eg. *receive*)
* Bob tracks usage of the camera (4 times) by creating an EconomicEvent (*use*), which references as resource https://alice.example/stuff/photo-camera-1234
* When Bob retuns the camera, we have EconomicEvent (eg. *receive*) which fulfills the Commitment made by Bob

##### notes

* If Alice and Bob used some online platform, they both could have made Commitments before the events 1 - where the camera gets picked up and 2- where it gets returned.

**Comment by fosterlynn** [comment]
>When Bob picks it up, we have EconomicEvent (eg. issue) and Commitment made by Bob that he stays responsible to return it exactly one week later (eg. receive)

Hmmm.  Or do we have an issue and a receive both when Bob picks up the camera (Alice issues, Bob receives)?

Or do we just have a transfer of some rights to use?  From Alice to Bob.

**Comment by fosterlynn** [comment]
I think we should move this one to the Transfer milestone.

**Comment by elf-pavlik** [comment]
> The camera (serial resource) stays denoted by IRI https://alice.example/stuff/photo-camera-1234

Since we have only one resource, as I mentioned in https://github.com/valueflows/valueflows/issues/270#issuecomment-474053671

> I wrote many variants of moving resources around in https://github.com/valueflows/valueflows/pull/386/files including decrement of specific resource in one place and increment the same resource in another place.

This could apply to this camera as well. Alice can *issue* it in one place and Bob can *receive* it in another place using the same resource `https://alice.example/stuff/photo-camera-1234`. Also since Bob picks it up, transfer would only happen on Alice's *issue* not Bob's *receive*. Later again it would happen on Alice's *receive* since Bob would deliver it (drop off), not on Bob's *issue* at his place. *We could use *load* & *unload* here just as well as *issue* and *receive*.

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/valueflows/-/issues/220.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
