### ISSUE TITLE
improve repository structure in openvocab orga

### ISSUE THREAD

**Issue by elf-pavlik** [valueflows/valueflows#23]
https://github.com/openvocab

* seem not used or needed: membership, role, place, group, person, core
* ovn - makes sense as general workspace focused on putting all other elements together
* holodex - rename to **agent**? while I find it a cool name, for most people it will make no sense. also brings confusion with https://github.com/holodex
* exchange - makes sense to me as one of ovn sub workstreams, for example IPO tables experiment might ignore this part and focus just on process

**Comment by bhaugen** [comment]
We do intend to create another substream focused on process. If IPO tables
wants to take an active part, that would immediately trigger the substream.

**Comment by elf-pavlik** [comment]
@Lars2i what do you think? To my understanding you don't want to get into *exchanges* and *currencies* aspect of OVN. But if we isolate **process** aspect nicely as well as **ressources** (or assets) for I/0, we would all find nice common ground to work on.

**Comment by ahdinosaur** [comment]
:+1: 

- [ ] remove unused
- [ ] rename holodex to agent
- [ ] add @elf-pavlik as org admin

maybe also make a `meta` repo for discussions like this?

**Comment by ahdinosaur** [comment]
i also recommend we update [meta](https://github.com/openvocab/meta), as it hasn't changed since this org began; i think it could be useful to link the repos together, provide overall context, and be a space for discussions like this.

**Comment by bhaugen** [comment]
@elf-pavlik @ahdinosaur - I'm good with whatever restructuring you all want to do.

**Comment by Lars2i** [comment]
@elf-pavlik from what i understand, sounds good.

**Comment by bhaugen** [comment]
Do you all want to initiate the projects repo, or should I do it?

If you do it, please make it so both we (NRP) and IPOTables can comfortably use it. For example, include something like:
![Recipe, Plan, Reality](https://camo.githubusercontent.com/4e022abb6358edae8b381fedf1899d23b8eaac2e/68747470733a2f2f692e696d6775722e636f6d2f373467495935432e706e67)
where IPOTables lives in the Recipe layer (if I understand correctly).

And if I do it, I'll include something similar that would show the IPOTables view. @Lars2i - got any suggestions? Is some of the language and the diagram from http://ipotables.net/ good for starters?

Then we can work out the details in issues.

**Comment by elf-pavlik** [comment]
@bhaugen please just go ahead and start *process* repository including in the README whatever you see fitting there. We can all iterate from it using issues and pull request workflow :dart:

**Comment by elf-pavlik** [comment]
@ahdinosaur I don't understand difference between *ovn* and *meta* repositories :confused: Can't we just move few bits of information from meta to ovn and then if really needed rename it?

**Comment by bhaugen** [comment]
First draft done: https://github.com/openvocab/process

Please improve.

**Comment by ahdinosaur** [comment]
@elf-pavlik my thinking is that this org is for all vocabs, not only value network vocabs although that's what i'm most interested in. but happy with whatever the group wants to do with this org, i'll follow along.

**Comment by ahdinosaur** [comment]
from https://github.com/openvocab/ovn/issues/17#issuecomment-135807072, :+1: to a separate vocab repo for resource, as it seems "assets" from ["Open OS"](https://docs.google.com/document/d/1as22xHOG5JzxKb8sDZW4iCyQHh8st52g3bAXoYzoYHc/edit?pli=1#heading=h.odkahue79nna) (which i'm now using as my reference Enspiral use case for Holodex) would be resources with relationships but no exchanges or processes.

**Comment by ahdinosaur** [comment]
i'm thinking this repo should be our "home repo" for this org.

to me, this means:

- [ ] rename this repo to `valueflows/valueflows`
- [ ] delete `valueflows/meta`
- [ ] over time edit the content of the this repo's README to be an overview of the entire vocab
- [ ] ? maybe eventually we generate the content in `valueflows.github.io` from the content here (with markdown -> html conversions and other magic)

thoughts?

**Comment by fosterlynn** [comment]
@ahdinosaur sounds good to me. 

 Except I don't get the last one.... and I noticed that you have a generated context, and then I put out my context attempt in a different place.... sorry!

**Comment by ahdinosaur** [comment]
@fosterlynn yeah, at the moment i'm thinking [we follow @elf-pavlik's lead](https://github.com/valueflows/agent/pull/24) and put our per-vocab contexts within each vocabulary repo (based on the examples in that repo's markdown), then somehow we build everything all together (which may include using markdown sources in this repo) [into the website](https://github.com/valueflows/valueflows.github.io). this is all open for discussion and/or an experiment to find what works best through trying things out.

**Comment by elf-pavlik** [comment]
not sure how you did renaming of orgas but now both exist

* https://github.com/valueflows
* https://github.com/openvocab

it also got gitter chat room freaked out :wink:

**Comment by bhaugen** [comment]
https://gitter.im/valueflows seems to be a little confused, but also seems to work.

**Comment by ahdinosaur** [comment]
> not sure how you did renaming of orgas but now both exist
>
> https://github.com/valueflows
> https://github.com/openvocab
>
> it also got gitter chat room freaked out :wink:

yeah, that was me renaming and then creating `openvocab` again (in case i start another vocab project that doesn't fit within value flows, at least was what i was thinking). not sure i thought of all the consequences, sorry about that.

**Comment by bhaugen** [comment]
I sorta waiting to see if @elf-pavlik and @fosterlynn can get to the valueflows chat room.

If not, https://gitter.im/gitterHQ/gitter seems to be a pretty good place to ask for help.

**Comment by fosterlynn** [comment]
I can't get in, I get to a page for valueflows, but nothing is there, can provide details if it will help.

**Comment by bhaugen** [comment]
https://gitter.im/valueflows seems to work again, thanks to an intervention by @mydigitalself of gitter.
