### ISSUE TITLE
Event date: add end date?

### ISSUE THREAD

**Issue by fosterlynn** [valueflows/valueflows#230]
We have a start date on EconomicEvent, vf:start.  Working with some people now, sometimes people log several days work at a time, say a week in one event.  I'd like to suggest we add an end date, so people can put in one of those dates, and it is explicit what it means.

Another thing this made me realize is that in terms of time based events (work, use), duration is not really the right concept for a situation like this.  The duration might be a week, and the hours might be 40.

I can do a PR on this at some point, just noting it to not forget it. :)

**Comment by elf-pavlik** [comment]
Let's work on PR with example inspired by this issue to check that we cover it well.

**Comment by fosterlynn** [comment]
>Let's work on PR with example inspired by this issue to check that we cover it well.

https://github.com/valueflows/valueflows/pull/446/files, at the end of the work.yaml file.  Feedback welcome!

**Comment by fosterlynn** [comment]
resolved by the work on owl time
