### ISSUE TITLE
EconomicEvent.affects for work

### ISSUE THREAD

**Issue by fosterlynn** [valueflows/valueflows#231]
EconomicEvent now references its affected resource, which makes sense for inventoried resources.  We have also talked about if a material (or digital) resource is not inventoried, and we only have the category or model of the resource, that would still be a vf:Resource, but it would only have the category or model reference, not other info that exists on an inventoried resource.  (If I remember and understand correctly.)

I am trying to create VF compliant api, and ran into work events.  It is not very clear that an economic event "vf:affects" a category of work.  This is the first time I have seen an actual need to subclass or differentiate EconomicResource in any way.  I'm sure there are other ways too.

Ideas how to best handle this for VF?

For now, I created another property called workCategory.....

**Comment by elf-pavlik** [comment]
Since *work* event directly represents the work, I think you can simply use `vf:classifiedAs` to reference classification. 
Actually this doesn't directly relate to *schedules*, I added it to this milestone to quickly.

**Comment by fosterlynn** [comment]
I think this is too old, we have moved way beyond this, closing.  Please re-open if you think we need it.
