### ISSUE TITLE
New use case: pack, transport, unpack

### ISSUE THREAD

**Issue by bhaugen** [valueflows/valueflows#233]
This is a use case for [LearnDeep](http://learndeep.org/), an organization that runs student maker projects in Milwaukee Wisconsin schools. They're experimenting with our NRP software.

They get materials for projects from donors, store them in warehouses next to school workshops, and transport them from school to school using the Inter-Library Loan system.

Here's a [slide deck about transferring materials via inter-library loans](https://docs.google.com/presentation/d/1zhyh6F1Dum2pN9TPUel7HvD49Teq2-kolskRfR7SWHY/edit?usp=sharing).

The overview:
![pete- how to handle library transports](https://user-images.githubusercontent.com/117439/28753714-e289c932-74fd-11e7-986b-954705c35af5.png)

More concretely, materials are packed in containers, given to the sending school's local library for transport, which goes through the inter-library loan system, and then picked up from the receiving school's library, and unpacked.

Here's a simple NRP recipe:
![screenshot from 2017-07-30 08 09 05](https://user-images.githubusercontent.com/117439/28753747-a242b72a-74fe-11e7-9893-a742070a3754.png)

And here's a workorder (a plan) generated from the recipe:
![screenshot from 2017-07-30 05 31 23](https://user-images.githubusercontent.com/117439/28753755-c412b468-74fe-11e7-83e8-c3865cf892ab.png)

A "Packable" is any material that could be packed in a container and sent via this process flow. This is a parent recipe; the actual Packables would be the children of Packable, for example:

**Resource Type: Packable
Children:**
* Corrugated Cardboard Sheet
* Gear - plastic 1"
* Motor - DC 6v
* Wearable Tech Kit
* Wheels

We have several interesting issues about how to implement this use case, both in NRP and VF. If you are interested in discussing them, ask questions here or in https://gitter.im/valueflows/welcome .

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/valueflows/-/issues/233.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
