### ISSUE TITLE
Resource Specification

### ISSUE THREAD

**Issue by fosterlynn** [valueflows/valueflows#235]
I'm trying to reconcile the ways we can think about and identify resources (or planned or intended resources).  I'd like to improve our current model where an EconomicResource (on the observation layer) can be identified by just a ResourceTaxonomyItem (in cases where there is not an inventoried resource, where for a Commitment that is not the case.  Commitments often just specify the taxonomy item, but can specify a specific resource.  And for intents (offers/requests), this will be even more complex, where often it is just a set of categories, but could be more specific or could even be an existing resource.

Proposal (not solid enough to do a PR yet, but would really appreciate some feedback on this @elf-pavlik and anyone else interested):

Create a new thing called ResourceSpecification (or please suggest better name) that handles all the varying specificity of how people want to refer to resources (actual, planned, offered/requested).  I'm thinking to use EconomicResource only for inventoried/observable resources (material or digital).  

ResourceSpecification could include any of (would like help adding to or cleaning this up):
-- resource: an EconomicResource
-- model: a ResourceTaxonomyItem (as specific as needed)
-- category: a list of ResourceTaxonomyItems used for search and matching algorithms
-- producedBy: an EconomicAgent
-- recipeUsed: a ProcessTaxonomyItem

Then EconomicResource, Commitment, Intent/Request/Offer (however that model works out), and EconomicEvent would have a property to reference a ResourceSpecification, which would contain whichever combination of properties are needed.

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/valueflows/-/issues/235.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
