### ISSUE TITLE
Website certificate invalid

### ISSUE THREAD

**Issue by almereyda** [valueflows/valueflows#240]
Currently, the website https://www.valueflo.ws is not accessible due to an outdated certificate.

**Comment by bhaugen** [comment]
@ahdinosaur is this something you set up and could do something about? Or does anybody else now how to update the certificate or whatever else needs to happen?

**Comment by bhaugen** [comment]
Wait wait I just got there in firefox. @almereyda does it work for you now? Or if not, what browser?

**Comment by fosterlynn** [comment]
I also got in in FF; tried Chrome which also seems fine, and where I couldn't have any cache.  Seems like it was temporary.....

**Comment by elf-pavlik** [comment]
> The certificate expired on October 5, 2017, 6:59 PM. The current time is October 17, 2017, 10:52 AM.

**Comment by almereyda** [comment]
This is weird, my client displays me a working certificate created on September 23.

> Ausgestellt am	Samstag, 23. September 2017 um 02:29:00
Gültig bis	Freitag, 22. Dezember 2017 um 01:29:00

**Comment by bhaugen** [comment]
I  get roughly what @almereyda reported. Mine says created on Sept 22, expires Dec 21.

**Comment by fosterlynn** [comment]
OK, I finally got the error in FF, mine is like @elf-pavlik 's.

`The certificate expired on 10/05/2017 06:59 PM. The current time is 10/17/2017 06:56 PM.`

I don't know whether to worry about the different results.  But if do we need to renew our certificate, if somebody can tell me what to do, I'll do it and pay as needed.

**Comment by elf-pavlik** [comment]
no need to pay for the  cert - https://letsencrypt.org/

**Comment by ahdinosaur** [comment]
ah yes, i got a few emails leading up to this that i never actioned on. does somebody want to take over hosting the website? the current code is [pretty much only a redirect](https://github.com/valueflows/valueflo.ws/blob/master/server.js).

**Comment by bhaugen** [comment]
Aside: that should be https://www.rootsystems.nz/

**Comment by bhaugen** [comment]
I am very confused. When I go to https://valueflo.ws/ in Firefox, I see this, which seems to say that it is already using LetsEncrypt.
![screenshot from 2017-10-19 03-25-01](https://user-images.githubusercontent.com/117439/31761390-401d678e-b47d-11e7-99d8-2a60ed9e13f9.png)

In Chrome, I get this:
```
Your connection is not private

Attackers might be trying to steal your information from valueflo.ws (for example, passwords, messages, or credit cards). Learn more
NET::ERR_CERT_DATE_INVALID
```
Why the difference?

Also, if I go here first and click the Read button, I get to https://www.valueflo.ws/ just fine, no security error in Chrome at all:
https://www.gitbook.com/book/valueflows/valueflows/details

>  does somebody want to take over hosting the website? 

Where is it hosted now?

P.S. some of my confusion might be that I don't understand how gitbooks work, nor certificates, nor LetsEncrypt...so lots of ignorance...

**Comment by almereyda** [comment]
When opening https://valueflows.github.io/linked-data-browser/ directly, it the console warns about a missing CORS header on valueflo.ws

Also opening http://valueflo.ws redirects to https://www.valueflo.ws/ despite there's no `www` specified in https://github.com/valueflows/valueflo.ws/blob/gh-pages/CNAME

I guess there's another webserver involved?

---

@ecobytes may soon be able to offer dedicated static hosting, eventually based on DatHTTPD or Dokku.

---

All in Chrome

**Comment by fosterlynn** [comment]
>@ecobytes may soon be able to offer dedicated static hosting, eventually based on DatHTTPD or Dokku.

:+1: 

I would be happy to do grunt work (admin stuff) on this, but I am completely clueless on the technical side.  Like, if someone can write up or link to simple instructions, I can do them.  

Or if someone can just contribute by taking care of it, that would be truly awesome!

**Comment by bhaugen** [comment]
In the shorr term, I will start telling people to go here: https://www.gitbook.com/book/valueflows/valueflows/details and click the Read button.

If the best solution longer term is for @ecobytes to host it, let us know. Apparently this is how the financing works?
https://ecobytes.net/donate

We can handle that...:smile:

**Comment by elf-pavlik** [comment]
@almereyda could figure out best TLS config for gitbok and maybe if needed move it for now to VM `5.9.161.176` ?

@ahdinosaur maybe you could transfer the domain name to @fosterlynn and @bhaugen since they do most of the work on taking care of VF, this way they could manage DNS directly and collaborate with @almereyda on fixing the setup.

**Comment by bhaugen** [comment]
Another data point: right now, in both chrome and firefox,
https://valueflo.ws/ fails, 
but https://www.valueflo.ws/ is ok.

I think some of the anomalies I was seeing in some of the comments above was because I had used the www in firefox, but not in chrome.

**Comment by ahdinosaur** [comment]
https://www.valueflo.ws is hosted by GitBook.

but they can only host subdomains, so not https://valueflo.ws, which is hosted by my server and redirects to https://www.valueflo.ws.

i linked to https://rootsystems.nz (which errors) on purpose because i didn't make a special server to redirect to https://www.rootsystem.nz.

**Comment by fosterlynn** [comment]
@ahdinosaur thanks for the explanation!  (Although I didn't understand about rootsystems.)  

Would you like us to get https://valueflo.ws off of your server?  If so, anyone got ideas of where to host?  Bob and I have stuff on site5, but would like to move off of there when we have some energy. :)  There is a local small hosting company we are thinking of moving to, so we could include vf if you all want.  But are there better solutions?

**Comment by bhaugen** [comment]
@almereyda is @ecobytes ready to do this? See also upthread https://github.com/valueflows/valueflows/issues/240#issuecomment-338010787

**Comment by ahdinosaur** [comment]
https://www.valueflo.ws works fine. the only thing the server does is redirect from https://valueflo.ws to https://www.valueflo.ws.

i'd be happy to continue hosting, but i need a free afternoon / evening to focus on updating the setup. if anyone wants to do this sooner, i'm happy to point the dns elsewhere.

**Comment by ahdinosaur** [comment]
fixed with a simple nginx server hosting redirects using lets encrypt certificates. was pretty easy following https://www.nginx.com/blog/using-free-ssltls-certificates-from-lets-encrypt-with-nginx/ and https://stackoverflow.com/questions/10294481/how-to-redirect-a-url-in-nginx#10303879, was able to have the same server solve the same problem for https://rootsystems.nz and https://scuttlebutt.nz as well.

**Comment by bhaugen** [comment]
Thanks a lot!

**Comment by elf-pavlik** [comment]
Thanks @ahdinosaur !
I followed the same article a while ago to setup a cron job that auto-renews certificates without stopping nginx :)

**Comment by fosterlynn** [comment]
@ahdinosaur thanks you're awesome! :heart:

**Comment by almereyda** [comment]
Many thanks. Ecobytes is still in process of deciding proper hosting
schemes for redirects and static pages.

**Comment by fosterlynn** [comment]
>Many thanks. Ecobytes is still in process of deciding proper hosting schemes for redirects and static pages.

@almereyda please continue to keep us informed about Ecobytes, sounds like a useful resource for VF and others!
