### ISSUE TITLE
Use case: Validation of work for income distribution

### ISSUE THREAD

**Issue by fosterlynn** [valueflows/valueflows#244]
We've been working with FairCoop on some of their new internal systems, and it provides an interesting use case.  Also, we're implementing VF in an api on our software that feeds a new UI.

They are starting to systematize paying for internal work (with FairCoin as of now), and call it Open Coop Work.  Some people have a "salary" per month because those people need to rely on a basic income.  Other work is put out "Sensorica style" as work commitments that people can commit to and work on, on a more "ad hoc" basis.

Like at Sensorica, people can flag work (or other) events as something they would like to be paid for, or work as a gift.

Unlike Sensorica, they also are experimenting with ways to validate everyone's work.  Right now all the work has to be validated by 2 people from a project or group (scope) to be eligible for income distribution.  

Income distribution happens monthly, from an agreed-upon budget.  They get paid within a range, depending on the budget, and there is a maximum allowed per person.

#### Model / Vocabulary Possibilities

Right now in the software we have a flag on events where people can request payment in exchange for their work.  We think that isn't really right.  In VF we have moved to being able to exchange work (for example, but any event action) for any other event action.  In the case of FairCoop, this is some kind of Give or Issue or Disbursement  (or whatever) of Faircoin.  So we are thinking that instead, the people who want to get paid can create a vf:Commitment (in REA this is a Claim) for any number of events where they are the provider and the organization is the receiver.  The Commitment is a claim for some payment for the work.  Note the quantity of the payment isn't known yet because of the range of rates based on the budget.

Unlike our tentative exchange model, they need a commitment (claim-type) to cover more than one event at a time.  This is because they have the validation step, and they want to validate at a higher level than one event.  (So far this has been either commitment or process level, but they are still experimenting.  We think they will want to be able to choose any granularity that makes sense, could be a specific deliverable or a whole month or whatever.)

Anyhow, this is triggering some re-thinking of parts of the VF exchange model for us.  Will post on that later, either here or a new issue or PR.

**Comment by TiberiusB** [comment]
Interesting, thanks for the explanation.

Are contributions transfered in faircoins?

Can someone sell its contributions to a project, transferring future
benefits to others?

Is the notion of fluid equity implemented?

**Comment by fosterlynn** [comment]
>Are contributions transfered in faircoins?

The contributions are just work right now.

>Can someone sell its contributions to a project, transferring future benefits to others?

No.

>Is the notion of fluid equity implemented?

No.  They're keeping things pretty simple, except for the validation, which is not so simple (especially since it isn't yet implemented in software).

Also, unrelated to Tibi's questions, I just read back to a bunch of the discussion here: https://github.com/valueflows/exchange/issues/32.  I had forgotten the objections to the word "claim".  Sorry about that.  

I am still thinking about what to propose for the model, people's thoughts are welcome of course.  Minimally I think we will need to make the direct relationship between events and the commitments they create to be many-to-many rather than direct as now.

**Comment by elf-pavlik** [comment]
http://conversationsforaction.com/ uses concept of *satisfaction* as acknowledgement of *fulfillment* 
in https://vientos.coop/ we haven't gotten into structured commitment and event but we had very basic *review*

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/valueflows/-/issues/244.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
