### ISSUE TITLE
Separate repo for Resource and ResourceType?

### ISSUE THREAD

**Issue by bhaugen** [valueflows/valueflows#25]
See also https://github.com/openvocab/ovn/issues/17#issuecomment-135807072 and https://github.com/openvocab/ovn/issues/23#issuecomment-136093150

I would like to do this. But do we have enough agreement on resources, and what is and is not a resource, to create one? Should we discuss those questions upfront here, or as issues in a separate resource vocab repo?

For example, we [NRP] consider anything that is an input or output to a process, or transferred from one agent to another in an exchange, to be a resource. That includes material goods, work, money, designs, whatever. All of those would be subclasses of Resource that have different behaviors as inputs and outputs and in exchanges. But one of the benefits of REA as a minimal model is that the base models for processes and exchanges are simple and symmetrical, and composable into resource flow networks (graphs).

But I know some people have philosophical differences about treating money as a resource, and some have reservations about work. 

Also, in https://github.com/openvocab/ovn/issues/23#issuecomment-136093150 , @ahdinosaur says, 
>  it seems "assets" from "Open OS" (which i'm now using as my reference Enspiral
> use case for Holodex) would be resources with relationships but no exchanges or processes.

I'm sure those assets have histories and futures: are not static things, but got their relationships with e.g. agents through processes and/or exchanges, and will go on to participate in other processes and/or exchanges.  Those events are captured in a conventional accounting systems through journal entries of economic events that may or may not be connected to processes and exchanges in the accounting system, but were so connected in the real world. Everything exists in streams of change, flow, flux, whatever you want to call it.

**Comment by ahdinosaur** [comment]
thanks for starting this discussion @bhaugen. i'm not sure the answer to "what is and is not a resource", here is a good place to start though. i agree with your NRP definition, also i consider money and work hours to be resources. 

for more context, the example "assets" from ["Open OS"](https://docs.google.com/document/d/1as22xHOG5JzxKb8sDZW4iCyQHh8st52g3bAXoYzoYHc/edit?pli=1#heading=h.odkahue79nna) are: brands, legal entities, and financial accounts. the reasoning is to integrate these legacy illusions in our model of reality without being coupled to them.

**Comment by elf-pavlik** [comment]
Just quick note on term *Resource*, in Linked Data it gets used as super generic term for web resources and real world resources which pretty much include any thing.

Vocabulary drafted for web payments, at least when DigitalBazaar lead work on it under codename Payswarm, also used term *Asset* and *Listing* https://github.com/schemaorg/schemaorg/issues/134#issuecomment-56262883

I don't see urgency in separating repository for that, especially that in most cases we will look at resources/assets from perspective of either *Process* or *Exchange* and we already noticed that currencies play role in exchange while products and services in process. I actually will create now a relevant issue in process repo!

**Comment by bhaugen** [comment]
@elf-pavlik - that's why in our actual vocab (and in REA) we use the name EconomicResource. (Just shorten it to Resource for most discussions in this context where we know what we mean. Same goes for Resource Type, it is actually named EconomicResourceType. Likewise EconomicEvent, to differentiate from all the other meanings of Event.)

What I wanted to tease out, though, is any remaining differences in the meaning and scope (range?) of EconomicResource. What is one, and what ain't. If we have unresolvable differences there, it will affect the models and vocab for both Process and Exchange. Doesn't actually require a separate repo to have that discussion, but if we can come to agreement, I think it would help to publish it in a separate repo. Then we can refer to that as an explanation of what we mean, and don't need to repeat it for both Process and Exchange.

**Comment by ahdinosaur** [comment]
[made a new repo for `Resource` / `ResourceType`](https://github.com/valueflows/resource), since it's clearly part of our vocab if it's used within `Process` and `Exchange`. i didn't push any code yet, while we're in discovery (although @bhaugen and @fosterlynn i reckon y'all know enough already for what a Resource is, i'm happy to follow your lead).

i wish i could transfer this issue into that repo.

as for the name *Resource*, isn't that the whole point of namespacing? our `Resource` is `valueflows:Resource`, i reckon we should use the names that make the most sense within our namespace.

**Comment by bhaugen** [comment]
@ahdinosaur - thanks. I'd like to rename it economicresource even if we can namespace it because the word resource is so overloaded in LOD land.

Anybody got any problem with that? Or counter-suggestions?

**Comment by ahdinosaur** [comment]
@bhaugen in my opinion, we shouldn't have to worry about the word resource being overloaded in LOD land because we are in our `valueflows` namespace. again, otherwise what's the point of a namespace if we're worrying about conflicts with names in all possible LOD namespaces? so i guess my gut has a problem with that...

**Comment by ahdinosaur** [comment]
i might be being unreasonable though. feel free to do what you think is best, if it *really* irks me i'll bring it up again.

**Comment by bhaugen** [comment]
@ahdinosaur - I am aware that technically, we can do that. I've just seen so much confusion about a couple of overloaded words - resource and event - that I tend to use the "economic" prefix with people until they grok the territory.

**Comment by ahdinosaur** [comment]
@bhaugen that provides useful context and makes sense, cheers. my instinctual reaction is to make that extremely clear in the docs, but i'm keen to go with an economic prefix for now, maybe a better solution down the road is a name that is less overloaded. i was thinking randomly before about a better name for event being flow. then randomly now maybe resource is material, idk. again, do what you think is best and i'll follow along, even if i throw random thoughts around. :smile:

**Comment by bhaugen** [comment]
Actually a somewhat alternative name for event in REA is stockflow. (It is literally the name for the relationship between and economic resource and economic event.)

I'm trying to think if all economic events are flows. A lot of economic events just change ownership of an economic resource without changing the resource in any other way. Like, A sells B a house.

I'm reluctant to divorce ourselves from the REA names too much, though. It is both a fairly large body of documentation and practice about the models behind economic networks, an international standard, and a bunch of people, especially in Europe, developing software somewhat behind the scenes. Mostly academic. For example:
http://vmbo2015.blogs.dsv.su.se/program/

At some point, I plan to recruit a few of that gang for this vocab project.

**Comment by ahdinosaur** [comment]
[a separate repo for Resource and ResourceType has been created](https://github.com/valueflows/resource), closing. feel free to re-open or continue discussion as necessary.
