### ISSUE TITLE
Add link to Github repo in docs

### ISSUE THREAD

**Issue by pmackay** [valueflows/valueflows#254]
Just been browsing through most of the pages in https://www.valueflo.ws/ and it occurred that I could not see a link to the GitHub repo - would it make sense to add one somewhere?

Similarly would a Contributing page or note be useful?

**Comment by bhaugen** [comment]
Yes, please. I guess this is what we got for contributing: https://github.com/valueflows/valueflows/blob/master/CONTRIBUTING.md

**Comment by fosterlynn** [comment]
This was done awhile ago.
