### ISSUE TITLE
Agreement Classfication

### ISSUE THREAD

**Issue by elf-pavlik** [valueflows/valueflows#262]
As I mentioned in https://github.com/valueflows/valueflows/issues/242#issuecomment-354001923, in Vientos we have something like mini classification of agreement emerging:

* gift (no direct reciprocity)
* barter (exchange of non currency resources)
* time exchange (time banking)
* trade (exchange where at least one side involves currency 'resource')

We could specify *trade* even narrower with *currency trade* which would involve only currency 'resources'. At the same time we don't plan to support that case in Vientos.

We plan to explore barter chains, which would come as multi-lateral agreements involving only non currency resources. In that case it seems like more general case and 1-on-1 barter comes as more specific (narrower) version of it.

I see *Agreement Classification* as distinct from *Agreement Recipe* which we could start exploring in #261 for *work* and *use*. I will propose some other case later, possibly based on some `schema:Offer` and `schema:Demand` examples, which I start seeing as possibly equivalent to what we might call *Agreement Recipe* with *trade* classification for e-commerce.

**Comment by fosterlynn** [comment]
> in Vientos we have something like mini classification of agreement emerging:

Nice, thanks.  In NRP, all of those would be ExchangeTypes, and would be all user defined.  ExchangeTypes contain one or more TransferTypes.  Or people could define more specific classifications too, name everything what they want, etc.  (Not necessarily recommending for VF, just comparing notes.)

I hesitate to encode those specifics in VF.  I'm afraid we don't have the experience to say what people will want to do into the future.  I'd rather let people define their own patterns of exchange/gift.

I'm also thinking in general about where do we want to draw the line on what VF supports for agreements, and what we leave to other vocabularies.  Not sure where the best line is.  Can we define some kind of agreement structure that is part of a recipe without being too limiting?  There are incredible numbers and configurations of agreements to exchange.  Hmmmm.

**Comment by elf-pavlik** [comment]
> In NRP, all of those would be ExchangeTypes, and would be all user defined. ExchangeTypes contain one or more TransferTypes.

I guess in NRP those work more as recipes rather than classifications. Probably in in VF we may need *vf:AgreementRecipe* which would come close to *nrp:ExchangeType* and *vf:FlowRecipe* would possibly could come somehow near *nrp:TransferTypes* (unless you have something like *nrp:CommitmentType* in exchange recipes)

When it comes to classification of 'Flow (R | I | C | E)' in VF, *vf:action* seems to serve that purpose - *work*, *use*, ... 


> I'm also thinking in general about where do we want to draw the line on what VF supports for agreements, and what we leave to other vocabularies.

I think in VF we may limit our scope to agreements around **reciprocity**. All the agreements classifications I posted here differ by how the reciprocity work under those agreements.

**Comment by fosterlynn** [comment]
> possibly could come somehow near nrp:TransferTypes (unless you have something like nrp:CommitmentType in exchange recipes)

>When it comes to classification of 'Flow (R | I | C | E)' in VF, vf:action seems to serve that purpose - work, use, ...

Yeah, I think it does correspond.  Except our experience is they do need to be user defined on the exchange side - at least the labels/names.  Whereas in processes, there will probably be a fairly clear set that does have specific meaning and behavior, even if we haven't discovered all of them yet.

But you could prove me wrong! :blush: 

>I think in VF we may limit our scope to agreements around reciprocity.

Well, distribution using value equations is based on reciprocity, and I don't think we should put that in VF.  And there are very detailed exchange contracts that are reciprocity based but not nearly as simple as what you are doing in Vientos or what we did in NRP.  It could be a giant black hole in some ways.

**Comment by elf-pavlik** [comment]
> Except our experience is they do need to be user defined on the exchange side - at least the labels/names.

I think 'user defined' may apply more to Agreement Recipe #266 not as much to the very general classifications like I mentioned in the first comment.

**Comment by fosterlynn** [comment]
>I think 'user defined' may apply more to Agreement Recipe #266 not as much to the very general classifications like I mentioned in the first comment.

Ah I see where you are going.  Yes, I'm talking more about recipes.  

But.... Classification taxonomies or categories can be whatever people want too though.  You have defined one for the users of Vientos; others will define others that may or may not overlap yours.  Or are you thinking VF would define something like your list that would have specific implications for data structure or behavior?  (If so, it starts to sound more like a high-level recipe....)

**Comment by elf-pavlik** [comment]
> You have defined one for the users of Vientos; others will define others that may or may not overlap yours.

I think I can find wikidata reference for all of:
>* gift (no direct reciprocity)
>* barter (exchange of non currency resources)
>* time exchange (time banking)
>* trade (exchange where at least one side involves currency 'resource')
>We could specify *trade* even narrower with *currency trade* which would involve only currency 'resources'.

**Comment by fosterlynn** [comment]
>I think I can find wikidata reference for all of:

Yes.  But doesn't that make it part of a referenced taxonomy?  Rather than explicitly defined in the vocabulary?

**Comment by elf-pavlik** [comment]
I didn't propose to include any of them in the vocab. I will look for wikidata references for all of them and they can just serve as an example of classifying agreements using references to a very common knowledge base.

**Comment by fosterlynn** [comment]
>I didn't propose to include any of them in the vocab. I will look for wikidata references for all of them and they can just serve as an example of classifying agreements using references to a very common knowledge base.

:+1: Yes, they will make great examples, could go somewhere in the text explanations too.

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/valueflows/-/issues/262.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
