### ISSUE TITLE
Use Case: Taxi vs. Carpooling/Ridesharing

### ISSUE THREAD

**Issue by elf-pavlik** [valueflows/valueflows#263]
Another possibly interesting use cases to explore how *Agreement Recipe* could work with *Flow Intent* and *Flow Recipe*.

In case of Taxi most likely they would use some 'general' *Flow Recipe* for their services, based on *recipeQuantity* with distance or time. Possibly including some initial boarding fee.

In case of Ridesharing, a person might offer a particular ride on particular route at particular time. Then this person possibly would never offer a ride again. In that case it seems that we have a *Flow Intent* not *Flow Recipe*. Possibly we would also not need *Agreement Recipe* but something more like *Agreement Proposal* - not a recipe but not signed agreement yet, still it would include instances of *Flow Intent* not yet *Flow Commitment*. 

For Taxi, based on their *Agreement Recipe*, interested passenger would from that agreement recipe create a proposal and then taxi could confirm it which would result in actual *Agreement*.

Or proposing side would already include commitments and it would transition into agreement once other side makes all the Commitments for all proposed Intents. This way we can have single instance of Agreement which starts with Intents or some Intents and Commitments and at some point have all Commitments. Similar as one instance of Process progresses from Intents through Commitments to Events.

**Comment by fosterlynn** [comment]
Yes, I think recipes are only useful for repeatable activities.      

>This way we can have single instance of Agreement which starts with Intents or some Intents and Commitments and at some point have all Commitments. Similar as one instance of Process progresses from Intents through Commitments to Events.

I like this :+1: .  I'm a little worried that the name "agreement" implies that there has been an agreement already, but I like the model, and am willing to go with the name.

>Flow Intent, Flow Commitment.

I don't want to change the names of Intent, Commitment, and EconomicEvent.  They are fine as they are imo, and don't need the connecting naming to the recipe layer.

**Comment by elf-pavlik** [comment]
> I'm a little worried that the name "agreement" implies that there has been an agreement already, but I like the model, and am willing to go with the name.

We can come up with a different term, in a way it starts as *Proposal* and once all intents get covered with commitments it becomes an *Agreement*. Let's think how we can avoid it having 'changing its type' over time. In practice we may need to treat it differently than the process and based on *Proposal* create new instance of *Agreement*. We most likely will find out once we dive into YAML :wink:

**Comment by fosterlynn** [comment]
>Let's think how we can avoid it having 'changing its type' over time. 

:+1:

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/valueflows/-/issues/263.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
