### ISSUE TITLE
Considering a Recipe class?

### ISSUE THREAD

**Issue by fosterlynn** [valueflows/valueflows#267]
Should we consider adding a class to represent a Recipe? It is not required probably, but might give some advantages.

Pros:
* If we allow a Recipe to specify which recipe processes it contains, then people can create a self-contained recipe that doesn't require a choice at planning time for every process encountered in the value flow, which process to use that creates the same output, or make vs buy decisions.  If we are in a situation of finding recipes on the web, that could get overwhelming. 
     * It could even include multiple recipe processes/transfers so an interface could present a more controlled choice
* It could have informative notes.  
* It could explicitly define that it is a fork or gr:isVariantOf another recipe.

Cons:
* One more thing to define, and it is not strictly needed because you can already trace back from a ResourceClassification to find all possible recipe processes (or recipe agreements for transfer sourcing) that create or transfer the resource classification you need.

Other pros or cons?

**Comment by elf-pavlik** [comment]
> If we allow a Recipe to specify which recipe processes it contains, then people can create a self-contained recipe that doesn't require a choice at planning time for every process encountered in the value flow

Do you see cases for a 'Recipe' that can't get expressed with 'ProcessRecipe' with inputs and outputs, even if you can distinguish sub processes in it, possibly each one also having a 'ProcessRecipe' ?

Maybe you can just provide an example of two where you would like to use it?

**Comment by fosterlynn** [comment]
>Do you see cases for a 'Recipe' that can't get expressed with 'ProcessRecipe' with inputs and outputs, even if you can distinguish sub processes in it, possibly each one also having a 'ProcessRecipe' ?

No, I don't see any case where it can't get expressed that way, either with or without sub-processes.  That's why it is a choice.  (Sub-processes would need some definition to see how that might affect this question.)

I don't have a specific use case I've worked with because our experience is all pretty contained to a context where they have defined their own recipes, and there is only one recipe for one output resource classification.  So there aren't 10,000 recipes for chocolate chip cookies say.  And for the create the dough process (before adding the chocolate chips), say there are 10,000 ways to create the same basic dough  (and say the same dough can be used for different kinds of cookies, which is why it is defined as a separate process in the first place).  Having a Recipe object would allow a bakery to say we use this set of recipe processes for our chocolate chip cookies, and it includes this process for creating the dough, not one of the other 9,9999 options.

**Comment by elf-pavlik** [comment]
I understand that from an instance of such recipe one wouldn't get an instance of something but some kind of plan that includes multiple instances of processes. Each of those processes would get created based on some *ProcessRecipe* referenced from that umbrella Recipe, but based on your example of 'cookie dough' that *ProcessRecipe* would very unlikely reference that umbrella Recipe, since many umbrella Recipes could use the same *ProcessRecipe*. I wonder if it would make sense to have such umbrella equivalent on Plan & Observation layers eg. *ProcessChain* and call the umbrella Recipe with a more specific name like eg. *ProcessChainRecipe*. This way one can track more clearly how many times they used that recipe.

If we want to refer to a conceptual layer as *Recipe* layer, I would avoid defining any specific class meant for that layer and naming it just *Recipe* but always use more specific naming. While Recipes for Processes may not need any references to something like *AgentSlot* I suggested in #266 Agreement Recipes may need to include *provider* and *recipient* information. At the same time we may find a way to use single *FlowRecipe* in both *ProcessRecipe* and *AgreementRecipe* and Flow Intents and/or Flow Commitments each could reference both, a *FlowRecipe* related to *ProcessRecipe* and *FlowRecipe* related to *AgreementRecipe*.

**Comment by bhaugen** [comment]
The reason I liked Lynn's idea, after some discussion, is thinking about a combination of multiple recipes to do roughly the same thing, which you can see all over the internet, and then multiple recipes at each layer of the recipe explosion tree (where the inputs to one recipe process, for example, find outputs for another recipe process, etc etc, all the way down). See https://www.valueflo.ws/appendix/dependent-demand.html

So either the planner will need to make separate decisions of what recipe to use at each layer, or the recipe will stop, not knowing what to do, or just picking one of the processes at random. (Our NRP software does have a recipe class, and also cannot handle multiple creation processes for the same resource classification, for that set of reasons. People regularly create and plan multiple recipe layers at the same time.)

If we had a recipe class that could have a list of all the process recipes that it used, that could shortcut a lot of those decisions. People would be able to list as many or as few as they wanted, so you could manage the scope of your planning by how far your recipe extended.

Seems worth thinking about, at least.

**Comment by gcassel** [comment]
I'm not well-oriented to this discussion (nor to VF lately, sorry), but feel free to consider adapting any elements of my entry for [recipe](https://github.com/gcassel/Modular-Organization-Terminology/blob/master/terms/recipe.md) in MOT.

My terminology is a bit different and may not seem entirely compatible.  For me, *formula* is the root term which *represents a process*, and the only special function of *recipe* is that it's a *recommended creative formula*.

**Comment by bhaugen** [comment]
> A recipe is a formula which one or more agents recommends for performing a specific creative process, often within a specific physical or social context such as a social network or community.

Formula doesn't seem to me to add much more than recipe and would confuse the naming. So I guess I would prefer either recipe or formula, and think recipe is more widely used and understood. Recommendation seems like an action of some agent toward.

> Notes:

> Recipes are often included in the media resources of specific networks.

That's critical. Recipes are resources. That's one of the key aspects that we did not implement in NRP.

> Networks often enable agents to comment upon or evaluate specific recipes.

Yeah, we want recipes to be published and versioned and forked and reused.

**Comment by elf-pavlik** [comment]
> If we had a recipe class that could have a list of all the process recipes that it used, that could shortcut a lot of those decisions.

In my comment I didn't suggest we shouldn't add such class, I would just like to use more specific naming. Since you described it as: *"list of all the process recipes"*, maybe we could call this case something like *vf:ProcessChainRecipe* or *vf:ProductionRecipe* or ...

**Comment by bhaugen** [comment]
I don't care much about the name as long as it communicates. I think also such a construct could be optional. I went with the idea based on problems in coding plan explosions in NRP when we considered multiple recipe processes for the same resource classification.

**Comment by gcassel** [comment]
>Formula doesn't seem to me to add much more than recipe and would confuse the naming. So I guess I would prefer either recipe or formula, and think recipe is more widely used and understood. 

That perspective makes sense to me within the relatively strict objectives of VF  (economic interactions).    MOT is meant to cover broader context of information modelling, and I'm happy for our terms to differ at times (especially when I understand the difference).   :)

**Comment by bhaugen** [comment]
@gcassel 

>  I'm happy for our terms to differ at times (especially when I understand the difference). :)

We're working with Tibor of Communecter and others on vocabulary translations and I just posted an issue about alternate names for the same concept: https://github.com/valueflows/valueflows/issues/265

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/valueflows/-/issues/267.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
