### ISSUE TITLE
quantity value investigation (was: qudt appears to have changed their website and documentation)

### ISSUE THREAD

**Issue by bhaugen** [valueflows/valueflows#268]
For a couple of examples:
* Our link in https://github.com/valueflows/valueflows/blob/master/release-doc-in-process/all_vf.TTL is now a 404. We use http://qudt.org/schema/qudt/ - looks like http://qudt.org/1.1/schema/qudt might work? But they also have a 2.0: http://qudt.org/doc/2016/DOC_SCHEMA-QUDT-v2.0.html
* I spent 20 minutes looking for operational doc on QuantityValue through their website and links, and failed to find it. Finally found something in a popup on that 2.0 link above. Would like something to point people to that is more usable and complete.

**Comment by elf-pavlik** [comment]
This page looks like decent overview: http://www.qudt.org/pages/QUDToverviewPage.html

Some link work on http://www.qudt.org/release2/qudt-catalog.html and some not, I tweeted at folks related to QUDT to ask them about updating those links.

We also may need to update prefix to `http://qudt.org/2.0/schema/qudt`

**Comment by fosterlynn** [comment]
Great, thanks @elf-pavlik !

**Comment by fosterlynn** [comment]
Ran into this paper http://www.semantic-web-journal.net/system/files/swj1825.pdf, skimmed it.  It compares several unit ontologies, including QUDT.  No clear conclusions, would need to study it more carefully.  One interesting thing that I didn't know: wikidata has a lot of unit data.  I'm still interested in re-thinking the QUDT decision, partly because of the difficulty of their website plus so many unfinished specs in 2.0; also thinking about sources, and wondering if NASA is a good long term source.  Anyway, I'll continue with some investigation.

**Comment by fosterlynn** [comment]
Some more investigation re. `unit`:

From schema.org `unitCode`:
>The unit of measurement given using the UN/CEFACT Common Code (3 characters) or a URL. Other codes than the UN/CEFACT Common Code may be used with a prefix followed by a colon.

GR (gr:hasUnitOfMeasurement):
>The unit of measurement for a gr:QuantitativeValue, a gr:UnitPriceSpecification, or a gr:TypeAndQuantityNode given using the UN/CEFACT Common Code (3 characters).

Here are the Common Codes (link is on this page): http://wiki.goodrelations-vocabulary.org/Documentation/UN/CEFACT_Common_Codes

Note: gr and schema.org tend to focus on e-commerce.  But this list includes a lot besides that.  (Side note: "Each" is called "one", symbol "1", code C62.)

**Comment by fosterlynn** [comment]
Exploring OM: http://www.semantic-web-journal.net/sites/default/files/swj177_7.pdf

Exploring wikidata: 
https://www.wikidata.org/wiki/Q47574 (unit of measure)
https://www.wikidata.org/wiki/Property:P2968 (qudt code)
https://www.wikidata.org/wiki/Property:P2370
https://www.wikidata.org/wiki/Property:P6512
https://www.wikidata.org/wiki/Property:P3328 (OM reference)

My current thoughts: It would be good if we can allow reference to any of the unit lists that people want to use.  It is not clear to me that there is *one* really standard reference.  Will investigate if QUDT supports that - structurally it seems to. 

Subjectively: I like wikidata's commons approach, and that it supports many languages for the text representations.   Also that it references some of the other biggest measurement ontologies, thus tying them together.  They don't really have a model though afaik, but do have many units of measure.

**Comment by fosterlynn** [comment]
Saving this note, since we should do the attribution: "The QUDT Ontologies are issued under a Creative Commons Attribution Share Alike 3.0 United States License. Attribution should be made to NASA Ames Research Center and TopQuadrant, Inc."

**Comment by elf-pavlik** [comment]
> My current thoughts: It would be good if we can allow reference to any of the unit lists that people want to use. It is not clear to me that there is _one_ really standard reference.

I think we should pick one reference for units and possibly provide mapping to other units, still if data ends up using alternative references for the same units it will add a lot of complexity to implementations. We pretty much have choice between
* all implementations have to implement all known references for units
* all implementations have to implement one specific reference for units + some implementations may need to implement conversion to that specific reference if they have existing (legacy) dataset using that reference.

**Comment by pospi** [comment]
Copying this from the gitter chat, originally via @samrose -

> See this:
>
>> "QUDT is also one of the medium sized ontologies. The most important issue of QUDT is its inferential inconsistency. For example, it contains the following definitions:
>>
>>    ```
>>    Class: qudt:Unit
>>    SubClassOf:
>>    qudt:typePrefix exactly 1 owl:Thing,
>>    qudt:typePrefix value "U"^^xsd:string
>>
>>    Class: qudt:ResourceUnit
>>    SubClassOf:
>>    qudt:Unit
>>
>>    Class: qudt:FinancialUnit
>>    SubClassOf:
>>    qudt:ResourceUnit,
>>    qudt:typePrefix value "UF"^^xsd:string
>>    ```
>>
>> This means that every individual of the class FinancialUnit has the type prefix “UF”. Moreover, because it is also an individual of the class Unit, it has the type prefix “U”. As the number of type prefixes is, however, limited to one, this results in a conflict. As a result QUDT can not be used with a reasoner.
Also critical, three conversions and two prefixes contained wrong factors."
>>
>> http://www.semantic-web-journal.net/system/files/swj1775.pdf
>>
>> Jan Martin Keil on 02/15/201
>
> I have not read that whole paper yet, there may be a better unit of measurement ontology for the target of using with reasoners.

So now in the context of https://github.com/holo-rea/holo-rea/issues/65#issuecomment-532193335 I'm thinking it might be time to revisit this decision again, and consider the use of an ontology compatible with a reasoning system capable of performing unit conversion for us. If done manually I think [that implementation](https://github.com/holo-rea/holo-rea/blob/082e2af/lib/vf_core/src/measurement.rs#L17) is going to get quite large and complicated, and would not yield the same breadth of functionality as a fully-blown reasoner.

**Comment by pospi** [comment]
@samrose we'd be very interested in your thoughts on the OM ontology and its use with reasoners if you have bandwidth to review! :)

http://www.semantic-web-journal.net/sites/default/files/swj177_7.pdf
https://github.com/HajoRijgersberg/OM

**Comment by samrose** [comment]
@pospi 

I took a moment to do some more digging on this. The issue appears complex.

An older but still relevant discussion is found at https://lists.w3.org/Archives/Public/public-vocabs/2014May/0081.html

The issues seem to revolve around mixing RDF and OWL 2 / OWL DL standards, and how different tools like Jena, TopBraid etc support mixing these standards, and running rules and reasoners on them. So, it may in practice depend on the specific reasoners, and specific tools/rules engines you choose. 

A potentially appealing thing about https://github.com/HajoRijgersberg/OM  is that it simply implemented fully in OWL 2. 

It may be worth actually just creating a scope now for what you want to do with UoM, and narrowing down to reasoners that fit that scope, and then actually trying out rules/writing tests for rules etc and possibly even trying it with one of both of these ontologies.

**Comment by samrose** [comment]
There is also https://github.com/dieudonne-willems/om-java-libs  which has an implementation and tests of OM

**Comment by pospi** [comment]
For our purposes, I expect [horned-functional](https://lib.rs/crates/horned-functional) is likely to be the parser we would embed into the DNA runtime; if that helps any. I'm unsure what to look for in finding a reasoner compatible with the parser bu maybe [TrOWL](http://trowl.org/) is what we're looking for?

**Comment by fosterlynn** [comment]
I assigned myself to this, I'm going to continue the research and am hoping to come to some reasonable recommendation in the next week or so.  We shall see.  @pospi @jvanbockryck

**Comment by fosterlynn** [comment]
There are two related pieces of this.  They can be possibly separated, depending on our choices.
* The model itself, the range of our various quantity properties (currently qudt:QuantityValue)
* The unit taxonomy

**Notes on requirements, possibly incomplete and probably not absolute:**
* A quantity with some availability of datatypes (decimal, float, etc.) associated with a unit (that has a standard taxonomy)
* A way to do conversions
* A "kind" or "classification", such as weight, volume, count, etc.
* Both engineering and standard "business" units
* The model supports units from other taxonomies and ontologies, although we want to start with one
* Open and free standard
* Clear documentation
* Linked Open Data (rdf) based

**Models:**

GoodRelations (and therefore schema.org I think):

![GR-quantity](https://user-images.githubusercontent.com/3776081/66755777-4c8a9d80-ee5e-11e9-997a-2c7777903058.png)

Note:  gr:ProductOrService is what is in the upper right that points to gr:QuantitativeValue.  gr:ProductOrService encompasses both our ResourceSpecification and EconomicResource.

OM:

![OM-quantity](https://user-images.githubusercontent.com/3776081/66756451-ab9ce200-ee5f-11e9-887d-7a3eaa9762b6.png)

QUDT:

![QUDT-quantity](https://user-images.githubusercontent.com/3776081/66757845-a4c39e80-ee62-11e9-97a4-24a108bfb385.png)

Note: More here http://www.qudt.org/pages/QUDToverviewPage.html

**Comment by bhaugen** [comment]
**floats vs currencies**
* Don't do that! https://spin.atomicobject.com/2014/08/14/currency-rounding-errors/
* Probly not: https://stackoverflow.com/questions/3730019/why-not-use-double-or-float-to-represent-currency
* It's complicated: https://evertpot.com/currencies-floats/

Try some of the examples in a shell in your favorite programming language:
```
python:
>>> .3 - .2
0.09999999999999998
```

**Comment by jvanbockryck** [comment]
The “numericValue” is a union if four datatypes, in which float is one. So in this case, a double should be chosen, right @bhaugen ?

**Comment by bhaugen** [comment]
@jvanbockryck 
> a double should be chosen, right @bhaugen ?

Lynn says float, decimal, double, and integer.

I have always used decimal numbers in any setting that needed to deal with currencies. Like anything, they have pluses and minuses:
+ base 10, like money, so fewer rounding and equality comparison issues.
- not as flexible as doubles; in all implementations I have used, I needed to specify at least the number of decimal places if not the whole number of digits altogether.

**Comment by fosterlynn** [comment]
I'm starting a comparison table between QUDT and OM.  Will be adding more columns probably, and filling things in, in this comment.

Ontology | Kind | Conversions  | Qty datatype | Currency | Time | Documentation |
------------ | ----- |  ----------- | ------- | ------ | ---- | ---- |
QUDT | yes |   | union | yes |  | lousy |
OM  | yes |    | float? | no |  |  |

**Comment by pospi** [comment]
+1 for decimal values, which I think as far as GraphQL goes have to be declared as `Float`, but that doesn't mean the underlying implementation can't use robust decimal math. Might be good to make that clear in `vf-apps` spec documentation.

It may also be good to wrap the values in something like `BigNumber` in JavaScript-land, so that developers dealing with data from the API know that they need to take care if doing math on those values. Which they really shouldn't be... but you never know what requirements are going to be down the line...

**Comment by fosterlynn** [comment]
I'm closing this since there is now a PR for switching to OM2.  I can put the recent investigation and thinking about this here later for the record.
