### ISSUE TITLE
VF site not working properly

### ISSUE THREAD

**Issue by fosterlynn** [valueflows/valueflows#272]
If you go in using the gitbook url directly, it is OK.  If you go in using valueflo.ws, it shows the content part, but not the left side.  You can scroll the content pages, but they go directly to our github docs.  Doesn't seem like it is getting to gitbook at all from valueflo.ws?

@ahdinosaur maybe ??

**Comment by elf-pavlik** [comment]
It seems to work ok now, maybe some CDN glitch?

**Comment by bhaugen** [comment]
Looks like it, working for me now, too. I'll close this.
