### ISSUE TITLE
update README to match rename / restructure / overview

### ISSUE THREAD

**Issue by ahdinosaur** [valueflows/valueflows#28]
per https://github.com/valueflows/valueflows/issues/23#issuecomment-143894615, i renamed this repo to `valueflows/valueflows`, to act as our "home repo" for this org.

i reckon we should update the README to:

- [x] reflect the "OpenVocab" -> "Value Flows" rename
- [x] provide an overview of the project (pretty much done, maybe needs an update?)
  - [x] include [our principles](https://github.com/valueflows/valueflows/issues/12) in the README
- [x] provide links to each vocab repo (so far), namely `agent`, `resource`, `process`, and `exchange`

thoughts? anyone (particularly @bhaugen or @fosterlynn) want to tackle this?

**Comment by bhaugen** [comment]
@ahdinosaur - I'll get it done today. [Principles](https://github.com/valueflows/valueflows/wiki/Principles-for-this-vocabulary) are in the Wiki, which is easier to edit than the README, which requires a pull. And then they'll get out of sync. So I'd prefer a link, which I'll add prominently. And get rid of some of the Mikorizal-oriented language. Etc. General cleanup. Yell if you see other changes that shd be made.

**Comment by ahdinosaur** [comment]
@bhaugen awesome :+1: :cat:

**Comment by bhaugen** [comment]
First cut here, in our new fork: https://github.com/valnet/valueflows

Please suggest improvements, otherwise I will issue a pull request.

**Comment by fosterlynn** [comment]
@bhaugen Suggest: update the checkbox list, and something gets a check when we actually have jsonld context plus doc.

**Comment by bhaugen** [comment]
Checkboxes done, I think. @ahdinosaur - is Role still part of the vocab?

I probably got a couple of other improvements to think about before a pull request.

**Comment by ahdinosaur** [comment]
@bhaugen looks great. :smile: Role is no longer part of the vocab, we realized Relationship is more than enough.

**Comment by ahdinosaur** [comment]
closed by #29
