### ISSUE TITLE
repository size

### ISSUE THREAD

**Issue by elf-pavlik** [valueflows/valueflows#287]
I just cloned this repo noticed its size
```bash
➜ git clone https://github.com/valueflows/valueflows
Cloning into 'valueflows'...
remote: Enumerating objects: 83, done.
remote: Counting objects: 100% (83/83), done.
remote: Compressing objects: 100% (77/77), done.
remote: Total 2233 (delta 39), reused 16 (delta 6), pack-reused 2150
Receiving objects: 100% (2233/2233), 55.79 MiB | 207.00 KiB/s, done.
Resolving deltas: 100% (1325/1325), done.
```

Caused by this file
```bash
➜  ls -lh valueflows/.scripts/lod-converter.jar
-rw-rw-r-- 1 elf-pavlik elf-pavlik 55M nov  6 10:37 .scripts/lod-converter.jar
```

I think we will need to remove it and possibly end up needing to rewrite history to get rid of it for good

**Comment by fosterlynn** [comment]
>I think we will need to remove it and possibly end up needing to rewrite history to get rid of it for good

:+1:   Do you remember what it is for?

**Comment by elf-pavlik** [comment]
I think it generates all the different representations in gh-pages branch. Possibly we could keep it but instead of having it in the repo CI script would download it from somewhere else, even simply a separate repo.

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/valueflows/-/issues/287.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
