### ISSUE TITLE
Next formal release

### ISSUE THREAD

**Issue by fosterlynn** [valueflows/valueflows#297]
How about we do a formal release when we get the process nesting, basic recipe, and intents in there?  And maybe revisit transfers, depending on how hard that is?

- [x] Review and clean up all_vf.ttl.  Include status of all elements (how stable https://www.w3.org/2003/06/sw-vocab-status/note).
- [x] Clean up UML diagram, make sure it matches ttl.
- [x] Re-generate all the small webvowl pictures on the text pages.
- [x] Do a content review of all text pages, upgrade as needed.
- [x] Pick a release number, update the status page.
- [x] Make https://w3id.org/valueflows# work.
- [x] Do a search and create a complete contributors list; and include REA advice we've received [edit]
- [x] Simple examples [edit]

(Feel free to edit!)

**Comment by elf-pavlik** [comment]
SGTM I think I will try to choose two days in a week where I would systematically work on VF at least 3h, sometimes 6h on those days. Sometimes we could try to sync-up and have a voice call to clarify things faster.

**Comment by fosterlynn** [comment]
>SGTM I think I will try to choose two days in a week where I would systematically work on VF at least 3h, sometimes 6h on those days. Sometimes we could try to sync-up and have a voice call to clarify things faster.

:+1:  Sounds good!  Right now I am making this a priority, hope to be able to continue.  Voice call is good; and/or do you want to get back to gitter?

**Comment by elf-pavlik** [comment]
I just opened gitter after very looooooon time :fearful:

**Comment by fosterlynn** [comment]
Just edited the first comment with what we may want to do for next release in terms of actual content.  I want to define and cut back to the smallest amount we really need now, so we can do all those "cleanup" kinds of things and get the doc and w3id stuff really usable.

What do you think @elf-pavlik ?

(When I put this issue out, I thought it would be quicker to get through all the major things in process.  But since it isn't (my bad), I feel the need to do at least some of the cleanup, with more people trying to use the doc.)

**Comment by elf-pavlik** [comment]
I think we should document working on the vocab process:

* vocab term maturity based on usage coverage with examples and open source implementation
* PR workflow - starting with examples and adding terms to the vocab and documentation prose as consensus emerges
* use of YAML for examples and https://github.com/valueflows/vf-examples-jsonld-context
* keeping PRs granular - avoiding any unrelated changes (now we have some PRs that include cleanup commits not related to that PR)

**Comment by elf-pavlik** [comment]
TODO:

* [ ] extract `vf:Satisfaction` from #302 into new PR and rename #302 to Proposal @fosterlynn 
* [ ] extract cleanup from #293 
* [ ] #287 @elf-pavlik 
* [ ] examples and JSON-LD context @elf-pavlik
