### ISSUE TITLE
Evaluate PROV for Knowledge Resources (including Recipes)

### ISSUE THREAD

**Issue by elf-pavlik** [valueflows/valueflows#298]
**https://www.w3.org/TR/prov-primer/**

*Capturing from https://github.com/valueflows/valueflows/pull/296#discussion_r236365174*

**Comment by fosterlynn** [comment]
More details: This came about from wanting to support forking of recipes.  Thought of using relationships variantOf and successorOf, borrowed from Good Relations.  We agreed we need to look at the requirement more broadly and consider the options more carefully.

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/valueflows/-/issues/298.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
