### ISSUE TITLE
Finish recipe

### ISSUE THREAD

**Issue by fosterlynn** [valueflows/valueflows#299]
After PR https://github.com/valueflows/valueflows/pull/296 we will still need to add some features:
- ability to fork recipes
- integrate transfers as much as it makes sense
- support workflow recipes
- ???

Please feel free to add....

**Comment by elf-pavlik** [comment]
> integrate transfers as much as it makes sense

I think in many cases we can use transportation as well. This keeps us away from 'changing rights' and just have resources moving between stock along all those transformations. Possibly wherever we can include transportation we can insert 'transfer' (teleportation) as well.

**Comment by fosterlynn** [comment]
I thought about integrating exchanges, since that is needed now.  I think we can do it very simply, thanks to the simplification of transfers into individual events.  In the below diagram, I just added RecipeExchange and the relationship to RecipeFlow.

![exch-recipe](https://user-images.githubusercontent.com/3776081/69007909-c30d3600-0909-11ea-85b2-0352bbab8602.png)

Notes:
* This will create an Agreement.
* I don't see the need for a "specification" since it seems only useful as part of a recipe.
* In NRP, we had some configuration elements, but I propose to wait and see what is actually needed.  All of it was basically internal to an app and used to simplify the UI, I don't think needed as part of the vocabulary used to communicate between agents or apps.

@jvanbockryck @bhaugen I would love some feedback.

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/valueflows/-/issues/299.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
