### ISSUE TITLE
Named bi-directional properties

### ISSUE THREAD

**Issue by fosterlynn** [valueflows/valueflows#306]
From @elf-pavlik in another issue:
>inverse properties just complicate queries, one has to always query for both directions to make sure all results get returned. 

>on can always adjust position of object and subject in the statement without need to have inverse property, in JSON-LD @reverse keyword provides some convenience

An example is Process.inputs and EconomicEvent.inputOf.

I have never tried sparql, so I don't know how it works.  Why would you have to query both directions?

From the non-rdf world, it seems like having named properties for both directions will be helpful, perhaps essential, as people will need to approach querying from either direction.  For example, I just wrote a graphql api using VF to serve a UI app that wants to be able to plug into any VF backend.  I ended up making up a lot of names (some of them not so good in retrospect) to accommodate many "other direction" queries.

If we truly can't have a named reverse property, we will need to decide if we do relational (foreign key) or OO (containers) direction as a consistent choice.  Does rdf have a preference?

**Comment by elf-pavlik** [comment]
> An example is Process.inputs and EconomicEvent.inputOf.

I don't know how `vf:inputs` slipped in. Besides using anti-pattern of plural name, it would force everyone to check for both `vf:inputs` and `vf:inputOf`.

> Why would you have to query both directions?

Because data any creator could have used either one, and as a consumer of all that data we now must to check both options. For example if Alice uses `vf:inputs` in her data and Bob uses `vf:inputOf` in his data, for my application to work with Alice's, Bob's and everyone else's data I have to always check those both possibilities.

> If we truly can't have a named reverse property, we will need to decide if we do relational (foreign key) or OO (containers) direction as a consistent choice. Does rdf have a preference?

Could you please provide an example to clarify what you meant? In RDF we have an underlying model of *directed labeled graph* where properties / predicates get used as labels on those directed edges. The whole data model then boils down to making *Statements* (represented as triples), on can state
```
Bob likes pineapples  (subject: Bob predicate: likes object: pineapples)
```
While for 'human consumption' it might sometimes make more sense to say something like  
```
pineapples are liked by Bob (subject: pineapples, predicate: are liked by, object: Bob)
```
for the machine we just need to provide a triple that will get used in reconstructing this underlying *directed labeled graph*. Having property / predicate just in one direction, one can always make appropriate statement by choosing what to use as subject and what as object in a statement.

This works very similar to *entity attribute value* model, just the full description of certain entity will need to include both cases, where we have it in entity (subject) position and where we have it in value (object) position.

**Comment by fosterlynn** [comment]
>I don't know how vf:inputs slipped in.

It's been there a long time.  I took it out in my Intents PR so we can have a consistent pattern while we think about it.

>Because data any creator could have used either one, and as a consumer of all that data we now must to check both options. 

Why wouldn't any data be served with the appropriate direction, no matter what is stored?  If I query a process and expect its inputs and outputs as part of the result, I should get them no matter how they are stored, no?  Nobody would store both directions, but anyone could derive either direction and serve it up if requested.

>>If we truly can't have a named reverse property, we will need to decide if we do relational (foreign key) or OO (containers) direction as a consistent choice. Does rdf have a preference?

>Could you please provide an example to clarify what you meant? In RDF we have an underlying model of directed labeled graph where properties / predicates get used as labels on those directed edges.

Like, 
* A Process has these inputs and outputs which are EconomicEvents.  (OO style)
* An EconomicEvent is inputOf this Process.  (relational style)

In the directed graph, we will want to follow the graph in both directions.  And even when graphing one direction R-I-P-O-R-I-P-O-R, I needs to point to its P, then the P needs to point to its O's. 

Right now, we have everything relational style, I think, if we count the Intent PR.

A small survey:
* GR seems to use OO style.
* AS seems mostly OO, but sometimes has both directions, like `replies` and `inReplyTo`.
* Schema.org defines inverse properties explicitly in the doc, see [this example](https://schema.org/Thing).

**Comment by elf-pavlik** [comment]
If we take for example a Triple Patter Fragment as illustrated on http://linkeddatafragments.org/concept/

To get all the flows appearing as input or output of given process `<ex:some-process>` I could use queries:
* `{ predicate: 'vf:inputOf', object: 'ex:some-process' }`
* `{ predicate: 'vf:outputOf', object: 'ex:some-process' }`

This would match specific patter in a union graph of queried dataset.

For those queries to work, and for someone to store in the dataset statements like
```ttl
<ex:some-process> vf:inputs <ex:some-flow> .
```
LDF interface would have to run a reasoner that would based on `owl:inverseOf` infer in addition to triple asserted above this triple:
```ttl
<ex:some-flow> vf:inputOf  <ex:some-process> .
```
Having a tread-off in either requiring to have such reasoner in place or only providing property in one direction, I wouldn't like to rush with making reasoner a requirement.

For your use case with GraphQL queries, we could look at one of the side developments by LDF team [GraphQL-LD](https://gist.github.com/rubensworks/9d6eccce996317677d71944ed1087ea6)

**Comment by fosterlynn** [comment]
>To get all the flows appearing as input or output of given process <ex:some-process> I could use queries:
>    { predicate: 'vf:inputOf', object: 'ex:some-process' }
>    { predicate: 'vf:outputOf', object: 'ex:some-process' }

What if you have an EconomicResource, and you want to know its process related history?  First you look for an output EconomicEvent that produced or improved it.  Then you find the process for that output event.  Then you find the inputs to that process, and find the resources referenced by the events.  Then for each of those resources, .... etc.

**Comment by fosterlynn** [comment]
I think the graphql-jsonld interfaces will be useful.  And I don't mind keeping rdf based communications as sort of a core.  But do you think we want to mandate people use linked open data for VF?  We have always talked about using VF for sms messages, csv files, whatever.  We have @luandro working on VF in ssb.  We have an active holochain project.  I think the vocabulary and ontology/model needs to be separable from the communication technology or format.  Although I admit there are some challenges there.

**Comment by fosterlynn** [comment]
Moving the general conversation here.  From #418:

>This PR would require some implementations to update Process every time new flow gets added.  

Thinking some more:  That is true if the backend database is relational.  But this is about the vocabulary for communicating across apps, which doesn't have to match the backend database.  And per my mini-survey  in https://github.com/valueflows/valueflows/issues/306#issuecomment-447081675 the directions are mixed.  So it doesn't seem that it is a standard to support the easiest relational updates.

I don't have experience with coding the rdf side of things.  In my VF graphql api, it is easy to send whatever you want to the create/update calls, so to have the more common query direction defined in a standard manner might be better if we have to choose.  But having the inverse defined would be even better, so I can look at how that is done.

**Comment by elf-pavlik** [comment]
> Thinking some more: That is true if the backend database is relational. But this is about the vocabulary for communicating across apps, which doesn't have to match the backend database.

It doesn't make such assumption, myself I haven't used RDBS at all in last 10 years. I think about implementations I plan that would use Linked Data Platform (LDP) or Solid more specifically and where I would create process first and then use IRI of that process in all of related flows I'll create later on.

> I don't have experience with coding the rdf side of things. In my VF graphql api, it is easy to send whatever you want to the create/update calls, so to have the more common query direction defined in a standard manner might be better if we have to choose.

I'll read https://comunica.github.io/Article-ISWC2018-Demo-GraphQlLD/ and let's take a look together at how those directions impact your graphql api.

Maybe we don't need to define reverse directions in OWL ontology but only the GraphQL API your work on needs to define inverse names specific to usage in that very GraphQL API.

**Comment by pospi** [comment]
I think there are some preconditions for these types of links that might resolve some of the discussion going on here. Basically, if (for example) an `EconomicEvent` exists as a `Process.inputs`, it's an invariant of the system that the same `EconomicEvent` **must** have an `inputOf` which binds to the `Process`.

That's the way I have been thinking of things under GraphQL. Given the nature of RDF, these are probably properties that you *don't* want as part of the spec in RDF (to avoid that duplication) but *do* want as query fields in other systems which don't provide for RDF's more complex reasoning methods. For RDF, the `@reverse` property definition is probably the more desirable option.

Question: when using `@reverse`, does this make the relationships transparently queryable in both directions? If so, I think we can consider `@reverse` to provide equivalent functionality to the named reverse-direction properties in GraphQL et. al.

> Maybe we don't need to define reverse directions in OWL ontology but only the GraphQL API your work on needs to define inverse names specific to usage in that very GraphQL API.

It sounds like we are saying the same things (: Are the assumptions I'm checking above making sense?

**Comment by elf-pavlik** [comment]
> Question: when using @reverse, does this make the relationships transparently queryable in both directions? If so, I think we can consider @reverse to provide equivalent functionality to the named reverse-direction properties in GraphQL et. al.

If you define in JSON-LD `@context` something like
```jsonld
"@context": {
  "vf": { "@id": "https://w3id.org/valueflows#", "@type": "@vocab" },
  "me": {"@id": "https://me.example/" }, 
  "inputs": { "@reverse": "vf:inputOf" }
},

```

It will mean that anything like:
```jsonld
{
  "@context": { /*...*/ },
  "@id": "me:myProcess",
  "@type": "Process"
  "inputs": [
    {
       "@id": "me:myEvent",
       "@type": "EconomicEvent"
  ]
}
```

During JSON-LD expansion any `inputs` (local application alias defined in `@context`) will get replaced with canonical IRI `https://w3id.org/valueflows#inputOf`, and subject and object will get *reveresed*.

So in N-Triples (natively designed to represent RDF graph) equivalent to expanded JSON-LD would incude
```nt
<https://me.example/myEvent> <https://w3id.org/valueflows#inputOf> <https://me.example/myProcess> .
```

Or in less verbose Turtle
```ttl
@prefix vf: <https://weid.org/valueflows#> .
@prefix me: <https://me.example/> .
me:myEvent vf:inputOf me:myProcess .
```

This makes `input` sort of syntactic sugar used in compacted form of JSON-LD, underlying datastore preferably would never include it and always rely in cannonical `https://w3id.org/valueflows#inputOf`.

Still reference implementation of GraphQL-LD seems to support `@reverse`, and translating local aliases defined with it to canonical IRIs. (plus swapping subject and object of the statement).

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/valueflows/-/issues/306.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
