### ISSUE TITLE
Exchange without commitments

### ISSUE THREAD

**Issue by fosterlynn** [valueflows/valueflows#307]
This issue was triggered by a demo implementation we are doing that doesn't yet have Commitment.  I didn't see a way that we could record reciprocal Transfers without a Commitment or Agreement of some sort in our current model.  Seems like we need to be able to do that, irrespective of a limited demo.

The most obvious use case is retail.  But also the appreciation use case fits in here too.  And any scenario where an exchange is made on the spot without prior commitment.

Here is a current view and a proposed view.  Naming could probably use some tweaking.  Note that Reciprocity in the proposed view would cover appreciation, just probably not need the quantity.  Also note that in the retail scenario, there could be a Proposal with an exchange rate attached that would drive the quantities.  The M:M supports retail scenario of purchasing a bunch of stuff and paying with one currency amount.  Not sure how we would support trading one bunch of stuff for another bunch of stuff.... might need another way to bundle it.

![exchange-no-commit](https://user-images.githubusercontent.com/3776081/50055103-b7b8f580-010f-11e9-8d9a-b0330ccd4710.png)

**Comment by fosterlynn** [comment]
> Not sure how we would support trading one bunch of stuff for another bunch of stuff.... might need another way to bundle it.

Actually, our current model for the use case of an EconomicEvent creating a Commitment doesn't really support trading many things for many things.  It supports many EconomicEvents creating a Commitment, and one EconomicEvent creating many Commitments, but not many EconomicEvents creating many Commitments, as far as I can see.

**Comment by fosterlynn** [comment]
>>Not sure how we would support trading one bunch of stuff for another bunch of stuff.... might need another way to bundle it.

>Actually, our current model for the use case of an EconomicEvent creating a Commitment doesn't really support trading many things for many things.

A possible solution would be to create a new EconomicResource which vf:contains the bundle of resources.  Then there would be one transfer for each bundle.

**Comment by elf-pavlik** [comment]
Could you please write a snippet to clarify your use case? I think that we might simply reuse however we model exchange rate and have a way to save it (make a copy) and reference from an agreement. Let's discuss it around specific snippet.

**Comment by elf-pavlik** [comment]
I think the only difference in representing 'exchange rate' / 'reciprocity ratio' between Proposal and Agreement, comes down that in Commitments and Events we have quantities specific for that Agreement, while quantities in Intents don't stay specific for any specific Proposal.

In that way, in Agreement we seam to just need construct with single quantity and we can rely on quantity from one of Commitments or Events in reciprocal pair. At the same time whatever construct we use to use in Proposal, we could simply reuse for agreements in a way not trying to take advantage that the quantities stay specific for agreement but just making sure we represent the rate / ratio.

We can probably go with the snippet from #301 unless you mean something different, as you see i that proposal I didn't even include Proposal but only Agreement since it seems like what you need in this issue here.

**Comment by elf-pavlik** [comment]
I've just re-read this issue. As I understand, we currently model exchanges with `vf:ExchangeAgreement` which instances of `vf:Commitment` and `vf:EconomicEvent` reference using `vf:under`. 

>  I didn't see a way that we could record reciprocal Transfers without a Commitment or Agreement of some sort in our current model. Seems like we need to be able to do that, irrespective of a limited demo.

Exchange Agreement can get created just before Economic Event, then event can reference it with `vf:under` and Commitment that has reciprocal relation to that event would also reference it with Under. In addition the agreement would also reference Reciprocity Ratio (exchange rate) used between that event and commitment.

Something we may need to keep in mind, agreement happens between two (or more) agents. If Alice creates EconomicEvent, she MUST NOT create Commitment 'for Bob', only Bob can create commitments for oneself. 

>  The most obvious use case is retail. But also the appreciation use case fits in here too. And any scenario where an exchange is made on the spot without prior commitment.

If we don't have prior commitment, I would see it as agents just making exchange agreement and events under it right away. I experiment with prototyping small exchanges tracking app, in current stage one agent would create agreement all the events so it doesn't really represent the full scenario. Still so far I find Exchange Agreement + 2+ Economic Event + 1+ Reciprocity Ratios (exchange rates) enough to represent such transactions.

**Comment by elf-pavlik** [comment]
> Not sure how we would support trading one bunch of stuff for another bunch of stuff.... might need another way to bundle it.

That sounds like situation where Agreement Templates with Flow Templates #266 seems to have an advantage over Reciprocity Ratio (exchange rates #301). The later only works with pairs, it has patterns, quantities and possibly units for *primary* and *reciprocal*. While Agreement Template works practically the same as Process Recipe, you can have any number of Flow Templates (like Flow Recipes) and they all should scale by the same factor. 
One of the Use Case actually exchanges work for accommodation + food [Work exchange](https://github.com/valueflows/valueflows/wiki/Use-Cases-and-Requirements#work-exchange)

**Comment by fosterlynn** [comment]
I would like to re-think this also with Transfer included.  It has gotten lost, perhaps because we were looking more at process related events originally with Appreciation.  Or perhaps because it is a lot of machinery for these simple use cases.

Interestingly, in the holo-rea project the separate give and receive events are looking more useful because of the agent-centric distributed nature.

**Comment by elf-pavlik** [comment]
Ok, please don't forget to always include some *work* and *use* flows. Transfer currently seems like an artifact related to racking products / resources. Services, work, usage currently don't have any additional 'transfer' construct, just the same flows as in processes.

> Interestingly, in the holo-rea project the separate give and receive events are looking more useful because of the agent-centric distributed nature.

I don't see it in any way specific to Holochain. With Solid or even IndieWeb we also get the same distributed approach. Sometimes agents may even use a 3rd trusted party, a notary in a way to track all the flows related to specific agreement. 

![exchange agreement](https://user-images.githubusercontent.com/876431/50168905-15854300-02b2-11e9-8cba-d75802d656a3.png)

On top of that we may need to keep in mind cases where both agents have their mobile devices but they both currently stay offline.

**Comment by fosterlynn** [comment]
>I don't see it in any way specific to Holochain. 

Yes, same for any agent-centric distributed architecture.  That just happens to be the place I personally am running into it. :)

**Comment by fosterlynn** [comment]
I don't actually think we need Transfer in this change, it will relate to the events or not.

>Ok, please don't forget to always include some work and use flows.

I think this will work fine for work and use the way it is, especially if we are ignoring Transfer.

I'm going to do a PR and see if we can wrap this one up.

**Comment by elf-pavlik** [comment]
I think we may have some vagueness here. Recalling past conversation, I understand a *claim* as Commitment under Agreement where the other party *have already fulled their commitments* under that agreement. So we only have Commitment but based on the fulfillment of other commitment we can sometimes consider it as *claim* and sometimes not.

All I wanted to say in that paragraph you quoted, only agent acting as *provider* can make Commitment. If Alice makes a Commitment that Bob will provide it has no 'binding' aspect, she could make an Intent that she would like Bob to provide but only Bob can make Commitments where he provides. For that reason, when some agent plans from a recipe they should start with *work* Intents and each agent which would *provide* that work has to create a Commitment. Of course agents can automate it and have their systems create Commitments without asking them every time to approve it. Similar if plan includes *use*, *consume*, or any other flow that another agent has to provide.

**Comment by elf-pavlik** [comment]
I understand that in #384 we agreed that we need something that works also in non-dual situations and can connect any number of commitments and or events together. I recall that `vf:Agreement` with `vf:under` supposed to have that responsibility.

Having many commitments and events *under* the same agreement, one can easily interpret if some *claim* exists based on which commitments have events fulfilling them.

**Comment by fosterlynn** [comment]
>I recall that vf:Agreement with vf:under supposed to have that responsibility.

I recall vf:under to be something different - we use it when an event or whatever is calculated using an agreement, which is then referenced.  But not when it is an ExchangeAgreement that contains some commitments and/or events.  That seems like a different and more particular use case to me.  For example many sets of commitments/events could reference an Agreement using vf:under over time.  Like using a DistributionAgreement for example.  But something like a planned exchange should contain only the commitments for that particular exchange - like an order for example.

I closed the original PR related to this, agreeing that an ExchangeAgreement can be used for just events.

But I do think we need different relationship(s) than vf:under for this.  And my experience is that it is useful to have 2 relationships, one for "primary" and the other for "reciprocal", understanding that there can be any number of commitments that are either one.  This could be the same structure as Proposal and Intent in the future, then the proposals and exchange agreements would be consistent.

If you agree to this in general, I'll make a PR for the cleanup milestone.  If not, I guess we leave it until later.

**Comment by fosterlynn** [comment]
>Having many commitments and events under the same agreement, one can easily interpret if some claim exists based on which commitments have events fulfilling them.

Agree, claims can often be inferred.  Or can be instantiated, depending on people's needs. 

The only thing I think we can do here for the cleanup milestone is to change the name vf:Reciprocity to vf:Claim, which would map a bit better to standard REA.  But not a show-stopper for me.

At some point, we should clarify that whole use case and see if we want instantiated claims to occupy a different place than Commitment, which is what they do now.  So maybe that means we do nothing now?

**Comment by elf-pavlik** [comment]
> But I do think we need different relationship(s) than vf:under for this. And my experience is that it is useful to have 2 relationships, one for "primary" and the other for "reciprocal", understanding that there can be any number of commitments that are either one.

Could you please make a PR with YAML showing it?

**Comment by fosterlynn** [comment]
Resolved in v.3
