### ISSUE TITLE
Recurrence Rules

### ISSUE THREAD

**Issue by elf-pavlik** [valueflows/valueflows#308]
Some resources which should help with designing recurrence for flows:

* https://icalendar.org/iCalendar-RFC-5545/3-8-5-3-recurrence-rule.html
* https://icalendar.org/rrule-tool.html
* https://developers.google.com/calendar/concepts/events-calendars#recurring_events
* https://developers.google.com/calendar/recurringevents

I find it interesting that google calendar seems to still create event *instances* which reference recurring event with `recurringEventId`

I think we could consider defining generic `vf:ReccurrenceRule` which actual flows could reference and this way keep flows similar to those event *instances* in google calendar.

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/valueflows/-/issues/308.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
