### ISSUE TITLE
Proposals are different from Requests and Offers

### ISSUE THREAD

**Issue by bhaugen** [valueflows/valueflows#314]
How should Proposals be defined and modeled in VF? Requests and Offers can resemble (and become) Commitments, and include Resource Classifications. But Proposals are more like proposing to do something with other agents. More like a Process Classification than a Resource Classification.

We have a situation in FairCoop where people want what they call a "kanban board" modeled after Trello or Wekan, with columns called Backlog, Doing, and Done.

Doing and Done are Processes. Backlog is more like a proposal for a process, and could become a process.

Are Proposals a different type of Intent, or are they something else?

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/valueflows/-/issues/314.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
