### ISSUE TITLE
modeling various matches between vf:Offer and vf:Request

### ISSUE THREAD

**Issue by elf-pavlik** [valueflows/valueflows#318]
I created new use case - [Olive oil request](https://github.com/valueflows/valueflows/blob/master/use-cases/olive-oil-request.md). Based on that we can analyse how to represent various matches between _vf:Offer_ and _vf:Request_. In captured use case:
- Various agents distributing olive oil publish they offers which include matching request as they imagine it
- I publish my request and need to create matching offers, based on the matching requests published by providers.

I will add more TODO directly to the page of this use case. For example, if provider don't can't provide full 2L, do I want to make my request flexible so it still matches.

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/valueflows/-/issues/318.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
