### ISSUE TITLE
defining Transportation

### ISSUE THREAD

**Issue by elf-pavlik** [valueflows/valueflows#331]
Let's start with transportation of physical resources.
1. Do we have a use case we can start working with? @bhaugen 
2. If we want to transport 1000kg of apples, already packed in 50kg wooden crates. How do we connect that resource with transport? I don't think it goes as neither the input or output... (let's maybe pick a use case and let it drive our work)

**Comment by bhaugen** [comment]
Anders Hessellund's REA transportation paper referenced above is no longer available from that URL. Here are a couple of alternatives, plus I have downloaded and saved it locally just in case.
* https://www.researchgate.net/publication/255608424_Supply_Chain_Modeling_with_REA
* https://www.slideshare.net/Demetrius_Gallitzin/Hessellund05a

Here's another related paper by Anders:
* https://www.academia.edu/22757503/Modeling_Issues_in_REA

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/valueflows/-/issues/331.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
