### ISSUE TITLE
start & stop events for usage & work (similar to load & unload) in transportation

### ISSUE THREAD

**Issue by elf-pavlik** [valueflows/valueflows#336]
It looks like currently we can't track in real time which tools and people stay occupied (blocked) by which processes. With only _use_ and _work_ events we can't track the start and stop of work and usage. Many processes will also allow interruption so single usage and work will have multiple _start_ and _stop_ events referencing them.

**Comment by fosterlynn** [comment]
A perspective on this issue: I don't think that start and stop work is actually the same as load/unload.  Stop work won't be an output of a process.  I think the way to think about it is just different methods of recording work.  In the end you get one or more observed work events.

**Comment by elf-pavlik** [comment]
I think this ties to #230 and this diagram:

![flows](https://raw.githubusercontent.com/valueflows/valueflows/0d24fe91a85b02d7f6ec5b64033138cc40ea296c/assets/flows.png)

It only addresses future and past but we can have events which we started observing but they haven't finished yet. I think this might apply to any action, even *consume* on a grid resource (water, gas, electricity) which has a meter will have weeks long *consume* events.
We could possibly rely on `vf:finished` to tell difference between present events and past events. I think also `vf:Fulfillment` would get created only after the event finishes.

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/valueflows/-/issues/336.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
