### ISSUE TITLE
consistent labelling system across our vocab

### ISSUE THREAD

**Issue by ahdinosaur** [valueflows/valueflows#34]
as mentioned in https://github.com/valueflows/agent/pull/30#issuecomment-145809856 and https://github.com/valueflows/agent/issues/9#issuecomment-144392445, i think we should aim for a consistent labelling system across all our domains. i'm bringing this issue up here and now so i don't block https://github.com/valueflows/agent/pull/30 and https://github.com/valueflows/agent/issues/31.

features we need in our labels:
- primary names
- [nick names](https://github.com/valueflows/agent/issues/9#issuecomment-144098333)
- long descriptions
- language maps (as supported by [JSON-LD language maps](http://www.w3.org/TR/json-ld/#dfn-language-map))
- [audible labels](https://github.com/valueflows/agent/issues/31#issue-109958938)
- ???

possible options:
- [`skos` labels](https://en.wikipedia.org/wiki/Simple_Knowledge_Organization_System#Labels_and_notations)
- `as` [`displayName`](http://www.w3.org/TR/activitystreams-vocabulary/#dfn-displayname), [`title`](http://www.w3.org/TR/activitystreams-vocabulary/#dfn-title), and [`summary`](http://www.w3.org/TR/activitystreams-vocabulary/#dfn-summary)
- `rdfs` [`label`](http://www.w3.org/TR/rdf-schema/#ch_label) and [`comment`](http://www.w3.org/TR/rdf-schema/#ch_comment)
- `dcterms` [`description` ](http://dublincore.org/documents/dcmi-terms/#terms-description)
- ???

**Comment by elf-pavlik** [comment]
awesome summary! thanks @ahdinosaur :smile:

**Comment by fosterlynn** [comment]
Another one: 

dcterms:description

**Comment by ahdinosaur** [comment]
i propose we adopt the following [labels](http://www.w3.org/TR/2009/NOTE-skos-primer-20090818/#seclabel) and [documentation](http://www.w3.org/TR/2009/NOTE-skos-primer-20090818/#secdocumentation) properties for every domain:

- [`skos:prefLabel`](http://www.w3.org/TR/skos-reference#prefLabel)
- [`skos:altLabel`](http://www.w3.org/TR/skos-reference#altLabel)
- [`skos:hiddenLabel`](http://www.w3.org/TR/skos-reference#hiddenLabel)
- [`skos:note`](http://www.w3.org/TR/skos-reference/#note)

and for only the type objects:

- [`skos:definition`](http://www.w3.org/TR/skos-reference/#definition)
- [`skos:example`](http://www.w3.org/TR/skos-reference/#example)

this handles all the use cases described so far, except audible labels.

i'm not sure, but it's possible we alias these properties separately in some objects, e.g. Agent might have `prefName` (`prefLabel`), `nickName` (`altLabel`), and `bio` (`note`). i'm kinda leaning towards leaving that up to users (anyone can alias their own properties) and we just keep it simple and consistent here.

---

a future proposal by me will be to adopt [`skos` semantic relationships](http://www.w3.org/TR/2009/NOTE-skos-primer-20090818/#secrel) in our type objects, but this current proposal is limited to labelling.

**Comment by fosterlynn** [comment]
>if you would like to rename 'label' and 'labelMap' to 'name' and 'nameMap' I see no problem, actually even like it by lowering chance for cognitive mixing it with label as 'tag'. I initially used 'displayName' and 'displayNameMap' (from https://github.com/valueflows/agent/issues/53#issuecomment-150605692)

I don't see needing both 'name' and 'label'.  So if you all are OK, let's change it, keeping the reference to skos:prefLabel.  If it is that simple, we can then probably close this one and the other issues referenced by elf for now.

Do we like name or displayName?  I saw displayName in activity streams as property of agents (actors to them), nowhere else, when I looked a while back.  I'm good with either, although the definitions are a bit different.  displayName to me implies something more like a label, also could imply option to use personas - more a computer related concept than a real world usage.  But again, I'm fine either way.

**Comment by fosterlynn** [comment]
>Most likely in named issue we can also entertain renaming 'note' and 'noteMap' to 'description' and 'descriptionMap'

I think notes are more general purpose, can be used for anything to annotate about something.  Description is for defining or describing the object itself.  So the skos:definition might work for this, as documented earlier in this issue?

So I guess I like 'note'.  And 'definition' for type objects.  Others?

**Comment by ahdinosaur** [comment]
:+1: `name` instead of `label` for `skos:prefLabel`. 

for `skos:altLabel`:

- `nickNames`
- `alternateNames`

?

keen on `note` and `definition`.

**Comment by elf-pavlik** [comment]
I would just like to ask that we don't add any new terms unless we notice common need for them in existing and new examples.

**Comment by fosterlynn** [comment]
@elf-pavlik  I agree.  

Question on workflow / process:  I'm not putting anything into the examples that we haven't agreed upon.  Sounds like you are thinking the workflow is more to put proposed additions into the examples first, then discuss, then add to the vocab if we agree?

In this case, we (NRP) do have a definition for user defined types of agents and types of relationships in the data, some people use it and some don't.  At some point, I'd like to discuss adding skos:definition to those since they are vocabulary-like.

However, I'm good with waiting until we have a round trip working, and then re-visiting the various possible additions when we map to existing vocabs.....

**Comment by elf-pavlik** [comment]
> In this case, we (NRP) do have a definition for user defined types of agents and types of relationships in the data, some people use it and some don't. At some point, I'd like to discuss adding skos:definition to those since they are vocabulary-like.

If you have examples which need it, please don't hesitate to propose it! I just wanted to re-emphasize approach of examples driving eventual additions.

**Comment by fosterlynn** [comment]
>I just wanted to re-emphasize approach of examples driving eventual additions. 

:+1:
