### ISSUE TITLE
ResourceType taxonomy

### ISSUE THREAD

**Issue by bhaugen** [valueflows/valueflows#354]
For example, http://aims.fao.org/standards/agrovoc
or http://www.productontology.org/
or...?

**Comment by myriamboure** [comment]
We did work a lot of that in DFC and concluded to the need of a "facets" approach to be able to identify unique product IDs and recognize that product on platform A is the same as product on platform B. Inspired by Langual approach, but as local food hubs don't only sell food, and some products are multi or single origin we need some refined approach to describe that.
Here is a table with the result of the logic. Each combination of facet is a unique identifier.
https://docs.google.com/spreadsheets/d/1l0wCwerm1ZW6zkUF4uB_A8u6B-MRaY3DmKSZKK9Z0vc
On the "nature origin" facet for instance we could use agrovoc or itis base, but we need others for mineral components for instance (if I sell soap and want to share the composition).

I'm trying to discuss with Open Food Facts to see how we could contribute with the above logic and use their citizen driven product catalog as universal product IDs / URI we could base our interoperability logic on. There are some power/control fight at the moment on who is gonna control the universal product URI catalog... in France for instance the government did mandate the agro-industry representative and GS1 on it...

**Comment by bhaugen** [comment]
We used faceted categories for the NRP software we developed with Sensorica, as you can see here:
http://nrp.sensorica.co/accounting/inventory/
The facets are in the filter panel on the right.

Facets were the only thing that would work for them, but they did not actually *like* them. Found it difficult to create new facets and facet values. And over-classified - used too many facets for the same thing -  which caused some problems.

But we had tried simple categories first, and then taxonomies, and they always had multiple classes for many resource types.

When FairCoop forked NRP, they added a taxonomy and the taxonomy and facets interfered with each other to some extent.

I wrote a comparison of different methods of classification here: https://board.net/p/Classification
