### ISSUE TITLE
shares and 'logical stocks' of material resources

### ISSUE THREAD

**Issue by elf-pavlik** [valueflows/valueflows#365]
I would like to discuss it based on [Shares: Peanuts deposited in community storage](https://github.com/valueflows/valueflows/blob/master/use-cases/shares.md) use case

> 1. Community of 20 people produced 1000kg of peanuts in one season
> 2. They allocated 200kg to their community kitchen
> 3. They distributed shares to the remaining 800kg using [resource distribution algorithm](https://github.com/valueflows/valueflows/issues/120#issuecomment-217671421)
> 4. All the peanuts stay stored in the same cellar
> 5. Inventory management system keeps track on the allocations
>    - 1 allocation of 200kg community kitchen
>    - 20 allocations adding up together to 800kg
> 6. Each person has a claim for her/his share of peanuts in one's own independent data space
> 7. People can transfer those shares to each
> 8. When someone requests donation of peanuts, shareholders can meet that requests by combining the total weight from any combination of fractions of their shares
### Agents

Let's just focus on 3 people, where one of them also manages the community kitchen:

``` yaml
'@context': https://w3id.org/valueflows/v1
'@graph':

  - '@id': wendy:identity
    '@type': foaf:Person

  - '@id': matthew:identity
    '@type': foaf:Person

  - '@id': joel:identity
    '@type': foaf:Person
    'skos:note': Joel manages community kitchen
```
#### Physical

``` yaml
'@context': https://w3id.org/valueflows/v1
'@graph':

  - '@id': commune:peanuts-2016
    '@type':
      - vf:MaterialResource
      - prodont:Peanut
    'vf:quantity':
      '@type': qudt:QuantityValue
      'qudt:unit': unit:Kilogram
      'qudt:numericValue': 1000
    'vf:currentLocation': commune:big-cellar
```
#### Virtual

``` yaml
'@context':
 - https://w3id.org/valueflows/v1
 - https://w3id.org/role/
'@graph':

  - '@id': commune:kitchens-peanuts-2016
    '@type':
      - vf:MaterialResource
      - prodont:Peanut
    'vf:partOf': commune:peanuts-2016
    'role:owner': commune:identity
    'role:custodian': joel:identity
    'skos:note': For use in community kitchen
    'vf:quantity':
      '@type': qudt:QuantityValue
      'qudt:unit': unit:Kilogram
      'qudt:numericValue': 200

  - '@id': commune:joels-peanuts-2016
    '@type':
      - vf:MaterialResource
      - prodont:Peanut
    'vf:partOf': commune:peanuts-2016
    'role:owner': joel:identity
    'vf:quantity':
      '@type': qudt:QuantityValue
      'qudt:unit': unit:Kilogram
      'qudt:numericValue': 40

  - '@id': commune:wendys-peanuts-2016
    '@type':
      - vf:MaterialResource
      - prodont:Peanut
    'vf:partOf': commune:peanuts-2016
    'role:owner': wendy:identity
    'vf:quantity':
      '@type': qudt:QuantityValue
      'qudt:unit': unit:Kilogram
      'qudt:numericValue': 70

  - '@id': commune:matthews-peanuts-2016
    '@type':
      - vf:MaterialResource
      - prodont:Peanut
    'vf:partOf': commune:peanuts-2016
    'role:owner': matthew:identity
    'vf:quantity':
      '@type': qudt:QuantityValue
      'qudt:unit': unit:Kilogram
      'qudt:numericValue': 15
```

**Comment by elf-pavlik** [comment]
reopening since we seem to go over the same thoughts in #270

**Comment by fosterlynn** [comment]
From https://github.com/valueflows/valueflows/pull/499

>Probably we may need to solve first situation in #365 where we have one physical resource where different agents own different quantities of it.

I think the physical parts of a containing resource we can deal with as purely material resources.  (This is the distributed peanuts or bikes/bikeshed example.  Leaving aside anything that is shares or contributions and can't be divided easily.)  If you run into a contains situation, you just know to not double count your inventory.  And if the contained resources are owned by different agents, like with the peanuts, then that seems workable; probably also some custodianship and possession kind of things will be left with the agent that manages the whole stock.

**Comment by elf-pavlik** [comment]
I think we should do either but not both:
* represent actual physical resource as 'containing' sub resources owned by different agents
* represent ownership 'rights' themselves as resources with 'underlying' actual physical resource, as in your PR #498

**Comment by fosterlynn** [comment]
>I think we should do either but not both:

>    represent actual physical resource as 'containing' sub resources owned by different agents
>    represent ownership 'rights' themselves as resources with 'underlying' actual physical resource

I lean towards the first.  Or do you mean let people decide which to do, but they shouldn't do both at the same time?

**Comment by elf-pavlik** [comment]
I mean we shouldn't do both at the same time, all implementations should just need to implement one way of handling such use cases.

**Comment by fosterlynn** [comment]
>I mean we shouldn't do both at the same time, all implementations should just need to implement one way of handling such use cases.

I'm not sure we want to keep the concept of underlyingResource.... but maybe we won't know until we get transfer and quantities done....  (Part of my thinking is I thought you didn't like it though....?)

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/valueflows/-/issues/365.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
