### ISSUE TITLE
packaging

### ISSUE THREAD

**Issue by elf-pavlik** [valueflows/valueflows#370]
Often resources come with packages. In many cases producers accept the packaging back to reuse, in other cases different facilities accept them for recycling. I work on minimising disposable packaging and will document some use cases where we return containers after emptying them.

It also relates to #26 , in many cases generic product types will have no information about packaging, but vendor specific product models will often include packaging information.

**Comment by elf-pavlik** [comment]
VF has a clear model for processes with inputs and outputs. We also had some discussion about assembling and disassembling #158 which differ from irreversible compositions (transformations).
Besides that we also discussed to put emphasis on circular economy #97 so keeping track on all the packaging materials makes a lot of sense here.

> I can share some file about this logic if you want with various examples !

Yes please, I plan to take some time now to organize all kinds of Use Cases and Requirements for ValueFlows.

**Comment by elf-pavlik** [comment]
I have just added initial use case for packaging focused on food networks: https://github.com/valueflows/valueflows/wiki/Use-Cases-and-Requirements#packaging

**Comment by bhaugen** [comment]
[LearnDeep](https://learndeep.org/) https://github.com/LearnDeepMilwaukee has a requirement for reusable containers used for resource-sharing where fablab components and tools are packed into containers for the library trucks to move to another school. I've done this in code, but not in VF. If this use case is interesting to anybody, I will detail it out in a VF use case.

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/valueflows/-/issues/370.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
