### ISSUE TITLE
timeline based stocks (availability?) for Usage and Services 

### ISSUE THREAD

**Issue by elf-pavlik** [valueflows/valueflows#375]
in https://github.com/valueflows/valueflows/issues/148#issuecomment-239818476 @bhaugen writes: 

> The [Quick Response Engine](https://en.wikipedia.org/wiki/Quick_Response_Engine) (QRE)  was a skunkworks project for an ERP software company I worked for in the 1990's, and was also my first implementation of the set of ideas that fed into VF.  
> 
> We did shift scheduling for people and equipment in that project. The inventory of such time-based resources was a shift calendar composed of 15-minute slots. It was implemented as sparse array composed only of slots where the resource was scheduled to be available: for a person, the shifts they were scheduled to work. Each time-based resource had a shift calendar. A process could reserve as many of these 15-minute slots as it needed, assuming they were not already taken by some other process.

For _work_ and _use_ #29  type events we need a way to describe a resource/stock #41. I would consider describing timeline of availability as stock in which we can create 'logical resources' which we can reference in allocations #39

**Comment by elf-pavlik** [comment]
Looking at https://valueflo.ws/introduction/flows.html#timeline-plans-and-observations

![vf-timeline](https://raw.githubusercontent.com/valueflows/valueflows/master/assets/flows.png)

I don't really see how 'time based resources' would fit there. Intents and commitments seem capable of representing planned (intended) availability.

![flows schedule](https://user-images.githubusercontent.com/876431/54950304-9b92d480-4f06-11e9-87bb-9f5a46237817.png)

*(on both diagrams blue intent, orange commitments)*

For personal schedule one could have similar diagram just use quantity 1 (just me).

Reading https://valueflo.ws/introduction/resources.html#the-difference-between-a-resource-and-its-specification-or-classification

> An economic resource is observable. Its specification or classification defines what type of thing the economic resource is.

So far any 'future resource' to my understanding has to have `vf:currentQuantity: 0` which actually one can observe. While I can see how we can express future plans with intents (independent plans) and commitments (agreed plans), at this moment I don't see need for instances of `time based` `vf:EconomicResource`.

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/valueflows/-/issues/375.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
