### ISSUE TITLE
Keep Location?

### ISSUE THREAD

**Issue by fosterlynn** [valueflows/valueflows#402]
Right now we have vf:Location defined in the ttl, and 2 properties referring to it: vf:currentLocation, vf:primaryLocation.

Should we keep vf:Location?  If so, put some minimal definition in it?  Or treat it as something that people can find online, and have those 2 properties refer to a URI?

We have made a few attempts to find an existing vocabulary, but if there is one that is used by say OpenStreetMap etc., we could use that.  Some investigation needed.

If we want to leave it as-is, I'll add it to the UML, it's not there right now.

**Comment by elf-pavlik** [comment]
I would prefer to remove it and for now just leave ranges of those two properties undefined

**Comment by fosterlynn** [comment]
Done (last PR).
