### ISSUE TITLE
How to document examples

### ISSUE THREAD

**Issue by fosterlynn** [valueflows/valueflows#409]
What structure should we use to include examples in the doc?  Separate section we can structure as we like? Examples for each text page?  (I think not the best.)  Examples for classes / properties?  (Might be hard given the tool we use to generate the specification document.)  I guess my current vote is a new section, what do you think @elf-pavlik ?

I think the first sets of examples should be very simple examples for all the basic concepts.  The purpose would be to help people who are just starting to explore understand the concepts.

Then we can do more complex examples of different use cases - maybe for this release or maybe not.

**Comment by elf-pavlik** [comment]
I think we can just use different section and add links to relevant examples in existing sections. I also would like to try something like https://plugins.gitbook.com/plugin/codesnippet to avoid duplicating existing `.yaml` files.

**Comment by fosterlynn** [comment]
>I think we can just use different section and add links to relevant examples in existing sections.

Ok fine with me.

>I also would like to try something like https://plugins.gitbook.com/plugin/codesnippet to avoid duplicating existing .yaml files.

You want to check into it?

I'll start writing some simple examples.

**Comment by fosterlynn** [comment]
Here is a tentative list of basic examples that would be helpful.  Feedback welcome!  Or feel free to edit.

- [ ] Agent and relationships
- [ ] Planned process with inputs and outputs, manufacturing
- [ ] Planned process with inputs and outputs, workflow (accept/improve)
- [ ] Events fulfilling commitment (different scenarios representing the M:M)
- [ ] Recipe
- [ ] Exchange agreement with commitments (and events??) (depending on if we agree on vf:under)
- [ ] Event triggering a commitment (depending on where we think we're going with claim)
- [ ] Process with intent, which gets committed to

It occurs to me that it might be interesting to create a whole series of connected examples, starting with recipe, plan from recipe, commit to an intent, execute the plan, trade some of the output.  Not sure, might experiment.

**Comment by fosterlynn** [comment]
Another (additional?) way to approach examples might be to do some of the use cases that people could directly relate to: timebank for example.

**Comment by elf-pavlik** [comment]
Once we get #411 merged I'll make PR for including code from files in gitbook

**Comment by fosterlynn** [comment]
>#414 doesn't seem to work with new gitbook

We could just put the examples into the md directly, so a code block or something?

**Comment by elf-pavlik** [comment]
Actually now it seems to also seams work with gitbook.io https://www.valueflo.ws/introduction/agents.html#examples
