### ISSUE TITLE
RDF spec plus non-RDF spec

### ISSUE THREAD

**Issue by fosterlynn** [valueflows/valueflows#427]
Right now we are RDF centric (which is fine) in the actual spec, while noting that we will support any format needed.  The all_VF.ttl file is our "system of record" and the only machine-readable spec we have.  We are also discussing it not being good practice to include other vocabulary terms inside our vocabulary (skos:note, but also foaf:Agent, etc.).  See https://github.com/valueflows/valueflows/issues/423 and https://github.com/valueflows/valueflows/pull/424 and https://github.com/valueflows/valueflows/pull/415.

But, also we want to support non-rdf implementations (and are doing a couple of them now).  Even many of the ActivityPub developers want to use just plain json.  

Proposal: 
* We keep our machine-readable ttl spec with its generated human-readable spec as it is (and we can eliminate all other vocab elements).
* We add a parallel spec that is also machine-readable, and has the same content but includes the elements we want to have that are already represented in other rdf vocabularies.  One idea: json-schemas.  I think that is what we have in holochain (can check); and that is what ssb uses.

**Comment by elf-pavlik** [comment]
For non-RDF applications, I would also like to know strategy for using VF together with other non-RDF vocabs and having a way to know which terms come from which vocab, as well as not having collisions int terms defined by different vocabs.

Currently non-RDF spec sounds to me more like "let's make a VF-centric bubble" rather than "let's contribute to an open ecosystem". Possibly because I don't see how those non-RDF approaches address challenges I mention above.

**Comment by fosterlynn** [comment]
>When it comes to JSON Schema, AFAIK it can't properly represent RDF and similar solutions exist which can

But we have rdf definitions already, so we don't need to do that.  We need something that people can easily use that doesn't require rdf conventions.  I'm not suggesting we get rid of what we have of course.

>For non-RDF applications, I would also like to know strategy for using VF together with other non-RDF vocabs

Sort of interesting, I think the fact that rdf has properties that don't have to be part of a class makes a big difference here.  Like in non-rdf land (at least afaik), you can't have something like a free-floating skos:note, so you just put a note wherever you need one, and that is that, you aren't conflicting with anything else.  So the only overlap will be classes.

And I don't know how easy it is to mix and match vocabs that aren't rdf-based, that is something that the semantic web people have done relatively well imo.  But anyhow, I don't have experience with other kinds of standards.  @bhaugen was involved in some ISO and UNCEFACT standards for REA, he may have some knowledge there.

>For example we could jump into your GraphQL work and see how we can deal with #306

If you have time and inclination (no rush), here are a bunch of sample queries in graphql that are basically VF.  (NOTES: They are not current with recent changes.  There are some things that won't ever be in VF but were needed for that app.  There are a few cheats and short-cuts.  But you will recognize it for the most part.  And it was the first experiment, so please give some allowances and don't get worried if you see something weird. :blush: )  https://github.com/FreedomCoop/valuenetwork/blob/master/valuenetwork/api/tests.py#L996 

This might also be interesting:  Here are the schemas for the holochain demo.  https://github.com/holo-rea/holo-rea-proto/tree/master/src/HoloREA/dna  I need to do a PR to get the VF definitions in, and there are a few other details to fix. And again this is from earlier VF, and was done from looking at the VF doc.

**Comment by elf-pavlik** [comment]
> There are some things that won't ever be in VF but were needed for that app.

Maybe you could define those terms as some custom vocab (if you can't reuse existing ones), and then propose solution to avoid collisions if someone else who needed something else for different applications used the same name to mean something different. So yet another application can get data produced by those two apps and don't end up confusing things.

**Comment by fosterlynn** [comment]
>Maybe you could define those terms as some custom vocab (if you can't reuse existing ones), and then propose solution to avoid collisions

Good thought!  The example that comes to mind is they do validations of work events (supposed to be validated by someone who was involved and knows the work done).  The rules are fairly specific, and also experimental, so I don't think it is ready to "vocabularize" yet.  Something like value equations could be another thing that could eventually have some extension to the vocabulary.  Anyhow, your point is very good, and it will be worth keeping track of what people need that isn't in VF.  And before that, worth checking for existing vocabularies.

**Comment by bhaugen** [comment]
Yesterday @fosterlynn pointed me to https://www.w3.org/TR/vocab-org/ where they say:
> The ontology does not provide category structures for organization type, organization purpose or roles. Different domains will have different requirements for classification of such concepts. Instead the ontology provides just the core base concepts needed to allow extensions to add specific sub-class structures or classification schemes as required. Users of the ontology are encouraged to define profiles which strengthen interoperability by specifying particular controlled vocabularies to use for these concepts.

They do provide slots for the concepts they mentioned, e.g. https://www.w3.org/TR/vocab-org/#class-role   , so it's clear where they fit into the vocabulary structures, but they leave the details to profiles. 

@elf-pavlik do you have experience or knowledge of such profiles?

**Comment by elf-pavlik** [comment]
@fosterlynn thinking about our discussion on the call and #433 
How do you plan to capture that some class names and their meaning stay *testing* or even *stable* but each of properties used on instances of those classes can range from *unstable* to *stable* ?

**Comment by fosterlynn** [comment]
>How do you plan to capture that some class names and their meaning stay testing or even stable but each of properties used on instances of those classes can range from unstable to stable ?
Someone not keeping RDF in mind might expect that properties belong to classes and stability of properties stay accounted for in stability of the class.

I think the ttl file is good enough for now.  But when I figure out the best format for non-RDF stuff, I'll check to see if there is an accepted way to do that there, making the properties clearly distinct.  But if not, ttl file seems fine.  OK for you?

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/valueflows/-/issues/427.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
