### ISSUE TITLE
What is "stable"?

### ISSUE THREAD

**Issue by fosterlynn** [valueflows/valueflows#433]
List for discussion by just running through the ttl file, based on my impressions of use in the field and REA status (not how many examples we have in VF):

classes

concept is stable, name maybe not
* Action 
* ResourceSpecification
* RecipeProcess
* RecipeFlow

concept and name stable
* Commitment
* EconomicResource
* Process
* EconomicEvent

properties

concept is stable, name maybe not
* action
* involves (name not stable)
* affects
* definedQuantity
* observedTime
* committedTime
* intendedTime
* plannedTime
* basedOn
* classifiedAs
* resourceClassifiedAs
* resourceConformsTo

concept and name stable
* provider
* receiver (unless we change it to recipient on this release and leave it that)
* currentQuantity
* currentLocation
* finished
* consume
* work
* cite
* produce
* substitutable
* unit

**Comment by elf-pavlik** [comment]
> concept is stable, name maybe not

I think we should not change name after going to *testint*, never for stable.

Also we might need to keep in mind that those names only matter for developers who speak enough english language to work on software. People using UIs will always use *labels* provided by application and preferably in the language of their preference.

> * observedTime
> * committedTime
> * intendedTime
> * plannedTime

I think we have changed them very recently to use `time:emporalEntity`, I can't imagine that two open source implementations would already have it implemented.

> action

You mentioned possibility of considering to define `vf:Action` as instance of `rdfs:Class` not `rdf:Property`. If we want to consider doing that, we should keep it *unstable*.

I think we should follow [suggested workflow](https://github.com/valueflows/valueflows/blob/master/CONTRIBUTING.md#a-suggested-workflow) and focus on writing examples until we feel very comfortable to promote some of the terms heavily used in those examples to *testing*, and writing implementations to promote terms which reliably work across those implementations to *stable*. 

I can start writing script which would parse all our examples and show usage statistics for each term.

**Comment by fosterlynn** [comment]
>I think we should not change name after going to testint, never for stable.

Agreed. 

>I think we have changed them very recently to use time:emporalEntity, I can't imagine that two open source implementations would already have it implemented.

True enough.

>You mentioned possibility of considering to define vf:Action as instance of rdfs:Class not rdf:Property. If we want to consider doing that, we should keep it unstable.

Agreed.

>I think we should follow suggested workflow and focus on writing examples until we feel very comfortable to promote some of the terms heavily used in those examples to testing, and writing implementations to promote terms which reliably work across those implementations to stable.

I think that makes sense when starting from nothing.  But we do have some things implemented and used to varying degrees, as well as the REA ontology itself.  That's why I wanted to do somewhat of a gut dump on it.  I like your observable criteria, but also to keep in mind the formal definitions of the status vocabulary:

>'unstable'
>    The meaning, deployment practices, documentation (or important associated software/services) associated with this term are liable to change arbitrarily at some point in the future. They may not, but stability is not guaranteed. Use with caution.
'testing'
>    The meaning, deployment practices, documentation and general understanding of this term are approaching some stability, but changes are still possible due to implementation experience or other unanticipated factors.
>'stable'
>    The term is relatively stable, and its documentation and meaning are not expected to change substantially.

All that said, I suppose we don't have much that is actually stable.

**Comment by elf-pavlik** [comment]
> All that said, I suppose we don't have much that is actually stable.

I think we can consider promoting few things to *testing* and use it as motivation to write more extensive examples.

**Comment by elf-pavlik** [comment]
Also to clarify, we will proudly release `v0.2` but before we hit `v1.0` we might end up with versions like `v0.24`, i think every milestone we should release new version and if we keep focus on making progress maybe by the end of this years we'll reach near `v1.0`, so having 2 milestones a month we should get at least till `v0.23`

**Comment by elf-pavlik** [comment]
Can we remove *cleanup* milestone since we've merged #439 ?

**Comment by fosterlynn** [comment]
>Can we remove cleanup milestone since we've merged #439 ?

done
