### ISSUE TITLE
Multiple aspects of usage (taxi)

### ISSUE THREAD

**Issue by fosterlynn** [valueflows/valueflows#442]
Use case: Taxi service involves recording
1) miles
2) idling time when not moving

How to record this kind of usage of the taxi?  Or is there a better way of thinking about this use case than usage?

**Comment by bhaugen** [comment]
Taxi fare calculations:

* Seattle:
> Taxi fare is a combination of three separate charges:
Drop (or base) charge.
Distance charge.
Time charge.
You don't simultaneously pay both distance and time charges; you pay one or the other.

Drop charge: Applied as soon as you enter the taxi and accept a ride | $2.60
-- | --
Distance charge: Applied once the taxi is travelling to your destination | $2.70 per mile($0.30 per 1/9 mile)
Time charge: Applied when the taxi stops or travels at slow speeds during the trip (for example, at red lights or in heavy stop-and-go traffic) | $0.50 per minute ($0.30 per 36 seconds)

* Wash DC:
> base charge of $3. Total distance traveled is charged at $2.16 per mile... The traffic wait time rate is $25 per hour, or about $2 every 5 minutes. Riders pay 50 cents for "each piece of luggage the operator places in his or her trunk."

* NYC:
> base fare of $2.50 plus 25 units at $0.50 each, or $12.50, for a total of $15.00. It is customary to tip the driver 20%.

**Comment by elf-pavlik** [comment]
> Drop charge: Applied as soon as you enter the taxi and accept a ride

Sounds like agreement might include *load* event and that specific charge.

> Riders pay 50 cents for "each piece of luggage the operator places in his or her trunk."

Similar just *load* luggage not the person.

> Distance charge: Applied once the taxi is travelling to your destination 	$2.70 per mile($0.30 per 1/9 mile)
> Time charge: Applied when the taxi stops or travels at slow speeds during the trip (for example, at red lights or in heavy stop-and-go traffic)   $0.50 per minute ($0.30 per 36 seconds)
[...]
> base charge of $3. Total distance traveled is charged at $2.16 per mile... The traffic wait time rate is $25 per hour, or about $2 every 5 minutes.

Do you know how does this get calculated? Would having total distance and total duration suffice or one has to have continuous record of speed throughout the whole duration of the ride?

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/valueflows/-/issues/442.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
