### ISSUE TITLE
Untangling work, use, transfer in scheduling

### ISSUE THREAD

**Issue by fosterlynn** [valueflows/valueflows#443]
I'm thinking that the scheduling milestone should be done without resolving transfer if possible, as that is already defined for later, and is another big "can of worms".  So part of this is to see if we can separate out the transfer aspects of scheduling for later.  Or if not, then so be it.

Also there are some differences in work and usage, in that work does not involve a material resource (we do not too much like the term "human resources" and would like to work towards human agency as people and democratic groups, therefore don't foresee people as EconomicResources).

Copying from #394 to here, and will delete from that issue:

Summarizing the quantities we may need to think about for usage:
1. Number used of a larger stock resource.
2. Actual time used (a QuantityValue)
3. Duration on a schedule (reserved, available, others can't use it)
4. Duration (larger) where the usage occurred - like (10 hours) used in the last month
5. Duration of the actual usage event, where the resource was used as input to a process. [edit]

Looking at similarities and differences with work:
1. No material resource, always one provider agent
2. Actual time worked (a QuantityValue)
3. Duration on a schedule (reserved, available, others can't schedule the person to work)
4. Duration (larger) where the work occurred - like (10 hours) worked in the last month
5. Duration of the actual work event, where the work was input to a process. [edit]

Work is the same except 1.

[edit] I think that 3. involves transfers.  Although it is also a chunk of time on a schedule, so could be represented as an interval or duration.

**Comment by fosterlynn** [comment]
Further random thoughts:

I think we should reserve the action `use` for actual usage, which contributes to a process.  So availability or possession does not imply usage, as we can see in #220.  (Nor does ownership for that matter.)

Likewise for `work`.

Interestingly, `cite` has a similar aspect to `use` and `work` where the quantity that matters is not the same as the quantity of the cited resource (document, design, etc.).  And I can't think of a situation where a citation could be made for more than one of a "stock" resource.  The quantity that matters still could be '1' in that citations (the events) are counted that way.  For Sensorica's distribution logic, they wanted to have the person doing the citing record a percentage of the process/output that they felt the cited resource contributed to that process, then the contributor(s) to the cited resource would get that percentage of income assigned to that process .  It is different in that citations don't affect availability.  But we could consider `cite` in terms of figuring out what quantity properties are used for what.

In terms of quantity/duration fields, I think that the `observedTime` could be either the exact interval of the usage or work, or it could be a longer interval (like a month, week, etc.) during which the actual work or usage actually happened.  Seems like the same property should work for both, as this property is basically about when: putting things in order / on a timeline / on a schedule, etc. more than actually measuring quantities of the usage or work.  So this relates to schedule, but not so much accounting.  I think that could accommodate 3.,4.,5. above.

**Comment by elf-pavlik** [comment]
> For Sensorica's distribution logic, they wanted to have the person doing the citing record a percentage of the process/output that they felt the cited resource contributed to that process, then the contributor(s) to the cited resource would get that percentage of income assigned to that process .

I think we should deal with this use case as part of *agreements* milestone. It sounds to me like something related to *Reciprocity* removed in #430 I hope we can agree that we should not put any reciprocity related responsibility directly on flows and that Sensorica experiment of using quantity in *cite* event for that reason will have different way to model it in VF.

> I think we should reserve the action use for actual usage, which contributes to a process. So availability or possession does not imply usage, as we can see in #220. (Nor does ownership for that matter.)

I think while looking at that we may need to touch *transfers* milestone and *proposals* milestone. Since it all ties into planning.

**Comment by elf-pavlik** [comment]
> Also there are some differences in work and usage, in that work does not involve a material resource (we do not too much like the term "human resources" and would like to work towards human agency as people and democratic groups, therefore don't foresee people as EconomicResources).

In case of passenger transportation and health care, *load*, *unload*, *accept*, *improve* might actually affect person directly. So the person might have both roles in those situation Agent & EconomicResource.

**Comment by fosterlynn** [comment]
>In case of passenger transportation and health care, load, unload, accept, improve might actually affect person directly. So the person might have both roles in those situation Agent & EconomicResource.

In those cases, are you OK with the person just being an Agent?  Like a receiver of a service such as transportation or dental work or whatever?

**Comment by elf-pavlik** [comment]
I think as a middle ground case we can take pets, transporting them and health care. If they can appear as a resource and think we can also appear as both resource and agent. We don't define those as disjoint model should have no problem with it.

**Comment by fosterlynn** [comment]
I don't particularly see the pet as a resource either, although I realize there is probably a whole philosophical discussion involved, and people's thoughts will vary.  I think in all the examples we are talking about, there is a service involved which is created by the process.  And maybe a pet that is being transported acquires some resource like a container that has a trackingIdentifier during transport, but it seems like the pet itself doesn't need to be a resource.  If a pet gets some health care, I think that is also a service, probably with the "owner" being the receiver in our world.  If some critters or plants or fungi or whatever in a "wild" ecosystem get some services, it becomes more interesting, but I still don't see them as "resources" in that case.

**Comment by elf-pavlik** [comment]
Let's take some examples where transpiration gets included in schedules of transported resources. Just as planning of use that involves some resource may need to take into account transporting it, planning one's work may need to take into account commute. Possibly the same code can work with calculating equipment schedules and personal schedules. I will make PR with some examples and we probably will get better results working on concrete use cases.

**Comment by fosterlynn** [comment]
>I will make PR with some examples and we probably will get better results working on concrete use cases.

:+1:

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/valueflows/-/issues/443.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
