### ISSUE TITLE
GraphQL schema for documentation/specification

### ISSUE THREAD

**Issue by fosterlynn** [valueflows/valueflows#447]
Copying here from the Welcome channel, from @pospi .

>Hi all, I've been chatting with @fosterlynn during work on https://github.com/holo-rea/holo-rea-proto and am starting to think that converging on a standard GraphQL schema for ValueFlows-based systems would be very worthwhile. @ivanminutillo & Luandro (another VF contributor from SSB-land, unsure of his github username) look to have already started the work with their Scuttlebutt & ActivityPub projects, and having a reference implementation to track would really help to keep all of us aligned.

>I would probably start by taking the NRP implementation and codifying that schema into the GraphQL type language. @fosterlynn tells me a few fields have changed in the interim, but doesn't seem like that many. We can use the work from NRP as a proposal for the relationship names, which are not yet defined in the UML / RDF specs so far as I can tell. It does look like you can take a schema written in this language and load it up for validation, though I'm still trying to figure out how to use one schema to validate another schema (rather than specific query). Anyway, seems a promising start.

Existing issue references: #427 #306

Schema doc: https://graphql.org/learn/schema/

**Comment by elf-pavlik** [comment]
Once you have some preliminary work on it, I will look how it could work with https://comunica.github.io/Article-ISWC2018-Demo-GraphQlLD/

**Comment by elf-pavlik** [comment]
I will deploy soon LDF server to host all examples from VF repo and we will have chance to query it with LDF Client which since few months also supports GraphQL-LD http://query.linkeddatafragments.org

**Comment by pospi** [comment]
That's very cool! It will be interesting to see how the LDF backend presents to the GraphQL engine, and what the availability of different language implementations for executing the queries is.

I have done a little more digging and I found [this utility method](https://github.com/graphql/graphql-js/blob/9e40465/src/utilities/findBreakingChanges.js) in the `graphql-js` codebase that allows comparison of two schemas to determine what the breaking changes are. This could very easily be used in unit tests to validate that any implementation is VF-GraphQL compatible.

It could also be used in combination with [another method](https://github.com/apollographql/graphql-tools/blob/4a33eed5d2bb56f58c240f62b162c2ed48b5e058/docs/source/generate-schema.md) that takes a schema authored in the "GraphQL schema language" plus some resolver callbacks to generate an executable one. This means you could actually create a VF-GraphQL gateway on top of *any* service with minimal scaffolding code- only the resolver callbacks for relationships need to be implemented.

I'm curious if these are well-supported methods, or only present in the JavaScript implementation. Ideally we would be able to do the same things regardless of the implementation language chosen.

**Comment by pospi** [comment]
Did some fiddling today and converted the introspection query from OCP into a GraphQL language definition and then hand-edited out some nonstandard FreedomCoop extensions. Pushed up the results to [a new repo](https://github.com/valueflows/vf-graphql) for now- let me know if the code should be moved and whether we should continue discussing things here or in issues in that repo.

Other than the schema itself, there is an entrypoint that returns a compiled JS version of the schema, a test to validate that it compiles, and an (untested) method to validate another schema using the reference, which will return an array of incompatibilities. The compiled schema is already usable with `makeExecutableSchema` to create real APIs.

I still need to take a pass over it and compare to the most recent VF spec (pointers as to the best place to locate that are appreciated), as well as taking input parameters and converting to nested objects (eg. `resourceImage`, `resourceNote` etc in `createEconomicEvent`). I think it would also be a good idea to consolidate some of the methods that are in there, eg. `resourceClassificationsByProcessCategory`, `resourceClassificationsByAction` etc could all be handled by filter parameters in `allResourceClassifications` (and maybe the `all*` methods could be renamed to `query*` - thoughts?)

Other than that, these are the questions I currently have for you @fosterlynn:

- How do you feel about the way I've split things up into multiple files? Especially WRT `Unit`, `Place` & `QuantityValue` being in "config". Those three don't make much sense regardless of where you put them.
- `OrganizationType` doesn't seem to be linked to anything. Can I get rid of it?
- Everywhere where `action: String` is defined, should it actually be `action: Action`?
- I took out `userIsAuthorizedToCreate`. Seemed like a nonstandard extension.
- I've left `Validation`s in for now. Do we really want to take them out? Having others verify that work has been done is a use-case I have often seen requested. Perhaps we can find a way to have optional extras like this as composable additions to a base schema?

Would also be great to get @ivanminutillo and @luandro across this, as their efforts in SSB & ActivityPub will want to eventually validate against what we're doing here.

**Comment by fosterlynn** [comment]
@pospi great! :heart_eyes: 

>I still need to take a pass over it and compare to the most recent VF spec (pointers as to the best place to locate that are appreciated)

I can take that pass if you like, I already know some things that have changed, am deep into the current state of VF, and know some queries (inverse relationships mostly) that I would like to change the names of.  And I want to just look it over in general anyhow.  But for your reference, this is the system of record if you don't mind a turtle file: https://github.com/valueflows/valueflows/blob/master/release-doc-in-process/all_vf.TTL.  It generates a human-readable spec, visible in the gitbook doc (the website) under Specification.  Might not be working this minute due to transferring the domain.

>    * `OrganizationType` doesn't seem to be linked to anything. Can I get rid of it?

yes

>    * Everywhere where `action: String` is defined, should it actually be `action: Action`?

yes

>    * I took out `userIsAuthorizedToCreate`. Seemed like a nonstandard extension.

yup, goes out

>    * I've left `Validation`s in for now. Do we really want to take them out? Having others verify that work has been done is a use-case I have often seen requested. Perhaps we can find a way to have optional extras like this as composable additions to a base schema?

That validation method is pretty specific, and imo doesn't work well for them anyhow.  I agree it is a general request.  But I don't think it will be in VF any time soon.  But I do like the idea of extensions, and this would be a good one, especially if we can figure out how to generalize it.  Things like value equations would fit into that category too.  Or maybe extensions don't need to be generalized, and there will be multiple versions?  Don't know.

**Comment by fosterlynn** [comment]
>But for your reference, this is the system of record if you don't mind a turtle file: https://github.com/valueflows/valueflows/blob/master/release-doc-in-process/all_vf.TTL.

But note also that it doesn't include everything - basically the classes and properties we are using from other LOD vocabularies aren't there.  But those should be included in the graphql and other non-rdf renderings.

**Comment by fosterlynn** [comment]
>    * How do you feel about the way I've split things up into multiple files? Especially WRT `Unit`, `Place` & `QuantityValue` being in "config". Those three don't make much sense regardless of where you put them.

I think I would combine config and knowledge files (`knowledge` being the better name), or at least put Action into knowledge.  QuantityValue isn't really config or knowledge, just a data structure for quantities.  We'll have something similar for dates/times, probably more complex.  I wonder if these should just get blown out and included wherever they occur, which fortunately is the way graphql will work anyhow.  The types/category enums aren't in VF, although we may want something like them.  They also need some work.

As of now, we don't have Place (Location) any more, just references as properties (currentLocation, primaryLocation).  I think it may remain like that.  Or we could pick a reference vocabulary for Location/Place and just use that in the graphql as recommended vocabulary.

Otherwise, I think the split is fine, although just to note Process and Transfer are applicable to both planning and observation, so not sure what to do there.

And we will want to add Intent (which doesn't exist in NRP/OCP but will be needed very soon in at least one graphql implementation.

**Comment by fosterlynn** [comment]
> But for your reference, this is the system of record if you don't mind a turtle file: https://github.com/valueflows/valueflows/blob/master/release-doc-in-process/all_vf.TTL. It generates a human-readable spec, visible in the gitbook doc (the website) under Specification. Might not be working this minute due to transferring the domain.

@pospi the website / gitbook is working now again.  The generated spec is here: http://www.essepuntato.it/lode/owlapi/https://raw.githubusercontent.com/valueflows/valueflows/master/release-doc-in-process/all_vf.TTL

**Comment by pospi** [comment]
Thanks for the feedback! Took care of some of that stuff. Added some brief docs on how to contribute to the module easily, too.

As we discussed on Mattermost, I can take this repo and import it elsewhere, preserving commit history. Log me an issue for how you want the reorg to go and I will try to find time to take care of it early next week.

The enums are now in `knowledge`, and I renamed `config` to `structs` as it now contains... just those core structures. Sensible?

I don't think we should have anything more complex for DateTimes than ISO8601. It's got timezone info and is easily parseable in any language... what more would we need?

RE the type category enums, I think they are an artifact of OCP and may present a problem. *Unless* the core set is very minimal we will end up with redundant items in many deployments, and *if* the core set is very minimal then every implementation that extends it will not pass validation. Have we ever considered making them first-class citizens of the system, in that they are stored as data rather than code? If that were the case, they'd all be passed as the `ID` type and it would be a non-issue. The other option is that our validation logic could filter out the relevant errors on those fields. So both arrangements are probably doable, I just want to get a sense of where the group is heading.

> As of now, we don't have Place (Location) any more, just references as properties (currentLocation, primaryLocation)

You mean those are string fields now? Agree that there is probably some good reference vocab we can use. I guess the issue with locations is when you want to have "cupboard under the sink" type things as a locations.

> just to note Process and Transfer are applicable to both planning and observation, so not sure what to do there.

Yeah. I just went along with the discussion you and @sqykly had on the topic recently. Related: did `Exchange` change its name to `ExchangeAgreement`?
Random curveball: what about `fulfillment` as the module name for these? One could say that they track the fulfillment of things in the planning layer by activities in the observation layer... they sort of feel like more in-depth forms of `Fulfillment` (which would move into that layer as well, I guess).  `realization` also felt like a nice module name when I pulled out the thesaurus.

Anyway, ready for you to take a pass over now and maybe that's a more effective way forward than me pestering you with questions as I go, heh.

Something I might have a fiddle with today is those turtle grammars. There's a possibility they are close enough to the GraphQL field names that I can validate the GQL spec against the TTL spec, too.

**Comment by fosterlynn** [comment]
>I don't think we should have anything more complex for DateTimes than ISO8601. It's got timezone info and is easily parseable in any language... what more would we need?

Sometimes we may need durations.  Working on some of this now...

>RE the type category enums, I think they are an artifact of OCP and may present a problem.
>Have we ever considered making them first-class citizens of the system, in that they are stored as data rather than code?

I agree, I think they need to be first class citizens.  Yes, an artifact of OCP and also the stage we are at in VF for the knowledge layer, a lot of which awaits further development.  Some of them might be implementation specific too.

>> As of now, we don't have Place (Location) any more, just references as properties (currentLocation, primaryLocation)

>You mean those are string fields now? Agree that there is probably some good reference vocab we can use. I guess the issue with locations is when you want to have "cupboard under the sink" type things as a locations.

Yes, strings that are a url (uri, whatever).  And yes, we will have "cupboard" locations, like in warehouses with aisles, tiers, etc.  Should at some point look for a good location vocab.

>did `Exchange` change its name to `ExchangeAgreement`?

Yes.  Still some disagreement on the definition though too, how we will use it in VF.

>Random curveball: what about `fulfillment` as the module name for these?

We do already have a class named Fulfillment.... so don't know.....

**Comment by fosterlynn** [comment]
@pospi some questions:

1. What is the significance of the '@package'?
2. When I first named a lot of the relationship queries (like agentProcesses, or agentPlans), I prefaced with the 'starting point', like in this case agent.  After working with it, I don't like that, it always appears in the right place in the graph so shouldn't need that qualification.  I'd like to get rid of all those - but is there a reason that I shouldn't from your experience?
3. In rdf, there is a standard that "contains" type relationships, where more than one item is expected, still are stated as singular.  Is there anything like that in graphql or json or elsewhere in your experience?  (In rdf, the model tends to be looser anyhow, and data returned perhaps more unexpected, I think that is part of it, although @elf-pavlik could explain better than I can.)

Probably more to come....

**Comment by fosterlynn** [comment]
More questions:

1. What should the id's be?  I see String, and ID!
2. Also related to id's, MoodleNet does an interesting thing - they have a string `id` which is a url to the served linked open data (and I understand holochain also uses a string, in their case for the hash).  And MoodleNet also has a `localId`, which for them is the database id.  For the OCP api, the id is now an int and is the database id.  I like the localId idea.  Thoughts?

Probably still more to come....

**Comment by fosterlynn** [comment]
I have done a bunch of cleanup on this here https://github.com/valueflows/vf-graphql/tree/master/schemas.  Plenty of TODO's left though.

**Comment by fosterlynn** [comment]
More cleanup done, added stuff not yet in OCP api, like recipes, satisfaction, fulfillment.  I think it is at a point where it is reasonably up to date with VF definitions.  Still lots of vocabulary questions and a few technical questions, plus I'm sure there are just bugs.  But it is at a point that it can be at least viewed and be open for questions and comments.

**Comment by pospi** [comment]
Amazing! Moved this discussion into the GraphQL repo here: https://github.com/valueflows/vf-graphql/issues/5
