### ISSUE TITLE
Created time?

### ISSUE THREAD

**Issue by fosterlynn** [valueflows/valueflows#448]
It is useful to know when an agent committed to something, etc.  This may be the same as the standard "created time" kind of thing, meaning that is when the record got saved in a computer system.  Or may have a bit more actual functional meaning.

Do we need a createdTime on everything (or many things) in the vocabulary?

**Comment by elf-pavlik** [comment]
http://dublincore.org/documents/dcmi-terms/#terms-created

**Comment by fosterlynn** [comment]
>http://dublincore.org/documents/dcmi-terms/#terms-created

Has Range: | http://www.w3.org/2000/01/rdf-schema#Literal

Do you think its preferable to use this instead of tapping into the owl time ontology in some way?  I'm fine with whatever works best in rdf-land.

**Comment by elf-pavlik** [comment]
`xsd:dateTimeStamp` belongs to literals, we should just add `dcterms:created` to https://valueflo.ws/specification/external-terms.html

**Comment by fosterlynn** [comment]
Small thing - but I'm curious if dcterms:created is about when the record was stored (which I would guess, but its hard to tell from the definition) or when the Commitment (in this case) was committed to in the real world?

**Comment by elf-pavlik** [comment]
I would see it more as when the record gets created, do we really need both? In what situation adding information that maybe some verbal commitment was made before creating record of it comes useful? I think we may first consider how mutual commitment gets created, do both agents sign it etc.

We discussed that usually agent who *provides* creates the commitment, I think in most cases the date it gets recorded really matters.

**Comment by fosterlynn** [comment]
>In what situation adding information that maybe some verbal commitment was made before creating record of it comes useful?

Yes.  Don't need both, and yes they will be mostly the same, but I think the date actually committed is the one we would care about.  But we can let it sit, not super important.

**Comment by fosterlynn** [comment]
Closing, if we decide we really don't like dcterms:created, we can re-open.
