### ISSUE TITLE
Citations - how to record quantity?

### ISSUE THREAD

**Issue by fosterlynn** [valueflows/valueflows#449]
Ref. #443 

>>>Interestingly, `cite` has a similar aspect to `use` and `work` where the quantity that matters is not the same as the quantity of the cited resource (document, design, etc.). And I can't think of a situation where a citation could be made for more than one of a "stock" resource. The quantity that matters still could be '1' in that citations (the events) are counted that way. For Sensorica's distribution logic, they wanted to have the person doing the citing record a percentage of the process/output that they felt the cited resource contributed to that process, then the contributor(s) to the cited resource would get that percentage of income assigned to that process . It is different in that citations don't affect availability. But we could consider `cite` in terms of figuring out what quantity properties are used for what.

>> For Sensorica's distribution logic, they wanted to have the person doing the citing record a percentage of the process/output that they felt the cited resource contributed to that process, then the contributor(s) to the cited resource would get that percentage of income assigned to that process .

>I think we should deal with this use case as part of _agreements_ milestone. It sounds to me like something related to _Reciprocity_ removed in #430 I hope we can agree that we should not put any reciprocity related responsibility directly on flows and that Sensorica experiment of using quantity in _cite_ event for that reason will have different way to model it in VF.

It is no more related to the removed vf:Reciprocity than recording work or usage.

I agree with you that we should not be recording agreements in events.  But somewhere you need to record what the receiver thinks the use value was of the cited resource for their process (if you are Sensorica), since it is specific to that citation, not an agreement or general rule.  What that means in terms of reciprocity is recorded in the agreement, agree.  There are probably other creative ways to record citations' use value too, but this was the best they and we came up with.

**Comment by elf-pavlik** [comment]
Could you document here that Sensorica use case in detail and how NRP handles it?

**Comment by fosterlynn** [comment]
Could you document here that Sensorica use case in detail and how NRP handles it?

https://github.com/valueflows/valueflows/wiki/Use-Cases-and-Requirements#citations-and-value-flows

Sensorica records the percentage number in the numeric value field, and the unit as Percent.  When the trace of the value flow happens during calculation of distributions of income, if NRP encounters a citation event with a Percent unit, it allocates to the citation that percent of the amount that the process has been allocated.

**Comment by fosterlynn** [comment]
Yaml example to clarify.  Not making a PR, wanting to keep the discussion all here until we come to some understanding.

```
# Example: Citation

'@context':
  - https://git.io/vf-examples-jsonld-context
  - bob: https://bob.example/
    alice: https://alice.example/

'@id': rgh:valueflows/valueflows/master/examples/cite.yaml
'@graph':

  # a design resource

  - '@id': bob:68cabaf3-deb8-4bd5-a439-798263abe35d
    '@type': EconomicResource
    classifiedAs: https://www.wikidata.org/wiki/Q82604 # a design
    name: Piezo design
    currentQuantity:
      qudt:unit: unit:Number
      qudt:numericValue: 1

  # alice plans to make use of the piezo design to produce the piezo

  - '@id': alice:8baa8ff7-9c1e-4586-ae7b-79d620a3cac7
    '@type': Commitment
    action: cite
    provider: https://bob.example/
    receiver: https://alice.example/
    involves: bob:68cabaf3-deb8-4bd5-a439-798263abe35d # the piezo design
    committedTime:
      '@type': time:Instant
      time:inXSDDateTimeStamp: 2018-12-01T9:00:00-5:00

  # alice makes the piezo according to the design

  - '@id': alice:f0b8bfb1-ed29-4ab0-aabd-f5e2a3515625
    '@type': EconomicEvent
    action: cite
    provider: https://bob.example/
    receiver: https://alice.example/
    involves: bob:68cabaf3-deb8-4bd5-a439-798263abe35d # the piezo design
    observedQuantity:
      qudt:unit: unit:Percent
      qudt:numericValue: 20
    observedTime:
      '@type': time:Instant
      time:inXSDDateTimeStamp: 2018-12-07T9:00:00-5:00

  - '@id': fablab:daa2ec3b-2c1a-4eb1-839f-8dcec1a1f93d
    '@type': Fulfillment
    fulfills: alice:8baa8ff7-9c1e-4586-ae7b-79d620a3cac7 # the commitment
    fulfilledBy: alice:f0b8bfb1-ed29-4ab0-aabd-f5e2a3515625 # the economic event
```

**Comment by elf-pavlik** [comment]
> Percent unit, it allocates to the citation that percent of the amount that the process has been allocated.

I guess you could represent that expected amount as instance of `vf:EconomicResource`. Then under that agreement one would record the *cite* (both commitment and event) and the commitment to *issue/give* 5% involving that resource representing what will get allocated to that process.

I propose assigning this issue *agreement* milestone and take it as one of use cases for it.

**Comment by fosterlynn** [comment]
>I propose assigning this issue _agreement_ milestone and take it as one of use cases for it.

Done.

**Comment by fosterlynn** [comment]
Reviewing this.  I don't think this has anything to do with agreements actually.  Citations are sort of like "gifts" in the Sensorica use case, the quantity decided by the citer - and they document the value flow.  In academia or science, there are clear standards for citing others' work that contributed to your work, but it isn't really about an agreement.

I see the issue more related to getting the quantity field(s) nailed down.  Moving to "scheduling", where we are trying to finish the "cleanup" in terms of getting core attributes more stable.  So we don't forget it in that cleanup.

**Comment by elf-pavlik** [comment]
If we talk about reciprocity, single flow doesn't have any notion of reciprocity, it requires agreement to start grouping mutually reciprocal flows.

If we talk about something else, for example *perceived related value fraction of the process outputs*, on might want to use such markers on any input flow, and possibly any output flow to capture *perceived relative valuing for the process*. Given that, I don't think one can use any of the quantitative values we discussed so far and it looks to me that we talk about yet another quantitative value. This one seems reasonably clear to define so we only would need to see if we want to dedicate efforts now to defining it. It might also get affected by *composition* milestone where single flow gets listed as input or output of more than one process. In that case we can't tell to which process that *perceived related value fraction* would apply. It almost looks like in that case we would need a qualified version of *inputOf* and *outputOf* relationships, which would reference flow, process and qualify it with that *perceived related value*. 

I would find it enough at this stage if we could agree that one should not use any of previously discussed properties for that and we can consider it as additional feature which we would need to work on and define new constructs for it.

**Comment by fosterlynn** [comment]
>If we talk about reciprocity, single flow doesn't have any notion of reciprocity, it requires agreement to start grouping mutually reciprocal flows.

>If we talk about something else, for example perceived relative added value fraction of the process outputs, one might want to use such markers on any input flow,

I'm not talking about reciprocity, I'm talking about recording an event as in your second statement.  We haven't seen any need on other flows, but citations do not lend themselves to just counting something up.  The percentage is what Sensorica came up with, and we couldn't think of anything better.

>This one seems reasonably clear to define so we only would need to see if we want to dedicate efforts now to defining it.

I would like to talk about it in relation to discussion of core quantity field(s), so we can get that as stable as possible, without running into something that disrupts it later.

>It might also get affected by composition milestone where single flow gets listed as input or output of more than one process. In that case we can't tell to which process that perceived relative added value fraction would apply.

I don't see composition working this way, nor any need to "complexify" the horizontal value flow pattern on the operational level, at this stage, after working it around in a circle over the last months myself.  I'm happy to wait on that and see if composition affects anything - but prefer to get citations worked into the "simple" version of value flows.

>I would find it enough at this stage if we could agree that one should not use any of previously discussed properties for that and we can consider it as additional feature which we would need to work on and define new constructs for it.

:-1: If we can fit into an existing property, that would be best imo.

**Comment by elf-pavlik** [comment]
> :-1: If we can fit into an existing property, that would be best imo.

I don't think we can since again, one may want to assign such *perceived relative added value fractions* to all flows related to process and while citations doesn't seem to need other quantitative values other actions do.

Also this value seems to have very specific meaning other than all the other meanings of various quantitative values related to flows we discussed in more depth.

**Comment by elf-pavlik** [comment]
https://github.com/valueflows/valueflows/pull/471#discussion_r268873079

> To clarify that specific use case, do they count words from the original document or words in the translated document?

I think *cite* related use cases needs much more clarification, for example recording partial translation - someone translates a book and in certain cycle produduced 10% of translated version. The *cite* flows might have a *word count* as well as the *produce* flow on the translated version might have word count as well.

**Comment by fosterlynn** [comment]
>for example recording partial translation - someone translates a book and in certain cycle produduced 10% of translated version

>The cite flows might have a word count as well as the produce flow on the translated version might have word count as well.

Yes, that is one reason to have it on the flow, in this case `work`.

**Comment by elf-pavlik** [comment]
Yes it mixing a bit of other issue related to *cite* but it also shows that one may want to have 'word count' quantity on *cite* flow.

**Comment by fosterlynn** [comment]
Got it.  Seems like we need to let people define what unit they want to use for citing.  Some people will probably just cite 1 specific document too, standard academia method.  

Might have a page number, might have a standard formatted citation.  Don't know if that matters for VF.

**Comment by elf-pavlik** [comment]
> Seems like we need to let people define what unit they want to use for citing.

I don't see it a matter of 'what unit' but what does that quantitative value mean - how does it relate to that flow, for different meanings we should provide different properties. In some cases people will use additional properties from whatever vocabs they need to add more specific quantitative values.

**Comment by fosterlynn** [comment]
Resolved for v.3, please re-open if needed.
