### ISSUE TITLE
Flow time variations

### ISSUE THREAD

**Issue by fosterlynn** [valueflows/valueflows#455]
This is to specifically look at how we think about the time properties on Intent, Commitment, EconomicEvent.  This is to try to sort out the discussions on using the time properties for quantities on schedule-based flows, or for deriving quantities in these situations.

i was thinking about a use case I have experience with, which I documented here https://github.com/valueflows/valueflows/blob/master/use-cases/buying-club.md.

Some possible implications for how we think about time on intents, commitments, events.
* There is something like an accounting period (an order cycle), which in many other cases is financial calendar based, but here based on the actual operational cycles (which are calendar based but not the usual).  We have need for accounting period in the [budgeting use case](https://github.com/valueflows/valueflows/issues/284) too, and I think should consider adding something like this. It might take the place of logging a whole month in the time property for 20 hours of work, in the facilitation example, which is also a real example.
* For the scheduled work, there are the equivalent of intents, commitments, and events.  The number of hours could be derived from the calendar time worked, but I think it is just recorded as number of hours, where the commitment and intent schedules are carefully based on calendar times and are what is important for coordination.  The quantity of hours isn't that important on the intents and commitments, although it probably helps people understand they are signing up for enough hours.
* For work at home, there aren't formal intents or commitments, people manage that themselves, and generally have the same role for a long time.  A finish date is recorded for coordination.  The time is recorded for accounting.  But of course those could and would be combined in VF.  So it would be quantity of hours worked, and finish date.

Generally, I think this and other use cases bear out that we want to keep time for scheduling/availability and coordination.  Quantities would be used for accounting and exchange, also analysis.  (If some agent wants to derive quantities from times internally, that of course is their choice, but the vocabulary would reflect that derived quantity just like any other quantity.)

And also that we need to be flexible on how people think of the times in flows, as there are a variety of needs.  Especially for unscheduled activities or wherever close coordination is not required, often just a date is plenty, and sometimes that is just the finish date.  In these cases, the time is for reference and can be loose.  Where for close coordination, often an accurate duration is needed (at least for usage and work).

**Comment by elf-pavlik** [comment]
> Where for close coordination, often an accurate duration is needed (at least for usage and work).

I would see those use cases as primary for *scheduling* milestone. When we deal with resources (goods, products), we have convenience of 'buffering' them in stock. On the other hand, *service*, *work*, *use* needs to happen synchronized. Even for resources which one can 'buffer' in stock, some events will require synchronization between agents (*load* & *unload* / *accept* & *issue*).

> The quantity of hours isn't that important on the intents and commitments, although it probably helps people understand they are signing up for enough hours.

When one creates plan from recipe, in general one can only create intents, sometimes right away make self-commitments which immediately satisfy those initial intents. I don't understand in what cases you wouldn't consider a time duration of planned *work* and *use* not important for your plan?

> For work at home, there aren't formal intents or commitments, people manage that themselves, and generally have the same role for a long time.

I would stay careful with trying to generalize it this way. Even in remote cooperation, people will to different extend synchronize their work. Starting from a montly/weekly/daily conference call, all the way to remote pairing.

> And also that we need to be flexible on how people think of the times in flows, as there are a variety of needs.

Application needs to take responsibility for translating human inputs into VF data which later needs to get interpreted in consistent way no matter which application generated it.

**Comment by fosterlynn** [comment]
>> The quantity of hours isn't that important on the intents and commitments, although it probably helps people understand they are signing up for enough hours.

>When one creates plan from recipe, in general one can only create intents, sometimes right away make self-commitments which immediately satisfy those initial intents. I don't understand in what cases you wouldn't consider a time duration of planned _work_ and _use_ not important for your plan?

@elf-pavlik that is exactly what I *was* saying.  The quantity is not as important as the time or duration when planning. 

Really they are both important for planning and observation, just for different reasons, imo.  And depending on type of event and type of resource.  So my statement applies really more to work or use.

**Comment by fosterlynn** [comment]
>> For work at home, there aren't formal intents or commitments, people manage that themselves, and generally have the same role for a long time.

>I would stay careful with trying to generalize it this way.

I wasn't trying to generalize, I was just describing this use case.

**Comment by fosterlynn** [comment]
>Application needs to take responsibility for translating human inputs into VF data which later needs to get interpreted in consistent way no matter which application generated it.

What should we do about applications that don't assume the complexity and nuance of the time ontology inside the application?  Maybe because they don't need to for their users, maybe because they didn't think about it?  Take NRP, which basically has event_date.  (It doesn't have a calendar scheduling feature.) For some NRP users, that is actually too simplistic, and it would have been better to give the date/time information more capabilities.  But hindsight is always nice, that's the way it is, and NRP can only report back a date, even in a VF api.

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/valueflows/-/issues/455.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
