### ISSUE TITLE
validate YAML and JSON-LD parsing on CI

### ISSUE THREAD

**Issue by elf-pavlik** [valueflows/valueflows#457]
* [x] validate YAML syntax using https://github.com/nodeca/js-yaml/#safeloadall-string--iterator--options-
* [ ] validate all dates with [`Data.parse()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/parse)

**Comment by fosterlynn** [comment]
I ran the examples from .3 through the validator, using js-yaml filename.  Caught and fixed a few things.  Let me know if I should have used safeloadall or one of the other options.

**Comment by fosterlynn** [comment]
Added to README for examples folder so we can find it more easily, so closing this.
