### ISSUE TITLE
What needs to be resolved for scheduling milestone

### ISSUE THREAD

**Issue by fosterlynn** [valueflows/valueflows#460]
I'm gathering items that we want to resolve for this milestone, so things are not so scattered.  I understood the scheduling milestone existed so we can make sure that what we have or want to represent quantities and times for intents, commitments, and events will work for calendars and schedules, as well as all other non-calendared situations we have defined to date.  This includes all actions and kinds of resources, time-based with calendar/schedule and non-time-based, and also time-based but not coordinated through a calendar.

These are the use cases and ideas we have most recently tossed around (and there are others tagged with this milestone).
* booking rooms (with identifying numbers)
* ouikits (no identifying numbers)
* electricity flows, with different rates day and night
* work that has a strict schedule
* work that is like FairCoop facilitation where people don't keep track of every minute, but record the approximate amount worked per month, or treat it like a fixed number of hours (unless it gets too off)
* equipment usage
* transportation scheduling
* accept and improve scheduling

These are what I see as still open (a lot of these overlap):
* point in time transfers of possession/rights (like checkin and checkout) vs. events with a time interval
* having access to a resource and rights to use it vs actually using it in a process
* process-related flows that have an instant for time vs flows that need some kind of interval
* can quantities be asserted separately from scheduled or observed durations (what is the definition and usefulness of quantities vs times, how do they work for different actions and situations but keep the simple underlying model)
* do we need more than one quantity in flows and if so, what are they? (and what do we call them?)
* flow unit of measure matching the resource (or resource classification/specification) unit of measure: handle by underlying resource vs handle by defining different units for different actions for one resource (unit of use, unit of citation, etc.)
* proposed new action: reserve
* different proposals for how to actually represent an interval or instant on flows, what vocabulary and data structure to use

Might be more, please feel free to add!

**Comment by elf-pavlik** [comment]
> process-related flows that have an instant for time vs flows that need some kind of interval

not sure what exactly you see needed clarifying here

>  point in time transfers of possession/rights (like checkin and checkout) vs. events with a time interval

i think we may have an option that combines both, flow could start and end with flows, this way transfer of rights could happen both at the beginning and at the end of flow representing an interval. as for transfers of rights, i think we only need instants to represent them, i can't imagine where we would have need to represent transfer as interval.

**Comment by fosterlynn** [comment]
>> process-related flows that have an instant for time vs flows that need some kind of interval

>not sure what exactly you see needed clarifying here

I guess mostly how to represent those somewhat different vocabulary elements (assuming we agree that both are valid).

>> point in time transfers of possession/rights (like checkin and checkout) vs. events with a time interval

>i think we may have an option that combines both, flow could start and end with flows, this way transfer of rights could happen both at the beginning and at the end of flow representing an interval. as for transfers of rights, i think we only need instants to represent them, i can't imagine where we would have need to represent transfer as interval.

Yes, agree with transfers being instants only.  That is what I was trying to say, when is it best to use transfers, when is it best to try to represent something where there is possession or rights held for a time period (sort of like `reserve` concept - or maybe `service` in some cases)

**Comment by fosterlynn** [comment]
> >> process-related flows that have an instant for time vs flows that need some kind of interval

>> not sure what exactly you see needed clarifying here

>I guess mostly how to represent those somewhat different vocabulary elements (assuming we agree that both are valid).

So is it a correct understanding (aside from the question of commitment or event being an interval) that it could be valid to express:
```
    committedTime:
      hasBeginning: 2019-03-07T00:00:00-5:00
      hasEnd: 2019-03-10T00:00:00-5:00
```
or
```
    committedTime:
      hasBeginning: 2019-03-07T00:00:00-5:00
```
or
```
    committedTime:
      hasEnd: 2019-03-10T00:00:00-5:00
```
and same for events?

**Comment by fosterlynn** [comment]
>as for transfers of rights, i think we only need instants to represent them, i can't imagine where we would have need to represent transfer as interval.

Had a thought: What about transfers that have an implied interval using the interval to express the potential time the rights are transferred for.  So like a library book gets transferred as of a datetime, but also expresses an end time 3 weeks later.  The actual event of returning the book would be another event with just the point in time.  Or bnb possession or rights to use for 5 days could have a transfer at the beginning but also give the end 5 days later as part of the interval.  The transfer happened at the hasBeginning time.

Is this related to what you were trying to suggest with this?
>i think we may have an option that combines both, flow could start and end with flows, this way transfer of rights could happen both at the beginning and at the end of flow representing an interval

**Comment by elf-pavlik** [comment]
> So is it a correct understanding (aside from the question of commitment or event being an interval) that it could be valid to express

Actually to handle nicely both and Interval and Instant we might want to just use OWL-Time directly and leave that `time:inXSDDateTimeStamp`.

Interval:

```yaml
'@type': Commitment
time:hasBeginning:
  time:inXSDDateTimeStamp: 2019-03-07T00:00:00-5:00
time:hasEnd:
  time:inXSDDateTimeStamp: 2019-03-10T00:00:00-5:00
```
Instant:

```yaml
'@type': Commitment
time:inXSDDateTimeStamp: 2019-03-07T00:00:00-5:00
```

If someone just provides `time:hasBeginning` or `time:hasEnd` and omits the other one, we still have Interval just with undefined duration due to unknown other extreme. 

Treating flows as `time:TemporalEntity` #453 provides some interesting composition possibilities:

```yaml
'@type': Commitment
action: reserve
time:hasBeginning:
  '@type': EconomicEvent
  action: transfer
  time:inXSDDateTimeStamp: 2019-03-07T00:00:00-5:00
time:hasEnd:
  '@type': EconomicEvent
  action: transfer
  time:inXSDDateTimeStamp: 2019-03-10T00:00:00-5:00
```

and with intervals

```yaml
'@type': Commitment
action: service
skos:note: transporting something
'@reverse`:
  time:intervalStarts:
    '@type': Commitment
    action: load
    # ...
  time:intervalFinishes:
    '@type': Commitment
    action: unload
    # ...
```

I'll add YAML snippet taking advantage of interval relations from OWL-Time to https://github.com/valueflows/valueflows/pull/446#issuecomment-464391081

**Comment by elf-pavlik** [comment]
also
```yaml
'@type': Commitment
action: service
skos:note: repairing something
'@reverse':
  time:intervalStarts:
    '@type': Commitment
    action: accept
    # ...
  time:intervalFinishes:
    '@type': Commitment
    action: improve
    # ...
```

**Comment by fosterlynn** [comment]
:-1:  to events within events or commitments within commitments.  Repairing something is a process.

**Comment by elf-pavlik** [comment]
Since we have underlying graph model and not tree model nothing stops all those commitments to reference a process as well:

```yaml
'@type': Commitment
action: service
skos:note: repairing something
outputOf: foo:p1
'@reverse':
  time:intervalStarts:
    '@type': Commitment
    action: accept
    inputOf: foo:p1
    # ...
  time:intervalFinishes:
    '@type': Commitment
    action: improve
    outputOf: foo:p1
    # ...
```
We can draw as many edges between nodes as we need to capture all relevant relations between them.

I just notice that sometimes we may need to express relation between various intervals and instants. As we realized with check-in & check-out experiments, having single flow to represent interval has some advantages over having two flows representing instants that should define bounds of implicit interval. As we continue our experiments we have above available as one of the options to express relations between temporal entities.

**Comment by fosterlynn** [comment]
>These are what I see as still open (a lot of these overlap):
    * point in time transfers of possession/rights (like checkin and checkout) vs. events with a time interval
    * having access to a resource and rights to use it vs actually using it in a process
    * process-related flows that have an instant for time vs flows that need some kind of interval
    * can quantities be asserted separately from scheduled or observed durations (what is the definition and usefulness of quantities vs times, how do they work for different actions and situations but keep the simple underlying model)
    * do we need more than one quantity in flows and if so, what are they? (and what do we call them?)
    * flow unit of measure matching the resource (or resource classification/specification) unit of measure: handle by underlying resource vs handle by defining different units for different actions for one resource (unit of use, unit of citation, etc.)
    * proposed new action: reserve
    * different proposals for how to actually represent an interval or instant on flows, what vocabulary and data structure to use

Taking out the ones related to transfers and leaving out anything related to composition, and doing some combining and re-ordering and maybe adding, I get these:
    * do we have what we need for scheduling and calendars for time-based flows? and will that still work for non-time-based flows?
    * how to represent an instant for time vs flows that need some kind of interval?
    * do all intervals that are part of the flow represent a duration with no breaks? 
    * can time-based quantities be asserted separately from scheduled or observed durations (what is the definition and usefulness of quantities vs times, how do they work for different actions and situations but keep the simple underlying model)?
    * do we need more than one quantity in flows and if so, what are they? (and what do we call them?); and if so, how do we handle the fact that different kinds of quantities are primary for different actions?  (given the requirement for one quantity field to handle the primary quantity for the event; and the requirements for time-based flows and also other actions that use a quantity other than the inventoried quantity)
    * how do we handle different units for different actions (and possibly different quantities, depending on the above) upon the same original resource (like consuming vs using) - what is the vocabulary to define those units and where does it live?

**Comment by fosterlynn** [comment]
>do we have what we need for scheduling and calendars for time-based flows? and will that still work for non-time-based flows?

and specifically, how to reserve a period of time based on two separate flows? without getting into transfers, this applies to accept-improve, load-unload.  (transfers later may follow the same pattern)

**Comment by fosterlynn** [comment]
>how to reserve a period of time based on two separate flows?

logic:
```
get all commitments in calendar period, order by time or beginning of the duration
for each commitment:
    if use or work:
        block off the duration of the commitment
    if load:
        get the unload
        block off the duration from the load time to the unload time
    if accept:
        get the improve
        block off the duration from the accept time to the improve time
end for
```

**Comment by fosterlynn** [comment]
Here is your example:

>Interval:

```yaml
'@type': Commitment
time:hasBeginning:
  time:inXSDDateTimeStamp: 2019-03-07T00:00:00-5:00
time:hasEnd:
  time:inXSDDateTimeStamp: 2019-03-10T00:00:00-5:00
```

>Instant:

```yaml
'@type': Commitment
time:inXSDDateTimeStamp: 2019-03-07T00:00:00-5:00
```

Checking my understanding, if Commitment does not inherit from TemporalEntity or Instant, is the following the correct way to represent your example?

```yaml
'@type': Commitment
committedTime:
    '@type': TemporalEntity
    time:hasBeginning:
      time:inXSDDateTimeStamp: 2019-03-07T00:00:00-5:00
    time:hasEnd:
      time:inXSDDateTimeStamp: 2019-03-10T00:00:00-5:00
```

>Instant:

```yaml
'@type': Commitment
committedTime:
    '@type': Instant
    time:inXSDDateTimeStamp: 2019-03-07T00:00:00-5:00
```

**Comment by elf-pavlik** [comment]
Yes, this also looks like a valid option. Just as a reminder, until this recent PR, which originally tried to address something different, we did consider both Flow and Process as temporal entities and it simply had start timestamp (similar to has beginning) and duration (similar to has duration). https://github.com/valueflows/valueflows/pull/291/files#diff-a5832671e1376b69e3b7f7fb50526009

**Comment by elf-pavlik** [comment]
> logic (simplified - and edited)

This looks useful to track `currentQuantity` of a resource, it would also need to keep track on *issue* and *receive*. Actually more specific `availableQuantity` since use *use*, *accept*, *improve* doesn't decrement `currentQuantity` while *load*, *unload* do +/- https://valueflo.ws/introduction/flows.html#actions (we already considered that *accept* and *improve* might need to +/-)

To track availability of specific quantities of specific resource over a timeline it doesn't seam enough. If we assume 24/7/265 availability than just tracking `currentQuantity` of a resource looks enough. On the other hand, when agent wants to to define some specific availability schedule, we could use intents with some action (like *reserve*) to represent providing and receiving availability.

I see no problem with putting *scheduling* milestone 'on hold' and jumping into *transfers* milestone continuing with the same use cases we already have in PRs.

**Comment by fosterlynn** [comment]
>Just as a reminder, until this recent PR, which originally tried to address something different, we did consider both Flow and Process as temporal entities and it simply had start timestamp (similar to has beginning) and duration (similar to has duration).

I never understood it that way.  We never defined flow or process as *being* a temporal entity - they both *had* a temporal entity as part of their information, a property about them just like action or quantity.  But no inheritance was ever in the ttl or any diagrams or text, afaik.

**Comment by fosterlynn** [comment]
>This looks useful to track `currentQuantity` of a resource

It was meant only to be able to show calendar availability in the future, only about scheduling.  Perhaps intents (offers anyway) could also come in useful in some cases.  Let's look at that when we dig into intents more.

>I see no problem with putting _scheduling_ milestone 'on hold' and jumping into _transfers_ milestone continuing with the same use cases we already have in PRs.

I would like to get the core property names that are up in the air nailed down enough to give them to a few projects with more confidence.  I can do a limited PR for those and then we can jump to transfers if you prefer.

**Comment by elf-pavlik** [comment]
> I never understood it that way. We never defined flow or process as _being_ a temporal entity - they both _had_ temporal entity attributes [edit] as part of their information, a property about them just like action or quantity.

https://www.w3.org/TR/rdf-schema/#ch_domain
> rdfs:domain is an instance of rdf:Property that is used to state that any resource that has a given property is an instance of one or more classes.

`rdfs:domain` causes reasoner to infer some of the classes that resource using that properties can get assigned to. We don't talk about OOP classes and inheritance here.
Any implementation can use whatever paradigm it wants and follow idiomatic way of using particular programming language. People can write OO implementations, functional implementations, procedural implementations, aspect oriented implementations what have you.

Whatever Flow or Process used `vf:duration` before mentioned PR, one has no reason not to consider it as an Interval. At the same time one can consider it 1000 other things as well, sometimes based on other properties used to describe that resource, but what matters that if we describe it with `duration` we have not reason not to consider it an interval.

**Comment by fosterlynn** [comment]
>Whatever Flow or Process used `vf:duration` before mentioned PR, one has no reason not to consider it as an Interval. At the same time one can consider it 1000 other things as well, sometimes based on other properties used to describe that resource, but what matters that if we describe it with `duration` we have not reason not to consider it an interval.

Ah the intricacies of rdf... :sweat_smile:  As long as we are not defining it that way ourselves conceptually, then cool.

**Comment by fosterlynn** [comment]
@elf-pavlik given that we are moving into a stage of supporting several projects in starting to use VF, I'd like to figure out how to close our current discussions on something that we can use for this round.  Starting with some VF training I'm going to start offering, first with our existing handful of devs actively working, and then opening it up (have been getting requests).  I actually can't delay much more in preparing for this.  I want to use the doc to drive it so we can figure out where the doc needs improvements.  But also we need a temporarily stable vocabulary, at least in the core that everyone will use.

Also given this new stage, I'm becoming more aware that we will need to be more careful and disciplined about releases.  I'm pretty sure VF will keep changing for several rounds of practical implementations, and I'd like to personally figure out how to draw a line now without seeking perfection.  I think both of us have the perfectionist tendency, honestly. 

I consider what we are doing now still to be basically cleanup.  Define and name a few core properties that everyone needs, cut the .2 release for real.  I'd like to do it within a day.

From discussion with @bhaugen: The next stage could be making changes for the active user groups only, and only where needed because of newly understood requirements. We can work on in the background on future things, but the vocab would be basically frozen at .2 with the exception of these new requirements.  Sort of like emergency bugs.  Until we can cut a next release with some set of new features.

Since it looks like we aren't going to agree on our current round of discussions, where should we cut it for .2 and this next round of user groups and dev groups?  I'd like to rename the flow quantities we have now, hopefully with one name, but if not, rename the event quantity.  Take our best guess.  I'd like to finish the time PR.  Beyond that, I don't see what we can actually do, we haven't gotten really much closer, just little bits here and there.  Although having a base way to do transfers would be really really nice, I can't think of any user group who won't be doing "pure" transfers as some part of their apps.  Otherwise, we'll need to go with what we've got for this round.  It's not what either of us prefer, but it isn't terrible.

Comments?

**Comment by elf-pavlik** [comment]
I think we should do our best to narrowing scope of the features where we see more than one path to go and honestly explain it in documentation. At the same time inviting use cases relevant for that TBD feature and feedback based on implementation experience.

**Comment by fosterlynn** [comment]
>I think we should do our best to narrowing scope of the features where we see more than one path to go and honestly explain it in documentation

That can be an option.  If there's any way we can come up with some naming that will work for both paths, that would be really helpful.

**Comment by fosterlynn** [comment]
>EDIT: if in some cases we keep two or three alternative approaches, we should document both (or all three) and invite people to try them out and give feedback.

I think that will be good once people (users/devs) come up to speed enough to even think about it.

**Comment by elf-pavlik** [comment]
I don't see issue in naming, applications should work even if we use Wikidata approach with opaque names: `wdo:P432`. The meaning of those relationships represented by those properties matter and what assumptions applications can make what use of those properties and quantitative values they reference implies. It comes again to solving #471

**Comment by fosterlynn** [comment]
>I don't see issue in naming, applications should work even if we use Wikidata approach with opaque names

I think naming will be important in helping people understand VF, including devs.  And once they start working with the core names, it will be disruptive to change them.  It will already be a little disruptive to the couple people who have been using the .1 version for some months - but they understood that from early on.

And there will start to be videos out there and it will start to be more and more important to stabilize for some time period.

**Comment by fosterlynn** [comment]
Closing after v.3, please re-open if we re-look at this topic.
