### ISSUE TITLE
refining plans (including allocation step)

### ISSUE THREAD

**Issue by elf-pavlik** [valueflows/valueflows#464]
I don't think we have looked into refining plans. Both independent plans which might only include Intents as well as shared plans which require Commitments. I think common example might come from having a specific allocation step.

For example agent can make commitment to provide usage of 3 cargo bikes and make commitment based on
```yaml
'@type': Commitment
resourceClassifiedAs: wd:Q573863 # cargo bike
involvesQuantity:
  qudt:unit: unit:Number
  qudt:numericValue: 3
```

Later agent might want to schedule specific bikes, and supersede the previous commitment with 3 new ones:

```yaml
'@type': Commitment
involves: ex:96af8b82-cde2-4148-bd63-18419921a00f # specific cargo bike
involvesQuantity:
  qudt:unit: unit:Number
  qudt:numericValue: 1

'@type': Commitment
involves: ex:83b2d80e-9a66-4d31-b05a-36bfb0775922 # specific cargo bike
involvesQuantity:
  qudt:unit: unit:Number
  qudt:numericValue: 1

'@type': Commitment
involves: ex:b4ab48b7-fe1f-4c9e-b67d-048315bc35fc # specific cargo bike
involvesQuantity:
  qudt:unit: unit:Number
  qudt:numericValue: 1
```

Similar someone may want to commit to work 20 hours in specific month, later refining planning and creating more specific commitments to work at specific times.

I think composition and *includedIn* could address that, where more specific (refined) commitments stay *includedIn* the less specific ones.

**Comment by fosterlynn** [comment]
Can we do this by changing the commitments?  I think we need to move towards sort of functional style, some kind of "activity" creating, updating, deleting the VF entities, event flows.  So then that kind of history is kept, but there is only one current plan.

In our ActivityPub experiments, we think we can just use existing types of Activity, and reference the VF entities using as:object in the activity. Warning: Not implemented yet!

Maybe in VF doc, we can just recommend people use AS vocabulary for this.... but maybe this is OT, don't know....

**Comment by elf-pavlik** [comment]
I see it more like having events fulfilling commitments or commitments fulfilling intents. We don't have situation when we just update single Commitment but as in example above based on one less specific Commitment (eg. no *involves*) we create multiple more specific Commitments. Similar some 'monthly quota' Commitment would result in adding more specific scheduled Commitments throughout the month, in a variant of your FC use case, Alice would commit to work 20h in next month and then make more specific commitments to for example chair specific scheduled teleconference.

**Comment by fosterlynn** [comment]
OK, sounds a bit like the solawi budgeting, or somewhere in between that and operational scheduling.  So yes let's consider during composition milestone.

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/valueflows/-/issues/464.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
