### ISSUE TITLE
Planning scenarios

### ISSUE THREAD

**Issue by bhaugen** [valueflows/valueflows#472]
I meant these as a set of use cases, but the master branch is closed and I don't want to create a pull request yet, so will post them here for now.

# Planning scenarios

### Demand-driven

Demand-driven planning starts with the final outputs or deliverables that the plan is supposed to create, and schedules backwards in time from the required end dates.

Most products that are assembled from components use demand-driven planning.

### Supply-driven

Supply-driven planning starts with the source materials and plans what to do with them, scheduling forward in time from the start date. Somewhere in the flow, supply meets demand and the supply flows at that stage need to be separated to meet the various demands.

Agricultural crops are the prototypical example of supply-driven planning: the crop is ripe in the field and will rot unless harvested.

Another supply-driven example is a paper mill.

# Recipes

Most types of planning use something like a recipe or work breakdown structure to guide the planning algorithm.

I'll add more detail for each of these scenarios in comments below.

**Comment by bhaugen** [comment]
# Supply-driven example: Fresh Salads 

See video at https://www.freshexpress.com/fresh/fresh-at-every-step

As they say, "coolness is key" and they claim to be "cold-chain obsessed". 

That means crews of pickers go out in the early morning to pick greens, and put them through a conveyor into a refrigerated truck waiting in the field.

Then they get culled, washed, dried, separated into sets for salad kits, and bagged, as fast as possible, in cool temperatures all the time. Refrigerated trucks of salad kits head out for distribution channels and supermarkets every day.

The "cold chain" means they stay cool at every step in their journey (at least according to the company's claims).

This example is typical of food processing in that the products are perishable. Milk is another example where "cold chains" and speed are critical.

**Comment by bhaugen** [comment]
# Supply-driven example: Paper mill

A paper mill is an example of a continuous process. See https://en.wikipedia.org/wiki/Paper_machine

The mill typically runs 24 hours 7 days a week for 4 weeks, and then shuts down, cleans up, and restarts for another 4 weeks.

During that time, it produces one continuous sheet of paper, as you can see here:
![paper machine](https://www.scrapmonster.com/uploads/news/2015/1/1420536825.jpg) 

For those 4 weeks, the paper machine needs to be fed constantly with wood or rag or recycled paper pulp. 

In an integrated mill, the paper mill is fed by an attached pulp mill which mashes the feed stock into pulp.

Part of the planning process for a paper mill is getting the required feedstock at the right time.

When the roll at the end grows to the largest size the equipment can handle, the paper machine crew slits it sideways and removes it to the rewinder station, and they start another roll.

## The rewinder station is where supply meets demand. 

The big wide roll goes thru a slitter which separates it out into narrower sheets according to orders from customers, and the narrower sheets are rewound into smaller rolls.
![rewinder](https://sc01.alicdn.com/kf/HTB1HvCZkNWYBuNjy1zkq6xGGpXat/paper-mill-Slitter-Rewinder-slitter-rewinder-machine.jpg)

The smaller rolls are then moved into railroad cars which are waiting on a siding by the paper mill, which will ship the paper rolls to customers which will make them into some kind of paper products.

The rewinder station is a difficult scheduling job. The paper mill has limited space for rolls of paper and railroad cars, and the correctly-sized rolls of the required grade of paper need to be moved into the correct railroad car for the correct customer.

**Comment by bhaugen** [comment]
# Demand-driven example: bicycle manufacturing

See http://www.madehow.com/Volume-2/Bicycle.html 

The demands for bicycles might come from stores or individual customers.

Each bicycle model will have a recipe, usually in the form of a multi-level bill of materials and routing (sequence of manufacturing processes). In ValueFlows, we combine them into the same structure called a Recipe.

The algorithm for planning is called a dependent demand explosion, which you can read about in some detail in this pattern: https://hillside.net/plop/plop97/Proceedings/haugen.pdf

The recipe is called the Knowledge Level in that pattern.

**Comment by bhaugen** [comment]
More detail on the bicycles, from http://www.madehow.com/Volume-2/Bicycle.html

Given a demand for a bicycle, the dependent demand algorithm will start backwards from the last process, attaching the components to the frame. 

> The components, such as wheels, derailleurs, brakes, and chains, are usually made of stainless steel. These components are generally made elsewhere and purchased by the bicycle manufacturer.

In that case, the dependent demand algorithm will plan the assembly process, and then look for the components.

If bicycle manufacturer has all the components in stock, this can go quickly. If any of them will need to be ordered and delivered from external suppliers, the lead time for order and receipt will need to be added to the schedule. This may push the bicycle delivery date farther into the future.

Then the algo will plan the frame manufacturing process. This will require not only blocks of steel but also some equipment for drawing out the tubes and assembling them together, as well as some workers with the required skills.
> Seamless frame tubes are constructed from solid blocks of steel that are pierced and "drawn" into tubes through several stages. These are usually superior to seamed tubes, which are made by drawing flat steel strip stock, wrapping it into a tube, and welding it together along the length of the tube. Seamless tubes may then be further manipulated to increase their strength and decrease their weight by butting, or altering the thickness of the tube walls. Butting involves increasing the thickness of the walls at the joints, or ends of the tube, where the most stress is delivered, and thinning the walls at the center of the tube, where there is relatively little stress. Butted tubing also improves the resiliency of the frame.

The steel might exist in-house, or again, need to be ordered and delivered. 

At the end of the backscheduling for all the processes and component procurement, the whole series of processes might have been backscheduled into the past, which means they all need to be shifted into the future by at least as much time as they are now scheduled into the past.

**Comment by bhaugen** [comment]
# Demand-driven example: $30 wind turbine electrical generator

![wind turbine](https://cdn.instructables.com/FWE/4XVX/HSVGHLJZ/FWE4XVXHSVGHLJZ.LARGE.jpg)

One interesting feature of this example is an open-source recipe that was published on the Web: http://www.opensourcelowtech.org/wind_turbine.html

In order to implement it, we [copied and pasted the recipe into NRP](http://nrp.webfactional.com/accounting/xbomfg/16/). But that is because NRP was not able to plan from recipes from the Web, and also because doing so will require recipes published in some shared vocabulary (VF maybe?)

If that happens (recipes published in repositories using common vocabularies) then open source hardware can become like open source software: reusable, collaborative, forkable, etc.

Here's the [plan generated from the recipe](http://nrp.webfactional.com/accounting/order-timeline/7/)

**Comment by bhaugen** [comment]
# Planning for time-based resources

Time-based resources, like human work and machines like 3d printers, are used, not consumed.

In the typical old-school manufacturing planning process, [Material Requirements Planning](https://en.wikipedia.org/wiki/Material_requirements_planning) (MRP) planned consumable material inputs and the production of material outputs. [Capacity Requirements Planning](https://smallbusiness.chron.com/definition-capacity-requirements-planning-36994.html) (CRP) used the MRP results to somewhat plan the time-based resources. 

But CRP assumed infinite substitutable quantities of time-based resources (infinite humans or 3d printers) because if two MRP planned processes used a time-based resource of the same type at the same time, CRP would plan two uses at the same time. Or three or ten...

[Finite Capacity Scheduling](https://searcherp.techtarget.com/definition/finite-capacity-scheduling) systems have been added to the mix more recently. They tend to be add-on systems, and they also tend to be expensive and difficult to implement.

We have a friend who has been working on implementing a finite capacity planning system for 2 years, with more than one death march along the way.

It is possible to all three - MRP, CRP, and Finite Capacity Scheduling - using the same model, in the same system. ValueFlows will be able to support that. NRP was almost capable. I worked on [this skunkworks project](https://en.wikipedia.org/wiki/Quick_Response_Engine) in the mid-1990s that as capable of doing it all in real time, event-driven, always up-to-date.

**Comment by elf-pavlik** [comment]
> In order to implement it, we copied and pasted the recipe into NRP.

Thanks @bhaugen but in that recipe I only see some *consume*, one *cite* and one *produce*. In our current quantitative values exploration *use* and *work* seem little more challenging because they may need to state number of used equipment and number of people working plus durations of those actions.

> Finite Capacity Scheduling systems have been added to the mix more recently.

Will take a look

>  I worked on this skunkworks project in the mid-1990s that as capable of doing it all in real time, event-driven, always up-to-date.

Did it support recipes?

**Comment by bhaugen** [comment]
@elf-pavlik 
>  but in that recipe I only see some consume, one cite and one produce. In our current quantitative values exploration use and work seem little more challenging because they may need to state number of used equipment and number of people working plus durations of those actions.

We implement the use cases we got...;-)

I would like to do this one, though: https://organictransit.com/

>> I worked on this skunkworks project in the mid-1990s that as capable of doing it all in real time, event-driven, always up-to-date.

> Did it support recipes?

That was in the era of bills of materials and routings. Recipes were evolving to combine those separate structures. That skunkworks project was a planner's workstation that connected to an ERP system that used the older structures, and we combined them in the workstation software to be able to do MRP and finite capacity planning at the same time.

We did not call them recipes yet, though. That name and the popularizaton of the concept came from some software called [Prism](https://books.google.com/books?id=Bax-DwAAQBAJ&pg=PT567&lpg=PT567&dq=prism+software+recipes+process+industry&source=bl&ots=xHQ0DOZ9qx&sig=ACfU3U0ROnS0uoRKFUCFKlDjYYDLzakF3w&hl=en&sa=X&ved=2ahUKEwiGu4z3jaXhAhXr5IMKHR11BJsQ6AEwB3oECAkQAQ#v=onepage&q=prism%20software%20recipes%20process%20industry&f=false), which is now dead.

**Comment by fosterlynn** [comment]
@bhaugen I put your info into a use case in that directory.  (Apologies for 3 commits.)  Any further changes should go into that file.

**Comment by bhaugen** [comment]
@elf-pavlik 
> in that recipe I only see some _consume_, one _cite_ and one _produce_. In our current quantitative values exploration _use_ and _work_ seem little more challenging because they may need to state number of used equipment and number of people working plus durations of those actions.
> 

In general, I would not put number of machines and number of people into a recipe (unless the recipe has processes that require more than one person or machine for the same process). The usual planning-and-scheduling process has at least two passes: planning and capacity scheduling. Numbers of  people and machines is a capacity scheduling problem.

Here's an example with two variations. In each case, planning and scheduling happens in at least two passes: planning and capacity scheduling.

The problem is many work orders for a machine shop with a number of substitutable machine+people combinations. (Substitutable means you can run the work orders in parallel on more than one machine at the same time.). The recipe details the process flow for the number of machines and people needed to run one production batch through each process, and defines the elapsed time to do one production batch in each process

The planning pass does a dependent demand explosion figuring out if you have the required materials, equipment, and people, to produce the required outputs, but does not yet care how many of the machines and people you have. It will tell you how long it will take for one machine+worker combo per process to do the whole combined output quantity. That might be longer than you want, and that's when more machines and people come in.

The capacity scheduling pass loads the work orders onto machines and people. How many of each depends on how many are available and how fast you need to get all the work orders done.

Variation 1: all the workers are identical in quantity and use the same recipe. In that case, decide how fast you want them done, and figure out how many machines and people will be required using simple math, and divide the work orders equally among those machines and people. 

Variation 2: the work orders are different sizes but use the same recipe. In that case, make a guess at how machine-worker combinations you want to use, and line them up in a queue. Take the first work order by due date and assign it to the first machine, and continue until all the machines have one work order. If you have more work orders, re-sequence the machines starting with the one with the lightest load, and load that one up until it is loaded roughly as much as the most loaded machine. And then give the next work order to the next machine. Etc.

The whole machine shop will have a combined schedule, and each machine+worker combo will have their own schedule.

Did that make sense?

If you have a machine shop with different numbers of different machines and people, the scheduling pass is in the worst category of [computational complexity](https://en.wikipedia.org/wiki/Computational_complexity_theory) and all you can do is hope you got some regularities in the situation that you use to simplify the problem.

**Comment by bhaugen** [comment]
### Supply-driven examples: translation and editing

Translation and editing start with source material and transform it through a series of processes. For translation, the processes might include translate, proofread, edit, and format for publication.

For editing, the source material may be written documents or movie seqments.

In all of those cases, as in most supply-driven planning, the processes are forward-scheduled from a starting point, rather than back-scheduled from a due date like demand-driven planning.

**Comment by fosterlynn** [comment]
This is pretty much moved to use cases.
