### ISSUE TITLE
Reciprocity: claims

### ISSUE THREAD

**Issue by fosterlynn** [valueflows/valueflows#473]
From a walk-n-talk with @bhaugen , and related to https://github.com/valueflows/valueflows/pull/471 but also broader.  Putting it for now in "schedules" milestone to focus on implications for quantity requirements first.

The above issue about requirements for quantitative values has touched on the "other side" of the reciprocity requirement: knowing what is or will be created as the reciprocal side of the event recorded.

I'd like to explore how this could be modeled to handle all kinds of exchange:
* income distribution (we have code that creates claims based on value equation formulas)
* straight up trading this for that
* intents need something that is "reciprocity ratio" or "unit pricing" kind of thing

I'll start with trying it out on the "use of X things for Y time" use case - ouikits should be good for this I think.  And assuming that they will charge agents by "kit-hour"

**Comment by elf-pavlik** [comment]
> intents need something that is "reciprocity ratio" or "unit pricing" kind of thing

I don't wont to sound like nit-picking but while we discuss flows (including intents) having some kind of `reciprocityQuantity`, we need other constructs to express reciprocity between flows, currently `vf:Agreement` serves that purpose, in a way providing a closure around reciprocal flows via *vf:under* and pending *vf:clauseOf* #421 . As we discussed in other issues, 'reciprocity ration' or 'exchange rate' doesn't suffice since it stay limited to dual flows. More flexible alternative which in some discussions i refereed to as 'Agreement Template' #266 could work in a similar way as Recipe, possibly reuse all the same scaling related constructs, and fit dual as well as scenarios where reciprocity involves more than 2 flows.

> Putting it for now in "schedules" milestone to focus on implications for quantity requirements first.

I don't see how it fits *schedules* milestone, probably first [*agreements*](https://github.com/valueflows/valueflows/milestone/6) and later [*proposals*](https://github.com/valueflows/valueflows/milestone/2)

**Comment by fosterlynn** [comment]
>I don't wont to sound like nit-picking but while we discuss flows (including intents) having some kind of reciprocityQuantity, we need other constructs to express reciprocity between flows, currently vf:Agreement serves that purpose,

I wasn't trying to imply that it has to live on Intent, sorry that was unclear.  Just saying we need it somewhere, agreement might be the place.

>I don't see how it fits schedules milestone, probably first agreements and later proposals

Possibly not.  But it relates to the quantity fields on events, and came up on the use case discussion, and I feel like I don't completely understand yet all of what is needed to act on those quantity fields yet.  I'm OK leaving it until later and not worrying about the quantity fields that affect only reciprocity until later if you like.

**Comment by elf-pavlik** [comment]
> I'm OK leaving it until later and not worrying about the quantity fields that affect only reciprocity until later if you like.

So far it looks that we will need dedicated property referencing a quantitative value relevant specifically for *reciprocity* related requirements, anything else except that one specific value, so any kind of reciprocal closure for flows - currently an agreement,  IMO stays outside of responsibilities of any single flow. If you see anything affecting requirements for that *quantity affecting reciprocity*, let's include it in #471 , anything related to how to construct reciprocity relations involving number of flows I would leave for *agreements* milestone.

**Comment by fosterlynn** [comment]
>So far it looks that we will need dedicated property referencing a quantitative value relevant specifically for reciprocity related requirements, anything else except that one specific value, so any kind of reciprocal closure for flows - currently an agreement, IMO stays outside of responsibilities of any single flow.

Yes I agree we don't need to define what the agreement part looks like,  I just want to make sure we understand that dedicated property enough.  Maybe its OK, we can see when we try to name it. Let's give it a try tomorrow.

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/valueflows/-/issues/473.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
