### ISSUE TITLE
complete fullfillment with some quantities lower than commited

### ISSUE THREAD

**Issue by elf-pavlik** [valueflows/valueflows#474]
In https://github.com/valueflows/valueflows/pull/471#issuecomment-478255415 I suggested something like *acceptedCompleteFulfillment* for situations where event had different quantities than commitment (especially lower) but agent wants to mark that this factor of commitment still should considered fully fulfilled. 

While it seems more relevant when commitments get made on *use*, it might play less or no role where commitments get made on *reserve* and for example the whole duration of reservation gets fulfilled even though usage lasted shorter time.

**Comment by fosterlynn** [comment]
Can we close this one, resolved by vf:finished on the commitment?  If there needs to be a conversation for action on it, we could discuss that when we get to CfA.

**Comment by elf-pavlik** [comment]
I'll add some examples before closing it.

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/valueflows/-/issues/474.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
