### ISSUE TITLE
"Workflow" recipes and plans

### ISSUE THREAD

**Issue by fosterlynn** [valueflows/valueflows#477]
This is a placeholder issue so that we look at the situation of same economic resource into and out of a process, often a series of processes.  We found you need something in addition to just the economic resource to prevent cycle problems in processing.

I'll come back and fill in the issue with more explanation and earlier discussions.

**Comment by elf-pavlik** [comment]
I think resources might need some kind of 'states', I just thought of an example of refrigerator - same one with same serial number but disconnected (idle) vs. connected (cooling).

**Comment by fosterlynn** [comment]
Resolved in v.3.
