### ISSUE TITLE
profiles or subsets of vocabularies

### ISSUE THREAD

**Issue by bhaugen** [valueflows/valueflows#479]
Here's an example: https://stephank.nl/p/2018-10-20-a-proposal-for-standardising-a-subset-of-json-ld.html

Might be useful for VF, both in terms of users of the VF vocabulary, as well as VF uses of other vocabularies like owl:time.

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/valueflows/-/issues/479.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
