### ISSUE TITLE
Actions: properties, instances

### ISSUE THREAD

**Issue by fosterlynn** [valueflows/valueflows#487]
Opening this issue to discuss in one place:
 
1) What additional actions are needed and/or what actions should be combined?  In general, what is the sweet spot for definition of actions to get a balance of non-proliferation and enough semantic meaning to make them clear? 

2) Right now we have actions defined as `rdf:Property`s and have set up a property inheritance structure to define decrement/increment.  There are a number of other attributes that could be defined so that handling actions could be completely data driven, rather than hard coded.

There are some other ways to slice the above too. If we define 2), we could combine those into core behaviors, which could be referenced on actions, opening up the semantics to broader definitions, even user definitions.  Or those core behaviors could be the actions, with less semantic meaning than we have now.  And probably others.

**Comment by fosterlynn** [comment]
Action | Affect | I/O | Changes existence | Changes availability | Changes possession | Changes Full R&R | Pairs with |
------ | ------ | --- | ----------------- | -------------- | ------------ | ----------- | ---------- | 
produce | Increment  | Output | Yes | N/A | N/A | N/A | N/A |
consume | Decrement  | Input | Yes | Yes | N/A | N/A | N/A |
use | No effect*  | Input | No | Yes | No | No | N/A |
work | No effect*  | Input | N/A or No | Yes | No | No | N/A |
cite | No effect  | Input | No | No | No | No | N/A |
load | Decrement**  | Input | No | Yes | Might? | No |  unload |
unload | Increment**  | Output | No | Yes | Might? | No |  load |
accept | No effect  | Input | No | Yes | Yes | No | improve |
improve | No effect  | Output | No | Yes | Yes | No | accept |
give | Decrement | Input | No | Might | Yes? | Might | receive |
receive | Increment | Output | No | Might | Yes? | Might | give |
raise | Increment | N/A | N/A | No | No | No | N/A |
lower | Decrement | N/A | N/A | No | No | No | N/A |

*Or decrement calendar resource
**I think load and unload maybe could go either way, no effect if the resource is already packaged or identified as the resource in the transportation process.

(Making some notes and changes to existing entries too.)

Still thinking about implications.

**Comment by elf-pavlik** [comment]
I see no reason why full R&R can't change during *load* and *unload*. Also *produce* and consume may change full R&R for the small-r resource when it gets consumed or produced.

In general I don't think we should expect that action implies anything about R&R, we could document common scenarios like FOB origin / destination, pickup and drop-off etc. Still we should either explicit R&R effect in flow or dedicated *transfer* flow with that explicit R&R effect.

I also see possibly two different ways of seeing *availability*
* physical constraints based - if someone currently uses a quantity of a resource or has commitment to use quantity of a resource, no matter of R&R no on else can use it - even person who has full R&R
* social constraints - if someone wants to use (directly event) or create commitment to use, one needs to have R&R for that

I would see the social constraints adding up on top of physical constraint. If action has anything to do with any of them, I think it should only relate to the physical constraints, not any R&R related.

**Comment by fosterlynn** [comment]
>I see no reason why full R&R can't change during load and unload. Also produce and consume may change full R&R for the small-r resource when it gets consumed or produced.

Yeah, I was trying to see what actions implied change of R&R in their nature, without adding other transfer info.  Just exploring connections.  I may have been inconsistent though.  I'll change those.

>If action has anything to do with any of them, I think it should only relate to the physical constraints, not any R&R related.

Agree, I was not counting the constraints of full R&R on availability to others.

**Comment by fosterlynn** [comment]
A few actions that have been mentioned over the past months that we might want to think about:
* assemble and disassemble
* move (defined as changing only location, moving with 2 resources would have to have a process and a load/unload or consume/produce or something - I would prefer load/unload)
* something for 'issue/receive', 'split/merge', etc. - not the same as give/receive, but possibly related and we could look at all of these to see what makes sense to be different and the same

**Comment by fosterlynn** [comment]
>something for 'issue/receive', 'split/merge', etc. 

I'm liking issue/receive at the moment, but probably need to look at a bunch of use cases to see if the semantics are reasonable.

Another one to consider:
* pack and unpack (could use vf:contains if needed - @bhaugen wrote some code for this one a while back for the highschool fablab group we're working with) - sort of like assemble and disassemble, but not really

**Comment by fosterlynn** [comment]
Another action:
* service (mostly an output but also can be an input)

**Comment by elf-pavlik** [comment]
>  not the same as give/receive, but possibly related and we could look at all of these to see what makes sense to be different and the same

I don't see where this supposed to differ as action, it just increment/decrement and does not change existence. Anything R&R related should get taken care of by *transfer*.

> service (mostly an output but also can be an input)

Both output and input

> move (defined as changing only location, moving with 2 resources would have to have a process and a load/unload or consume/produce or something - I would prefer load/unload)

I still don't see flows which involve 2 different resources.

> * pack and unpack
> * assemble and disassemble

how does suppose to differ? I guess both increment/decrement and don't change existence.

**Comment by fosterlynn** [comment]
>>service (mostly an output but also can be an input)

>Both output and input

Yes.  So, can be just an output, or both an output and input if it needs to go into another process... right?

>I still don't see flows which involve 2 different resources.

Right, I'm staying away from those per your request.

> * pack and unpack
> * assemble and disassemble
>How those two supposed to differ? I guess both increment/decrement and don't change existence.

They are helpful semantically, and I guess we need to see what are all the ways we want to define actions to see if they are 100% the same.  Maybe we can think of terms that cover both?  Or, it might be useful to note for actions, which apply to transformation, which apply to transportation, which apply to transfer (depending on how transfer gets resolved).  Just thinking ahead, not making a proposal until we get transfer done.  Or it might be useful for the packed resource to be referenced directly by an "owning" agent, while nobody would do that for something assembled, it is not a separate resource until it is disassembled.

>I don't see where this supposed to differ as action, it just increment/decrement and does not change existence. Anything R&R related should get taken care of by transfer.

I think I need to wait and see how you want to handle transfer as an event or non-event or 2 events or 2 non-events, and then we can figure this out.

**Comment by pospi** [comment]
Can we get some descriptions of the `vf:action` types in the RDF spec? Actually finding some ambiguity in deciding upon the correct action for stocking a resource one already has; descriptions would help with that :)

**Comment by fosterlynn** [comment]
>Can we get some descriptions of the vf:action types in the RDF spec? Actually finding some ambiguity in deciding upon the correct action for stocking a resource one already has; descriptions would help with that :)

There are some descriptions here https://valueflo.ws/introduction/flows.html (scroll to the middle-ish).

We certainly can clarify them!  In terms of "stocking a resource one already has", it will depend on what leads to stocking it - could be produce, could be receive, possibly others, would have to look.

**Comment by fosterlynn** [comment]
Another action issue:  Bob has started working on CfA, and one of the verbs there is "accept".  I think we ought to use that for CfA, so I think we ought to change our action `accept` to something else. This gets into all the give/take words too.  Maybe obtain. 

On the topic of accept, someone said they weren't sure they liked `improve` on the grounds that they weren't sure it was always improved.  I'm find with keeping it, but if there is something better, this is the time....

**Comment by pospi** [comment]
I like "obtain". As to "improved", the implicit bias in that is somewhat appealing to me from the perspective of making the intentions of those who set up the `vf:Process` clear, but I hear that criticism. I can't think of ways to display action effects in network planning UIs as anything other than positive / negative / neutral though; and I do note that `vf:improve` is currently considered a "neutral" event.

**Comment by fosterlynn** [comment]
Thanks @pospi .

>As to "improved", the implicit bias in that is somewhat appealing to me from the perspective of making the intentions of those who set up the vf:Process clear, but I hear that criticism.

Could be just "change".  Although maybe "improve" can include dismantling, etc.

>I do note that vf:improve is currently considered a "neutral" event.  That's because it doesn't create a resource or change the quantity of an existing resource.  Changing the insides of a resource doesn't count.

**Comment by fosterlynn** [comment]
>> As to "improved", the implicit bias in that is somewhat appealing to me from the perspective of making the intentions of those who set up the vf:Process clear, but I hear that criticism.

>Could be just "change". Although maybe "improve" can include dismantling, etc.

Got another suggestion recently: "modify".  I rather like that the best, as I'm sure there are some edge cases where a resource that goes both in and out of a process is not improved.

**Comment by gcassel** [comment]
I like "modify" and use it too.   I define [modify](https://github.com/gcassel/Modular-Organization-Terminology/blob/master/terms/modify.md) as the root/primary term for  [transform](https://github.com/gcassel/Modular-Organization-Terminology/blob/master/terms/transform.md), transport, transfer and transmit.  (I'm hyperlinking modify & transport here for emphasis, in case anyone wants to dig deeper into my forms & elements model which seems increasingly resilient to me.

"load" and "unload" are obviously important for supply chains, but they seem secondary to "transport" and thus tertiary to "modify", although agents should of course be directly enabled to document loading & unloading actions without manually attaching them to "transport" or "modify".

**Comment by gcassel** [comment]
I think that "improve" and "optimize" are potentially useful, but only when they're related to one or more specific goals or functions which a resource has been directly linked to.

**Comment by elf-pavlik** [comment]
I don't think we should worry to much about how we end up naming something. On the other hand, we need to clearly define what using specific action implies since conformant implementations all need to process flows in consistent way.
I think the table we have gives a good start and we could see what different combinations based on table columns we need. I think we also should check if anything would require implementation to code against a specific action or only rely on set of implications an action can have.

**Comment by fosterlynn** [comment]
This is resolved, at least for now, see doc.
