### ISSUE TITLE
essepuntato spec generation not working

### ISSUE THREAD

**Issue by fosterlynn** [valueflows/valueflows#493]
Get 'internal server error' when trying to run it directly in the form on their site.  Tried an older branch to see if it had anything to do with removing the external vocab pieces. webvowl works for our current version, although it looks a bit disjointed now.  Seems like the site is still supported, at least some of the examples linked do work, and others get a much more verbose error message.

http://www.essepuntato.it/lode/owlapi/https://raw.githubusercontent.com/valueflows/valueflows/master/release-doc-in-process/all_vf.TTL

**Comment by elf-pavlik** [comment]
> http://www.essepuntato.it/lode/owlapi/https://raw.githubusercontent.com/valueflows/valueflows/master/release-doc-in-process/all_vf.TTL

This one seems to work or you see problems with it?

**Comment by fosterlynn** [comment]
Worked for me yesterday, tried it this morning, got:

Proxy Error
The proxy server received an invalid response from an upstream server.
The proxy server could not handle the request GET /apps/LODE/extract.
Reason: Error reading from remote server
Apache/2.2.22 (Ubuntu) Server at eelst.cs.unibo.it Port 80

I'm guessing it is up and down on their side.  Hmmm.

**Comment by fosterlynn** [comment]
closing since I did a PR to save snapshot, for now

**Comment by fosterlynn** [comment]
From the essepuntato github:

>The online version is now usable at another URL, starting with https://w3id.org/lode, e.g. https://w3id.org/lode/owlapi/http://purl.org/spar/cito.

**Comment by fosterlynn** [comment]
And another comment from https://github.com/essepuntato/LODE/issues/21#issuecomment-529179453

>FWIW my mate @nicholascar has cloned LODE in Python - an API is described here https://kurrawong.net/pylode-online

**Comment by fosterlynn** [comment]
Changed to the new LODE location.
