### ISSUE TITLE
Preventing ontological leakage in `AgentRelationshipRole`

### ISSUE THREAD

**Issue by pospi** [valueflows/valueflows#494]
This follows on from discussion @fosterlynn & I started in #423.

I don't see any issues regarding `AgentRelationshipRole`; and the verbs are commented out, plus it has no fields defined in `all_vf.TTL`. AFAIK it gives only `label` & `inverseLabel`, and has no classification in order to derive meaning from the field (in the VF repo, I have a commented-out field given as "`category: AgentRelationshipCategory #TODO: figure out`").

Given the status of that, I don't see any way to define app-specific behaviours which are linked to certain agent relationships, which is the key use-case we're aiming to support, no? `memberOf` / `partOf` / `peerOf` etc all seem to be deprecated. And would be really great to use these fields as a gateway into http://stratml.us/ or similar organisation management ontologies.

It seems an ommission to me to not have some structured ontology present around those fields in order to enable better reasoning around agent relationships whilst allowing the freedom for extension? And when it comes to creating custom names for things, wouldn't it be idiomatic to use `owl:sameAs` and *still* base defaults on a well-known ontology, so that such extensions maintain ontological integrity?

**Comment by elf-pavlik** [comment]
> Given the status of that, I don't see any way to define app-specific behaviours which are linked to certain agent relationships, which is the key use-case we're aiming to support, no?

Could you clarify your use case and include some examples of those app-specific behaviors?

**Comment by bhaugen** [comment]
@pospi regardless of what gets agreed upon in VF, we can and should support behaviors tied to relationship roles in HoloREA.

**Comment by fosterlynn** [comment]
@pospi we did find we needed something in NRP like the set of behaviors you see commented out.  And in VF we had some discussion of the need, as well as how to structure it, but it was quite early on, and we ended up leaving it for later.  I agree with @bhaugen we will need it, but I'm also fine leaving it for the first groups that wants to use VF and have that requirement.  It would be good to have some additional experience with use cases in the wild, and I expect in the kind of agent-centric architecture we are working on, we will find fertile ground to work on it.

**Comment by pospi** [comment]
Cool, that makes sense. I was speaking from the perspective of NRP in any case. Happy to leave this issue here and revisit / workshop it when users start requesting the feature. I might make a point of adding links to these github issues in the GraphQL spec next to the affected records & fields so that when groups start integrating with the spec they have somewhere to go to start exploring implementations.

**Comment by fosterlynn** [comment]
>I might make a point of adding links to these github issues in the GraphQL spec next to the affected records & fields so that when groups start integrating with the spec they have somewhere to go to start exploring implementations.

Good.  Also, I'd like to keep close contact with user groups until there are too many (which isn't yet).  We can learn a lot by listening to their needs and requirements with our "business analyst" hats on.  I have some decades of day job experience as a BA, so I'll happily volunteer to talk to people, help map their needs to VF, etc.

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/valueflows/-/issues/494.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
