### ISSUE TITLE
Add high-level examples section to website

### ISSUE THREAD

**Issue by pospi** [valueflows/valueflows#502]
More groups are starting to do VF modelling of systems & processes in their respective disciplines (CC @metavents @seajones7 @tommycp3). I'd like to leverage some of that work to create a new top-level "examples" section on the website.

I see this as different to https://github.com/valueflows/valueflows/issues/409 because it deals with *holistic* examples which model systems as a whole; not with the lower-level specifics of marking up each individual resource type. So it's not code examples, it's visual flow examples as per https://github.com/valueflows/valueflows/issues/507

Some of the examples people have been asking for in recent weeks which I have recorded:

- [x] Canonical "market maker", using `intent`s to model offers & requests
  - [ ] Agreed state: `commitment`s showing agreement to trade
  - [ ] Complete state: `event`s showing the completed exchange
- [ ] Sourcing of alternative resources, using `intent` as a request for work; many `intent`s to provide the work/resource
  - [ ] Use of [CFA](https://valueflo.ws/introduction/cfa.html)s to proceed from an `intent` to `commitment`
  - [ ] Failed CFAs which do not result in a commitment
  - [ ] Agreed state: `commitment`s being created as a result of the CFA flow
  - [ ] Complete state: `event`s showing the completed exchange, as above
- [ ] Skills marketplace *(may be similar to "sourcing of alternative resources" or "contributory economy", but needs to be worked through separately / explicitly)*
- [ ] Contributory economy, using open `process`es to model available work
  - [ ] Agreed state: `commitment`s showing agreement to complete the process
  - [ ] Complete state: `event`s filling out the process
- [x] A simple transfer, eg. "Alice sending Bob 10 apples"
- [x] A simple exchange, eg. "Alice swaps 10 apples for Bob's 3 pears"
- [ ] Complex (non-paired) exchange example: 2 meals a day + accommodation <-> 20h a week of work
  - *(This way we don't really have exchange rates which assume a pair, we have more of a exchange agreement templates which similar to process recipes can require any number of flows and allow scaling quantities defining those flows.)*
- [x] 3-5 working real-world examples for modelling agents / roles / relationships

Each of these may best be done as a separate page, with some commentary as to how the real-world situation is evolving in line with each diagram.

The above list is loosely ordered by priority, based on demand from various Holochain projects in the works. Market makers, alternative resources & skills marketplace are certainly the most requested.

**Comment by bhaugen** [comment]
In the medium-term, maybe I should continue to work on the [Vocabulator](http://valueflows.pythonanywhere.com/). The idea of that was to be able to add examples as data and generate vocabulary excerpts in different formats, including diagrams. Continued work would involve bringing it up to the latest valueflows changes and maybe evolving a better diagram style. But then we and others could add examples at will.

In the meantime, work out a diagramming style and create them by hand. Problem with hand-drawn (or I mean diagramming-tool-drawn like draw.io but not generated from data) is that the style might be difficult to recreate from data using a graphics library. Tools are starting to exist for generating string diagrams, if people like those.

**Comment by fosterlynn** [comment]
>I'd like to take the opportunity to get to a shared visual design language for these types of diagrams (colour palette, shape & line styles as well as 'overall style') so that we are all modeling in a consistent way. We could just follow the style of the old NRP diagrams, but I think there's an opportunity here to do something more considered.

Yes, please, let's do a new style!

>Each of these may best be done as a separate page, with some commentary as to how the real-world situation is evolving in line with each diagram.

Sounds good.  Perhaps adding yaml examples to each diagram/commentary.  And creating an index.

And I agree that we need both the small specific examples and more general system-wide examples, the more the better.

>Some of the examples people have been asking for in recent weeks which I have recorded

:writing_hand: This is great input for prioritizing pieces of VF still needing some work, thanks.  And I want to explicitly note to @Metavents @seajones7 @tommycp3 that we love working directly with user groups in VF, can provide you with direct support in working through your use cases, which also helps us to develop and better document things here.

**Comment by seajones7** [comment]
Hi all! Thanks for the great write up and insights.

I have an awesome friend and graphic designer with whom I have been sharing a bit about VFs - think she might be able to help us think about and draft a shared visuals design language.

Also B and L - would love to get on another call to speak specifically about the VFs we are working with food -  something you two have thought much about already!

**Comment by fosterlynn** [comment]
>I have an awesome friend and graphic designer with whom I have been sharing a bit about VFs - think she might be able to help us think about and draft a shared visuals design language.

That would be great!  Let us know if you need input from us, for example about what information might be useful to include....

> Also B and L - would love to get on another call to speak specifically about the VFs we are working with food - something you two have thought much about already!

Sure, let's plan it in HC mattermost....

**Comment by bhaugen** [comment]
@pospi @seajones7 @fosterlynn I think it's worth spending some time to understand the category theory string diagrams, because they are computable and thus also computer-generatable. 

Takes awhile to get your mind deeply into these, but at least one or more of the Holochain core devs is into it. And they are totally compatible with valueflows.

Here are a couple of cryptic references:
* the source of the lemon pie diagram: https://arxiv.org/pdf/1803.05316.pdf
* https://arxiv.org/abs/1208.5205

**Comment by pospi** [comment]
Some more existing work at http://valueflows.pythonanywhere.com/vocab/egg2worm-flow/ (and http://valueflows.pythonanywhere.com/ for more); as well as the diagrams on http://locecon.org/

**Comment by pospi** [comment]
May also tie in to how we represent CFAs: https://github.com/valueflows/forum.valueflo.ws/issues/131

**Comment by pospi** [comment]
Further thoughts:

- intents, commitments, events (states of completion) may not be super important in modelling, but are critical in walking through examples
- events going in to & out of processes are typically downplayed- maybe just the [action verb](https://github.com/valueflows/valueflows/issues/487) or even +/- should be shown?
- we don't often show agents in diagrams because processes generally don't care who carries them out; but when explaining the model it can be very helpful to show who's involved where

**Comment by pospi** [comment]
Also to note, Conversations for Action and other "non-resource" flows will probably need to be integrated along with REA-based flows in any non-trivial system design graph https://valueflo.ws/introduction/cfa.html

**Comment by bhaugen** [comment]
> Also to note, Conversations for Action and other "non-resource" flows will probably need to be integrated along with REA-based flows in any non-trivial system design graph

Absolutely! The conversations make decisions about the resource flows. I was trying to illustrate thata little bit here: 
![cfas in flows](https://user-images.githubusercontent.com/117439/56869035-7d663b80-69c0-11e9-856c-6f27ab8f5a67.png)
From https://github.com/valueflows/forum.valueflo.ws/issues/131#issuecomment-487407887

How to depict intents in the flows needs more experiments. But I think we will be interested in intents that either lead to flows or come from needs of processes or both.

**Comment by fosterlynn** [comment]
>events going in to & out of processes are typically downplayed- maybe just the action verb or even +/- should be shown?

Yeah, events are the "edges" in the graph, processes and resources are the "nodes".  So the events tend to become arrows with information on them in flow pictures.

**Comment by pospi** [comment]
Note I've just forked off the "visual design language" aspects of this into their own issue, as there's quite a few things to discuss there and it's messy to have both topics in the same place.

New issue @ https://github.com/valueflows/valueflows/issues/507

**Comment by fosterlynn** [comment]
@pospi I added a new examples section, see on the left menu.  Feedback welcome!  Specific requests also welcome!

**Comment by pospi** [comment]
@fosterlynn you mean these pages? https://valueflo.ws/examples/ex-complex.html
If so, I like them and they're a good slice through the information and I want to add many more! Specific requests as at the start of this thread, I guess.

**Comment by fosterlynn** [comment]
>@fosterlynn you mean these pages? https://valueflo.ws/examples/ex-complex.html
If so, I like them and they're a good slice through the information and I want to add many more! Specific requests as at the start of this thread, I guess.

Yes, all the pages under Examples on the left menu.  And yes I'll continue to add more, as time permits. :)  I started checking off your initial list, please feel free to disagree.  There are a lot more pieces of your suggestions done, but I'll try some all-connected as suggested.  We also have a lot of in-process yaml examples which just need to be adopted to the current version of the vocab.

**Comment by fosterlynn** [comment]
Closing this, with the understanding that more examples will get added as needed.  A basic section is done.
