### ISSUE TITLE
Proposal publishing category

### ISSUE THREAD

**Issue by fosterlynn** [valueflows/valueflows#504]
I"m thinking about adding a proposal category kind of thing to the proposal PR https://github.com/valueflows/valueflows/pull/503, but want to keep the PR as simple as possible to try to get something out there.  So creating an issue to discuss.

I was earlier thinking we would probably need something besides Proposal for multilateral exchange agreements, but maybe not.  Already every intent software I know expects an "offer/want" flag.  Although that can be derived from our provider/receiver data, it is a bit messy.

So, how about a category code to help publishers figure out what to publish where, in their particular app?

Like:
* offer
* request
* multilateral exchange
* ??

**Comment by elf-pavlik** [comment]
>  Already every intent software I know expects an "offer/want" flag. Although that can be derived from our provider/receiver data, it is a bit messy.

I don't see anything messy about it.

As for classifications I think the one's on Intents that Proposal builds on will play the main role.

As for offer / request any proposal that should result in exchange will build on a pair of intents, to provide and to receive. I thought you wanted to use that extra *primary* (reciprocal) flag to try to mark one of the intents as 'more important' for the agent.

**Comment by fosterlynn** [comment]
>>Already every intent software I know expects an "offer/want" flag. Although that can be derived from our provider/receiver data, it is a bit messy.

>I don't see anything messy about it.

Query: get all the offers.
1. get Proposals where code == offer
2. get Proposals that have at least one Intent that isn't a reciprocal ProposedIntent and that has a provider

But also I'm seeing other categories like the multilateral arrangements that won't always be part of the same apps, or at least will be presented differently.

>As for classifications I think the one's on Intents that Proposal builds on will play the main role.

When I said category I meant something more like type, except i'm not allowed to use that word. :)  Or maybe more like behavior.  It isn't related at all to a classification in the sense that we have classifications on intents so people can search and match.  More like different kinds of proposals related to publishing them.

>As for offer / request any proposal that should result in exchange will build on a pair of intents, to provide and to receive. I thought you wanted to use that extra primary (reciprocal) flag to try to mark one of the intents as 'more important' for the agent.

Are you saying that if we have a code thing in the proposal, we shouldn't need the reciprocal flag?  Might be right.  But I think it will be useful in matching so it doesn't enter into matching logic, which is what I meant specifically by more important - like they wouldn't even post the reciprocal intent if they didn't have reason to post the primary intent.  Or I might be missing your point?

**Comment by elf-pavlik** [comment]
> get Proposals that have at least one Intent that isn't a reciprocal ProposedIntent and that has a provider

To present proposal in meaningful way application needs information about intents i build on anyways.

> More like different kinds of proposals related to publishing them.

>> * offer
>> * request
>> * multilateral exchange

Since application needs information about Intents, it should know based on that all above. Do you have requirements for other 'different kinds' which one can't easily get from information on intents?

>  Are you saying that if we have a code thing in the proposal, we shouldn't need the reciprocal flag?
> [...] Or I might be missing your point?

I was thinking in the other direction. If we introduce some way to mark intents as *primary* or not, then 'matching logic' doesn't need anything extra directly on proposal.

**Comment by fosterlynn** [comment]
>I was thinking in the other direction. If we introduce some way to mark intents as primary or not, then 'matching logic' doesn't need anything extra directly on proposal.

OK, got it.  I think this would be useful for more than matching, just up front easy filtering. from possibly distributed data stores over the network.

How would you tell from the intents that someone is interested in a multilateral exchange situation?

**Comment by elf-pavlik** [comment]
> How would you tell from the intents that someone is interested in a multilateral exchange situation?

I think for a person it may not matter if they do 1 on 1 exchange or multilateral exchange. They just want to provide some things and receive some things, I don't think it makes difference for anyone if the same agent provides one thing for them and receives another thing. If a proposal builds on pair of intents that define expected reciprocity, same 1 proposal could get used to create 1 on 1 agreement as well as M on M agreement, which would get build from M proposals including that 1.

**Comment by fosterlynn** [comment]
>I think for a person it may not matter if they do 1 on 1 exchange or multilateral exchange

Actually it might matter to a person, because multilateral exchange adds a lot of complexity, and most of the user stories in "small ads" use case want to be very simple one-time things, so dealing with one person directly and being able to just plan the exchange, meet and get it done is what some people are going to want. Dealing with more than two people is double the work, and there is more risk that some part of the larger exchange falls apart.  Especially if there are multiple conversations for action and any negotiation.

Also multi-lateral agreements may tend to be ongoing kinds of things, or it is not worth all that complexity and planning.  So that involves more data, etc.

The software that deals with setting up multilateral exchanges will need to be more complex too.  So simple "small ad" software may want to filter out the multilateral exchanges.

**Comment by elf-pavlik** [comment]
Ok, it makes sense for the proposal to somehow state if it requires 1 on 1 exchange only or allows M on M as long as they satisfy the intents. Still I don't see it as 'category' but very specific constraint one may want to put on a proposal.

**Comment by fosterlynn** [comment]
>Still I don't see it as 'category' but very specific constraint one may want to put on a proposal.

Suggestion of how to do it?

BTW, what were the categories you came up with for Vientos?  Barter, gift, ????  Maybe that fits in too.

**Comment by elf-pavlik** [comment]
I think we only used four 'reciprocity classifications': gift, barter, trade, time-exchange. But that mostly came out of UX and possibly some or all of them may not need anything explicit in data and could get inferred from:

* gift - only *provide* or only *receive*
* barter - both *provide* and *receive* with no currencies
* trade - both *provide* and *receive*, at least one with currency
* timeexchange - both *provide* and *receive* only for *work*

**Comment by fosterlynn** [comment]
>possibly some or all of them may not need anything explicit in data and could get inferred

Thanks.  I'm not sure we should be worried about categories that can get inferred by the data so much.  Even if the software wants to infer them, it seems really helpful to have a vocabulary to attach to them so there is consistency.  Especially when they are a de-facto standard already, like offer / want seem to be.

I worry also that most of the intent apps I've seen (timebanks, small ads, project requests) are way simpler than what we are doing.  Most of them use just description for almost everything, including what is expected for reciprocity.  So deriving some of these things that will be essential to the apps I've seen may be impossible.

But... this is secondary for me, we can let it sit and just let it happen with the first user groups.  Lots higher priorities...

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/valueflows/-/issues/504.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
