### ISSUE TITLE
Create new visual design language for representing flows

### ISSUE THREAD

**Issue by pospi** [valueflows/valueflows#507]
Forking this off from #502 as there will likely be a lot of chatter in this and they are two separate tasks.

Currently we're heavily considering string diagrams, like this one:

![flows-example](https://user-images.githubusercontent.com/117439/55940612-172e9a00-5c06-11e9-8929-360fcb1a26c0.png)

More reading on this style of diagram can be found at https://arxiv.org/pdf/1803.05316.pdf

There have been quite a few different representations for flows created over the years, such as:

- http://valueflows.pythonanywhere.com/vocab/egg2worm-flow/ and various other examples on http://valueflows.pythonanywhere.com/
- The diagrams on http://locecon.org/
- Various places on http://valueflo.ws/

It would be ideal to get to a shared visual design language for these types of diagrams (colour palette, shape & line styles as well as 'overall style') so that we are all modeling in a consistent way. We *could* just follow the style of the [old NRP diagrams](https://speakerdeck.com/mikorizal/everything-in-valueflows-is-connected-to-everything-else?slide=2), but I think there's an opportunity here to do something more considered & have a re-think with some designer input. Plus, computer-generated diagrams similar to these will likely become part of various interfaces in future.

Other relevant comments on this topic to date:

- https://github.com/valueflows/valueflows/issues/502#issuecomment-487326910
- https://github.com/valueflows/valueflows/issues/502#issuecomment-488249017

**Comment by pospi** [comment]
Some additional considerations copied from https://github.com/valueflows/valueflows/issues/502#issuecomment-488157223:

- intents, commitments, events (states of completion) may not be super important in modelling, but are critical in walking through examples
- events going in to & out of processes are typically downplayed- maybe just the [action verb](https://github.com/valueflows/valueflows/issues/487) or even +/- should be shown?
- we don't often show agents in diagrams because processes generally don't care who carries them out; but when explaining the model it can be very helpful to show who's involved where

**Comment by pospi** [comment]
Trying to give a bit more detail on the components of VF in a way that is (hopefully) useful to designers. I see the need for two distinct types of diagrams:

- "Flow design" diagrams, which simply depict the planned flow of resources & processes through an ecosystem. Should be clean, simple & useful for business analysts in designing systems.
- "Flow state" diagrams, which show particular agents & resources moving through the flows. Should give "concreteness" to the "flow design" diagrams by allowing step-by-step explanations to be walked through. I think of these as overlays that use the same flow layouts from the design phase to aid in comprehension. They basically depict the key states that a system can be in.

These are just my personal thoughts, there might be better ways. For example, maybe showing the roles of agents in these systems *is* very important in the design phase. Trying to strike a balance between giving information and imposing my own ideas is hard :/

Again, without trying to impose too much of my own subjective viewpoint, here are some of the VF building blocks; as well as their key attributes and the states they can be in (referencing the "[egg to worm](http://valueflows.pythonanywhere.com/vocab/egg2worm-flow/)" flow from above):

- The main building blocks are the *"flow items"*: *Resources* (green squares in the diagram), *Events* (orange diamonds) & *Processes* (blue circles).
- *Resources*:
    - Have a "type of resource", which can be any description of a "thing".
    - There are also "skill" resources, which denote types of work effort.
    - Also have a quantity, which is typically not shown in "flow design" diagrams but may be relevant in "flow state" examples.
- *Processes*:
    - Describe the types of things that happen in a network- they alter resources
    - Have a "type of process", which can be any description of "something to do"
    - May be fed by 0 or more tangible resources
    - Often also fed by "skill" resources which indicate the types of work needing to occur
        - Historically these have not been shown as the simple case (1 type of work needed to carry out a process) doesn't really need detailing- the process & the work skill can be considered equivalent in these cases
        - However it may be useful to show work inputs along with the agent doing the work in "flow state" diagrams
            - Certainly display of "skill" resources is needed to show how multiple agents can commit to doing some work to complete a process. But if it's just one agent, maybe they can be shown to have committed to the process instead.
    - Progress through "planned", "committed" and "completed" states as resources are provided and work is undertaken
        - Note they don't really have any state of their own&mdash; these are inferred from the input *Events*
- *Events*:
    - Link resources to processes by describing which action connects them
    - Have an "action verb" that is mostly (but not always) one of the [VF action verbs](https://github.com/valueflows/valueflows/issues/487).
        - Actions have the concept of whether they increment or decrement a resource which can be useful in planning
    - Usually progress through "planned", "committed" and "completed" states as resources flow through a system
        - Sometimes things are not pre-planned, so events can start off as "committed" in some cases
            - Likely only relevant in "flow state" diagrams if wanting to show how extra work happening outside the planned flow can occur
    - Are typically downplayed in diagrams, often omitted entirely (especially in systems where "produce" and "consume" are the only action verbs commonly used). In the above "lemon meringue" example they are the joins between lines & boxes.
        - In some flows, increment / decrement may be displayed as `+`/`-`
        - In other flows, the action verb might be more important
        - If we could agree on a consistent way to represent these that works for any system, that would be amazing. But would settle for a few styles of varying detail to pick from.

There are also some less prominent *"flow items"* that can be part of a system:

- *Transfers* sometimes feature in place of *Processes*; you can think of them as processes which move a resource from one agent to another. However they may require a depiction which makes agents visible; since the input & output resource are the same (only the owner changes). An alternative would be to show the "give" event going in to the transfer, and the "take" event coming out. You could place agent icons next to each event to show the sender & receiver.
- Exchange of resources can be modelled by *Agreements* which simply enable sets of *Events* to be coordinated. In the simple case of an exchange it looks much like two *Transfers*. There are actually a minimum of 4 events at play here: two incoming "give" events and two outgoing "take" events. But there may be more, if multiple things are exchanged for another. These too probably look much like *Processes*.
- For more complex *Agreements* the "process-like box representation" probably works just as well. In the end they are just a means of grouping *Events*.

And some other parts of the vocabulary for special cases, which we may or may not want to consider at this stage:

- One *Event* may be linked as an *"Appreciation"* for another event. Relevant to gift economy flows. Could probably be displayed fairly simply as a connecting line.
- *Claims* may be created, which specify future *Event*(s) desired as return for some *Event* that has already occurred. For example, you could say "I gave you 10 apples and I want $5 for them some time in future". This may overlap with the "flow state" diagram styles, because an open claim kinda feels like a "planned" event to me. Later in the flow, real *Events* would be filled in to complete the claim.

And finally, there is the *Plan* concept, which is probably best represented as boxes which group different parts of flows. Basically a plan is just there to group a body of work into a single logical task.

I hope this makes sense and is not too overwhelming! Please correct, elaborate and discuss as needed (:

**Comment by elf-pavlik** [comment]
Thanks for raising it @pospi I've been experimenting with something like below:

![web](https://user-images.githubusercontent.com/876431/57224598-9ded5180-6fcf-11e9-90bf-3df9af57c120.png)


It uses sort of pink for resourcey stuff (including personal skills), purple for processey stuff, orange for agreements, flows - blue intent, orange commitment, green event.

While doing that I also lean more towards not treating agents, resources and processes as disjoint. So we can also treat agents as 'very high level process' which can have inputs and outputs. Processes should preferably form **circular economy** cycles, and Agreements should preferably form **circular reciprocity** cycles. Simplest example: 

![reciprocity-cycle](https://user-images.githubusercontent.com/876431/55694130-37e1c000-5978-11e9-9431-8746572fb224.png)

*Flows with *service* actions go directly process to process without involving any resource*

Also this image from our website:

![dual flow](https://raw.githubusercontent.com/valueflows/valueflows/master/release-doc-in-process/coffee-oliveoil-flows.png)

Could have multilateral variants like:

![exchanges](https://user-images.githubusercontent.com/876431/56085818-ed48c380-5e0f-11e9-9290-b0f16b719433.png)

**Comment by bhaugen** [comment]
@elf-pavlik if you conflate agents with high-level processes, then do processes have agency?

Or if you conflate resources with processes with agents, than do resources have agency?

(To be more explicit, I think agents, processes, and resources are distinct concepts for very good reasons.)

**Comment by elf-pavlik** [comment]
> Usually progress through "planned", "committed" and "completed" states as resources flow through a system

This sounds like;
* planned - Intent (not yet committed)
* committed - Commitment
* completed - EconomicEvent

Where Satisfaction and Fulfillment allows M:M to refine it between those phases and we may still need some kind of further withing one phase refinement constructs #464

**Comment by elf-pavlik** [comment]
@bhaugen to avoid hijacking this issue let's continue on disjointedness in #508

**Comment by pospi** [comment]
@elf-pavlik planned / committed / completed is exactly as you describe. Even though those are separate distinct record types in VF, conceptually I feel that they just indicate the state of a particular event / process.

Unfortunately the diagrams you posted don't seem to have legible lines- are they white or something? Any chance of a reauthoring for Github's display context?

**Comment by fosterlynn** [comment]
A few comments and clarifications on this https://github.com/valueflows/valueflows/issues/507#issuecomment-489503638 .

>I see the need for two distinct types of diagrams:
>    "Flow design" diagrams
>    "Flow state" diagrams,

I like this overview and distinction.  Is it more of a priority to focus on the former first, as that helps groups think about their processes and workflow as described in VF?  Or focus on both at the same time?  If just the first, we can simplify a lot of the explanations.

>For example, maybe showing the roles of agents in these systems is very important in the design phase.

It might be useful to some people.  Examples I can think of are an herbal network we worked with that had "growers", "harvesters", "drying sites", "sellers", with flows between them.  Or maybe showing roles like "customer" or "supplier" as flows go out of scope for the agent doing the diagram.  Can we think of doing this exercise with the ability to add in layers or not, like "click" and it shows agent roles? Or "click" and it hides the resources and just shows flows?

>Often also fed by "skill" resources which indicate the types of work needing to occur
>  *  Historically these have not been shown as the simple case (1 type of work needed to carry out a process) doesn't really need detailing- the process & the work skill can be considered equivalent in these cases
>  *  However it may be useful to show work inputs along with the agent doing the work in "flow state" diagrams
>      *  Certainly display of "skill" resources is needed to show how multiple agents can commit to doing some work to complete a process. But if it's just one agent, maybe they can be shown to have committed to the process instead.

I think this makes things too complex.  And I'm not sure that the one-type-of-work processes are really the norm, although they will be for some domains.  My opinion: let's just stick to the structure we have and not second guess the differences.  Especially to start.  Also I think sticking to the observation layer might be best to start with also, rather than including commitments, etc.  For the "flow design" diagrams, this is just analytical anyhow, so we could think of possibly mythical and aggregated observation layer items, but still thinking of "real" processes.

>Sometimes things are not pre-planned, so events can start off as "committed" in some cases 

Sometimes things are not committed either (which should actually be thought of as part of planning).  Sometimes there are just events.

>Events: 
>Are typically downplayed in diagrams, often omitted entirely (especially in systems where "produce" and "consume" are the only action verbs commonly used). In the above "lemon meringue" example they are the joins between lines & boxes.

Just to clarify, I don't think you can get a line without the events.  In that diagram I think of the lines with the resource classification text as events, not as resources, although clearly there is resource related info there.   Might just be different ways of conceptualizing, but thought it might be useful to mention.

**Comment by fosterlynn** [comment]
>Just to clarify, I don't think you can get a line without the events. In that diagram I think of the lines with the resource classification text as events, not as resources, although clearly there is resource related info there. And 2 events form each line. Might just be different ways of conceptualizing, but thought it might be useful to mention.

@bhaugen  thinks I am confusing things more.  Sorry about that!  When I said you can't get a line without the events, I meant that literally, the visual line.  Could display just the line with no labels, could add textual information from there for the resource classification/specification (like "lemon filling"), and from there information about the events if you want.

**Comment by bhaugen** [comment]
> When I said you can't get a line without the events, I meant that literally, the visual line. Could display just the line with no labels, 

Like this:
http://valueflows.pythonanywhere.com/vocab/processes-only/
There you can see some processes with lines connecting them. Each line has 2 events and one resource behind it, that were necessary to the code that constructed the line, but are not shown on the diagram.

**Comment by elf-pavlik** [comment]
> planned / committed / completed is exactly as you describe. Even though those are separate distinct record types in VF, conceptually I feel that they just indicate the state of a particular event / process.

I think we should stay careful when we talk about *events*, since VF only has notion of past (observed) events, and any future (plans) get represented by *intents* and *commitments*. I find *flows* as safer term to talk about *intents*, *commitments* and *events* in general without distinction if we talk about future plans or past (sometimes present) observations.

![flows](https://raw.githubusercontent.com/valueflows/valueflows/master/assets/flows.png)

> Unfortunately the diagrams you posted don't seem to have legible lines- are they white or something? Any chance of a reauthoring for Github's display context?

I actually mostly tried avoid adding lines not to create extra noise, since flows act as lines (inputs & outputs), usually one can see how things connect just by looking at the glyph with a little wave: blue: intent, orange commitment, green - event. I think about adding a timeline slider to that map which when used could show when each of the flows occurs / lasts. Since my map also represents some recurring flows, I'd like to have a way to give bubbles next to them (also 3 colors) with how many I, C, E we have in the same place. One could also hover to see list of all the flows.

**Comment by elf-pavlik** [comment]
>  Processes should preferably form **circular economy** cycles, and Agreements should preferably form **circular reciprocity** cycles.

Expanding a little bit on my comment above. Since we live on a globe (plant Earth) and I hope aim at **circular economy** and **circular reciprocity**, when we take independent perspective we don't really have *forward* and *backward* flows. With respect to processes, we always have I > P > O direction. When it comes to agreements and reciprocity, in general we have mutually reciprocal flows. Currencies seem like a special case where one may consider flow involving currency as 'non primary'. Still as long as we stay connected to *use value*, it seems that we have mutually reciprocal flows and no forward or backward notion of reciprocity if we take independent perspective.
We may see certain direction with *provide* > *receive* but in general case of exchanges we have at least two of those directions agreed upon, sometimes more.

![multilateral](https://user-images.githubusercontent.com/876431/56085818-ed48c380-5e0f-11e9-9290-b0f16b719433.png)

**Comment by pospi** [comment]
> Also I think sticking to the observation layer might be best to start with also, rather than including commitments, etc

I don't think it's necessary to show any of those in the design phase. I have been using "Events" too loosely, and agree with what @elf-pavlik is saying: it's actually "Flows" I have been talking about. When I think of events / commitments / intents in the context of diagrams, I think of them as "the states a flow can be in".

**Comment by fosterlynn** [comment]
>>planned / committed / completed is exactly as you describe. Even though those are separate distinct record types in VF, conceptually I feel that they just indicate the state of a particular event / process.

>I think we should stay careful when we talk about events, since VF only has notion of past (observed) events, and any future (plans) get represented by intents and commitments. I find flows as safer term to talk about intents, commitments and events in general

I agree the term "flows" can be useful, and the visual language could possibly look 90-100% the same for all of them.  The lemon meringue pie diagram above could represent a recipe, a plan, or a record of what happened.

In terms of intended / committed / observed being conceptualized as stages:  I think we need to be a bit careful of that, since they may not correspond as exactly all the time as they may do in the very simplest cases.  They are all many-to-many relationships, sorry about the modeling lingo.  It means a commitment could satisfy many intents, an intent could be satisfied by many commitments, an event could fulfill many commitments (think paying several invoices at once), many events could fulfill one commitment (think you committed to work an estimated 40 hours to complete this task, you record your hours every day in separate events).

**Comment by bhaugen** [comment]
Tidbit on what is shown and hidden in a visual language: if you follow the rules of category theory string diagrams, you can nest details inside boxes to simplify a higher-level view. Like here is the whole lemon pie recipe from the first post above nested inside one box to add the baking process:
![lemon-pie-baked](https://user-images.githubusercontent.com/117439/57525055-4876b480-72ef-11e9-9e4c-97c4ada14b0c.png)

**Comment by pospi** [comment]
I really love the idea of interfaces which face in detail in varying levels of complexity, similar to how "Cards" operate on https://realtimeboard.io
We don't have a parent/child relationship implemented for VF to allow this behaviour yet, unless you use `Plan`s but then there is only 1 level of detail to adjust, where what you ideally want is for it to be fractal.

**Comment by fosterlynn** [comment]
>We don't have a parent/child relationship implemented for VF to allow this behaviour yet, unless you use Plans but then there is only 1 level of detail to adjust, where what you ideally want is for it to be fractal.

We've thought about it, but haven't decided anything yet.
https://github.com/valueflows/valueflows/issues/290
https://github.com/valueflows/valueflows/pull/293

There are (as usual) a bunch of trade-offs in this kind of flexibility for users.  But I also wonder how much the visual design language should tie into an operational system?  Don't know the answer.

I definitely think the visual design language should be very flexible and allow all kinds of composition.  Not so sure about how the vocabulary supports operational systems, where users (and developers) can be overwhelmed with configuration options.  On the other hand, I think we should be using the vocabulary in the visual language, as much as it works for it.  And the vdl can be really useful for operational UIs probably too.

I expect there is a sweet spot for each, or maybe it will be the same, don't know.

**Comment by bhaugen** [comment]
By the way, @pospi @fosterlynn and all visual language nesting fans, you can hide details or provide nests visually even if they are not implemented in the underlying data model. The variations on what is visible in [these flow diagrams](http://valueflows.pythonanywhere.com/) was all done in code. The underlying data was the same.

**Comment by fosterlynn** [comment]
>By the way, @pospi @fosterlynn and all visual language nesting fans, you can hide details or provide nests visually even if they are not implemented in the underlying data model. 

Yup makes sense.  At least for hiding some kind(s) of objects, like resources or whatever.  But it seems like in composed processes, you would need to give a name to the nesting process (like "prepare lemon meringue pie"), and define it what it nests.  And if you have to define that as data, then it seems like there is vocabulary involved.

On the other hand, we could define that part of the vocab just for analysis / display, not for operational entities perhaps.... gotta get some real use cases under our belts I think....

**Comment by pospi** [comment]
(via @fosterlynn) One nuance of the intents/commitments thing, is that the same pattern will also happen as part of production, for example when work is planned with some intents, and the group looks for people to commit to the work (Sensorica works like that).  That will happen more in looser networks than tighter groups where everyone knows their roles and there is not as much choice day by day.

And it may be more prominent in basic exchange, or at least in many situations.  Other situations there will be established supply chains where the exchange negotiation has basically been done before hand, maybe years ago.

I did an experiment yesterday for @seajones7 (working from his very complete information) where I skipped the intents and commitments.  But it is just as valid to put them in really, depending on how much detail you want to show.

For myself, I think I'll have to do a number of experiments in different domains before these patterns of what is most useful to show become more clear.

**Comment by pospi** [comment]
For me good solutions start to become clearer when you conceptualise things fractally, like @bhaugen is in https://github.com/valueflows/valueflows/issues/507#issuecomment-491260497.

In the same way that you can zoom in & out to varying levels of detail in a process flow "nesting hierarchy"; you can zoom in & out to varying levels of detail on an exchange, transfer, agreement... and within those containers you can show the details of how the underlying states flow for input resources to proceed "through" them and become output resources. When you zoom out more & can no longer absorb all that detail, only the input & output resources are shown.

Like Bob says, think of them like circuit diagrams. The inside of a transfer looks like two event "wires" pointing in opposite directions, which look like two commitment wires preceding event wires if looked at closely... the inside of an exchange looks like two transfer events crossing across each other; the inside of an agreement looks like a bunch of commitments building up over time until events begin to trickle out the other end... does that kinda make sense?

**Comment by elf-pavlik** [comment]
> I did an experiment yesterday for @seajones7 (working from his very complete information) where I skipped the intents and commitments. But it is just as valid to put them in really, depending on how much detail you want to show.

Using only events one can only describe observed past. For anything related to planning something in the future on needs intents and commitments, since in VF 'future events' don't exist.

![flows](https://raw.githubusercontent.com/valueflows/valueflows/master/assets/flows.png)

**Comment by fosterlynn** [comment]
>> I did an experiment yesterday for @seajones7 (working from his very complete information) where I skipped the intents and commitments. But it is just as valid to put them in really, depending on how much detail you want to show.

>Using only events one can only describe observed past. For anything related to planning something in the future on needs intents and commitments, since in VF 'future events' don't exist.

Sorry I was not clear.  I ignored the intents and commitments, making it more just "flows" as discussed above.  Not assuming events.

Here are my experiments to date.  Meant for food for discussion, there are known issues with both of them actually.

![vf-rootflows](https://user-images.githubusercontent.com/3776081/57656067-0b374e80-759d-11e9-8ac8-1ca10e018e37.png)

![vf-hummflows](https://user-images.githubusercontent.com/3776081/57656052-007cb980-759d-11e9-89f0-e1dc2315493a.png)

**Comment by pospi** [comment]
Probably overly technical for direct design consideration, but a good overview of petri nets in this presentation- http://di.ulb.ac.be/verif/ggeeraer/Tutorial-Perti-Nets-Geeraerts.pdf

I think there are a lot of parallels here and potentially useful ways of depicting value flows via the same methodology.

**Comment by bhaugen** [comment]
Coupla free petri net editors:
* http://www.pneditor.org/
* probly fancier, but wants Windows: http://cpntools.org/

Petri nets is what the catsters like: https://johncarlosbaez.wordpress.com/2018/08/15/open-petri-nets-part-1/

That is probly an obscure reference but that means they will work for VF.

**Comment by pospi** [comment]
Some nice examples showcasing community detection by representing the amount of data flowing between nodes in a network. Particularly fond of this one:

![(top left one)](https://www.pnas.org/content/pnas/105/4/1118/F1.large.jpg?width=800&height=600&carousel=1)

**Comment by pospi** [comment]
Another well-traveled convention worth exploring- [Harel Statecharts](https://statecharts.github.io/)

**Comment by bhaugen** [comment]
I thought I wrote and posted this already, but it seems to be gone. One more try:

I think string diagrams are taking off. Other people are picking up and using them. For example, https://forum.holochain.org/t/checking-in/2749/62

They seem to be simple enough for relative newcomers to understand and then use, and they can be precise. Some additional conventions could be applied to designate REA concepts.

**Comment by bhaugen** [comment]
> Another well-traveled convention worth exploring- [Harel Statecharts](https://statecharts.github.io/)

I like some form of state charts a lot, where we have distributed state machines going. Like [Conversations for Action](https://valueflo.ws/introduction/cfa.html) and other kinds of distributed transactions. Where else will they fit?

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/valueflows/-/issues/507.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
