### ISSUE TITLE
Resource identification in Transfers

### ISSUE THREAD

**Issue by bhaugen** [valueflows/valueflows#512]
This is a discussion topic. I'll introduce the concepts of independent and agent views of information in order to frame the topic.

This frame comes from REA, which provides an independent view of economic activities which is linked to, but different from, the trading partner or agent view. The independent view is public, the agent views are, or at least can be, private.

Here's an example of a transfer from https://content.iospress.com/articles/applied-ontology/ao198:

![Wim transfer diagram](https://user-images.githubusercontent.com/117439/57701109-e4226080-7620-11e9-8053-6b3314def03f.png)

The white boxes in the middle represent the independent view. The pink and blue boxes represent agent or trading partner views.

I think, in general, VF should represent the independent view, since its purpose is to communicate between apps, but that is part of what is up for discussion in this topic.

The other part is how to identify resources in the independent view. 

We've discussed identifying resources before in https://github.com/valueflows/valueflows/issues/351

We've also discussed resource identification on transfers, where in the agent views, two resources will be involved, one identified by the provider, the other by the receiver. But people have disliked having two resources identified on a transfer event, and also disliked having two events - a give and a take - involved in a transfer as a container of events. (The give and take events properly belong to agent views, not the independent view, as you can see in the diagram above.)

So I think if we want to represent a transfer as a single event, taking the independent view, all we need is the information to indirectly identify the resources involved. That could include a lot id or serial number, the providing and receiving agents, the resource classification and/or specification, and the transfer event. That set of information would be sufficient for each of the agents to identify the resources involved in their information space. 

Location could be added, but then you might be dropping into an agent view: which location do you mean?

ERP systems, which take the view of an Enterprise (a group agent), have some equivalent of a LotLocation record which identifies stock resources by the combination of Lot ID and storage location. Any resource with the same Lot ID that gets put into the same storage location gets added to that resource. Warehousing systems do the same thing.

An automated warehouse that we have visited first scans incoming resources and adds them to the warehouse inventory as a whole, and then the robot takes them to a specific location and records that information. All of those actions get deeper into the view of a specific agent.

In my opinion, ValueFlows should represent the independent view, and not get into identifying the agent views of specific resources on transfers either once or twice. Let that be the job of the agents.

**Comment by elf-pavlik** [comment]
I thought to avoid 'dummy' processes just to change resource IRI from one namespace to another one, we could just use IRIs like urn:uuid:123e4567-e89b-12d3-a456-426655440000 which has disadvantage that can't get dereferenced, but advantage of not 'belonging to' specific namespace.

On the other hand, each agent's dataset can include information about any things, not only denoted by IRIs in namespace related to that dataset. I don't see any disadvantage if dataset exposed somewhere in `bob:` namespace includes information about things denoted with IRIs in `alice:` or `charlie:` namespaces. Just as dataset can include information about things denoted with IRIs like `urn:uuid`.

**Comment by bhaugen** [comment]
@elf-pavlik 
> I thought to avoid 'dummy' processes just to change resource IRI from one namespace to another one, we could just use IRIs like urn:uuid:123e4567-e89b-12d3-a456-426655440000 which has disadvantage that can't get dereferenced, but advantage of not 'belonging to' specific namespace.
> 
> On the other hand, each agent's dataset can include information about any things, not only denoted by IRIs in namespace related to that dataset. I don't see any disadvantage if dataset exposed somewhere in `bob:` namespace includes information about things denoted with IRIs in `alice:` or `charlie:` namespaces. Just as dataset can include information about things denoted by IRIs like `urn:uuid`.

I can't follow how your comment relates to what I wrote. I don't recognize dummy processes is anything I wrote, for example. I was trying to speak to the issues of how resources could be identified on singular transfer events, without additional give and take events or two resources. And proposing that VF does not need to specify the resource IDs for each agent. Let them do that, and publish what they want as open inventory info (for example).

**Comment by elf-pavlik** [comment]
> And proposing that VF does not need to specify the resource IDs for each agent.

I was trying to make a point that different agents don't need different IDs for the same resource. I have impression that one of issues that *give* and *take* seem to address relates to dealing with unbound number of namespaces and trying to always keep IRI identifying a resource in a namespace of agent who... practically owns it. In a way trying to imply 'belonging to inventory' by identifying resource with IRI in namespace used for that inventory.

**Comment by elf-pavlik** [comment]
For example here: https://github.com/valueflows/valueflows/commit/ec13de1cc788f2c3d11c84068d4724f4d2a72090#r33513716

Nothing stops Dan from owning a resource denoted by IRI in `alice:` namespace. We could denote that resource by IRI like `urn:uuid:` as well which doesn't belong to anyone's namespace.

**Comment by bhaugen** [comment]
@elf-pavlik 
>> And proposing that VF does not need to specify the resource IDs for each agent.

> I was trying to make a point that different agents don't need different IDs for the same resource. 

The warehouse robot needs to know where to find the resource. No other agents need to know that.

> I have impression that one of issues that give and take tries to address relates to dealing with unbound number of namespaces 

I am not sure what you mean by "namespace". Give and take are the internal events within agent information spaces that are associated with what could be represented by a single Transfer event (or some other representation, but usually a single Transfer) from an independent view. The give and take events are necessary for an individual agent's inventory management, but not useful to any other agents. From there, it depends on how precisely an agent wants to identify resources: eg by specific location within a warehouse, which could include warehouse, room, aisle, row, tier.

Or if it's in your kitchen, cabinet and shelf?

Do the IRIs you posted relate to any info that could be used by humans to identify resources?

**Comment by elf-pavlik** [comment]
> The warehouse robot needs to know where to find the resource. No other agents need to know that.
> From there, it depends on how precisely an agent wants to identify resources: eg by specific location within a warehouse, which could include warehouse, room, aisle, row, tier.
> Do the IRIs you posted relate to any info that could be used by humans to identify resources?

Application acting as client should consider IRI as opaque identifier, so it can't get any information but decomposing it in some way. I only needs to know how to use that IRI to get information about it from some specific dataset. Information it gets from that dataset can have location, possession, ownership and any other details.

**Comment by fosterlynn** [comment]
>We could denote that resource by IRI starting with urn:uuid: as well, which doesn't belong to anyone's namespace.

Doesn't that have to resolve to some namespace though?

>Nothing stops Dan from owning a resource denoted by IRI in alice: namespace.

That seems impractical at best.  People need access to data about resources they have some role in relation to.  And need to have some control over that access and the availability of the data/server, possibly including for update.

But, also, I'm not sure that namespaces are really the key aspect of the problems in the model @bhaugen was trying to address... duplicate give/take events, exact reference to provider and receiver resource identifiers in a transfer.

**Comment by bhaugen** [comment]
@elf-pavlik Lynn explained my focus in the original post in this thread very well. I'll add one other point and then we are off for our morning walk:
> Do the IRIs you posted relate to any info that could be used by humans to identify resources?

> Application acting as client should consider IRI as opaque identifier, so it can't get any information but decomposing it in some way. I only needs to know how to use that IRI to get information about it from some specific dataset. Information it gets from that dataset can have location, possession, ownership and any other details.

I understand all that, but in an independent view, the agents involved don't actually need any IRIs identifying resources, all they need is the pieces of information they use to indirectly identify the reousrce involved in a transfer, and then they will identify it internally however they want. The transfer event has that information on its face. They don't need to dereference an IRI to find that information.

**Comment by fosterlynn** [comment]
Anyhow, I think that the concept of thinking squarely in the "independent view" as the REA people think of it has a really good possibility of resolving a lot of what we have been wrestling with.  If we can do that by using logical identifiers instead of a direct resource reference, that would be awesome.  So I'd like to try again to make a transfer into one record, and see if that brings forth any nasty unintended consequences.

**Comment by elf-pavlik** [comment]
> Doesn't that have to resolve to some namespace though?

`urn:uuid` doesn't have resolution mechanism defined

> That seems impractical at best. People need access to data about resources they have some role in relation to. And need to have some control over that access and the availability of the data/server, possibly including for update.

It requires clarifying when we talk about some thing eg. economic resource like 10kg of apples somewhere, and when we talk about digital (web) resources which one can have read or write access to. The second one - we resource - can describe the first - physical thing. They both have IRI denoting them, while agent may want to have IRI denoting the digital (web) resource in namespece their control, it doesn't matter what IRI they use to denote the physical thing. I'll follow up on that ASAP

> @bhaugen was trying to address... duplicate give/take events, exact reference to provider and receiver resource identifiers in a transfer.
> So I'd like to try again to make a transfer into one record, and see if that brings forth any nasty unintended consequences.

In all my examples one have transfer of ownership happening as one flow involving one and only one resource. I don't see requirement to have involved resource (physical thing) denoted by IRI in namespace controlled by agent who owns it. That agent will have in one's namespace digital resources that describe that physical thing. This applies even more to cases like #365 where one physical resource can have quantities of it owned by many different agents. Still process can move the whole resource from place A to place B (eg. evacuation due to flooding) and treat it as one physical resource which quantities stay owned by any number of agents.

My examples don't use *give* & *take* and don't have that duplication issue and have one flow for transfer that involves one and only one resource (specific quantity of it in case of ownership).

**Comment by fosterlynn** [comment]
>I think, in general, VF should represent the independent view, since its purpose is to communicate between apps, but that is part of what is up for discussion in this topic.

I do agree with generally taking the independent view.  But VF is also currently being used as a vocab between a backend and a frontend, so that those can be mixed and matched.  In that case, it may not be so "independent".  This may or may not be a problem with handling transfers as you suggest @bhaugen , just noting so we can make sure that is handled in some way.  Might be that a direct reference to the provider's resource plus the resource logical identifying fields would be sufficient.

>It requires clarifying when we talk about some thing eg. economic resource like 10kg of apples somewhere, and when we talk about digital (web) resources which one can have read or write access to. The second one - web resource - can describe the first - physical thing. They both have IRI denoting them, while agent may want to have IRI denoting the digital (web) resource in namespece their control, it doesn't matter what IRI they use to denote the physical thing. I'll follow up on that ASAP

I'm interested in understanding this better.  How would you relate those two "resources"?  Or, do you really want to consider them 2 resources, or another identifier for the same resource?  And can something like this work in non-rdf situations?

**Comment by elf-pavlik** [comment]
In https://github.com/valueflows/valueflows/pull/497#discussion_r284006000 we have related interesting aspect. Which namespace do we use (if any) for IRIs denoting the transfer flow (thing) itself. I think whenever we have flow with different *provider* and *receiver* both agents will want to have their own copy accessible in their own namespace (agent centric). In linked example I used trusted 3rd party `notary:` namespace for IRI denoting the flow thing itself. Both alice and bob will have their own records describing that flow in `alice:` and `bob:` accordingly. I don't think we should try to draw any conclusions just from the namespace used for IRI, in most cases we should assume that `urn:uuid:` could have been used which doesn't have resolution mechanism defined.

**Comment by fosterlynn** [comment]
> I think whenever we have flow with different provider and receiver both agents will want to have their own copy accessible in their own namespace (agent centric).

Agree.

>I don't think we should try to draw any conclusions just from the namespace used for IRI

Agree.

**Comment by fosterlynn** [comment]
Resolved for now, can revisit if needed after current round of projects.
