### ISSUE TITLE
break out lot

### ISSUE THREAD

**Issue by fosterlynn** [valueflows/valueflows#513]
Right now we have trackingIdentifier for lot, serial number, or any other identifier needed for tracking/tracing.  I would like to break out lot, which may have other information about it, such as expiration date.  This is inspired by our talks a few months ago with OFN / DFC and mapping their model with ours.

If possible, I would like to just use their model as is, or if that is not ready, just steal that part.

Will investigate with them.  But started the issue in case it affects how we think about resource identifiers.

**Comment by fosterlynn** [comment]
Found the documentation from DFC vocabulary with properties: https://github.com/datafoodconsortium/ontology/blob/master/DFC%20-%20Concepts%20Properties.pdf.

Here is what they have for lot (called ProductBatch)
![product-batch](https://user-images.githubusercontent.com/3776081/58551559-e6b2b780-81d5-11e9-8f43-8739e3139824.png)

I like this structure, and it comes from their experience with food, probably the most picky type of resource when it comes to lot tracking.  We can carry production date as a derived property, it would be useful rather than tracing the value flow of a resource.  Expiration date is required for food and possibly other things.

To discuss: The naming is somewhat an issue for us I think.  "Product" is a bit limiting, and we have thus far stayed away from it.  From mirriam-webster:
```
(1) : something produced especially : commodity sense 1
(2) : something (such as a service) that is marketed or sold as a commodity 
```
So, it definitely has a tinge of destined for the market as a commodity, although also possibly doesn't have to mean that.

`batchNumber` isn't always a number ("identifier" seems better), but seems like not a big deal.

I have mostly heard "lot" rather than "batch" but don't have enough experience, pinging @bhaugen .  Is there a best general term, not specific to food?

Possible other issue: does pointing to the DFC vocabulary cause confusion because it is a food vocabulary?

I am leaning towards using their structure but defining our own names as needed.  So it would be a part of vf.  Even though in general, we do try to reuse rather than redefine.  And I am fine with either decision.

**Comment by bhaugen** [comment]
@fosterlynn 
> I have mostly heard "lot" rather than "batch" but don't have enough experience, pinging @bhaugen . Is there a best general term, not specific to food?

I just [searched the US FDA](https://search.usa.gov/search?utf8=%E2%9C%93&affiliate=fda1&sort_by=&query=lot+batch&commit=Search) and they seem to use both.

Also found https://www.fda.gov/media/85366/download which says:
> Regulatory Definition of “Lot”
21 CFR 210.3
Lot - a batch, or a specific identified portion of a batch,
having uniform character and quality within specified
limits; or, in the case of a drug product produced by
continuous process, it is a specific identified amount
produced in a unit of time or quantity in a manner that
assures its having uniform character and quality within
specified limits.

[SAP (probly most used ERP system) says](https://answers.sap.com/questions/6792746/difference-between-lot-and-batch.html) that lot comes from inspection and batch comes from production.

[Batch production records can also refer to recipes](https://www.instantgmp.com/resources/mpr-bpr-defined/):
> Master Batch Records, also known as Master Manufacturing Formulas, are general manufacturing instructions....
Batch Production Records are copies the Master Batch Record. The BPR record documents when, how, by whom, with what tools and in what environment a product was produced. The Batch Record is where operators record specific lot numbers as well as the specific weights, measure or count of ingredients and components actually used to produce that specific batch.

Here's a [list of international regulations and standards](https://www.mastercontrol.com/21_cfr_regulations/regulations/) about these topics. Bewildering!
