### ISSUE TITLE
how to reference uri's in examples

### ISSUE THREAD

**Issue by fosterlynn** [valueflows/valueflows#514]
Want to figure out how to represent our @id's in examples.  This came out of the discussions that spawned urn:uuid references in the examples, and the work on what all this would look like in a distributed environment, triggered mostly by discussing transfers and resources.

I think the examples shouldn't assume distributed data architecture, and should not show records replicated in different namespaces.  But as long as we don't add layers of jargon, I'd like to express them in ways that people doing distributed architecture can benefit from.  And I don't like the way I've been using namespaces in the @id's because of this, when a record will be replicated in different agents' namespaces.

Starting investigation, from wikipedia: https://en.wikipedia.org/wiki/Uniform_Resource_Name, excerpts:

URNs were distinguished from URLs, which identify resources by specifying their locations in the context of a particular access protocol, such as HTTP or FTP. In contrast, URNs were conceived as persistent, location-independent identifiers assigned within defined namespaces, typically by an authority responsible for the namespace, so that they are globally unique and persistent over long periods of time

Since RFC 3986[5] in 2005, use of the terms "Uniform Resource Name" and "Uniform Resource Locator" has been deprecated in technical standards in favor of the term Uniform Resource Identifier (URI), which encompasses both...  A URI is a string of characters used to identify a name or resource. URIs are used in many Internet protocols to refer to and access information resources. URI schemes include the familiar http, as well as hundreds of others. 

In the "contemporary view", as it is called, all URIs identify or name resources, perhaps uniquely and persistently, with some of them also being "locators" which are resolvable in conjunction with a specified protocol to a representation of the resources.

Other URIs are not locators and are not necessarily resolvable within the bounds of the systems where they are found. These URIs may serve as names or identifiers of resources. Since resources can move, opaque identifiers which are not locators and are not bound to particular locations are arguably more likely than identifiers which are locators to remain unique and persistent over time. But whether a URI is resolvable depends on many operational and practical details, irrespective of whether it is called a "name" or a "locator". In the contemporary view, there is no bright line between "names" and "locators".

**Comment by elf-pavlik** [comment]
I think we shouldn't put any requirements what kind of IRIs (internationalized URIs) get used. I don't mind to always use `urn:uuid:` wherever we denote instances of VF classes. In examples of how one could have different datasets with documents describing some common instances of VF classes, I would still use `https:` IRIs to denote those documents (`@id` of a `@graph` in my examples).

**Comment by fosterlynn** [comment]
Done.
