### ISSUE TITLE
Value adding service

### ISSUE THREAD

**Issue by elf-pavlik** [valueflows/valueflows#516]
I put this into composition milestone.

Thinking here mostly for projects which do things like
* processing
* distribution
* etc.

Currently often they get ownership of inputs and then give ownership of outputs. In case of processing we have transformation, in case of distribution we have just movement and other logistics like handling agreements.

I think such projects should have a way to define their services (which they believe 'add value') and stay able to provide those services not matter how ownership aspect gets handled.
* they can own all intputs and all outputs
* others agent can own all inputs and all outpus
* etc.

This possibly could affect how they define recipes, for example ownership transfers wouldn't appear in those recipes since same operational recipe could work with all kinds of approaches to handling ownership.

I think this relates to #515 where I suggest pure transfers wouldn't relate to processes so would also not relate to recipes. Movement (physical and virtual shipping) related flows could appear in processes. This applies mostly to *ownership*, various processes require presence of physical resources so *possession* may play role here.

NOTE: issue name refers a little bit to https://en.wikipedia.org/wiki/Value-added_tax

**Comment by fosterlynn** [comment]
>I put this into composition milestone.

I still don't see why service implies composition.  I'm OK waiting though, unless we need to include this in the transfer discussion to get that resolved?

**Comment by elf-pavlik** [comment]
For transfers of ownership I think it just gives another reason why they probably shouldn't appear in I -> P -> O chains. Same I -> P -> O chain can occur with all kind of different transfers of ownership happening orthogonal to that chain.

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/valueflows/-/issues/516.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
