### ISSUE TITLE
Currencies as units vs resource classifications

### ISSUE THREAD

**Issue by fosterlynn** [valueflows/valueflows#517]
We have had a bit of discussion on this in some issue that I can't find easily now.  It doesn't affect the vocabulary directly, it only affects examples.  And it also affects the mapping of VF to existing or new applications, which I tend to be involved with somewhat regularly right now.

I believe @elf-pavlik has the opinion that currencies should be resource classifications, not units.  I think this is because the conversion between currencies is very different than conversions between say volume or weight units, which are fixed, while currencies fluctuate all the time.  Please elaborate or correct!

We did it both ways at Sensorica, and my conclusion at that time was that it is best if currencies are units.  But I haven't been very solid on that conclusion, and was thinking it wasn't critical either way for VF.

Now I'm seeing it would be good to make a considered decision so that people can easily coordinate between their apps.  

I'm also thinking again that it would be good to make the currencies units, which leaves the resource classification/specification for things like "social wallet", "bank account", "virtual account", "wallet address", etc.  People will need to define this somewhere.

We got one quick opinion from Cheryl Dunn, one of the core REA academics, agreeing with that, and it would be good to get some more. She said "I would say that the resource type would the account (crypto-currency wallet, bank account, etc.) and that the currencies would be units of measure. This is really the first I’ve thought about it, but that approach is consistent with how we’ve handled cash accounts in the past and various measurements such as foreign currency translation."

Another good resource might be to see how the Unit of Measure ontologies/taxonomies and key web taxonomies think of it.

**Comment by gcassel** [comment]
I don't have time to think about this, but FYI it seems to me that *currency* should be a resource classification, but to responsibly *define that class* (the currency) we must define (1) how units are created and (2) how new units are initially allocated/ assigned.

**Comment by elf-pavlik** [comment]
> I believe @elf-pavlik has the opinion that currencies should be resource classifications, not units. I think this is because the conversion between currencies is very different than conversions between say volume or weight units, which are fixed, while currencies fluctuate all the time. Please elaborate or correct!

Yes, units can have stable conversion algorithms, currencies not. Currencies could have something in lines of 'exchange rates' but same applies to peanuts & olive oil which we would not define as units.
I think currencies should always have `unit:Number` since they always act as numeric units.

Also in Proposals, one would reference Intents to *provide* and *receive*, here often classifications (sometimes specifications) play important role. Systems should work just with matching on classifications and specifications. Once they discover match they would take next step to compare demand (intent to receive) and supply (intent to provide) where quantities and units could come into play. In that case units conversion would 'kick in' where algorithms would rely in those stable conversion rates.

 > I'm also thinking again that it would be good to make the currencies units, which leaves the resource classification/specification for things like "social wallet", "bank account", "virtual account", "wallet address", etc. People will need to define this somewhere.

This sounds to me more like classifying the storage not the stored resource. Again with virtual resources like currencies it seems to get more blurry. If we look at physical resources olive oil could have flows which use `unit:Liter` while it gets stored in barrels or tanks or bottles or metal cans etc.

While I don't see currency classifications in no way used as units. I think we need to address distinguishing between classifying resource and how it stays stored. This could possibly translate directly to the requirement to classifying virtual entities like currency accounts (storage) and currencies ('resource').

**Comment by elf-pavlik** [comment]
One more note on matching intents when working with proposals. IMO if classification matches eg. Olive oil, we should get match not matter what units get used. One could in many cases convert units, even if one intent uses `unit:Kilogram` and other `unit:Liter` (it requires knowledge density of olive oil). I don't think different unit should result in non-match conclusion.
I really see that for algorithms dealing with converting unit, data which tries to stick currency classifications there would just cause issues.

> We got one quick opinion from Cheryl Dunn, one of the core REA academics, agreeing with that, and it would be good to get some more. She said "I would say that the resource type would the account (crypto-currency wallet, bank account, etc.) and that the currencies would be units of measure. This is really the first I’ve thought about it, but that approach is consistent with how we’ve handled cash accounts in the past and various measurements such as foreign currency translation."

Did their implementations also handled actual unit conversion (based on stable rules) ? Starting from simple ones like Liter to m3, and going into more complex like ones that require knowledge of resource density. From my limited knowledge of REA I would guess that they only do basic inventory accounting , and don't get into planning processes (including transformations) or matching intents.

**Comment by bhaugen** [comment]
@elf-pavlik 
> From my limited knowledge of REA I would guess that they only do basic inventory accounting , and don't get into planning processes (including transformations) or matching intents.

Most REA practitioners are academics and do not build or use operational systems.

But Bill McCarthy and his close collaborators are deep into planning and transformations, but not so much into matching intents.

Bill was the chair of the Automotive Industry Action Council supply chain committee for some years, which was very much concerned with planning, and not at all about inventory.  Workday, the only commercial REA software that I know of, focuses on "human resources" and associated financial accounting; again, no inventory.

**Comment by fosterlynn** [comment]
>One more note on matching intents when working with proposals. IMO if classification matches eg. Olive oil, we should get match not matter what units get used.

This is interesting.  Seems to me that in some cases you are exactly right, and in some cases people will want only specific sizes or specific containers.  I picture very different kinds of intent matching features and algorithms, depending on the situation.  And in the case of search, people can enter the degree of match they want, like "olive oil" or "olive oil glass bottle".

>> I'm also thinking again that it would be good to make the currencies units, which leaves the resource classification/specification for things like "social wallet", "bank account", "virtual account", "wallet address", etc. People will need to define this somewhere.

>This sounds to me more like classifying the storage not the stored resource. Again with virtual resources like currencies it seems to get more blurry.

I do see your point on container vs the resource itself, and also on the conversion differences.  But I also agree that currencies do get more blurry - they are a different creature in many ways.

> I think we need to address distinguishing between classifying resource and how it stays stored. This could possibly translate directly to the requirement to classifying virtual entities like currency accounts (storage) and currencies ('resource').

It is possible we are missing something that will deal with these concepts, even possibly both for currencies and physical resources.  I'll try to do some research.  We definitely will need to know the difference between a social wallet and a bank account and a virtual account, somewhere in the vocabulary.

**Comment by fosterlynn** [comment]
Some beginning investigation:
* Good Relations (and schema.org which has pulled in the GR vocab) have currencies as separate from both units and their version of various resource types.  In addition, they treat pricing separately, not as one of many resources.  So they are of no help for our model.
* QUDT has every currency defined as a unit, specifically a currencyUnit.  (The best way to get complete QUDT definitions is through their 1.1 version, since the 2.0 version continues to be incomplete.  Go to www.qudt.org, and take link for QUDT Catalog Release 1.1.)

**Comment by fosterlynn** [comment]
More investigation on containers: QUDT doesn't have much of anything on containers, and in general very little "business" stuff, with their primary focus on scientific needs.  On the other hand, here is a partial list of ISO units https://t3.apptrix.com/syteline/Language/en-US/fields/i/iso_um_ums.htm (the complete list is behind a paywall, grrrrr).  They have things like "55 gallon drum", "500 Kilogram Bulk Bag", "Super Bulk Bag", "Bale", "Bottle", "Ten-pack".

**Comment by fosterlynn** [comment]
A little more investigation:  

OM (Ontology  of  units  of  Measure), which is one of the quantity ontologies I thought we might want to use instead of QUDT), also has currencies as units.  

ISO has the currencies separated off in a separate standard https://en.wikipedia.org/wiki/ISO_4217.

Wikidata considers "currency" to be a subclass of "unit of measurement" among others.  It also considers "United States Dollar" to be an instance of "currency" among others.

**Comment by elf-pavlik** [comment]
I don't think any of the vocabs you mention tries to meet any of VF requirements. I could extract them in clearer format from my previous comment: https://github.com/valueflows/valueflows/issues/517#issuecomment-504752274

Eventually when we have implementations meeting those requirements we could evaluate how those different approaches would impact those implementations. I don't think we should try to decide it purely on hypothetical discussions.

**Comment by fosterlynn** [comment]
>I don't think any of the vocabs you mention tries to meet any of VF requirements.

Not sure what this means?  I looked at e-commerce vocabs, and quantity-unit vocabs.  Other suggestions welcome.

My conclusion at the moment is that most everyone does currencies as units of measure, and I would propose we follow that lead, even if they are not convertible in the same stable way as pounds to kilograms.  However, this doesn't necessarily mean that a bank account or wallet address is appropriate as the resource classification or specification of the resource.  I do think I understand your objection to that: I want to send 100 USD, I don't want to send 100 bank accounts.  I'm still thinking about this "container" aspect.

>Eventually when we have implementations meeting those requirements

I am working with a couple use cases that are crypto related.  One of them intends to support all kinds of resources in their new project, but we have started mapping to their current crypto app, which supports several existing crypto currencies as well as what they call "social currencies", which can be created by any agent.  I can share the mapping we are doing when we get more going (hopefully this week?) and I'll ask how they think about the question. The other wants to provide a way for coops and other groups to issue shares to other agents in exchange for currency, so the coops have a way to raise funds before they can make it without that up-front boost.  But not as speculation, just as support.  These shares can also be traded after they are first issued.  They already have an alternative bank which this will be a service of.  I need to find (and re-read) the white paper.  Not sure when they will actually get going on the phase we will be part of.

**Comment by fosterlynn** [comment]
>>Eventually when we have implementations meeting those requirements

>I am working with a couple use cases that are crypto related.

Actually, Sensorica implemented those requirements.  We tried it with the currency as the resource type, and then with the currency as the unit of measure so that we could define "virtual account" containedIn "bank account".  They both actually worked fine internally to the network, as long as everyone defined currencies in the same way.  We didn't have the situation of trading electronically with another non-NRP network.

**Comment by elf-pavlik** [comment]
> Actually, Sensorica implemented those requirements.

How does their logic work when it comes to matching intents? They can't just match based on the unit because unit:Kilogram doesn't really give much of a reason to match. What classification / specification they use for intents (or flows in general) with currencies?

**Comment by fosterlynn** [comment]
>>Actually, Sensorica implemented those requirements.

>How does their logic work when it comes to matching intents?

Sensorica doesn't do intents that involve currencies, only hours/skills.  You have a good point in terms of intent matching, you brought that up before, but I had lost it.  Mostly currencies will be on the reciprocal side, which would play a secondary role in matching, but still your point is well taken.

>What classification / specification they use for intents (or flows in general) with currencies?

You'll see a lot of duplication between the resource types and units. Partly this is because they both need to support accounts and just cash in your pocket.  Partly it is probably because it is confusing how to assign the data.  Both Sensorica and Freedom Coop do need to know what kind of account some things are for internal logic.  But neither does intent matching on currencies.

Resource types:
![sens-money](https://user-images.githubusercontent.com/3776081/60402150-50b1da00-9b51-11e9-8847-28c846f68c1a.png)

Here are their units:

![sens-units](https://user-images.githubusercontent.com/3776081/60402166-99699300-9b51-11e9-8000-9a64f5a73853.png)

From Freedom Coop:
Resource types:
![ocp-rts](https://user-images.githubusercontent.com/3776081/60402230-5a880d00-9b52-11e9-8df3-d1c772810c7a.png)

Units (a few extra, can't filter):
![ocp-units](https://user-images.githubusercontent.com/3776081/60402233-6542a200-9b52-11e9-8e25-93c1e7b7c419.png)

**Comment by fosterlynn** [comment]
One way I can see to do the resource classification/specification: Use `containedIn` for the currency and the account, both of which would be resources and resource classifications/specifications.  Like (loosely specified)

```yaml
  - '@id': group:fbff9852-36ca-4364-a943-bc0b49e1cab5
    '@type': EconomicResource
    classifiedAs: Virtual Account
    currentQuantity:
      qudt:unit: unit:Number
      qudt:numericValue: 1

  - '@id': group:fbff9852-36ca-4364-a943-bc0b49e1cab4
    '@type': EconomicResource
    classifiedAs: FairCoin
    currentQuantity:
      qudt:unit: unit:FairCoin
      qudt:numericValue: 1000
    containedIn: group:fbff9852-36ca-4364-a943-bc0b49e1cab5
```

Another is to use the ability to have more than one resource classification.  Something like this, or maybe with more careful use of specification.
```yaml
  - '@id': group:fbff9852-36ca-4364-a943-bc0b49e1cab4
    '@type': EconomicResource
    classifiedAs: 
       - FairCoin
       - Virtual Account
    currentQuantity:
      qudt:unit: unit:FairCoin
      qudt:numericValue: 1000
```
 Thoughts?

**Comment by elf-pavlik** [comment]
If Sensorica has 'resource type' for each currency, why don't they use 'each'? (or whatever NRP uses for unit:Number). Same for FreedomCoop, which logic wouldn't work with just 'resource type' and 'each' unit for currencies?

No thoughts about classifying resource containers yet, though with approach to transfers I propose the 'virtual accounts' would just work as ownership shares which don't require moving credits between accounts to keep track on them.

**Comment by fosterlynn** [comment]
>If Sensorica has 'resource type' for each currency, why don't they use unit 'each'? (or whatever NRP uses for unit:Number). Same for FreedomCoop, which logic wouldn't work with just 'resource type' and 'each' unit for all the currencies?

I don't know, it seemed more clear to them I guess.  Possibly also because they do have resource types that are different than just the currency also.

>No thoughts about classifying resource containers yet, though with approach to transfers I propose the 'virtual accounts' would just work as ownership shares which don't require moving credits between accounts to keep track on them.

But isn't my virtual account basically a resource to me?  Doesn't seem like the banking mechanism should make a difference, to me.  Otherwise where do you stop?  Is an address in a crypto wallet a share or a resource?  I think all things that consider themselves shares are just resources.

**Comment by elf-pavlik** [comment]
Responding to the original topic of this issue. Unit should have no responsibility in expressing *what kind of resource* we deal with, it should stay responsible for expressing *how do we measure it*.

IMO trying to stick kind of currency into unit mixes those two things.

Also classification / specification should refer to what quantity resource describes. If we have number, 450 we don't talk about 450 social wallets.

**Comment by fosterlynn** [comment]
In this ongoing quest, I'm recording another REA academic opinion (Wim Laurier), in answer to my written question.  Still just collecting information at this stage.

Also he mentioned verbally that sometimes people want to know the unique identifier of a bank note.  I think this also applies to crypto coins when doing transfers in the depths of the code?  I hadn't taken that into consideration for the vocab before, and am still not sure about it.  May learn more when we get going on the work with the crypto people doing a "social wallet", now starting in Sept.

Written question and answer:
When you have events (or commitments) involving a currency, do you consider the currency (Euros, BitCoin, etc.)  to be the resource type or the unit of measure (or both)?  If the resource type, is there any way to say something like “bank account”, “wallet address”, etc. as a resource type (also useful info)?
1. I believe I fully get your question after reading it :)
2. $,€, £ are units of measure
3. Bank account, bank note, coin, bank transfers are resource types

**Comment by fosterlynn** [comment]
Current conclusion:  Currencies should be resource specifications or classifications, not units.  So I am now agreeing with @elf-pavlik on his points above in this issue.

Based on:
* That does seem semantically more correct, although it is somewhat subtle
* Intent matching is on resource specifications/classifications, and there might be reason to match on a currency, for example in crowdfunding, or when people have a specific currency to "spend"
* We can use vf:containedIn to define resources that are accounts with types like "virtual account", "bank account", "crypto wallet", etc.  So "crypto wallet" is a type of resource, "FairCoin" is a type of resource, and specific FairCoins can be containedIn a specific wallet.
* Probably all Units have actually been defined (for our practical purposes), but all types of currencies have definitely not all been defined

I'll check the examples and see where things need to be adjusted for this conclusion (I think mostly they are this way).  Any objections, please let me know!

**Comment by iPlumb3r** [comment]
Just working on the same subject at this moment : currencies 

Trying to apply to his subject « lessons learned » on the « INT vs EXT » dichotomy …
(In the context of the « Ecosytem Mapping » initiative : https://github.com/iPlumb3r/EcosystemMapping) … which state that an ITEM/individual always belongs to more than only 1 TYPE/Class

And at least, it belongs to 
   - 1 « Intentional » TYPE/Class
AND
   - 1 Extensional » TYPE/Class
(But could belongs to more than 2 TYPES/Classes)

Where
   - INT is related to the « DO » ASPECT/Facet => What the thing « DOES »
   - EXT is related to the « BE » ASPECT/Facet => What the thing « IS »
> And each thing in the map (i.e. semantic network) DO something AND BE something « at the same time » !

More about this approach here : 
   - Short explanation : https://github.com/iPlumb3r/EcosystemMapping/blob/master/1_Semantic/About_Intentional_VS_Extensional_Dichotomy_EN.md
   - Basic Use Case : https://github.com/iPlumb3r/EcosystemMapping/blob/master/0_UseCases/Bob_develops_SmartphoneCase_EN.md
   - Current Model in the contexte of « Ecosystem Mapping » : https://github.com/iPlumb3r/EcosystemMapping/blob/master/6_Ontologies/OWL-Ontology.md

![Capture d’écran 2020-06-07 à 13 35 36](https://user-images.githubusercontent.com/46555634/83968051-ab59c700-a8c6-11ea-97e7-542b15154bcb.png)

Some exemples in the following schema, where we could see how this model works …

![Capture d’écran 2020-06-07 à 13 45 18](https://user-images.githubusercontent.com/46555634/83968151-6eda9b00-a8c7-11ea-8c97-d2d57819bebb.png)

In this exemple the ITEM/Individual « Dollar » belongs to :
   - 2 Intentional TYPES/Classes : « Mean Of Exchange » AND « Unit Of Measurement »
   - 2 Extensional TYPES/Classes : « Product» (Bills & Coins) AND « Digital Record » (Scriptural Money of Commercial Bank)

**Comment by fosterlynn** [comment]
Thanks @iPlumb3r , will study more and take a peek at your links.  And maybe be able to talk about correspondence and mapping around currencies a bit better once I do.  Anyhow, I'm always interested to see what you are working on.  Immediate thoughts:

>This example shows that most of the time talking about "XXX Type" totally overwrites things from a semantic point of view, because it presupposes that a thing can only belong to one category and ONLY one category ...
... which is usually totally incorrect because things naturally belong to many categories "at once" !

Yes, agree about things belonging to many categories.  But also we have a practical need for people to be able to know that they have the same understanding about some thing when communicating or interacting, which people would often call a "type" (we don't, since we don't use that word, but it is one definition that specifies what something is to the level of granularity that is low enough to be clearly understood for the purpose at hand); or in some cases the actual instance identification is needed for people to know what something is, like a painting or document for example.  Otherwise people can't easily trade with each other, or follow a recipe to make something reliably.  So our model tends to follow along with facilitating economic practices on the ground.  Multiple categories can also facilitate economic practices, for example intent matching or searching - and a good conceptual structure is very helpful for that, although we have chosen not to do that within VF, just refer to other categorization or classification schemes.

Bill McCarthy has a nice write-up somewhere about the concepts "typify" and "groupify".  Thought we had that in an issue but I don't find it.  You probably get the idea though, "typify" is like "type" where a resource has only one defined; "groupify" I think includes the kind of categorizations you are modeling in the INT and EXT.  Maybe the purple diamonds in the middle are "typify"?  At least in the currency picture they seem to be?

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/valueflows/-/issues/517.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
