### ISSUE TITLE
owl:inverseOf

### ISSUE THREAD

**Issue by elf-pavlik** [valueflows/valueflows#52]
I will use this issue to explain various nuances of owl:inverseOf
- http://richard.cyganiak.de/blog/2006/06/an-rdf-design-pattern-inverse-property-labels/
- `https://github.com/mnot/I-D/issues/39#issuecomment-89789736`

In examples which I added I use only single instance of rdf:Property - _vf:member_
- https://github.com/valueflows/agent/blob/master/examples/hackers4peace.jsonld#L13-L15
- https://github.com/valueflows/agent/blob/master/examples/elf-pavlik.jsonld#L14-L17

As I understand @ahdinosaur currently uses in holodex two different properties _hdx:hasMember_ and _hdx:isMemberOf_. To formalize that they have **exactly the same semantics**, but only reverse position of _rdf:subject_ and _rdf:object_ in _rdf:Statement_, one can use _owl:inverseOf_

I see need to explore those two ways of approaching the issue. As I see it now it may not make major difference when one traverses the graph, but it may complicate querying it by matching graph patterns!

With defining only one property on vocabulary level, both individual and group will have a single way to describe member relations

![member](https://docs.google.com/drawings/d/1pi6iy2vPXlEq_Y05ANOkf8YxeOD_lLbYFVfk3Z48oJM/pub?w=1237&h=567)

With defining both directions on vocabulary level, we end up in situation where individual and group can describe their relation in 3 different ways!

 ![member-inverse-a](https://docs.google.com/drawings/d/1b1_xeJwwYFfO3f-K76wvRqqwI9v-aJ6hh7eO-cibflc/pub?w=1237&h=567)

![member-inverse-b](https://docs.google.com/drawings/d/1UBCbgFKDbs_GSFZXBKQvOPprF6yzx7L1mjPCAIM-Sq4/pub?w=1237&h=567)

![member-inverse-c](https://docs.google.com/drawings/d/1ana7ep9uXh0zb2AUn1MPXDZ8hK7zuzXWNV8pdZ7n4ZI/pub?w=1237&h=567)

1) Please notice that last diagram (using only _hasMember_) differs from the very first one (_member_) only by naming of the property/predicate.
2) While from given individual perspective of given group perspective it may make more sense to use _hasMember_ or _isMemberOf_ in statements. When we describe something from 3rd person perspective, we can choose directions very arbitrary.

**TODO** explain difference when [used with Collections](https://github.com/w3c-social/social-vocab/wiki/Verbs---owl:Class-vs.-rdf:Property#collections)

**Comment by bhaugen** [comment]
@elf-pavlik - how does this relate to https://github.com/valueflows/exchange/issues/2 and https://github.com/valueflows/agent/issues/7?

We will have lots of things (for want of a better word) where one end lives with one agent and the other lives with another: relationships between agents, transfers between agents, agreements among agents, etc etc. In many cases, those things have the same semantics (as you described), just different views from different directions. If they could literally live in the ether (notice I did not say cloud), only one thing would be necessary. In an intended total decentralization, each agent involved will get their own copy.

So it's a pattern we should understand deeply before we go too much farther...

**Comment by elf-pavlik** [comment]
@bhaugen I would like to propose this topic here for the agenda of our next meeting! Actually I see danger that defining both directions on vocabulary level (which doesn't stop someone from [aliasing reverse properties in some specific customized JSON-LD context](http://www.w3.org/TR/json-ld/#reverse-properties)), can make reasoning over the dataset more complex. We will compare it on particular examples but IMO it may come even more prominent when we will get to transfers, exchanges (conditional bidirectional transfers) etc. I just want to make sure we document all the pros and cons of those two approaches which we all can find together (of course more will pop up in the future), and do our best to weight this choice in responsible way.

**Comment by elf-pavlik** [comment]
@ahdinosaur @fosterlynn @bhaugen I added some more pictures, do you think it helps illustrate the issue?

**Comment by ahdinosaur** [comment]
@elf-pavlik yes, thank you. :smiley: i'm not sure i'll be able to make a decision until a) it's been in the back brain for a while, and b) i have more hands-on experience through working on a real app that uses relationships heavily, i.e. Holodex.

**Comment by bhaugen** [comment]
Let's start an agenda for the next meeting and put this on it. There #56, I just did it.

**Comment by ahdinosaur** [comment]
[Holodex's relationship type data](https://github.com/holodex/enspiral-data/blob/compost/relationshipTypes.csv) is an example of defining both directions of relationship types. notice that we give each direction a different color, would work with either option but something to think about it.

---

@elf-pavlik if you only define one side of a relationship, is it possible to reference either side by `@id` without using a [JSON-LD specific construct like `@reverse`](http://www.w3.org/TR/json-ld/#reverse-properties), or does this vocab depend on using JSON-LD? in my app's code i'd want to be able to reference either side with a single `id` that we can use to lookup, would it be appropriate to say `dex:relationshipTypes/stewards#inverseOf`?

**Comment by ahdinosaur** [comment]
ah, seems you'd reference the other direction via its [blank node IRI](http://json-ld.org/spec/latest/json-ld-rdf/#blank-node).

**Comment by elf-pavlik** [comment]
> in my app's code i'd want to be able to reference either side with a single id that we can use to lookup, would it be appropriate to say dex:relationshipTypes/stewards#inverseOf?

@ahdinosaur can you please point me to this line in your code? thanks!
Speculating in my mind, once you can get reference to the definition of relationship which exists in vocab, it could have some interface defined to reference it's inverse e.g. `relationships['member'].inverse().label

also `dex:relationshipTypes/stewards#inverseOf` seems to me like asking to causing some major confusions!

**Comment by fosterlynn** [comment]
>ah, seems you'd reference the other direction via its blank node IRI.

@ahdinosaur yes when I coded the NRP data feed, that is how it worked, although I'm still using the one relationship rather than two, so it's not exactly the same example.  The way the library we're using works is that you give the graph rdf triples, and it generates whatever format you want.  So here just in case it helps, and if not, please ignore:

This is the sort of thing that comes out of the first pass from triples:

{
  "@context": {
    "owl": "http://www.w3.org/2002/07/owl#",
    "rdfs": "http://www.w3.org/2000/01/rdf-schema#",
    "rdfs:label": {"@container": "@language"}
  },
  "@graph": [
    {
      "@id": "http://example.org/ns/mentor",
      "owl:inverseOf": {"@id": "_:b1"},
      "rdfs:label": {"en": "mentors"}
    },
    {
      "@id": "_:b1",
      "rdfs:label": {"en": "is mentored by"}
    }
  ]
}

Then you run it through a method that combines it based on the _:b1 blank node.  If you want to look at the code, it is here: https://github.com/valnet/valuenetwork/blob/master/valuenetwork/valueaccounting/views.py, search for "def simplyframe".

**Comment by ahdinosaur** [comment]
> @elf-pavlik says: @ahdinosaur can you please point me to this line in your code? thanks!

Holodex is in the middle of a major re-write, so once we're further along i'll have a better understanding of what we need and can point to specific lines of code. for now, in general the concept we're going with is to have [a plain object singleton store](https://github.com/holodex/app/blob/2e10a44d7f98e4c1b37a74b727274db825f72686/src/node_modules/state/index.js) that we access with per-domain getters (e.g. [relationship-type/getters](https://github.com/holodex/app/blob/compost/src/node_modules/relationship-type/getters.js)).

@fosterlynn thanks for the example on how you did blank nodes.

**Comment by elf-pavlik** [comment]
> Holodex's relationship type data is an example of defining both directions of relationship types. notice that we give each direction a different color, would work with either option but something to think about it.

@ahdinosaur why do you give different color if you represent same relationship but just look at it from different direction?

* http://holodex.enspiral.com/people/mikey
* http://holodex.enspiral.com/people/jon

*steward* relationship seems to have same color no mater if you look at it as 'hasSteward' or 'isStewardOf', arrow seems to make the direction clear here :smile:

**Comment by ahdinosaur** [comment]
> steward relationship seems to have same color no mater if you look at it as 'hasSteward' or 'isStewardOf', arrow seems to make the direction clear here :smile: 

yeah, i agree. something something minimum viable something.

as a side note, we're trying to avoid `isRoleOf` or `hasRole` relationships, instead preferring `verb`. so it's `stewards`, not `isStewardOf`. not sure how to verb `member` though, which is why that's still `isMemberOf` and `hasMember`, but Simon [had a few ideas](https://github.com/holodex/enspiral-data/pull/21#issuecomment-119745249).

**Comment by fosterlynn** [comment]
>something something minimum viable something

hahaha, I'm going to start using that one....

**Comment by bhaugen** [comment]
I prefer something something maximum viable something.

**Comment by ahdinosaur** [comment]
mad science

**Comment by elf-pavlik** [comment]
> as a side note, we're trying to avoid isRoleOf or hasRole relationships, instead preferring verb. so it's stewards, not isStewardOf. not sure how to verb member though, which is why that's still isMemberOf and hasMember, but Simon had a few ideas.

I also like looking in this direction, @bhaugen do you remember where we have discussed role vs. verb?

Yesterday I thought about it while on a bus Paris -> Lille and after writing some very rough .jsonld examples (which I will start adding to repositories here soon!) it seemed like:

Process - role -> Agent
Agent - verb -> Resource

eg.

I can take *role:driver* during a BusTrip (Process) and provide my service as one of the inputs (other imputs: bus usage, fuel consumption, access to highway etc.). But in that very process I **do** *verb:drive* the Vehicle (Resource)...

Happy to discuss it further when I submit PR with .jsonld examples mentioned above!

**Comment by bhaugen** [comment]
@elf-pavlik:
> do you remember where we have discussed role vs. verb?

It was in Gitter, which doesn't seem to be searchable. And I don't find the same conversation in github issues, which might mean that we did not cut-n-paste the gitter convo, or that github issues search is lame.

> I can take role:driver during a BusTrip (Process) and provide my Service as one of the inputs (other imputs: bus usage, fuel consumption, access to highway etc.). But in that very process I do verb:drive the Vehicle (Resource). Person acting as driver yesterday did also other things besides driving the vehicle, like managed passenger check in and she even made a small repair when bus stopped in the middle of the highway...

Do you mean "role:driver" is equivalent to "providing my (driving) Service as one of the inputs"?

Or are those different ways of expressing the same concept? Or something else?

If different ways of expressing the same concept, "providing my (driving) Service as one of the inputs" packs a lot more economic information than "role:driver".

**Comment by elf-pavlik** [comment]
> If different ways of expressing the same concept, "providing my (driving) Service as one of the inputs" packs a lot more economic information than "role:driver".

As [I mentioned earlier](https://github.com/valueflows/agent/issues/28#issuecomment-145043093) we don't have to approach it as either-or! While we should have a long and verbose way of expressing information, we can **also** have short and rough way to make similar statements. They both can complement each other!

For example we could rely on
* http://patterns.dataincubator.org/book/materialize-inferences.html

Not to require OWL reasoning based for example on
* http://www.w3.org/TR/owl2-primer/#Property_Chains

Once again, I would propose not getting into either-or approach and while we all see need for verbose and complex structures for very detailed representation of real world happenings. I **also** see need for less detailed short hand constructs, which follow more the way many people think about those happenings in our daily lives. I see directed labeled graphs providing us with elegant way to draw few additional edges to create such *additional shortcuts*.

**Comment by bhaugen** [comment]
It's not about either-or, it's about getting the required economic information. Then we can infer lots of different views of the same economic information for different purposes.

The required economic info depends a lot on what we want to do with it. For example, one of our NRP collaborators, who shall remain nameless, would break driving the bus into each little sub-activity, for the purpose of deriving a chart of emergent roles. How to get all that detail remains unknown.

**Comment by elf-pavlik** [comment]
> It's not about either-or, it's about getting the required economic information. Then we can infer lots of different views of the same economic information for different purposes.

We can also start with simpler model, which makes decent sense but misses some granularity of information. Once we have .jsonld examples using that simpler model, which simplicity enables us to write those examples right now, without needing to go through week long debates about possible way to model more detailed complex views of all kind of things we can imagine, we can start step by step extending various examples with more details and let more complex views emerge this way. If we find 3 different but compatible ways of modeling something, with different degrees of complexity/verbosity, than we can decide to encourage two of them and documenting discovering the 3rd one and reasons why we recommend using one of two other ways.

**Comment by bhaugen** [comment]
One problem with the simpler model (by which I assume you mean role:driver) is that it introduces an unnecessary relationship (role) of agent to process.

**Comment by elf-pavlik** [comment]
> One problem with the simpler model (by which I assume you mean role:driver) is that it introduces an unnecessary relationship (role) of agent to process.

@bhaugen IMO we go really off-topic in this issue! I will make PR with **concrete, real world example** and explain why I see that in many (if not most cases) agents and processes stay related to each other. If you see need to continue this conversation before that, could you please create a dedicated issue for it?

**Comment by bhaugen** [comment]
I added the [bus trip example](https://github.com/valueflows/valueflows/blob/master/use-cases/bus-trip.md) an hour ago. Feel free to extend.

**Comment by elf-pavlik** [comment]
@bhaugen I see [bus trip **use-case**](https://github.com/valueflows/valueflows/blob/master/use-cases/bus-trip.md), thank you for capturing it!

Later today, I will add **.jsonld example** with *one of various possible modelings* to:
https://github.com/valueflows/process//tree/master/examples

This will provide us with clear starting point to iterate from, using PR workflow, which gives us space for small focused conversations about various clear proposals. I'll add for next telecom PR workflow topic, I see benefit with staring with PR and looking for agreement while it waits for merging (or rejection), over trying to agree on something before anyone even have concrete, exemplified proposal to offer - we still need to get in a flow here before outputting something which other people will value :wink:

**Comment by elf-pavlik** [comment]
closing in favour of #306
