### ISSUE TITLE
Get out of github

### ISSUE THREAD

**Issue by fosterlynn** [valueflows/valueflows#526]
We could keep this account and leave a trail from here, referring people to a new site.  Would have to fix up the gitbook too.  And imo a requirement is to have the source and discussion open on the web basically.

Ref https://github.com/valueflows/forum.valueflo.ws/issues/128#issuecomment-515601973

We started doing some research, any input welcome!

One response over in loomio Open App Ecosystem:
Chris Croome (Webarchitects Co-operative) - You could consider our GitLab server at https://git.coop/.  We're looking into that one, asking some questions there:
Chris Croome (Webarchitects Co-operative) · 2 hours ago

Here's a whole discussion from back when MS bought GH:
https://www.loomio.org/d/AKHTu1v7/creating-self-community-hosted-replacement-s-for-github?membership_token=BUZx5m9c2x6Ksio3nyHLANti&utm_campaign=discussion_mailer&utm_medium=email&utm_source=comment_replied_to

**Comment by almereyda** [comment]
The good thing is that we know from the libre.sh import into lab.libreho.st that the GitLab import of GitHub projects works really well, including issues and mapping of usernames, if already existing, when provided with an API key.

I'd suggest we recreate our handles from here over there and invite other participants in these repositories to do so, too. Additionally adding email aliases that are used in git commits to these profiles might help keeping the references intact, too.

I like that registration on their insance is open, and would like to keep that a requirement for the valueflows project.

The URL is also nice, plus they are a libreho.st er.

**Comment by bhaugen** [comment]
@almereyda thanks for the feedback. I got your comment by email before you edited it, and the edited version is much more clear.

> I like that registration on their insance is open, and would like to keep that a requirement for the valueflows project.

Do you mean https://git.coop/ ? That's one of our questions, if registration is open. We figured we (@fosterlynn and I) would pay for an organizational membership, but it wasn't clear to me how open the registrations would be for all present and future contributors. Did you see something definitive about that?

> the GitLab import of GitHub projects works really well, including issues and mapping of usernames,

Good! That was another question.

> gitlab.com would have the plus of a wider audience, 

Where hosted? I talked to another project doing nice indie hosting but they said they are hosted in the US and need to follow US law.

> which also counts for framagit.org.

Do you mean framagit.org would have a wider audience than git.coop (or lab.libreho.st)?

> Additionally adding email aliases that are used in git commits to these profiles might help keeping the references intact, too.

Will ask you again for how to do that when the time comes.

We're also thinking to keep the github repos up as-is but with new location notices in the readmes.

**Comment by fosterlynn** [comment]
>>gitlab.com would have the plus of a wider audience,

>Where hosted?

I assume @almereyda meant we could just use the gitlab hosted instance, which I believe we could do for free.  Yes, wider audience.

**Comment by bhaugen** [comment]
@fosterlynn and I talked, and she thinks the main question is where the company is registered, not where the servers are located. She says Gitlab's headquarters are in San Francisco, CA, USA. So the same thing that happened with github and US sanctions could happen to gitlab's hosted version.

**Comment by bhaugen** [comment]
Here's my current opinion, altho I am not in a hurry, and want everybody involved to have time to think thru all the angles.

1. Move to git.coop (pending a few more questions).
2. Start to experiment with federated repos using ActivityPub. [Writeup of the idea from Cory Slep](https://cjslep.com/c/blog/the-future-is-federating-forges). While we experiment, develop a ValueFlows vocabulary treatment for federated software collaboration.

**Comment by bhaugen** [comment]
git.coop will present some hurdles for newcomers and friction for us. They do not really offer open registration. Which I understand, they are afraid of being overwhelmed in more than one way.

So either every participant would either need to have their own git.coop account, which means joining the co-op, or they would whitelist valueflo.ws, which means everybody would need to have a @valueflo.ws email address or email redirect.

That would be possible: we could meet new people in some open place and they could ask for such an email redirect and we could create it somewhere, but it would be a lot of friction.

I still think moving to a gitlab instance would be the easiest next step. Anybody got other friendly candidates that could offer easier entrance for newcomers and not hosted in the US?

**Comment by bhaugen** [comment]
List of free hosted git evironments:
https://njoseph.me/mediawiki/Free_Software/Hosting

I don't think we should emphasize "free as in beer", though...but that's a good list to look through.

**Comment by y0va** [comment]
I'm also on the search for a new home for the solidbase app which is currently hosted at lab.allmende.io, but I see it's future unstable as it's infrastructure provider ecobytes has severe structural problems. It's also invite only as a lot of spam user registrations occurred.

Probably I move to lab.libreho.st which has open registrations. But its hard to foresee how it will do when spam users kick in. Maybe some of their members run also own instances.

**Comment by bhaugen** [comment]
I'm talking to https://codeberg.org/ in Mastodon. They are a non-profit and their hosting servers are in Germany. We can become voting members: 
https://join.codeberg.org/
https://codeberg.org/codeberg/org/src/branch/master/Satzung.md

Looks like they can also host our gitbook: https://pages.codeberg.org/

Anybody can raise issues but need a codeberg account, which is free.

**Comment by almereyda** [comment]
Codeberg seems just the right place.

**Comment by TiberiusB** [comment]
I am following this thread. Should we also move Valet and Sensorica?

**Comment by bhaugen** [comment]
@TiberiusB 
> I am following this thread. Should we also move Valet and Sensorica?

The practical issue depends on whether you got ongoing repository contributors from nations that the US has or might ban. In which case, github will ban their accounts. The ethical-political issues are different but related.

ValueFlows does not currently have any contributors whose accounts have been banned by github, but we would like to have some. That desire, plus the general opposition to all this banning by the US, sparked the idea of moving, which continues to move very slowly because Lynn and I have been very busy on VF-related projects and neighborhood projects.

**Comment by jbshirk** [comment]
Forgive my intrusion. I took a great interest in this project in 2014-15
but life took me to deal with urgent problems.

I just wanted to suggest looking at

http://fossil-scm.org/home/doc/trunk/www/index.wiki

It's really decentralized and serverless, not simply federated with
centralized control of accounts.

It's better than git in many ways

http://fossil-scm.org/home/doc/trunk/www/fossil-v-git.wiki

Tho I can't say how gitpages would work. Http access would seem to be very
different than what people are used to.

Two cents.

**Comment by fosterlynn** [comment]
@jbshirk thanks much for your "intrusion" and nice to see you popping in!  Will take a look, although as Bob mentions, we need to find a window of time to really do this, so you probably won't see immediate action.

**Comment by bhaugen** [comment]
We're seriously lagging on this.
https://twitter.com/EisenbergEffect/status/1240671036292485121
https://news.ycombinator.com/item?id=22628961

TL:DR: github shut down an account citing US sanctions and then restored it. But the whole incident explains why we need to get out github or gitlab or any other US host.

**Comment by dahacouk** [comment]
Just from reading this whole thread I'm wondering if there are a number of issues/layers going on here. I thought Git was meant to be an all singing replication protocol, so can't you have multiple Git repos all syncing? So, can't you keep GitHub in sync with a GitLab? But I bet the issues and other peripherals don't sync, yeah? Is that the issue? Darn these things don't interoperate! ;-)

And then there's the hosting layer. If all the tools (like GitLab) were Docker instances then couldn't you have an easy way to have a resilient network of GitLabs? Able to host them on different providers? Or is that all too over engineered? Or is it prudent?

**Comment by bhaugen** [comment]
@dahacouk 

> Just from reading this whole thread I'm wondering if there are a number of issues/layers going on here. 

Yup.

> I thought Git was meant to be an all singing replication protocol, so can't you have multiple Git repos all syncing? 

True of Git, as far as I know. And I think it was originally designed for email communication, not these centralized hosts.  But a central host is pretty useful at this stage of organization. Once federated repos get smoother, I personally want to move there...

> So, can't you keep GitHub in sync with a GitLab? But I bet the issues and other peripherals don't sync, yeah? Is that the issue? Darn these things don't interoperate! ;-)

Don't know yet. We plan to move everything to maybe (my current fave) https://codeberg.org/ but so far, lack the time to learn and do it.

> And then there's the hosting layer. If all the tools (like GitLab) were Docker instances then couldn't you have an easy way to have a resilient network of GitLabs? Able to host them on different providers? Or is that all too over engineered? Or is it prudent?

**Comment by dahacouk** [comment]
@bhaugen 

> Don't know yet. We plan to move everything to maybe (my current fave) https://codeberg.org/ but so far, lack the time to learn and do it.

Wouldn't it be great to find a Git repo that had an API for all it's functions. Then we could really interoperate between it and others when the time comes... Or even make that time come. ;-) But I guess that's a different project! ;-)

**Comment by fosterlynn** [comment]
>Wouldn't it be great to find a Git repo that had an API for all it's functions? Then we could really interoperate between it and others when the time comes...

Federated gits!  Would be great.  But yeah, don't know if we want to wait for that....

**Comment by bhaugen** [comment]
Codeberg seems to be very cooperative. And there's also https://scuttlebot.io/apis/community/git-ssb.html and some similar effort in the fediverse that I will look for tomorrow...

**Comment by almereyda** [comment]
To let you know, we have reopened public registration on the GitLab at
https://lab.allmende.io and intend to keep it that way. We would feel
honoured, if you'd be our guests.

It's not a cooperative, but a computational common. Therefore we all have
equal say in how things happen.

Bob Haugen <notifications@github.com> schrieb am Sa., 21. März 2020, 23:44:

**Comment by bhaugen** [comment]
> To let you know, we have reopened public registration on the GitLab at https://lab.allmende.io and intend to keep it that way.

That's your self-hosted gitlab in Europe, not subject to US laws, right?

> We would feel honoured, if you'd be our guests. 

@fosterlynn let's do that!

@almereyda what would it take to move all of https://github.com/valueflows/ ?

And can https://lab.allmende.io support the http://valueflo.ws/ gitbook, or is that a do-over?

> It's not a cooperative, but a computational common. 

And we love you! Transformap's name came up yesterday in a Mutual Aid Network convo. We might want to talk about mapping with y'all down the road a couple of weeks.

**Comment by fosterlynn** [comment]
>@fosterlynn let's do that!

Yes!  We are honored you invited us @almereyda !

**Comment by almereyda** [comment]
Yesss! That feels like a game changer. And yes, the server is hosted under GDPR supervision in the EU.

Okay, let me imagine and think out loud here how we could approach this process progressively.

First, there are extensive import options from GitHub to GitLab

* [Github · Import · Project · User · Help · GitLab](https://lab.allmende.io/help/user/project/import/github.md)
  * [Github imports · Monitoring · Administration · Help · GitLab](https://lab.allmende.io/help/administration/monitoring/github_imports.html)

and the look can be closed again with a roundtrip through

* [Repository mirroring · Repository · Project · User · Help · GitLab](https://lab.allmende.io/help/user/project/repository/repository_mirroring.html)

There does not seem to be a simple, non-commercial way to link GitHub and -Lab issues, so the move would be unidirectional and cannot be reversed. We have already done so with libre.sh to lab.libreho.st, and it worked very well. As an experience from that migration, it is left to note that comments in issues and merge requests are even mapped to locally existing users of the same username. Otherwise they are created by the user that conducts the migration. These need to exist beforehand, so a coordinated sign-up round of the currently active Value Flows participants appears useful before conducting the migiration. Please see this example:

* [Find a nicer name (#137) · Issues · libre.sh / compose.libre.sh · GitLab](https://lab.libreho.st/libre.sh/compose.libre.sh/issues/137)
* [Backup whithout sftp (#167) · Issues · libre.sh / compose.libre.sh · GitLab](https://lab.libreho.st/libre.sh/compose.libre.sh/issues/167)

- [Find a nicer name · Issue #137 · libresh/libre.sh](https://github.com/libresh/libre.sh/issues/137)
- [Backup whithout sftp · Issue #167 · libresh/libre.sh](https://github.com/libresh/libre.sh/issues/167)

As it seems that the mapping also works across user names, I guess the depicting factor is the email address, but I don't know for sure.

The GitBook will work again, eventually through provisioning to GitLab Pages or some other deployment target, when we finish deploying our improved and secured CI/CD environment, which is due soon. This is documented in

* [Introduction · GitBook | GitLab Pages](https://pages.gitlab.io/gitbook/)

And yes, let's talk mapping soon! There's lot's of new developments on the Intermapping side of things, also in preparation of the [WSF2020 Mapping Commission](https://forum.transformadora.org/assemblies/map), a possible prototype for the last round of the German Prototype fund, all those offer-request-matching engines that were born for https://wirvsvirushackathon.org/?lang=en, and more.

Let's stay in touch.

**Comment by fosterlynn** [comment]
@almereyda one more question about that gitlab instance - what is the support behind it?  Like, what is the [bus factor](https://en.wikipedia.org/wiki/Bus_factor)? (And, fun to see hackers4peace again...)

>And yes, let's talk mapping soon!

Yes!!  Where is the best place to have a chat about that?  Might want to get you connected up to a forming team, although it is early days for them.

**Comment by almereyda** [comment]
The suport is that it is run by Ecobytes as a core service for itself and its members, and extends to the Allmende (Common) due to us being a tax-exempt association working for the common good.

I'm always to discuss mapping at https://discourse.transformap.co, although that community seems quite dormant these days. I'm also a frequent user of Riot, where we use https://riot.allmende.io/#/room/#intermapping:matrix.org for mapping conversation (people need to register with an email, and revisit that link). Alternatively, we also hold a Discourse at meta.allmende.io, which is available to the community.

**Comment by fosterlynn** [comment]
@almereyda we got your request to move VF from github, but we haven't done our homework of getting people signed up first in gitlab so it finds the user matches.  Sorry, too much going on!  And do you know yet if it can match on email, or needs the same username?  If OK with you, let's let it sit until we get some people moved over, might take a bit....

**Comment by almereyda** [comment]
I always think it's good to take time, and give people time to accomodate to change, especially now. I'd be open to creating a new issue that outlines an offspring story, in a generalized form, about how a migration of the Value Flows GitHub organisation to GitLab could take place.

In there we could prepare a little for what it means to move

- people
- projects
- pipelines

into the new instance.

You'll be happy to hear that this decision to move to GitLab comes together with their announcement to release more enterprise features into the open core. Let's see when epics will arrive, in the end ... 

Also we're renovating our infrastructure, and are actively extending our CI/CD pipeline, which means sooner or later we can also offer GitLab pages. That's more disussed on the Ecobytes-level of things.

Meanwhile the Allmende remains welcoming to you, as we gather for the migration.

As you'll grow closer to our infrastructure, it's only naturally for me to consider that discussion-length posts about Value Flows considerations, or those that do not fit well into the GitLab interface (some consider its interface clunky for non-tech people), we also have a Discourse at https://meta.allmende.io running, and could spin up a category for https://github.com/valueflows/forum.valueflo.ws/issues/36

**Comment by fosterlynn** [comment]
@almereyda thanks so much!  Yeah, its pretty crazy right now in our software world (way more than usual with virus mutual aid response activities).

>I'd be open to creating a new issue that outlines an offspring story, in a generalized form, about how a migration of the Value Flows GitHub organisation to GitLab could take place.

That would be great if you can shepherd us through the process!  <3

**Comment by fosterlynn** [comment]
Hi @almereyda !  I just migrated the gitbook to their new version, which I think severs it from github as a source.  Made us think that we could start this move to gitlab into motion now or soon, as it fits your schedule.  I'd still like to take advantage of your kind offer to create a new issue that outlines how we do it.  And part of that would be asking people to create new accounts in the new space and giving some time for that, so the issues move over cleanly.  Thanks!

**Comment by almereyda** [comment]
Hi @fosterlynn, @bhaugen et al., the new issue is now available at #629. Please check and review, if I catched the prospect right.

Further down the road we can also check how to integrate the sources of the valueflo.ws website with GitLab CI and deploy through

- https://github.com/IlyaSemenov/gitlab-ci-git-push  
  https://github.com/valueflows/valueflo.ws/blob/master/package.json#L9-L12

All other suggestions from above about considering the Allmende Discourse or Riot remain applicable.

**Comment by bhaugen** [comment]
More incentive: https://www.zdnet.com/article/github-starts-blocking-developers-in-countries-facing-us-trade-sanctions/

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/valueflows/-/issues/526.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
