### ISSUE TITLE
Generating standard accounting reports from VF data

### ISSUE THREAD

**Issue by bhaugen** [valueflows/valueflows#541]
This is a trial balloon for the end of the https://valueflo.ws/introduction/accounting.html page.

### If you want to count beans...

A standard General Ledger, Balance Sheet, and Income Statement can be generated automatically from ValueFlows data. No need to create a Chart of Accounts or post double-entries, those can all be created by a computer program on request. 

![GL](https://user-images.githubusercontent.com/117439/62549655-815ef080-b82e-11e9-987c-5ff23b6535f5.png)

Moreover, General Ledgers and accounting reports can be created automatically for each agent in an economic network using the VF vocabulary. These features are on the roadmap for the [HoloREA  project](https://github.com/holo-rea/ecosystem/wiki/Coordinating-the-REA-community-of-practise) and possible another two or three projects now in the works.

This article describes how to generate General Ledgers etc from REA data using procedural code: [Operation of a Relational Accounting System, Graham Gal and Bill McCarthy](https://www.researchgate.net/publication/292781264_Operation_of_a_relational_accounting_system)

Wim Laurier is working on how to do it declaratively. [This paper](http://ceur-ws.org/Vol-2383/paper8.pdf) gives an early view of how Wim and Satoshi Horiuchi intend to do it.

The difference between doing it procedurally and doing it declaratively:
* A procedural program defines a step-by-step method of getting the desired results.
* A declarative program describes the desired results and hands it to another program that can generate the desired results from your description. The person who desires the results writes much less code.

**Comment by bhaugen** [comment]
Add after this paragraph:
> Moreover, General Ledgers and accounting reports can be created automatically for each agent in an economic network using the VF vocabulary.

Accounting statements can also be updated instantly for each participant in any economic event as soon as the event is recorded. For example, consider an economic exchange, where one agent transfers some goods to another, and the other agent transfers some money in return. The inventory of the goods-providing agent will be instantly decremented, and the receiving agent's incremented. Likewise the money accounts of the money-providing and receiving agents will immediately change. Income statements, balance sheets, and cash flow reports will reflect the new changes immediately. The financial positions of each agent will always be up-to-date as of the last recorded event.

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/valueflows/-/issues/541.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
