### ISSUE TITLE
Agenda for meeting 2

### ISSUE THREAD

**Issue by bhaugen** [valueflows/valueflows#56]
* https://github.com/valueflows/valueflows/issues/52#issuecomment-147193331

**Comment by elf-pavlik** [comment]
duplicate of https://github.com/valueflows/valueflows/issues/42 :wink: 
Can we also put agenda into Wiki of this repo instead of issue?

**Comment by bhaugen** [comment]
Sorry, I must not have been paying enuf attention when I started that dup...and I don't care where agendas go.
