### ISSUE TITLE
backup everything at .3

### ISSUE THREAD

**Issue by fosterlynn** [valueflows/valueflows#560]
Reminder to take a full export of VF at release .3, including issues etc, just to have a full backup.

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/valueflows/-/issues/560.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
