### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by wolftune** [valueflows/valueflows#578]
I can't find any reference to license for this work. Is it CC-BY or CC-BY-SA? It seems to be that sort of direction, not something that should have a software license. Please make sure it can be a valid Open Work (see https://opendefinition.org/od/2.1/en/ )

**Comment by fosterlynn** [comment]
Did a short review.  CC-BY-SA seems good to me.  Any other thoughts?

**Comment by wolftune** [comment]
CC-BY-SA would certainly be my suggestion and preference. Cheers

**Comment by fosterlynn** [comment]
Did a PR, closing this.  Any further discussion can happen there.  https://github.com/valueflows/valueflows/pull/584
