### ISSUE TITLE
SpatialThing vs Point

### ISSUE THREAD

**Issue by fosterlynn** [valueflows/valueflows#586]
@jvanbockryck has recommended using geo:Point rather than geo:SpatialThing.  

More info to be added later....

**Comment by jvanbockryck** [comment]
My reasoning is that geo:Point is the only actual geo object with geospatial coordinates in geo:SpatialThing.

**Comment by fosterlynn** [comment]
From discussion in offline chat, we think that we may want to some day use polygons or similar for locations.  Doesn't seem like SpatialThing does that now, but we decided to leave it as-is, to hold it open for that.  (Note: Point is a subclass of SpatialThing.)

**Comment by fosterlynn** [comment]
Re-opening because I forgot there was another potential question around the lat, long, and alt properties being `owl:AnnotationProperty`s.  Is this OK for us?  Seems like the intention is to keep it simple and let apps parse them?  From their doc:


"We do not use RDF's datatyping mechanism in the vocabulary's schema to note that the rdfs:range of the lat,long and alt properties are XML Schema float datatypes. Instead, from RDF's point of view, the properties are simply strings."

"This reduces the syntactic burden on RDF/XML documents using our vocabulary, since we write lat and long information as strings. The string representation of lat and long should follow the rules for XML Schema float, even though we do not indicate explicitly in RDF that we are representing floating point numbers."

@elf-pavlik @jvanbockryck

**Comment by jvanbockryck** [comment]
Indeed, unfortunately the lat, long, alt properties are now assumed to be having a string datatype, while for technical use string is not good enough. This means that we need to add in VF, using annotation properties (yes, they are meant for this type of purpose), that the actual datatypes should be double or float, TBD. So, adding our own annotation property on the geo annotation property. If that is what it takes, i would go for that “solution”

**Comment by fosterlynn** [comment]
Resolved by adding a range in VF.
