### ISSUE TITLE
Agreement vs Exchange

### ISSUE THREAD

**Issue by fosterlynn** [valueflows/valueflows#587]
I'd like to re-look at our use of Agreement class.  I think the name is too general for what we need there, which is an Exchange or ExchangeAgreement perhaps - something that groups reciprocal Commitments.  I think that is the very particular type of agreement that VF should include.

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/valueflows/-/issues/587.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
