### ISSUE TITLE
"one" vs "each"

### ISSUE THREAD

**Issue by fosterlynn** [valueflows/valueflows#596]
We are considering what (if anything) to do about the semantics of "one" as the count/each/piece unit of measure in OM.  We are also verifying what we understand about "one" with the OM team here thub.com/HajoRijgersberg/OM/issues/7.  Started this issue since this is still open although we are merging the OM PR.

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/valueflows/-/issues/596.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
