### ISSUE TITLE
need citation(s) for cfa

### ISSUE THREAD

**Issue by fosterlynn** [valueflows/valueflows#601]
From @bhaugen in SSB:

The model comes from Fernando Flores and some other people:
http://conversationsforaction.com/the-book

We got the diagram from http://www.itu.dk/people/kasper/REA2004/pospapers/PrasadJayaweera.pdf
(Used to have a citation in the VF intro, I think. @Lynn Foster we should have one.)

You can play with the protocol here:
http://conversationsforaction.com/cfa-playground

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/valueflows/-/issues/601.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
