### ISSUE TITLE
ResourceSpecification - Agent (unitOfEffort)

### ISSUE THREAD

**Issue by fosterlynn** [valueflows/valueflows#604]
This issue is triggered by HoloREA, where we are wanting to have a place for unitOfEffort in the knowledge layer for use in defining new economic resources that will involve effort.  When we split apart ResourceSpecification and RecipeResource, we put unitOfEffort into the RecipeResource, thinking it might be different for different recipes that make the same ResourceSpecification (for example different machinery or management of machinery - as well as agent preference, for example translation recorded in hours or words).  But sometimes there aren't recipes, just ResourceSpecifications.

Related to this issue is that we haven't decided yet how to make it so that the same ResourceSpecification can be used by different agents, and so that agents can define what ResourceSpecifications they want to use from the many out there, in possibly different public instances or websites.  We're not ready to address that in HoloREA yet.  When we do address that, it is possible that the unitOfEffort should be defined in the agent specific resource specification.

[edit] In the meantime, we will add defaultUnitOfEffort to ResourceSpecification in HoloREA.

**Comment by pospi** [comment]
Largely a duplicate, but see also https://github.com/valueflows/vf-graphql/issues/64

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/valueflows/-/issues/604.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
