### ISSUE TITLE
Facets as part of VF?

### ISSUE THREAD

**Issue by fosterlynn** [valueflows/valueflows#605]
This came up here. https://github.com/valueflows/valueflows/issues/603 

I'm wondering if we want to explicitly include a model for facets and facet values as part of VF knowledge layer?  I've always kind of boxed them into resource classifications, but they do have a more complex structure and are ubiquitous in e-commerce.  Example:  Shirt.  Size: 12, Color: Red.  Or Boxed Beef.  Cut: Round steak. Weight: 2 lb. Pastured 100%: true.  I think that mostly, all these would also be part of the ResourceSpecification, as they are all part of a specification specific enough to actually order, like a "size 12 red shirt", but they are kind of buried there without a model.

I looked in GoodRelations and did not find this structure.  I also don't see it in schema.org, but it is a bit hard to see all of their model.

But I can see that there might be standard definitions that would be re-used among agents.

**Comment by iPlumb3r** [comment]
For information, LanguaL develops a faceted food decription thesauri, with "facets"  such as :
* Food Source
* Par Or Plant or Animal
* Physical State 
...

More here : http://langual.org/langual_thesaurus.asp

**Comment by fosterlynn** [comment]
@iPlumb3r very cool, thanks!

Interesting they have more than 2 layers (facet and facet-value) - a hierarchy of facet-values.  @mayel does this kind of model fit into any of the taxonomy work you have been doing in recent years?

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/valueflows/-/issues/605.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
