### ISSUE TITLE
transfer-complete vs transfer

### ISSUE THREAD

**Issue by fosterlynn** [valueflows/valueflows#606]
Naming issue.  Experience is showing that the transfer naming is too much for some people, when they need something simple and without nuance, and it is basically always transfer-complete, which transfers all rights and custody at the same time.

Propose to change the name of `transfer-complete` to `transfer`.  And keep the others as is (transfer-all-rights, transfer-custody).

@pospi if you agree with doing this, when would you like to do it?  After this round of HoloREA and associated projects?  Or just do it?  Like, v0.4.1 or v0.5?

**Comment by pospi** [comment]
I'd just do it, and since it's a breaking change my vote would be `0.5` and to also include some of the fixes/changes to `pass`/`fail`/`modify`/`accept` that you, @bhaugen & I have been talking about. That makes such a release a more complete set of revisions affecting `Action`.
