### ISSUE TITLE
Are w3id.org links doing what they should?

### ISSUE THREAD

**Issue by fkleedorfer** [valueflows/valueflows#609]
The VF ontology states its URI as [https://w3id.org/valueflows/](https://w3id.org/valueflows/), its Version IRI is [https://w3id.org/valueflows/0.4/](https://w3id.org/valueflows/0.4/). The former redirects to [https://valueflo.ws](https://valueflo.ws), the valueflows landing page, the latter to [https://valueflo.ws/0.4/](https://valueflo.ws/0.4/), which returns a 404. 

While it is possible to find the [current version of the ontology](http://150.146.207.114/lode/extract?owlapi=true&url=https://raw.githubusercontent.com/valueflows/valueflows/master/release-doc-in-process/all_vf.TTL) within a few clicks, for automation reasons it would be nicer if the `w3id.org` URIs redirected to the ontology directly, ideally with content negotiation.

**Comment by fosterlynn** [comment]
@fkleedorfer Yeah, very sorry, we haven't gotten this together.  I guess its time we do our w3id.org work!

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/valueflows/-/issues/609.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
