### ISSUE TITLE
Want to offer a new Offers and Wants repo

### ISSUE THREAD

**Issue by bhaugen** [valueflows/valueflows#61]
[Stephanie Rearick](https://www.youtube.com/watch?v=MsvsJXXJsRs) of the [Madison WI Mutual Aid Network](http://www.mutualaidnetwork.org/), who also has a lot of experience with mutual credit systems -https://github.com/valueflows/exchange/issues/4 - has offered to join in and help, because she wants to use the vocab to intertrade between their [Wezer app](http://man.wezer.org/marketplace/search) and various mutual credit apps. 

Any objections? 

P.S. see also #40 and #24

**Comment by elf-pavlik** [comment]
How about something generic which can cover all the cases like Offer, Request, Demand, Want, Need, Desire etc.?

**Intent**

VRM has concept of *Intent Casting*: https://vimeo.com/53576832

**Comment by bhaugen** [comment]
I like it. But I think Demand is usually pretty specific, I'd leave that out.

Unless somebody objects by end of day, I'll set it up early tomorrow.

**Comment by fosterlynn** [comment]
The only problem with Intent is it covers process stuff too, and I think we don't want to do that here.  But this isn't a big objection, it's only a repo name.

**Comment by bhaugen** [comment]
I don't think it matters if it covers process stuff. I think we need to cover the predecessors to conversations for action and commitments, and work out Stephanie's ideas for how to refine offers and wants.

**Comment by ahdinosaur** [comment]
:+1:, this is great. also, [Hylo](https://www.hylo.com/) has intentions, offers, and requests.

> The only problem with Intent is it covers process stuff too, and I think we don't want to do that here.

i think it's all the better if it covers process intent as well, as @bhaugen mentions it seems like this could be a much needed form of activity to provide for a sweet conversation flow: Intent -> Commitment -> Action (ValueFlow). @bhaugen, am i understanding this correctly? @fosterlynn, do you want to expand on your objection?

**Comment by bhaugen** [comment]
> Intent -> Commitment -> Action (ValueFlow)
@ahdinosaur you are not only understanding this correctly, you have condensed it into ~almost~ a meme!

**Comment by fosterlynn** [comment]
@ahdinosaur I withdrew my objection.  (I was trying to limit it to what Stephanie/MAN needed to think about. This is better.)

**Comment by ahdinosaur** [comment]
yay. :smile:
