### ISSUE TITLE
Question on canonical schema(s) (JSON vs OWL)

### ISSUE THREAD

**Issue by orthecreedence** [valueflows/valueflows#615]
Hello! In an effort to start playing with VF in code more, I built a rust library that converts the vf-json-schema into (de)serializable rust structs: https://docs.rs/vf-rs/. After doing so, I realized there is also an [owl schema](https://raw.githubusercontent.com/valueflows/valueflows/master/release-doc-in-process/all_vf.TTL). I'm fairly unfamiliar with owl (and ontology in general). Is the owl schema more "canonical" than the JSON or are they kept in sync pretty well? I would like to figure out how to parse the owl into structs because I'd like to include OM measurements in the library (or as a sister library) and OM uses owl as well, but if the JSON and owl schemas are in parity I might save that project for another time.

Also, I noticed that `vf:cite` shows up in the owl schema twice. Is that purposeful? Thanks!

**Comment by orthecreedence** [comment]
Ok, after looking through the generated code for the rust lib, I'm seeing what appears to be an issue. Various structs (for example [EconomicEvent](https://docs.rs/vf-rs/0.1.2/vf_rs/economic_event/struct.EconomicEvent.html)) have a field `action` which seems like it should be a type [Action](https://docs.rs/vf-rs/0.1.2/vf_rs/action/struct.Action.html) but is being labeled in the JSON schema as a string. Should the `action` fields in `EconomicEvent`, `Commitment`, `Intent`, etc be `$ref` types that point to `https://raw.githubusercontent.com/valueflows/valueflows/master/json-schemas/Action.json`? If not, and they're supposed to point at the Action type's [Label](https://docs.rs/vf-rs/0.1.2/vf_rs/action/enum.Label.html) enum then does it make sense to break `Action.label` out into its own type in the schema?

**Comment by fosterlynn** [comment]
Hi @orthecreedence very nice to see you here!  And apologies for the json-schema gaps. 

The owl schema is actually the "system of record" "canonical" model, but it only includes the VF namespace, so is missing a number of things that are required for VF but we are attempting to re-use from other specs like OM (they are [all here](https://valueflo.ws/specification/external-terms.html)).  The json-schemas should include everything that makes the VF model hang together.  However, they are not being actively used, so we have let them get a bit behind; and also because of that they have never been really tested.  (Some day we'll automate creating them, but somehow need to include the non-VF-namespace elements.)  In any case, I will fix them if you want to use them!  And will create a separate issue anyhow so we don't forget, thanks.

There is also [another reference spec](https://github.com/valueflows/vf-graphql), using graphql, that is being used actively by a couple projects, who are also talking to each other, so that is kept well up to date.  But it is grahpql, and I don't know if that will apply to your work.

A project you might want to check into, because it is written in Rust and implements VF, is [Holo-REA](https://github.com/holo-rea/holo-rea).  It is not quite ready to be used (nor is Holochain in general), but getting there.  At least you may find some schemas and code you can make use of.  And we can connect you to the lead dev if you want, or you can ping them there.  cc @pospi .

>Various structs (for example EconomicEvent) have a field action which seems like it should be a type Action but is being labeled in the JSON schema as a string

Yes, needs to be updated!  Should be a $ref as you suggested.

>Also, I noticed that vf:cite shows up in the owl schema twice. Is that purposeful?

No, will fix, thanks!

P.S.  As you know, we love the Basis project; and I'm always happy to do some mapping with you if you think it would be helpful.

**Comment by fosterlynn** [comment]
I just had another thought on this: The graphql spec is defining standard names for "reverse" queries and other methods (like "track" and "trace", which were referenced in the other issue you started).  Those aren't defined anywhere else really, and they should be documented somewhere in the spec more generally, I would think.  I will start an issue for this, but in the meantime, that is where they are, in these schemas: https://github.com/valueflows/vf-graphql/tree/master/lib/schemas.

**Comment by fosterlynn** [comment]
>The owl schema is actually the "system of record" "canonical" model, but it only includes the VF namespace

Aaack, not true any more!  I was looking at something else, and see that we did put the non-VF-namespace elements into the OWL spec (the turtle file you referenced in your first post).  Sorry, they say the memory is the first to go....  So yes, this would be a good thing to use to generate anything else.  And the graphql spec is also reliable.  And I'm still happy to fix up the json-schemas if that works better for you @orthecreedence .

**Comment by orthecreedence** [comment]
Thanks @fosterlynn! This answers my questions. I think I'm going to take a crack at using the OWL spec (would be good for me to familiarize myself with owl anyway) which would hopefully make it easier to parse/include the OM measurements as well.

I just took another look at the graphql spec as well and noticed the `bridging/` folder which I missed before which has types I thought were originally missing from the spec. So it seems I have a few avenues I can follow now. Between GQL and OWL I think I should be able to get what I need, so please don't sink too much time into the JSON schema.

I met with @pospi a few days ago and am more familiar with the holo-rea project than before, so if I need guidance I will reach out.

Thank you!

**Comment by fosterlynn** [comment]
>I just took another look at the graphql spec as well and noticed the bridging/ folder which I missed before which has types I thought were originally missing from the spec.

There's something you can run that puts it all together into one file, or whatever pieces you want.  If you want to do that, and it isn't clear in the repo, ping @pospi .

>Between GQL and OWL I think I should be able to get what I need, so please don't sink too much time into the JSON schema.

Thanks....

**Comment by orthecreedence** [comment]
Hi, @fosterlynn! I have another question on the owl/turtl file. In the JSON schema, it looks like [inScopeOf](https://github.com/valueflows/vf-json-schema/blob/master/schemas/Commitment.json#L44) points to the Agent class, but the rdf is typed as `owl:Thing`.

```rdf
vf:inScopeOf  a             owl:ObjectProperty ;
        rdfs:domain         [ owl:unionOf (vf:Claim vf:Commitment vf:EconomicEvent vf:Proposal vf:Intent vf:Scenario vf:Process vf:AgentRelationship) ] ;
        rdfs:label          "in scope of" ;
        rdfs:range          owl:Thing ;
        vs:term_status      "unstable" ;
        rdfs:comment        "Grouping around something to create a boundary or context, used for documenting, accounting, planning." .
```

Looking at other fields in the owl file that use `owl:Thing`, they seem to correspond to the `Url` type when compared to the JSON fields. Should `inScopeOf` really be referencing `foaf:Agent`, and if so, is it safe to treat `owl:Thing` as a `Url` type?

Thank you!

**Comment by fosterlynn** [comment]
Hi @orthecreedence !  Yeah, good catch.  `inScopeOf` will most often be an Agent, but we thought there might be situations where people would want more flexibility, like scope of a geography that isn't an agent (like a bio-region), or a non-agentified group of people.  

There was a discussion on how to handle it in graphql between a couple projects recently, and I think they basically went with Agent, with the understanding that projects could extend that.  Probably we need a bit more discussion in that setting too.  Will initiate that and get back here.

In the meantime, let's stick with whatever works for owl:Thing, that's what it is in the "canonical" spec.  I think a Url will work if that is the ID in your situation, like it would be in the semantic web.  But I actually have no experience with using json-schemas. I can fix the json-schemas; may wait a few days to see if there is more in the vf-graphql side, in case we want to initiate a VF change.

Sorry you are a bit of a guinea pig in this, especially the json-schemas, but that's the stage right now. Thanks for your patience and for catching this kind of inconsistency!

>>The owl schema ... only includes the VF namespace

>Aaack, not true any more! I was looking at something else, and see that we did put the non-VF-namespace elements into the OWL spec (the turtle file you referenced in your first post).

Aaack again, looks like we did that when we were declaring something that isn't in the other vocabulary, a relationship or overriding a range.  So my first statement was more right, the OWL spec includes basically the VF namespace, in any case not everything you need for a working REA model.  Gotta slow down.

**Comment by orthecreedence** [comment]
Thanks for the update! I think for now I'll store `owl:Thing` as a url with the understanding that it can change later. I'll also keep in mind the special handling around `inScopeOf`, and am interested to hear how 

> Sorry you are a bit of a guinea pig in this, especially the json-schemas, but that's the stage right now. Thanks for your patience and for catching this kind of inconsistency!

Of course! I'm having fun figuring out how rdf/owl work and how this all fits together. I'm very new to ontologies/semantics stuff so picking through this is really helping my understanding.

> Aaack again, looks like we did that when we were declaring something that isn't in the other vocabulary, a relationship or overriding a range. So my first statement was more right, the OWL spec includes basically the VF namespace, in any case not everything you need for a working REA model.

This is what I've been seeing too: the schema adds fields/relationships to existing objects that aren't necessarily defined in the schema. I think what I'll end up doing is hardcoding the types that aren't included in the schema, but let the schema add whatever fields it wants to them, and then treat them like they *were* included in the resulting set of classes. Then it will have things like url, datetime, geo, om2, etc (at least as much as VF needs them).

Thanks so much for your responsiveness here, I'm pretty close to a first version and these answers are helping a lot.

**Comment by orthecreedence** [comment]
Hi, sorry, one more question =]

It looks like `vf:notApplicable` references itself as a subtype of `vf:PairsWith` but `vf:PairsWith` is not defined as a top-level class. I'm assuming it's not defined because really it's a subset of the enum values that provided by `vf:Action`. From the point of view of parsing, it might make sense to define `vf:PairsWith` topside (alongside `vf:InputOutput` and `vf:ResourceEffect`) and then each of the action values that `vf:PairsWith` should contain would list it as a type, such as:

```
vf:PairsWith a            owl:Class ;
        rdfs:comment        "The action that should be included on the other direction of the process, for example accept with modify." ;
        rdfs:label          "vf:PairsWith" ;
        vs:term_status      "unstable" .

...

vf:dropoff a                owl:NamedIndividual ,
                            vf:Action,
                            vf:PairsWith;    # note this addition
        vf:inputOutput      vf:output ;
        vf:pairsWith        vf:pickup ;
        vf:resourceEffect   vf:noEffect ;
        rdfs:comment        "Transported resource or person leaves the process; the same resource or person appeared in the input." ;
        rdfs:label          "dropoff" ;
        vs:term_status      "unstable" .
```

However, this may not be idiomatic owl, and it might just be that I'm butting up against the expressiveness of owl with some kind of limit in the rust type system. I'd appreciate your thoughts here. Thank you!

**Comment by fosterlynn** [comment]
>However, this may not be idiomatic owl, and it might just be that I'm butting up against the expressiveness of owl with some kind of limit in the rust type system.

No, it is a bug.  I understand your solution, and it is probably the least of the evils that I can think of right now. 

(I had a lot of help from a more knowledgeable rdf person on these Action properties, and he is currently not very available. So I probably won't understand all of the inferences, but I'm good with giving it a try, will do a PR.  Hmmm I see a #TODO in the graphql spec to figure this out too.  You'll probably be the first person to actually test generating from the owl spec.... so thanks!)

**Comment by fosterlynn** [comment]
@orthecreedence merged, let me know how it works for you!
