### ISSUE TITLE
Further needs for geo shapes

### ISSUE THREAD

**Issue by fosterlynn** [valueflows/valueflows#617]
We have a request from a project to include more than points in our geo (location) references - more for completeness than any immediate need.  There is experience using geoJson on that project.  Currently we are using SpatialThing from the Basic Geo vocabulary https://www.w3.org/2003/01/geo/, with lat, long, alt.  We picked it because is very simple, and attempts somewhat to bridge competing standards.

I found a really helpful document from the W3C discussing options, https://www.w3.org/TR/sdw-bp/, here are some especially useful sections:
* concepts https://www.w3.org/TR/sdw-bp/#spatial-things-features-and-geometry
* best practices https://www.w3.org/TR/sdw-bp/#bp-summary
* comparison tables here https://www.w3.org/TR/sdw-bp/#applicability-formatVbp

I'm still mulling over the best way to think about it for VF, but thought I would get the issue out here so others can connect if they want.  And have time. :)  [edit: but not required, I'll put out a proposal after I have settled some of this in my head, and then there will be something to really comment on]

**Comment by fosterlynn** [comment]
Some factors (somewhat random) to consider.
* What is the range of use cases VF will likely represent?  Thus far it is economic in mostly the people economy sense, what might be called "business" use cases but in a capitalist plus transitional plus post-capitalist sense.  But we also have done some work with people in Colorado on more technical electrical grid flows, based on connection over category theory.  And there have been several discussions with projects about including aspects of the ecosystem in value flows.
* What is the location of resources and agents used for specifically?  So far, pretty much putting on a map in a standard point way, using standard mapping libraries. We also have location on events, but that hasn't been actually used afaik.  Geo data could be used in the future for logistics, route planning, etc.  That might get us beyond points.  Or that might be beyond our scope and meld into another vocabulary, don't know.  Resources like farm fields seem a realistic scenario, and those might want to be defined in 2D.
* Our use of "location" involves more than geo coordinates.  For example, we added "mappableAddress" and "name" to the Basic Geo spec.  There are a bunch of conceptual nuances there around resource vs location, and even agent vs location.  It seems to me that we are basically interested in fixed locations, not defining shapes of things that tend to be moved around.

**Comment by fosterlynn** [comment]
I've been digging into more detail on some of the possible vocabularies.  Some observations:

Geo spatial vocab, GeoRSS Simple
* Pros: started with the vocab we use (Basic Geo) and extended for the stuff we want (2D)
* Cons: no 3D, the model changed from Basic Geo and is also confusing

Schema.org
* Pros: the model is pretty much the way we think about it, and also can be implemented progressively, using Place for the simplest version (probably 90% of our users), adding classes for more complex needs
* Cons: naming is pretty non-standard compared to the general discourse on geo vocabularies, no 3D

GeoSPARQL
* Pros: has everything, supports all formats; I like the base model
* Cons:  really complex, focused more on query than base model, actually "requires" a lot of the complexity

LOCN
* Pros: supports all formatting, 3D
* Cons: odd model, have to reference geometry and location and address separately

**Comment by fosterlynn** [comment]
Proposal:

1. If we think we will want 3D eventually, and want it badly enough: First study the geoSparql spec in enough detail to see if we can carve out a set of classes and properties, starting with geo:Feature and geo:Geometry, which are related in that a Feature hasGeometry a Geometry.  If it can't be done because of the requirements or it all seems too cumbersome, then the other option is LOCN, which is simpler to understand, but not the best model probably for us, and also allows any of the major specs to accommodate the specific geometries - giving the most possibilities in functionality, but may be more complicated to implement, unless we just pick out one to support in a limited manner.

2. If we think 2D will be good enough, then I think we should go with schema.org, even though it seems like it is not really part of the harder-core geo community (has fewer options for modeling geo shapes for example, and the naming is not in sync), and is there mostly to support SEO.  But it is also a major recognized vocabulary, and aligns more with our perspective of location being a somewhat peripheral VF element, and mostly approached from a more shallow "business" perspective than "real" scientific mapping.  Also, it can be incrementally added based on requirements, starting with Place, which provides name, address, latitude, longitude, which is all most of our users probably need; then adding on GeoCoordinates if elevation (altitude) is needed, and adding on GeoShapes if 2D is needed.

3. Else, stick with what we have, which is used by a lot of people because it is simple.  But, I added some things (name, mappableAddress), which gave it more of "feature" or "location" meaning (which is what we want but it tinkered with the original thinking I expect) than a pure "geo" meaning.  Schema.org has already put that into one vocab.

I think my leanings are to go with schema.org, other opinions very welcome!

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/valueflows/-/issues/617.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
