### ISSUE TITLE
Valueflows Haskell / E-commerce Implementation Heads Up

### ISSUE THREAD

**Issue by fabianhjr** [valueflows/valueflows#618]
Greetings everyone, since a while ago (back when I explored SSB for a bit) this project in particular was quite inspiring. I wanted to give a heads up that I, along others, are undertaking the development of an e-commerce site in haskell using much of what you all have developed trough these years.

The implementation is under LicenseZero Parity and is currently in early development with the hopes of funding the development of a DisCO / Platform Coop for Local Decentralized Economic Planning.

Thanks for your awesome and inspiring work and hopefully we will be in touch to contribute as much as possible.

https://gitlab.com/LibreCybernetics/LaTiendita / https://latiendita.coop

**Comment by fosterlynn** [comment]
Welcome @fabianhjr and thanks for the heads up!  Both an e-commerce site and local decentralized economic planning will be very exciting, I don't know of anyone else doing either one using ValueFlows.  Will be useful in many places in the world.  I'm particularly interested in how you are thinking about local economic planning, seems critical for these times to get something in place to fill the void from the pandemic.  Also, just to let you know we are working with Guerrilla Media Collective related to the DisCO model, but right now only "temporary" software pending better distributed framework, etc. - maybe some other synergies there in the future.

Please let us know if you would like our help in any way, we are very happy to work directly with you to map VF to what you are doing, answer questions, etc.

**Comment by bhaugen** [comment]
@fabianhjr I sent a PM in ssb to you and @fosterlynn ...

**Comment by fabianhjr** [comment]
Hi @fosterlynn, I am thinking of building a basic ecomerce site and then start developing common ERP features for the coops that sell through the site focusing not on money flows but resource flows and take inspiration both in things documented in VF and what you both have done at Mikorizal such as localecon and the fishery resource flow.

Right now I think I don't need help, however as the software gets refined I would like to both make it available to you and others and have it interwork as smoothly as possible with other VF software.

Hi @bhaugen, I no longer have my old key. I created a new id: @YDSXYP3Tog0vjXEwarqdBAm4lvXkYdCPZyfWmkL2Pek=.ed25519. Will try to get it set up.

**Comment by bhaugen** [comment]
@fabianhjr  
> I no longer have my old key. I created a new id: @YDSXYP3Tog0vjXEwarqdBAm4lvXkYdCPZyfWmkL2Pek=.ed25519. Will try to get it set up.

No rush. I guess that PM went off into the ether, but it doesn't matter. Where would you prefer to communicate, longer-term?

**Comment by fabianhjr** [comment]
Either here, email (fabianhjr@protonmail.com) or that new id.

**Comment by dahacouk** [comment]
I'm not sure if this is relevant but my local organic store just moved over to "online ordering" because of Coronavirus. They have a 2500 item Excel that you need to choose from! And then have to send an email to them with your list! I was going nuts trying to work with the sheet so I asked Darren, our lead developer, to build a shopping interface. [This is what he produced in a few minutes](https://app.kendra.io/seasons/seasonsListProducts). It's pretty simple. It turns out they's moved to Shopify now. But I'm still interested in quick solutions. May I request @fabianhjr that you think API first and interface last in your shopping project? We can build an interface super quick using our 'data browser'. Cheers!

**Comment by fabianhjr** [comment]
Greetings @dahacouk, currently trying to do a native vf implementation and I do intend to expose data.

**Comment by dahacouk** [comment]
Awesome @fabianhjr ! When you have something API-like, that we can plug Kendraio App into, then let me know and we'll come running.

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/valueflows/-/issues/618.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
