### ISSUE TITLE
Intent (Offer/Request) <-> Resource(Want/Product/Service/Currency)

### ISSUE THREAD

**Issue by elf-pavlik** [valueflows/valueflows#62]
I create this issue to address common issue with conflating Intent and Resource.

It relates to:
- https://github.com/valueflows/resource/issues/2 (Faceted Classification)
- #32 (GoodRelations - Offer/Demand <-> Product/Service)
- http://microformats.org/wiki/h-listing
- https://web-payments.org/specs/source/web-commerce/#offers (asset & license)

We can see an Intent as an Agent offering/wanting certain Resource.

Responsibility of Resource
- What exactly or vaguely agent casting this intent offers/wants

Responsibility of Intent
- On what conditions agent wants to make it happen

Often agent can create many intents for the same Resource. For example offer particular Resource on different conditions in different social circles - eg. borrow a Product to friends but only use-together for everyone.

**Comment by elf-pavlik** [comment]
I just renamed renamed this issue, and most likely I should add link to it from https://github.com/valueflows/intent README.

Still without addressing Recipe/Plan/Reality aspect. Similar to distinction between Product or Service and various Offer(s) to provide them. Distinction between Want/Need/Desire and various Request(s) to fulfill them seems to make sense. It also seems relevant to how [Nonviolent Communication four components](https://en.wikipedia.org/wiki/Nonviolent_Communication#Four_components) have distinct Need and Request. For example:

* Need:  Tomorrow I need to travel between Amsterdam and Berlin
* Request
 * I can ask people on ridesharing site to go with them by car
 * I can ask people working in bus carrier company to go with them by bus
 * I can ask people having a group train ticket to go with them by train

**Comment by fosterlynn** [comment]
@elf-pavlik a clarification:

>We can see an Intent as an Agent offering/wanting certain Resource.

Sometimes an agent offers/wants a certain Resource, more usually when offering.  Sometimes an agent offers/wants a Resource Type, and any resource of that type will do.  See https://github.com/valnet/valuenetwork/wiki/Resource-Types-vs-Resources

**Comment by bhaugen** [comment]
Want/Need/Desire = Plan.

They may evolve into Commitments for specific fulfillments, which would still be Plans.

In terms of @elf-pavlik's travel example, somebody commits to give Pavlik a ride in their car which will leave tomorrow.

The Reality would be the actual ride in their car tomorrow.

**Comment by ahdinosaur** [comment]
from my understanding, it seems the type of interaction is orthogonal to the type of event, as in we have:

- 2 types of economic interactions: process and exchange (transfer).
- 3 types of economic events: intent, plan, flow

for example, a conversion for action regarding an exchange between Alice and i:

- i make an intent for an exchange: "does anyone have hammer i can borrow?"
- Alice makes a plan for an exchange: "i'll let you borrow my hammer tomorrow until next Friday"
- i affirm the plan: "i'll borrow your hammer tomorrow until next Friday"
- we do the flow, i borrow the hammer from Alice and return it by next Friday.

@bhaugen @fosterlynn how do y'all feel about this recap?

**Comment by bhaugen** [comment]
@elf-pavlik - looks good to me except for the claim.  If you borrow the hammer in that conversation, Alice has an implicit claim that you should return it on Friday, given your commitment to do so and taking the hammer. She has no need to instantiate the claim explicitly unless it's (for example) Saturday and you have not returned it.

So she would probably not make a Claim that Mikey returned on time. That was an economic event that fulfilled a commitment, raising the claim was not needed.
 
Invoices are the most common example of instantiated claims. In fast-flowing commercial supply chains, they started to become eliminated waste in the 1990's. People just paid based on recorded receipts,, or in more advanced ones, on planned use.

**Comment by elf-pavlik** [comment]
Interesting conversation, I really need to start using a wishlist on my website to next week should start having much more examples of Intents to share.

> Sometimes an agent offers/wants a certain Resource, more usually when offering. Sometimes an agent offers/wants a Resource Type, and any resource of that type will do. See https://github.com/valnet/valuenetwork/wiki/Resource-Types-vs-Resources

where we find

> The Resource Type is the definition of all of the Resources that belong to that Type. In programmer-speak, a Resource Type is like a class, and Resources are like objects of the class.

i would say object - an 'instance' of the class, anyways.... as I see it, in the end we always want a particular on any instance of a class
* very specific - very particular instance of a very specific class (travel on Bus nr 7 on Sat, Oct 30 at 4PM)
* less specific - any instance of a very specific class (travel on a Bus from/to sometimes next week)
* very broad - any instance of a very generic class (travel from/to within those 3 days, which includes Bus/Car/Train)


i hope we all will get our personal wishlists published online before x-mas :wink:

**Comment by bhaugen** [comment]
An actual value flow is almost always a particular instance of a fairly narrowly defined Resource Type.

Exceptions that we run into are where the Resource instance itself is not worth tracking. The particular instance did occur in real life, it's just noise to record it. Examples include work and intangibles.

There is actually a way to "inventory" work: as slots on a calendar. Used often for space and equipment sharing, and sometimes also for scheduling people. In which case, people could commit to be available for given slots on a calendar, and (often in the case of rooms where the slots are days) commit to use the room on those days, and then do so (or not).

**Comment by bhaugen** [comment]
@elf-pavlik - re intent examples: I'll ask for a bunch from the Mutual Aid Network.

**Comment by cristianvasquez** [comment]
nice coversation, this reminds me "Speech Acts", where for example we count with 'Promises', 'Declarations' etc.... http://www.pattianklam.com/2009/12/fernando-flores-speech-acts-and-networks/

**Comment by bhaugen** [comment]
@cristianvasquez - Conversations for Action, the human-level protocol that we intend to use in these situations, incorporates a heavy dose of speech acts:
http://www.itu.dk/people/kasper/REA2004/pospapers/PrasadJayaweera.pdf

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/valueflows/-/issues/62.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
