### ISSUE TITLE
RDF/Owl schema: required/optional fields

### ISSUE THREAD

**Issue by orthecreedence** [valueflows/valueflows#624]
After spending a while on google, I'm still not clear on how (or even if) Owl determines whether a datatype is required or optional. The concept seems present in both json schemas and graphql, but I'm not seeing a differentiation in the object properties in the owl schema.

Because I don't know the best way to do this (maybe `owl:cardinality`??) I can't make any useful suggestions yet. I'd be happy to help out with a PR if we find an idiomatic way of handling this.

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/valueflows/-/issues/624.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
