### ISSUE TITLE
add work xfer example

### ISSUE THREAD

**Issue by fosterlynn** [valueflows/valueflows#625]
Add an example where work (or other non-explicitly-transfer event) is traded for another resource.

Also, fix "service" to "delivery-service" in examples.

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/valueflows/-/issues/625.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
