### ISSUE TITLE
Use of Processes

### ISSUE THREAD

**Issue by orthecreedence** [valueflows/valueflows#627]
Hello, VF team! I'm deep in the woods of converting [Basis to use VF](https://gitlab.com/basisproject/core) which is turning out to be a fairly large restructure. This is giving me the opportunity to take the things I know it needs, throw out the things it doesn't, and refine it all in the context of VF. I suspect there will be a few iterations of this, but have some questions on how this might be modeled.

The first question of probably many is regarding the idea of cost buckets. Cost buckets allow a company to split up costs (for instance inventory vs operational) and assign the costs to products or services proportionally to each other. So a product that uses a lot of inventory might get assigned 80% of the inventory costs, and all products share the operational costs (and remainder of the inventory costs) equally.

I'm realizing that a VF Process might be great for this, because it has inputs/outputs and economic events (like ordering inventory or worker labor). This seems to make logical sense given my understanding of a process as a sort of grouping of events. Is my understanding here correct?

If a Process does make sense here, then I have a follow up question. One of the core concepts in Basis is tracking resources (which are defined differently than VF and can be thought of almost as "raw materials"). However, one of its goals is to model transformations of these raw materials, such that "crude oil" might be a resource but is transformed into "gasoline" and "diesel" such that the oil is used up and the resulting resources replace it by some proportion. I originally thought of using a Process to model this kind of transformation. Does it make sense to use a Process in this context when also using it in the context of cost bucketing?

I guess my question boils down to: what if a transformative process (refining crude oil) needs to have several cost-bucketing processes within it? Would the refining process actually be a scenario in this case since many processes can live under it? Or perhaps each company has separate sets of processes: transformative and cost-tracking? I like the idea of transformative processes and cost-tracking processes being the same but I'm wondering if this causes limitations for cost tracking. Or maybe this limitation is actually desired because these transformative processes would essentially be pre-defined and fairly limited in scope.

Thanks!

**Comment by orthecreedence** [comment]
Sorry, just found this: https://github.com/valueflows/valueflows/issues/290

Going to give it a read since it might answer some of my questions (process "nesting" was one of the ideas that popped into my head).

**Comment by bhaugen** [comment]
You might want to look at
https://speakerdeck.com/mikorizal/5-nrp-recipe-concepts-and-tutorial
https://speakerdeck.com/mikorizal/10-nrp-value-equation-concepts-and-tutorial?slide=16

Those decks are about our old software, NRP, but conceptually it's the same.

**Comment by orthecreedence** [comment]
One question I have after looking through these is the "overhead" concept. An accountant may never directly produce any widgets but still puts in essential labor. How might this be modeled in VF? This is fairly essential to the idea of cost buckets in Basis.

**Comment by bhaugen** [comment]
This is how we did it in NRP (precursor to VF):
https://speakerdeck.com/mikorizal/10-nrp-value-equation-concepts-and-tutorial

We'll need to have a longer conversation about how to do it in VF. Lynn and
I will talk on the side and reply later with some ideas.

**Comment by orthecreedence** [comment]
Ok, so I'm starting to think about transforming what I have so far into the concept of events and processes. Making progress. 

After kicking the overhead labor idea around in my head a bit, I have a few thoughts/solutions:

1. Some larger process that all other processes route through, which would have the overhead labor as inputs. I don't find this particularly palatable because it obscures the inputs/outputs of the processes before it. Perhaps it could be placed at the incoming boundary rather than the outgoing, but it's still not great because it acts as an obscuring aggregator.
1. The ability to assign economic events as inputs to more than one process. It's currently somewhat ambiguous (to me, anyway) in the RDF whether a type is just a 1:1 connection or 1:N (talking mainly about `EconomicEvent::inputOf` (and I suppose to some extent `EconomicEvent::outputOf`). If it's intended to be 1:N then this problem could be easily solved by distributing the administrative labor equally among each process. Effectively, the CEO's labor event would list several processes as its `inputOf`. If it's not intended to be 1:N, then another solution might be needed (hopefully avoiding #1).

**Comment by fosterlynn** [comment]
>(process "nesting" was one of the ideas that popped into my head).

Yeah, and overhead was one of the reasons it popped into ours too.  But we dropped the idea, and I see you found Scenario, which is actually different because for it to be the operational level, it is a Process not a Scenario.  One of the reasons we dropped it in terms of overhead is that it would be the exception that all the processes on the ground would fit neatly into accounting periods used for overhead, they would slop over all the time, and cause more complexity in the model (including the obscuring issue you pointed out) for we thought not good enough reasons.

>I guess my question boils down to: what if a transformative process (refining crude oil) needs to have several cost-bucketing processes within it? Would the refining process actually be a scenario in this case since many processes can live under it? Or perhaps each company has separate sets of processes: transformative and cost-tracking?

I think your example of refining is the best use of process, especially since you want to do the tracing and tracking of value flows.  I think of processes as more than groupings of events, although they are also that - they really are transformation or transportation.  And I don't think parallel sets of processes is a good idea, I think you would make things hard for yourself..... more below...

>The ability to assign economic events as inputs to more than one process. It's currently somewhat ambiguous (to me, anyway) in the RDF whether a type is just a 1:1 connection or 1:N

I also don't think this is a good idea, I think it complexifies (we made up that word) the relatively simple shape of the model, as well as is kind of misleading about the actual operational inputs and outputs.  You are absolutely right about RDF, and our turtle file I expect doesn't stop you from doing that.  (Maybe some day I'll add cardenalities, but then we're in OWL2, and I don't know enough to know if that will cause people problems?  So for right now, it is in the UML diagram, sorry not machine readable.  So if you want them, I'll add them.) .....

So, let's think about a better way to do the cost buckets.  Some options that come to mind, probably in combination with each other:
* The actions on events give you some information, like it was work, it was usage (implying use of some fixed capital perhaps), etc.
* Almost everywhere you can classify with multiple classifications of your choice.  Seems like event and/or resource and/or resource specification classifications could give you possibly as much information as you want, because you can define and structure those however you like.  And you can have as many as you like.  For example, on resource specifications or economic resources, you could classify as "raw material" vs whatever.  I see no problem with Basis having its own set of classifications that it uses instead of or in addition to user chosen ones.

@orthecreedence does any of that seem like it could be a direction for cost buckets?  @bhaugen any other thoughts?

**Comment by fosterlynn** [comment]
>One question I have after looking through these is the "overhead" concept. An accountant may never directly produce any widgets but still puts in essential labor. How might this be modeled in VF? This is fairly essential to the idea of cost buckets in Basis.

Didn't really address this yet..   

Some info from @bhaugen : @orthecreedence part of what you want to do is what cost accountants call overhead allocation, for example https://www.accountingtools.com/articles/2017/5/14/overhead-allocation.  REA accountants like to try do the best they can to allocate overhead to the processes it belongs to, but it often belongs to more than one, so it's necessary to split it up into several processes.

I think generally, it's good to create overhead-y processes for what is actually being done, like "monthly bookkeeping", or at whatever level of detail is useful, and record directly onto that.  In terms of splitting it across other processes that more directly create value, if possible I think that should be done not as part of operational recording of what happened, which should be very observational and factual, but should be allocated as part of analysis of observed events, like putting into cost buckets or creating accounting reports. Then you have the freedom to do it how you like, others might do it differently for a different kind of analysis, or even the same kind, etc., maybe based on governance.  Also, people doing the overhead work may not have enough information when they are doing the work, perhaps it needs to be split evenly across all the processes for the month or something, or weighted based on other factors you have suggested.  And people could change their minds later and want to re-allocate.

So part of "costing" maybe is running a process against recorded events and storing that info.  (I wonder if we have a place for that?  I don't understand what you want to do enough to think about that yet probably.  But happy to continue to help think through it....)

**Comment by orthecreedence** [comment]
> But we dropped the idea, and I see you found Scenario, which is actually different because for it to be the operational level, it is a Process not a Scenario.

Ok, so scenario is not the right thing to use here. That's what I was thinking but also wanted to make sure I wasn't missing something.

> One of the reasons we dropped it in terms of overhead is that it would be the exception that all the processes on the ground would fit neatly into accounting periods used for overhead, they would slop over all the time, and cause more complexity in the model (including the obscuring issue you pointed out) for we thought not good enough reasons.

I think this makes sense. The more I think about it, the more the idea of a standalone, singular process makes sense, and nesting them adds in a lot of (probably unneeded) complexity.

>  I think of processes as more than groupings of events, although they are also that - they really are transformation or transportation.

This is helpful.

> And I don't think parallel sets of processes is a good idea

Agreed, different sets of processes that do different things is probably asking for trouble.

> For example, on resource specifications or economic resources, you could classify as "raw material" vs whatever. I see no problem with Basis having its own set of classifications that it uses instead of or in addition to user chosen ones.

That seems really obvious now, but I hadn't thought about using EconomicResource to track raw materials. Although given that VF resources can contain other resources, it would actually fit nicely into the cost tracking. Does tracking labor hours as a "resource" also make sense then? It should be easy enough to rebuild it from walking back the `work` events but just kind of spitballing here.

> https://www.accountingtools.com/articles/2017/5/14/overhead-allocation

Ok, so record the work into various processes, then pipe the outputs of those processes into the places they make sense on a per-business level. This is fairly close to what I was thinking.

>  I don't understand what you want to do enough to think about that yet probably.

A quick overview might be helpful.

In the pre-VF version of Basis, costs are essentially contained at the company level. The company is a black box, and can choose to internally account for things however it wants, using whatever software it wants. That said, Basis requires that in all cases, the outputs match the inputs. If in a given week we produced 100 chairs and it took 400 labor hours and 500kg lumber, then it follows that each chair costs exactly `(4L, 5kg lumber)`. However, if you have two different types of chairs, it doesn't make sense to divide the costs evenly. If chair 1 uses twice the lumber inventory as chair 2, then it makes sense to bucket the costs:

- When ordering our input lumber, we assign the cost to our `inventory` bucket
- We have a `production` bucket that contains the labor hours for production, and also an `overhead` bucket for everyone not directly related to production.
- On the product side (outputs) each chair type (ResourceSpecification) links to a cost bucket with some proportion.
- Chair 1 uses twice the inventory and three times the labor as chair 2, so chair 1's cost bucket link looks like `(inventory:2, production:3)` and chair 2 has the tags `(inventory:1, production:1)`. Unassigned tags (for instance `overhead`) are assigned in equal proportion to all products.
- So if inventory was 500kg lumber, chair 1 gets `(2 / (2 + 1)) * 500` of the inventory cost, chair 2 gets `(1 / (2 + 1)) * 500`. Essentially, for each linked cost tag, we divide the weight value by the total summed weights

This effectively forces all incoming and internal costs to be assigned to products/services on the outgoing side. So my challenge is thinking of a way to model this using processes such that there are no "dead ends" or lost costs. In market systems, this is enforced naturally because unaccounted for costs means bankruptcy. In a system that doesn't use exchange/profit, there has to be a systemic way to ensure that costs are all accounted for.

So in the pre-VF Basis, I suppose a company could have been one big process given its black box nature. I could keep that model and use the original cost buckets internally, but I am interested in leaning on VF as much as I can.

Thanks for your input here!

**Comment by orthecreedence** [comment]
Ok, after thinking about this a bit more, I have an idea of how to model this with processes, and I am fairly certain they can supersede cost buckets. There are some problems to solve, but the problems are the exact same as the old model anyway now that I think about it. Thanks for helping me think through this.

Would still like any thoughts you have on using EconomicResource for tracking costs (labor hours, wages, resources). I'd like to track them all in the same method, so if wages/labor hours don't make sense to track as sub-resources, I might track "raw materials" separately as well.

**Comment by orthecreedence** [comment]
One more follow up question: are processes always ephemeral in idiomatic VF? Or can a process (not a process specification, but the process itself) live on indefinitely? For instance, if I have a "make shirt" process, does a new one need to be created each time a new shirt is created? Or can the same process instance be used over and over?

**Comment by fosterlynn** [comment]
>One more follow up question: are processes always ephemeral in idiomatic VF?

More or less, and "more" in any case you want to know exactly what inputs went into an output (which could be a large batch or could be one, but whatever granularity the work actually happens in.  One thing that comes to mind in the "less" category is "stream processes" like production lines that just keep running.  And I don't actually know what makes sense there for a process, again I think it would have to do with what they need to know about tracing back from the output(s).  Another kind of long-running process might make sense for some of those overhead kinds of work that don't really produce distinct outputs, like "coordinate the project".  But I think the answer is "mostly yes".

**Comment by fosterlynn** [comment]
>Would still like any thoughts you have on using EconomicResource for tracking costs (labor hours, wages, resources). I'd like to track them all in the same method, so if wages/labor hours don't make sense to track as sub-resources, I might track "raw materials" separately as well.

Caveat: I haven't yet understood exactly how you are tracking costs, and am just thinking about your question now.  I think that tracking costs will be driven by events.  EconomicResources are a snapshot.  And EconomicResource implies something actually inventoried (including real stuff, currency accounts, etc.), which work is not.  I think that ResourceSpecification as related to events could do it for you.  And from there, whatever classifications you want to keep on ResourceSpecification.  Types of work, and really any kind of little-r resource can be represented there.  What do you think?

**Comment by orthecreedence** [comment]
This all makes sense. Thanks for the thoughts here.

> More or less, and "more" in any case you want to know exactly what inputs went into an output (which could be a large batch or could be one, but whatever granularity the work actually happens in.

I think where I want to track events is the company boundaries (ie, incoming/outgoing orders). Eventually tracking events internally would be desired, but for now I want a non-opinionated way of tracking costs, with the option of opting in to a full VF system if desired.

So I'm thinking internally in order to track the flows of costs that instead of the original idea of cost buckets, companies can use `RecipeFlow`/`RecipeProcess`. This would still allow standard transformations (which my old model was severely lacking) but as far as I know does not require tracking all internal events because the costs would mainly be derived from the interconnected RecipeProcess objects. Would this be an ok approach?

Actually I just realized that a problem might be that we are going to be tracking labor/work events, which *are* internal, and I suppose those can't attach to `RecipeProcess` objects. It seems I'm kind of stuck between using `Process` objects in a non-ephemeral way and going outside their intended use, or trying to create Process objects automatically and attaching some events to them. I guess the other alternative is to treat the company like a black box again and use another method for cost accounting and resource transformations. None of these methods feel super great to me, although for the sake of simplicity maybe all the Processes internally in a company could be "stream" processes (even if they aren't internally). 

> And from there, whatever classifications you want to keep on ResourceSpecification. Types of work, and really any kind of little-r resource can be represented there. What do you think?

That's how it's done in Basis right now, the costs are tracked on the `ResourceSpecification` equivalent. So I think this makes the most sense.

**Comment by fosterlynn** [comment]
@orthecreedence a couple more concerns about using recipes:  
* They give you a good idea of what "should" have gone into making something, but don't give you what did go into making something.  (Perhaps that is a good thing for you though, seems like you want to have some standard costing formula per product?  Maybe adjusted for different time periods?)  
* Not everything can use a recipe.  What about "job shops" that do more custom work?  Or any kind of more custom goods or services?  So they would work for "commodity" production, but not for anything else.  Not sure what percentage that covers.  Perhaps some very average recipe, or some other formula could handle that type of thing.  

>Actually I just realized that a problem might be that we are going to be tracking labor/work events, which are internal, and I suppose those can't attach to RecipeProcess objects.

No, you could account for work using RecipeFlows same as anything else.  All actions will apply to a recipe as well as a plan or observed events, so tool and equipment usage can work that way too.  And really agents external to the company (who have some sort of agreement with the company) are providing the work, so it can be an input to the company same as any component part.  At least post-slavery. :)

Which makes me think that inputs from "nature" will need to be accounted for as coming in to a company too, not just buried inside.  Which seems do-able.

**Comment by orthecreedence** [comment]
Thanks so much for your help here. I'm still mulling this over, but think I have enough to move forward for now.
