### ISSUE TITLE
Migrating the GitHub organization 'valueflows' to GitLab, instance lab.allmende.io

### ISSUE THREAD

**Issue by almereyda** [valueflows/valueflows#629]
Continuing from the discussion in https://github.com/valueflows/valueflows/issues/526, here I am proposing a suitable workflow for migrating user-generated content and users off from GitHub, in this case towards an independent, community-based GitLab instance maintained as a Common at lab.allmende.io. It is provisioned as one of the core contributions of the not-for-profit association Ecobytes to the public domain.

To conduct the migration, we want to make use of the automatic import capabilities of GitLab, and can prepare the environment a little to increase the level of re-integration. Commits and comments will be mapped to an existing GitLab user, if (a) it exists in advance and (b) has the same email identities used in commits and configured in the GitHub profile associated.

- [x] Create valueflows group https://lab.allmende.io/valueflows
    - [x] Add group description
- [x] Onboard existing users
    - via manual registration on https://lab.allmende.io/
    - via email invitations sent from https://lab.allmende.io/groups/valueflows/-/group_members
- [x] Add users to the Value Flows organisation
    - via a click to request to join the group on https://lab.allmende.io/valueflows
    - via the group members page at https://lab.allmende.io/groups/valueflows/-/group_members
- [ ] Replicate permissions from GitHub
- [ ] Import organization and projects ¹ ²

¹ https://lab.allmende.io/help/integration/github.md - in place
² https://lab.allmende.io/help/user/project/import/github.md - workflow

An additional effort comes with keeping visibility of the organisation on GitHub. Here we can make use of the the repository mirroring ³ functionality, that allows to republish pushed commits to a remote target.

- [ ] Configure repository mirroring for all valueflows repositories

³ https://lab.allmende.io/help/user/project/repository/repository_mirroring.html

**Comment by fosterlynn** [comment]
Pinging @elf-pavlik @mayel @pospi @bhaugen @pmackay @dahacouk @jvanbockryck @JamesVorder @ahdinosaur @aspasia @Connoropolous @djodjoni @gcassel @ivanminutillo @stevebosserman @fkleedorfer @orthecreedence - and I'm sure others - we are slowly getting ready to move to gitlab, and if you all sign up before we do the move with the same email address, all your posts will get moved properly.  (See above in this issue for links.  If you don't, I'll also try inviting you from there, if I have your email address, which I'm sure is not all of you.)

We plan on working in gitlab, but keeping the github version synced too, so this all should be retained.  But it would be nice to have it all properly in the new setting.  Especially those who have made a lot of contributions, including issue discussions!! :heart: :heart: :heart:

**Comment by orthecreedence** [comment]
Thanks for the heads up, I created an account over there!

**Comment by stevebosserman** [comment]
Thanks, Lynn. Created an account on GitLab per your request.

**Comment by almereyda** [comment]
Thanks Lynn for showing the steps. I liked how you requested to join the group https://lab.allmende.io/valueflows almost immediately after it had been created.

When you succeed with your registration, you can move to that page and already request to be granted access. I have amended the issue description above accordingly.

**Comment by fosterlynn** [comment]
@almereyda thanks!  I didn't know people could request access.  I'm also happy to invite people, if they let me know here.  Will invite @stevebosserman and @orthecreedence .

**Comment by jvanbockryck** [comment]
Hi @fosterlynn , I updated my Gitlab account to match my username and email.

**Comment by fosterlynn** [comment]
>Hi @fosterlynn , I updated my Gitlab account to match my username and email.

Hi @jvanbockryck good to see you!  I don't find you.  Note this is not the regular hosted gitlab, it is another instance hosted in Europe by Ecobytes, first register here https://lab.allmende.io/.

**Comment by jvanbockryck** [comment]
@fosterlynn just registered on https://lab.allmende.io/.

**Comment by almereyda** [comment]
With the observable traction, can we already conclude a date the migration takes place, or will we want to choose an open time frame up to a point, when we don't see enough new registrations coming?

Meanwhile on https://lab.allmende.io/groups/valueflows/-/group_members

@fosterlynn @bhaugen @elf-pavlik I have added you as owners of the group.

All, please also allow me to bring https://meta.allmende.io back into the discussion, based on the suggested #36, currently the forum.valueflo.ws repo. Many discussions regarding ontologies and modelling could also happen out in the open, outside from a development environment like GitLab, which often confuses users, and ease accessibility and participation in discussions. We'd love to see the Value Flows logo there next to the other commoning communities. And thus I'd propose a wider ranging communication "strategy", involving the website, Gitter, the repositories and eventually a public discourse, similarily aligned to what is presented in http://openlearning.cc/base/

**Comment by pmackay** [comment]
@fosterlynn I've registered now too :-) Should be same username/email as Github.

**Comment by fosterlynn** [comment]
@pmackay so nice to see you have registered!  I still use the "bike with dodgy brakes" story, just so I can sound British. :)

**Comment by fosterlynn** [comment]
@almereyda 

>With the observable traction, can we already conclude a date the migration takes place, or will we want to choose an open time frame up to a point, when we don't see enough new registrations coming?

I'm trying to round up people who have contributed a lot but haven't signed up.  Hoping to be as done as we can be soon.  Also I cut a release in prep for the move, to be at some sort of defined point.  So we can set a date if you like, any time after say Friday?  Maybe you and I set aside time for a couple days when we do it, so we can troubleshoot etc?  I can do it on your schedule.

We'll also prep changes to the github repo to tell people what has happened.

**Comment by fosterlynn** [comment]
Getting out of github soon!  Pinging @djodjoni @dahacouk @fkleedorfer @nogo10 @Connoropolous @coopchange  - it would be lovely if you register here https://lab.allmende.io/ !  And remember to use the same email you use in github.  Thanks! :heart:

**Comment by fosterlynn** [comment]
Good morning @almereyda I'm around.

**Comment by fosterlynn** [comment]
OK!  Well, @almereyda and I decided to consider our efforts today to be a test! :)  Everything worked except comments for some people were not able to find the corresponding user in gitlab.  Jon figured out, and we tested it, that besides the need to use the same email, people need to also set explicitly the social signon to github from gitlab, here https://lab.allmende.io/profile/account.  I expect you could deactivate that after we do the migration if you want.  Users who need to do this: me, @bhaugen , @fkleedorfer , @orthecreedence , @stevebosserman , @pmackay , @Connoropolous , @mayel , @pospi .  Others worked, or don't have any issue comments.

Sorry about that, friends!  Please let me know here (or wherever) when you have done it.

Here is a screen shot, where I have already activated github as social sign-in.

![gitlab-signin](https://user-images.githubusercontent.com/3776081/84529252-bf2a7200-aca6-11ea-810f-7db6d008a87f.png)

**Comment by fosterlynn** [comment]
P.S. That means we can use this VF repo for continuing discussion in the meantime.

**Comment by orthecreedence** [comment]
Done! (Connected github to my account there)

**Comment by pospi** [comment]
done!

**Comment by stevebosserman** [comment]
I did it!

**Comment by jvanbockryck** [comment]
Done

**Comment by bhaugen** [comment]
Done

**Comment by pmackay** [comment]
Done :)

**Comment by TiberiusB** [comment]
Why Gitlab?!

I personaly don't like their price politic. Perhaps I am missing something,
but I don't understand the hype around Gitlab. Can someone try to change my
mind?

**Comment by orthecreedence** [comment]
I think being open source and self-hostable are great points in favor of Gitlab. I use both regularly (I've used paid and unpaid Github as well as unpaid Gitlab) and as far as features go, Gitlab is easily as powerful/useful in my experience as Github. I tend to like the interfaces of both. The only real aspect missing from self-hosted Gitlab is network effect, but that's somewhat negligable with git hosts anyway because they are less about network building and more about collaboration on specific projects.

**Comment by fosterlynn** [comment]
>I personaly don't like their price politic.

We are using a self-hosted gitlab, hosted by Ecobytes, free to us, although I wouldn't mind supporting them.  The (giant) advantage of being open source, as @orthecreedence said.  We didn't go for the main gitlab because it is also hosted in the US therefore potentially (likely) subject to the US sanctions that finally gave us enough energy to get out of github.  And gitlab has a big "business plan" and is firmly embedded in capitalism, given their financial supporters.  I don't think gitlab is going to change the world.  Just didn't find any other good options right now.  And it is important to me that a VF founder and good comrade @almereyda is part of Ecobytes and is supporting VF through the move, and beyond.

>The only real aspect missing from self-hosted Gitlab is network effect

Yeah, and I expect we will miss that to some extent, getting another login is just one more hurdle for people to participate.  Hoping for federated git some day !

**Comment by Connoropolous** [comment]
I'm over there too 👍

**Comment by TiberiusB** [comment]
Thank you all very much for the explanation.

**Comment by almereyda** [comment]
Thank you everyone for following up and linking your GitHub logins to the new accounts at the lab.allmende.io GitLab, and @fosterlynn thanks for the collective note taking.

We seem to be quite ready for another attempt of the move, eventually best by the end of next week?

That could give @TiberiusB, @mayel and @fkleedorfer some more time to attach their accounts. Is that a thing that could be quickly achieved for you?

After registering via email, the connection buttons for social sign-in are available at https://lab.allmende.io/profile/account

It is also possible to directly register and login with your GitHub identity, which renders the extra connection step obsolete.

**Comment by fkleedorfer** [comment]
Thanks @almereyda, I am a member of the new valueflows group, AFAICT

**Comment by mayel** [comment]
OK I've linked mine

**Comment by fosterlynn** [comment]
>Thanks @almereyda, I am a member of the new valueflows group, AFAICT

Hi @fkleedorfer , yes you are a member, but we found out we need one additional step so your issue comments will transfer over under your id, see here https://github.com/valueflows/valueflows/issues/629#issuecomment-643392923.  If you did that, you're set!

**Comment by fosterlynn** [comment]
@TiberiusB hmmm, seems like I somehow missed you on my original list of people who had contributed to discussions in VF.  Sorry about that!  If you follow the instructions at the beginning of this issue and sign up with your github identity, I think that you can do it in one step.  Thanks!

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/valueflows/-/issues/629.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
