### ISSUE TITLE
Immutability and monotonic reasoning for VF

### ISSUE THREAD

**Issue by fkleedorfer** [valueflows/valueflows#630]
I am building a SHACL-based system for automatically making all the inferences in a VF model expressed in RDF. The goal is that this gives you a VF engine that does ALL the calculations that VF prescribes, so if you build your application based on it, you can focus on providing the inputs and handling the outputs. Inputs are rejected if they violate the rules. Outputs are `Fulfillments`, `Claims`, `Satisfactions`, changes to `EconomicResources` (and probably some more).

The technique I am using is being developed as [SHACL Advanced Features](https://www.w3.org/TR/shacl-af/), especially the new Rules feature, which does monotonic reasoning. It allows you to *generate* triples in response to certain conditions present in the data, but not delete any triples.

Unfortunately, the VF model does not lend itself to monotonic reasoning in its current state. One problem is that an `EconomicEvent` can change an `EconomicResource`'s `(accounting|onhand)Quantity` (or `currentLocation`, or `primaryAccountable` - which means deleting a triple and generating a new triple. So, I am thinking about tweaking the model to accommodate for that, and I appreciate any comments:

Essentially, `EconomicResources` need to become immutable, and an `EconomicEvent` that involves an `EconomicResource` *always* generates a new object - the next version or next state of the resource. Consequently an `EconomicResource` can only ever be involved with one event. With that change, the VF model becomes a complete history of all resource modifications. This would require a new relationship, eg. `vf:previousState`, and disallow any `EconomicEvents` on `EconomicResource` instances that have a `vf:previousState` relationship pointing at them. Thus, the latest version of an `EconomicResource` is the head of a linked list of versions, and each version is connected to the `EconomicEvent` that  caused the change.  If you have a planning or recipe entity that references an `EconomicResource`, let's say, a `Commitment`, and you now want to generate the `EconomicEvent` that will fulfill it, it is possible that the referenced `EconomicResource` has already been involved with other `EconomicEvents`. In that case, it would not be the head of the `vf:previousState` chain and you would have to find the head of that chain in order to instantiate your `EconomicEvent`. 

Currently, I can't think of another entity in the VF model that currently needs to be mutable, so that would be the only major change. Am I missing one?

**Comment by bhaugen** [comment]
@fkleedorfer - 

Bill McCarthy, the father of REA, never instantiates EconomicResources at all. He always computes the resources and their quantities and locations as needed by summarizing the EconomicEvents.

At least one of the current VF software implementations will do it that way (Holo-REA) and others may do likewise.

Does that help with your quest for monotonic logic? If so, we probably should document that pattern more clearly.

**Comment by bhaugen** [comment]
@fkleedorfer - @fosterlynn says that VF:EconomicEvents will need some changes to accommodate that practice. Doesn't include all of the necessary information.

I think that Holo-REA will instantiate EconomicResources but not their mutable properties. Would that be an acceptable compromise for your needs

**Comment by bhaugen** [comment]
I think the whole pattern of instantiating resources and their quantities on the fly from events would be called map-reduce. Right @fkleedorfer @pospi ?

**Comment by fkleedorfer** [comment]
> Does that help with your quest for monotonic logic? If so, we probably should document that pattern more clearly.

I would not have guessed that based on the docs. It requires, however, to have some sort of ordering among the events involving one resource, I don't see that in the model, either. Anyway, I'll try with the event states for now, as suggested above. I like that it is always easy to know the last state this way, and the event ordering is clear, too.

>  @fosterlynn says that VF:EconomicEvents will need some changes to accommodate that practice (of not instantiating resources at all). Doesn't include all of the necessary information.

That is interesting, I wonder what is missing. Something specific one or some actions or some cross-cutting thing?

**Comment by bhaugen** [comment]
@fkleedorfer 
> It requires, however, to have some sort of ordering among the events involving one resource, I don't see that in the model, either. 

For ordering, use EconomicEvent.hasPointInTime or (EconomicEvent.hasBeginning and EconomicEvent.hasEnd).

> > @fosterlynn says that VF:EconomicEvents will need some changes to accommodate that practice (of not instantiating resources at all). Doesn't include all of the necessary information.
> 
> That is interesting, I wonder what is missing. Something specific one or some actions or some cross-cutting thing?

Nothing is missing if you instantiate an EconomicResource with the less-mutable properties like name, classifiedAs, note, image, trackingIdentifier, conformsTo, etc. and only compute properties like quantities and location from events. Otherwise, if you do not instantiate resources at all, those other properties would need to be added to events. 

Clear enough? And this thread starting to give you workable answers?

**Comment by fkleedorfer** [comment]
yes, thanks!

**Comment by bhaugen** [comment]
@fkleedorfer we'll be very interested in what you do with SHACL and VF.
