### ISSUE TITLE
Question on amortization/depreciation

### ISSUE THREAD

**Issue by orthecreedence** [valueflows/valueflows#632]
I'm working on modeling cost tracking in Basis using processes, and one of the questions that came up for me is amortization of a cost over a period of time.

If my company buys a widget machine, and its expected lifetime is 10 years, when we use that widget machine for a day, is there a built-in way to express the *cost* of the use of the widget machine? For instance, if the widget machine cost $5000 and lasts 10 years then if we make 100 widgets/day with it, I would expect each widget to have the cost of the widget machine embedded in them as `$5000 / (100 * 365 * 10)` or `$0.014044944` + whatever labor/materials were used for the widget.

What does it look like/how is it expressed in VF to spread the cost of an asset over a period of time?

**Comment by orthecreedence** [comment]
I think I figured this out (but feel free to comment with notes if you have any): each `use` event would attribute some cost (how much cost is up to the company and how they do their accounting) to the process that uses the machine.

Overall, the process/event model is really helping me think through this in a really rigorous way. I'm identifying some flaws in how I was doing things before. I'm interested to see how things will go as I implement more of VF into Basis.

**Comment by fosterlynn** [comment]
What you are saying makes sense - you would need to take into account the action maybe in all cases.  What seems to be missing from VF for this use case is the expected life of something that will be "depreciated" or "amortized".  Somehow one will have to guess the expected life, if any cost based accounting is to be done before the thing actually gives out.  (Ignoring the way depreciation is currently used for tax purposes, etc., with already defined rules.)

This also brings up another thought for me, which is maintenance and repair of the thing being amortized.  Over its life, more inputs will be going into it, in addition to what went into creating it.  The data will be there; not sure how one would want to account for that in your use case.

Actually brings up one more thought, which is about Basis, not VF.  I like that you are using labor + raw materials as the two kinds of inputs that are costed.  Maybe raw materials have sort of the same kinds of constraints that a piece of equipment or a building has: limited lifetime (or limited supply).  And that could give some way to better live within the planetary boundaries?  Just thinking out loud.

**Comment by bhaugen** [comment]
@orthecreedence 
>  I'm interested to see how things will go as I implement more of VF into Basis.

Us too!

**Comment by orthecreedence** [comment]
> What seems to be missing from VF for this use case is the expected life of something that will be "depreciated" or "amortized". Somehow one will have to guess the expected life, if any cost based accounting is to be done before the thing actually gives out. (Ignoring the way depreciation is currently used for tax purposes, etc., with already defined rules.)

Possibly, but it seems like VF can handle the relationships just fine and people can attach whatever data they want to their resources after the fact. A lot of the work I'm doing involves using VF as a core piece that sits inside another object (which might have costing information attached directly). This followed from a discussion I had with Bob (#616) So far this model is working well.

> This also brings up another thought for me, which is maintenance and repair of the thing being amortized. Over its life, more inputs will be going into it, in addition to what went into creating it. The data will be there; not sure how one would want to account for that in your use case.

This is an interesting one, and I'm hoping to be able to model this in a somewhat natural way. We'll see what comes of it.

>  Maybe raw materials have sort of the same kinds of constraints that a piece of equipment or a building has: limited lifetime (or limited supply). And that could give some way to better live within the planetary boundaries? Just thinking out loud.

Yes, this is one of the ultimate goals! The ability to know rate of consumption along with renewal rates and data about known quantities would allow better collective decision making regarding our resources.

It's interesting to think about modeling them the same way as a resource within a productive entity. VF already does this by default, so maybe the concept of amortization and depletion/renewal could be built at a very core level. Definitely something to think about.

Thanks!

**Comment by fosterlynn** [comment]
>so maybe the concept of amortization and depletion/renewal could be built at a very core level.

Yeah, I think there is enough universality to it to strongly consider it.  One way to do that would be to see how it works for you, and then use that to build it into VF, in case I'm wrong about needing just that one property on EconomicResource.  But, if you are generating your schemas, that isn't so good.  So, if you decide you want it in core VF, let's talk.  And maybe by that time you will have a reasonably good idea of how it would work.

**Comment by orthecreedence** [comment]
I think that makes a lot of sense. Let's see what I come up with. I'll circle back around when I have something more solid and if it can be generalized then I'd be happy doing the work to move it out of my model and into core VF!
