### ISSUE TITLE
Update resources only from events?

### ISSUE THREAD

**Issue by fosterlynn** [valueflows/valueflows#637]
The question has come up recently here https://github.com/valueflows/valueflows/issues/636#issuecomment-633201754, as well as earlier with @fkleedorfer , and earlier than that with @pospi on Holo-REA.  We have said sometimes in the past that in REA, economic resources can be derived from economic events.  And in fact, Bill McCarthy does that, although he is working with a much smaller set of core data.  That has never been totally true in VF, where the key economic data can be derived from events (quantities, resource specification), but not the secondary non-economic data which also has some gray areas of economic-ness.  Gray examples might be trackingIdentifier, lot, containedIn.  Where note or name aren't really economic.

Coming out of the Holo-REA experience, as well as in earlier software, if a resource was to be created by an event, we just sent the "extra" resource data as extra parameters to the code that did the create.  And in our earlier software, the UI handled getting basically 2 sets of data for one create method that creates an event and a resource.

A note:  almost all of the non-quantity resource data generally only would be changed because a data entry mistake was made, or clarification was needed (like note).

@bhaugen and I discussed.  My current thinking is that we probably want to add at least one new action; but that we don't want to be creating "extra" economic events that don't do anything economic, too much clutter - and that for that we just update resources.  Meaning we won't ever be able to completely derive economic resources from events.  More discussion needed!  @bhaugen @pospi @fkleedorfer , maybe @mayel @ivanminutillo .

**Comment by fosterlynn** [comment]
My current thoughts, for discussion:

FIrst, the more I think about it, I don't think we want to make it so that you always need an economic event to make any update to resource data, as many of those won't be economic.  Note that in all current implementations afaik, the programming environment will still keep update records and/or versions of all records, and manage what is the current version for the dev, so the information is not lost.

Following from that then is what is "not economic" so would and would not be updated by an economic event?  First thoughts:

* vf:name - directly on resource
* vf:trackingIdentifier - directly on resource? - constraints ???
* vf:lot - directly on resource? - constraints ???
* vf:accountingQuantity - only by event
* vf:onhandQuantity - only by event
* vf:currentLocation - only by event
* skos:note - directly on resource
* vf:conformsTo - directly on resource - constraints ???
* vf:classifiedAs - directly on resource
* vf:containedIn - add new actions for this (pack/unpack?), only by event
* vf:image - directly on resource
* vf:unitOfEffort - directly on resource
* vf:stage - not user updated, derived from other data
* vf:state - not user updated, derived from other data

**Comment by bhaugen** [comment]
@fosterlynn @fkleedorfer 
Do you think it would be good to have an ActivityStreams-kind of non-economic event to update the non-economic data on a resource? Then it would still be possible to recreate resources from events, you'd just need to replay two event histories...

**Comment by fosterlynn** [comment]
>Do you think it would be good to have an ActivityStreams-kind of non-economic event to update the non-economic data on a resource? Then it would still be possible to recreate resources from events, you'd just need to replay two event histories...

Yes, I like this quite a lot.  So in ActivityStreams, it would be an activity (Update or Delete).  For other things that aren't part of this event > resource thing, like say a Process, it could also be Create perhaps.  I suppose that would be for technologies that don't already handle that kind of versioning as part of how they natively do things?

**Comment by pospi** [comment]
FWIW, the conversations we had in Holo-REA lead to the following edit behaviour:

- [Direct `EconomicResource` edits](https://github.com/holo-rea/holo-rea/blob/2d92bf2/lib/rea_economic_resource/storage/src/lib.rs#L148) are only for correcting data entry errors
- All other modifications to resources must happen [through `EconomicEvent` creation](https://github.com/holo-rea/holo-rea/blob/2d92bf2/lib/rea_economic_resource/storage/src/lib.rs#L166)

**Comment by fosterlynn** [comment]
>Direct EconomicResource edits are only for correcting data entry errors

Looks like the quantities are in this.  I want to make sure I understand you, and that we are (or can get to) the same page.  I don't think the quantities can be updated due to data entry error, because we can't control timing of people publishing accounting reports.  I think that would best handled by backing out the event (negative number), and re-entering the event correctly - and we'd have to think a bit about the date handling.  Or it could possibly be handled with a `raise` or `lower` event with an explanation.  Also from that perspective, we could pull currentLocation from my list above, and just include it in the data entry error set, it is just operational.  @bhaugen @pospi does this make sense to you?  

(Or maybe I misunderstand, since of course something has to update quantities on resources if they are not calculated on the fly.

**Comment by pospi** [comment]
No, you're correct.

            accounting_quantity: self.accounting_quantity.to_owned(),
            onhand_quantity: self.onhand_quantity.to_owned(),

These two lines (referencing `self`) mean that the values in the updated record are copied across from those in the original, rather than being applied from the update payload. Perhaps the input payload would have been a better reference for the shape of the data- https://github.com/holo-rea/holo-rea/blob/56d30c3/lib/rea_economic_resource/rpc/src/lib.rs#L80

**Comment by orthecreedence** [comment]
Wow good time for me to drop by the issues, I am just now building out the `EconomicResource` transactions in the new Basis and was going to ask about this.

FWIW I'm solving by using create/update/delete on resources, but only allowing it on some fields, and using events to manage the rest.

>     * vf:name - directly on resource
>     * vf:trackingIdentifier - directly on resource? - constraints ???
>     * vf:lot - directly on resource? - constraints ???
>     * vf:accountingQuantity - only by event
>     * vf:onhandQuantity - only by event
>     * vf:currentLocation - only by event
>     * skos:note - directly on resource
>     * vf:conformsTo - directly on resource - constraints ???
>     * vf:classifiedAs - directly on resource
>     * vf:containedIn - add new actions for this (pack/unpack?), only by event
>     * vf:image - directly on resource
>     * vf:unitOfEffort - directly on resource
>     * vf:stage - not user updated, derived from other data
>     * vf:state - not user updated, derived from other data

That's pretty much exactly what I was looking for, thanks!

I do have a question though: do `raise`/`lower` actions generally only apply to a resource's "accounting quantity" or can they also apply to "onhand quantity" (and if so is there a built-in way to differentiate)?

**Comment by orthecreedence** [comment]
Another, regarding these two:

> * vf:stage - not user updated, derived from other data
> * vf:state - not user updated, derived from other data

I get `stage` is updated when a resource is an output of a process that references a spec, this can be automated by event. Wouldn't this then be listed as "only by event"?

As far as `state` being derive from other data, can you expand on what that might look like? Thanks!

**Comment by fosterlynn** [comment]
>I do have a question though: do raise/lower actions generally only apply to a resource's "accounting quantity" or can they also apply to "onhand quantity" (and if so is there a built-in way to differentiate)?

They will apply to both accounting quantity and onhand quantity, which you can see here https://valueflo.ws/introduction/flows.html#actions and scroll down a bit for the table.  But, I'm thinking about what if those two fields are starting from a different point and being used for a manual inventory count correction.  And same condition for if this is for a beginning balance for a new system.  There might be some gotchas involved, but for now, let's just say that they apply to both fields, and that in general you can follow the table.  That data is also part of Action (recently improved), so you can drive it from the Action data rather than write logic for it.

**Comment by fosterlynn** [comment]
>FWIW I'm solving by using create/update/delete on resources, but only allowing it on some fields (and with some other restrictions), and using events to manage the rest.

I don't think you should ever need a Create on a resource, except in that it happens when the event that creates the resource is created.  But maybe that is what you are using it for...

>As far as state being derive from other data, can you expand on what that might look like? 

Placeholder:  I have to go back and look at this again.  This was for pass/fail on testing processes, but we got rid of those as actions.  So I need to get my head back into that thought process and then answer.

>I get stage is updated when a resource is an output of a process that references a spec, this can be automated by event. Wouldn't this then be listed as "only by event"?

That could make sense.  I just meant that data wasn't part of the event itself.

**Comment by orthecreedence** [comment]
> which you can see here https://valueflo.ws/introduction/flows.html#actions and scroll down a bit for the table.

Oh, thanks! I've seen that table probably 10 times now, you'd think I would have noticed onhand vs accounting.

> But, I'm thinking about what if those two fields are starting from a different point and being used for a manual inventory count correction. And same condition for if this is for a beginning balance for a new system. There might be some gotchas involved, but for now, let's just say that they apply to both fields, and that in general you can follow the table.

Ok, I'll follow this guidance.

> That data is also part of Action (recently improved), so you can drive it from the Action data rather than write logic for it.

Is this `vf:onhandEffect` you're talking about? That definitely helps, thanks. Also [this looks handy too](https://github.com/valueflows/valueflows/commit/9725b524f0fd32a56db7975e8b3b6ded2365a637#diff-a5832671e1376b69e3b7f7fb50526009), I'm glad about this. Are those optional fields or required?

> except in that it happens when the event that creates the resource is created. But maybe that is what you are using it for...

Pretty much. Because events themselves don't carry the information, it would need to happen beforehand. Effectively you can create a blank resource that the event operates on. That said, the create/update cannot affect any fields the event directly affects, and delete is really just a marker for "this resource is no longer used" and can only happen when all counts are 0 (effectively the blank state).

> Placeholder: I have to go back and look at this again. This was for pass/fail on testing processes, but we got rid of those as actions. So I need to get my head back into that thought process and then answer.

Cool, I'll just leave out the state field for now!

> I just meant that data wasn't part of the event itself.

Gotcha, thanks!

**Comment by fosterlynn** [comment]
>Also this looks handy too, I'm glad about this. Are those optional fields or required?

Optional.

>delete is really just a marker for "this resource is no longer used" and can only happen when all counts are 0 (effectively the blank state).

Except you need enough of a record to be there to maintain referential integrity, in case older event or commitment or whatever data is accessed and needs the resource it references.  Not sure how your stuff works...

>Cool, I'll just leave out the state field for now!

Yeah....

**Comment by orthecreedence** [comment]
> Optional.

Thanks, I'll note this in vf_rs!

> Except you need enough of a record to be there to maintain referential integrity, in case older event or commitment or whatever data is accessed and needs the resource it references. Not sure how your stuff works...

Oh, I should have mentioned that all deletes are "soft" and the records remain. I guess it could be thought of as "archived" instead.

**Comment by fosterlynn** [comment]
>>Placeholder: I have to go back and look at state again. This was for pass/fail on testing processes, but we got rid of those as actions. So I need to get my head back into that thought process and then answer.

>Cool, I'll just leave out the state field for now!

OK, I got my memory jogged.  We removed the pass/fail actions, and made state a string so people can use it any way they like.  Some people might want state to be part of the logical identifier, so that they could have a resource of widget X and another resource of widget X that failed QT and is in a rework process, or whatever.  I'll edit the above comments where it matters.

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/valueflows/-/issues/637.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
