### ISSUE TITLE
Use of owl:unionOf

### ISSUE THREAD

**Issue by fosterlynn** [valueflows/valueflows#642]
This seems to not be working in our LODE spec generator (needs more exacting investigation, but that's my suspicion of missing properties of classes).  And I saw a reference in some issue in LODE to the "awkward" use of owl:unionOf.  So this issue is to remember to investigate unionOf more thoroughly to see if it is the best way to specify a property that is the domain of more than one class, but shouldn't create any inferences about that set of classes in relation to each other.  And if it seems to be the best way, to discuss it with LODE.  If not, to fix it.

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/valueflows/-/issues/642.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
