### ISSUE TITLE
Stage and state need more work

### ISSUE THREAD

**Issue by bhaugen** [valueflows/valueflows#643]
I'll discuss **stage** first, and then discuss **state** in a separate comment below.

The object property [stage](http://150.146.207.114/lode/extract?owlapi=true&url=https://raw.githubusercontent.com/valueflows/valueflows/master/release-doc-in-process/all_vf.TTL#d4e1597) is applied to a vf:EconomicResource and references a vf:ProcessSpecification.

Its description says
> References the ProcessSpecification of the last process the economic resource went through. Stage is used when the last process is important for finding proper resources, such as where the publishing process wants only documents that have gone through the editing process.

The property **stage** was motivated by use cases where the same EconomicResource is both an input to and output from a process; especially when the same resource goes through a series of processes.

Common examples include bread dough, which can go through several stages of mixing, rising, and kneading until it is ready to bake. Another example is document translations, as mentioned in the **stage** description, which can go through several stages of translation, proofreading, editing, and preparing for publication.

What I think is missing is any way in VF to specify which stage is required for an particular process, for example, to specify that "the publishing process wants only documents that have gone through the editing process".

The logic of stages was prototyped in [NRP, aka ValueNetwork software](https://github.com/valnet/valuenetwork), where the specification of what stage of a resource is wanted by a particular process was implemented in the NRP equivalents of input vf:RecipeFlow and vf:Commitment as an input to a vf:Process. 

**Stage** was used in generating plans from recipes, in the netting method, where the plan generation looks for existing resources that can satisfy an input requirement, and also in selection lists in forms for entering which resources were the actual inputs to a process, so that if a particular stage was required, only resources with that stage would be selected.

But neither vf:RecipeFlow nor vf:Commitment have a **stage** property. I think those would be the appropriate places to specify what resource stage is wanted by a process, but they can't do it, as far as I can tell.

**Comment by bhaugen** [comment]
The object property [**state**](http://150.146.207.114/lode/extract?owlapi=true&url=https://raw.githubusercontent.com/valueflows/valueflows/master/release-doc-in-process/all_vf.TTL#d4e1615) is also applied to a vf:EconomicResource and has some similar behavior to **stage**, but it is a plain string, and its value can be anything you want, although some agreements on state values would be useful inside an economic network.

The description of **state** says 
> The state of the desired economic resource, after coming out of a test or review process.

Quality control tests were the motivating use case for **state**, where a resource might come out of a testing process in a state of "pass" or "fail". Similar to **stage**, subsequent processes might resources in a particular **state**:  a rework process might want resources in a "fail" **state**, while a production process might want resources that have a "pass" **state**.

**State** was also prototyped in NRP, and was also  implemented in the NRP equivalents of input vf:RecipeFlow and vf:Commitment as an input to a vf:Process.

And **state** was used in planning from recipes and selecting inputs to processes in entry forms similar to **stage**.

But neither vf:RecipeFlow nor vf:Commitment have a **state** property, and like **stage**, probably should have them.

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/valueflows/-/issues/643.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
