### ISSUE TITLE
How should adaptations from different contexts make it back into VF? 

### ISSUE THREAD

**Issue by bhaugen** [valueflows/valueflows#644]
This issue emerged from a question from @fkleedorfer in https://github.com/valueflows/valueflows/issues/636#issuecomment-641810339

VF emerged from a long series of participatory action research projects and now is going back into new projects which are deliberately using VF. We (me and @fosterlynn , anyway) see this as a spiral, learning from particular experiments, summarizing into more-general conclusions (making it back into VF), and then going back into practice (more particular experiments).

Some experiments will want to change or extend the vocabulary and model. Some of those changes might be accepted into VF as-is, and some might want to be listed or linked in the VF repositories as extensions or variations that might be useful for more than the original context.

For example, the [Data Food Consortium](https://datafoodconsortium.gitbook.io/dfc-standard-documentation/) has developed a vocabulary that can be mapped to and from ValueFlows. It would seem possible for a project to merge those vocabularies into something new that could be used in a data food context and also connect to other kinds of economic activities that could occur in the same economic network. I'm not sure what to call it: a fork, a mixin, a merger, or what. It would probably want to live in its own repository but link back to ValueFlows and DataFood. How would they handle upstream changes? I don't know. But I could foresee things like that happening and being useful, for example, for community economic systems.

I don't think I am anywhere near done with this issue yet. Looking for a better word for extensions and variations and mergers that would have their own repos but also be mentioned in VF as stuff you could use. And maybe other variations on the theme of how to bring back good ideas from the wild...;-)

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/valueflows/-/issues/644.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
