### ISSUE TITLE
Next steps 2015-10-15

### ISSUE THREAD

**Issue by bhaugen** [valueflows/valueflows#68]
Question asked in https://github.com/valueflows/valueflows/issues/55#issuecomment-148491552

I tried a feeble answer, but hope other people will help. And the answer might depend on where you are coming from.

For example, for the active participants in the project, we are focused on getting the first cross-project connections up and running, using the agent-organization vocab. You might fit nicely into that. My personal want is for the stuff that @fosterlynn is putting out from NRP instances to be visualized in Holodex. And we got at least one nagging technical issue to solve. We have a meeting next Tuesday, which all are welcome to attend.

For the project's external relationships, Lynn and I have been trying to get representatives from some other networks to join up: for example, the Mutual Aid Network, where we have at least a verbal commitment to help with the intents vocab.

For the 'collaborative software consortium', your guess is better than mine.

The Impact Economy participants are figuring out what they do next, which may or may not intersect with ValueFlows.

For people who have not yet joined the project, please jump in and we'll figure it out.

**Comment by fosterlynn** [comment]
@Connoropolous @bhaugen and all.  My top of the head thoughts on next steps, and hoping others have more ideas too.  This isn't in slide format or anything, would need to be really boiled down.  Also isn't necessarily single threaded, lots of this can happen in parallel.  Anyhow:

1. Main focus now should be completing one cycle of LOD, as we discussed our last hangout. This includes: agreement on a core agent vocab; write and test at least two data pushers; and at least one data puller.  Document it all.  This gets us to where we know that we can get the whole thing working, and basically how to do it.

2. Get the results of 1. out to others for review: PLP gang, Wezer, maybe W3C, anyone else who might have an interest and especially be working on an app that would want to use the vocab.  Make changes as appropriate.

3. Get our supporting project infrastructure, like website and website generation, @context generation, project visuals, etc., working well enough so the project is basically there for people to understand and start to use.  (A lot of that is done, although there are a couple missing links, and it may need to be enhanced when we have some stable stuff and some stuff in process - like will it need versions?)

4. Keep trucking..... to the vocab for the next subject area or areas, wherever we decide to go next.  Use our experience from Agent work to refine our internal processes for this.  I think that once we have one cycle under our belt, we could handle more than one at a time if we want to.  Then keep trucking some more....

5. Continue to get the word out to people who might want to help on any front.

6. Continue networking, and collaborating if it makes sense, with other next-economy software infrastructure groups that are pulling their oars in the same direction.  Like the groups possibly forming out of the SF Enspiral gathering and out of Impact Economy summit.....

**Comment by Connoropolous** [comment]
Thanks @fosterlynn 

I really like your #1 point, and for #6 I will continue to be working to act as a bridge for the various conversations which it is overwhelming, and unnecessary for everyone to have to do. I have invited @bortseb to help me in this task of sense-making and making the whole wider conversation ever more fluid and aligned. Even if that just means improving the sense that there are "parallel tracks" being worked on, and mutual awareness of future moments of intersection

**Comment by fosterlynn** [comment]
@Connoropolous and @bortseb cool!

**Comment by fosterlynn** [comment]
Assuming @Connoropolous got what he needed; and we are getting beyond this in our planning.  So closing.
