### ISSUE TITLE
Finishing context creation

### ISSUE THREAD

**Issue by fosterlynn** [valueflows/valueflows#77]
I know @ahdinosaur and @elf-pavlik have worked on this, or at least understand how we want to do it.  I'm wondering if we could get that working so we can have one combined context to actually use.  (I'm trying to get my jsonld data to work round trip, and I think that might be an issue.)

Apologies for asking you to do work!  (I haven't the slightest idea how to do it.....)

If you disagree, or just personally don't want to do it in the near term, just let me know!  And thanks!!

Or maybe it is done, and I just don't know how to use it, if so, cool!

**Comment by ahdinosaur** [comment]
@fosterlynn so are you asking for a single context, merged from all our sub-vocab contexts, available at <https://valueflo.ws>?

i'd like to take care of this, as it's part of https://github.com/valueflows/valueflo.ws/issues/10.

@elf-pavlik anything i know about when doing this? my immediate plan would be to script a naive merge of all the `@context` and `@graph` properties from the sub-vocab context files into a single context file.

**Comment by fosterlynn** [comment]
>@fosterlynn so are you asking for a single context, merged from all our sub-vocab contexts, 

Yup!  

>available at https://valueflo.ws?

Available wherever it's supposed to be available, I guess.  I'm not so clear on the where.

>i'd like to take care of this, as it's part of valueflows/valueflo.ws#10.

Extremely awesome!

**Comment by ahdinosaur** [comment]
oops, meant available at <https://w3id.org/valueflows/>.

**Comment by ahdinosaur** [comment]
[built a naive context file](https://github.com/valueflows/valueflo.ws/commit/d30ebd032dc02b5ca11b0f971980c5d7e27ece49), hosted by [our server](https://github.com/valueflows/valueflo.ws/blob/master/server.js):

```sh
curl -L 'https://valueflo.ws/ns/index.jsonld'
```

i updated the [Enspiral agents](http://json-ld.org/playground/#startTab=tab-expanded&json-ld=https%3A%2F%2Frawgit.com%2Fvalueflows%2Fagent%2Fmaster%2Fexamples%2Fenspiral.jsonld) example to use the above link, so it seems to work. :)

the next step for this is probably content negotation for the static files as @elf-pavlik describes [here](https://github.com/valueflows/valueflo.ws/issues/10#issuecomment-149536977).

**Comment by fosterlynn** [comment]
@ahdinosaur thanks very much!!! :smile: 

Looks good to me visually, I'll try it in my code also.....

No rush for the content negotiated version from my side, although I guess it would be one less thing we have to go back and change... but that doesn't make it a rush... :smile:

**Comment by elf-pavlik** [comment]
@ahdinosaur awesome!

1) We could move it to https://valueflo.ws/index.jsonld
2) In next [PR to w3id.org](https://github.com/valueflows/w3id.org) we can
 * change to https
 * redirect `^\/$ to https://valueflo.ws/index.jsonld
 * redirect `^\/(.*)$` https://valueflo.ws/ns/$1

This way we can leave content negotiation for later and already use simply
`"@context": " https://w3id.org/valueflows/"`

we could ping @almereyda to help us with checking mentioned apache rules 

BTW it looks like you don't include yet
* https://github.com/valueflows/resource/blob/master/context.jsonld
* https://github.com/valueflows/process/blob/master/context.jsonld

**Comment by fosterlynn** [comment]
@elf-pavlik @ahdinosaur I leave those technical details to y'all, with hearty thanks! :smile:

**Comment by fosterlynn** [comment]
@ahdinosaur I see a nice context from the link you provided: https://valueflo.ws/ns/index.jsonld

I'm not clear what to use as the prefix when constructing jsonld, like here:
```
    context = {
        "vf": "https://valueflo.ws/ns/index.jsonld",
        "owl": "http://www.w3.org/2002/07/owl#",
        "rdf": "http://www.w3.org/1999/02/22-rdf-syntax-ns#", ......
```
@elf-pavlik Clearly the vf there is wrong.  What would be the correct thing to use there?  Thanks!

**Comment by elf-pavlik** [comment]
@fosterlynn `"vf": "https://w3id.org/valueflows/"`

**Comment by fosterlynn** [comment]
@elf-pavlik thanks! Should that work now, or not until we have the re-directs etc. in place?  In any case, I just put that in my code.

Note I tried https://w3id.org/valueflows/Person and https://valueflo.ws/ns/Person and neither gave me anything from the browser address bar, and still don't.  Thus the question.  But maybe I'm doing this wrong?

**Comment by elf-pavlik** [comment]
valueflo.ws still needs some work, but @ahdinosaur takes a good care of it!

We can already use ` "vf": "https://w3id.org/valueflows/"` in the context and take our time to fix redirects and provide HTML pages or JSON-LD on requests. You don't do anything wrong :relieved:

**Comment by ahdinosaur** [comment]
@elf-pavlik what's the rationale for moving `index.jsonld` into the root directory? related to https://github.com/valueflows/valueflo.ws/issues/7.

**Comment by elf-pavlik** [comment]
People shouldn't rely on it staying in this location, we just use it for now as temporary location before we setup content negotiation. Everything we put in /ns/ I think we should keep stable and make sure it doesn't change, even that we use https://w3id.org/valueflows/ as the official stable namespace.

**Comment by fosterlynn** [comment]
Thanks guys!  Clarification: I'm going to start working on the data get/gathering side soon, and want to be able to reference a context that works in all of the code, or I don't think the get will work.  I don't care at the moment if it is the final resting place, although of course that would be even better.

**Comment by elf-pavlik** [comment]
Let's use already `"@context": "https://w3id.org/valueflows/"`, I can prepare PR to w3id.org

**Comment by fosterlynn** [comment]
@elf-pavlik excellent!!

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/valueflows/-/issues/77.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
