### ISSUE TITLE
Participation in developer consortium?

### ISSUE THREAD

**Issue by fosterlynn** [valueflows/valueflows#78]
I've posted this idea several places, you all probably got it somewhere.... but just in case..... :)

It feels right now like there is some momentum building for getting developers and projects together for infrastructure work for next economy or solidarity economy or solidarity non-economic infrastructure, etc..... valueflows being a big part of this!

Another one is a new tech workgroup coming out of the Impact Economy summit in BC (http://www.impacteconomy.io/). It comes out of media and fundraising, but several of us are determined that it will be a broad consortium to make this stuff happen, and not fall under any fundraising or other umbrella.

Also triggered by @elf-pavlik thoughts on collaborative fundraising somewhere else in this project.

Some starting thoughts:

I think it would be really helpful to create a list and eventually a technical architectural diagram of some sort to depict all the pieces of software and how they fit into the picture. Possible data to include (for discussion):

*    Functionality - maybe with some categorization or tagging?
*    Software layer - like Ethereum is a different layer than Loomio for example
*    What kind of users it supports
*    What kind of operability or integration it supports; or could support
*    Source software
*    Website or contact info
*    State of the software: running code, users, etc.; or in development

Information that could be gleaned:

*  For a group looking for software, what is available, how ready is it
*    For developers, what can we be collaborating on instead of working on the same problem separately
*    For developers, where are gaps that should be filled with new software
*    For developers looking for funding, where are opportunities for joint funding rather than competing for the same funds

Potential principles (for group discussion):

*    Software is open source
*    People are interested in collaborating for a greater ecosystem, not promoting their software as a product over others
*    ??

**Comment by gcassel** [comment]
I commented here  https://www.loomio.org/d/talTfv3k/re-invigorating-the-open-apps-ecosystem#comment-833024   
-- I understand and appreciate the cross-posting; thanks Lynn.   Recommend that people here follow the Loomio group too.

**Comment by fosterlynn** [comment]
There has been a fair amount of discussion in different venues, so I decided to go ahead and start a new loomio group to accommodate this broader discussion.  It is meant to be a neutral space where people from different groups can discuss where to go from here, and then we can move to whatever venues that is.  Please ask for an invitation if you want to participate!!  Or just reply here or to me if you want help getting connected. 

https://www.loomio.org/g/t2MDNapk/neutral-discussion-space

**Comment by fosterlynn** [comment]
Closing. Neutral discussion space largely superceded by the Hylo CTA group.
