### ISSUE TITLE
No 'Access-Control-Allow-Origin' header causes error in Linked Data Browser

### ISSUE THREAD

**Issue by bhaugen** [valueflows/valueflows#83]
We tried NRP jsonld error in @ahdinosaur 's Linked Data Browser

http://dinosaur.is/linked-data-browser/?focusId=http%3A%2F%2Fnrp.webfactional.com%2Faccounting%2Fagent-jsonld%2F

focus @id:
http://nrp.webfactional.com/accounting/agent-jsonld/

we get this error:
```
Fetch API cannot load http://nrp.webfactional.com/accounting/agent-jsonld/. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://dinosaur.is' is therefore not allowed access.
```

We'll add the required header. This issue is just to record the requirement. This is *not* a bug in the Linked Data Browser, just in the NRP jsonld feed. (Or so I think...)

**Comment by bhaugen** [comment]
@ahdinosaur - how do you get away with this re https://rawgit.com/valueflows/agent/master/examples/enspiral.jsonld ? I don't see any header there, either. 

P.S. looks like this might be what we need to do:
https://github.com/ottoyiu/django-cors-headers

@ahdinosaur @fosterlynn does this make sense to you, or is there a simpler method? I plead ignorance on this topic, but it looks like something we need to do post-haste for what we want to do here...

**Comment by ahdinosaur** [comment]
yeah nah, this is expected. [CORS](http://www.w3.org/wiki/CORS_Enabled#What_is_CORS_about.3F) headers are necessary for a browser to communicate with a server at a different domain then where the page was loaded.

with `curl -iL "https://rawgit.com/valueflows/agent/master/examples/enspiral.jsonld"`, i see `Access-Control-Allow-Origin: *` in the headers. [rawgit.com](https://rawgit.com) seems to add the proper CORS headers, as opposed to [raw.githubusercontent](https://raw.githubusercontent.com/).

[here's a resource on how to enable CORS on servers](http://enable-cors.org/server.html). for example, [here's how i added CORS support to our valueflo.ws `http` server](https://github.com/valueflows/valueflo.ws/commit/7174d32702e3f91d2d9fc3dc0d04bbaf83b52a38).

**Comment by bhaugen** [comment]
@ahdinosaur - you're right, I was thinking stupidly about it. I think that django app will do it for us, but we'll see.

**Comment by bhaugen** [comment]
Yay! It works now!
http://dinosaur.is/?focusId=http%3A%2F%2Fnrp.webfactional.com%2Fapi%2Fagent-jsonld%2F&viewId=nodeList

@ahdinosaur and all: note that the URL has changed. I moved all the jsonld stuff under /api/ instead of /accounting/
