### ISSUE TITLE
Get a list of offers

### ISSUE THREAD

**Issue by pmackay** [valueflows/valueflows#88]
As a user I can get a list of offers, so I know what products and services I could make use of.

---

http://schema.org/Offer is a pretty comprehensive set of properties related to an offer (schema.org doesnt seem to have a matching Want). Would there be overlaps with what https://github.com/valueflows/exchange could develop?

**Comment by bhaugen** [comment]
We intend to work on Offers and Wants and their matching in the [Intent repo](https://github.com/valueflows/intent). They are also used a lot in Mutual Aid and Mutual Credit networks, which we are gathering input from.

**Comment by fosterlynn** [comment]
@pmackay good user stories.  Should we collect them somewhere in the wiki, or keep as issues?  I guess as issues, we can mark them closed when they work.  But in the wiki they live on.

**Comment by pmackay** [comment]
Are you suggesting issues should all be raised there if related to that? What about cross cutting ones? Or are general stories OK here? 

I'm just testing this out to see what works best :)

**Comment by bhaugen** [comment]
I think it's fine to start as issues where we can discuss them, and then move them to the wiki when they are fully digested. With links to implementations if such exist.

**Comment by fosterlynn** [comment]
@pmackay I think it best if issues related to offers and wants go in the Intent repo.  (Possibly needs a better name if it isn't clear?)  And cross-cutting ones here.  Just my opinion, feel free to keep taking initiative, we're all feeling our way here!
