### ISSUE TITLE
Broken bike give away issues

### ISSUE THREAD

**Issue by pmackay** [valueflows/valueflows#94]
About this use case https://github.com/valueflows/valueflows/blob/master/use-cases/circular-economy/broken-bike-give-away.md, as @elf-pavlik rightly pointed out, there is a useful distinction between the Freecycle group Agent and the medium used to exchange info about things. Does the current entities now look better? 

One of the other aspects of this that I'm still puzzling over is the need to define more specific models for different things and how much that could use existing models? E.g. could the [Organisation](http://schema.org/Organization) and [ContactPoint](http://schema.org/ContactPoint) schema.org models be used to define a Freecycle group and its online presence? If not, what are the problems/concerns?

**Comment by fosterlynn** [comment]
@pmackay I like the way you have delineated the agents, resource types and resources now.

In terms of the resource flows, the first 3 are more like intents or commitments to do resource flows and a conversation for action to get there.  I don't feel personally like I have head space to get into intents by myself, although I'd be happy to do so with people who have worked more in that space.  I'd like to ping a bunch of them at some point and see if we can initiate a discussion, but hesitate to do it now, maybe after the holidays....

The other interesting piece of this use case is John giving Alice the bike - we have had a bunch of discussion on ownership (conceptual thing) vs. possession or location of a resource (concrete).  And what of this is a transfer and what is something else.  This stuff not resolved.  Ref. #81 

>One of the other aspects of this that I'm still puzzling over is the need to define more specific models for different things and how much that could use existing models?

Yeah, ongoing puzzlement.  Here's a LONG example of an earlier similar discussion around types of agents and types of agent relationships. https://github.com/valueflows/agent/issues/38  Not resolved but I feel we will get to a common understanding as we continue to work through these subject areas.  We did get to where we think we can define a small set of subclasses with some specific meanings as to behavior, and then let people either use other vocabularies' subclasses or create their own as subclasses of our defined ones.  But we didn't get them actually defined.  Yet. :)

**Comment by pmackay** [comment]
>the first 3 are more like intents or commitments to do resource flows and a conversation for action to get there.
Yes, see what you mean. Would it make sense with these use cases to have a separate Intents section? Appreciate this might be lower priority, but worth separating out?

**Comment by elf-pavlik** [comment]
@pmackay I think [Bike](https://github.com/valueflows/valueflows/blob/master/use-cases/circular-economy/broken-bike-give-away.md) use case could build around [vf:Offer](https://github.com/valueflows/intent/blob/master/Offer.md) leading to [vf:Transfer](https://github.com/valueflows/exchange/blob/master/Transfer.md).

Do you need to capture the physical delivery of the actual bike?
* John delivers it to Alice
* Alice picks it up from John
* John and Alice meet somewhere
* 3rd person picks it up from John and delivers it to Alice

**Comment by pmackay** [comment]
I guess this all depends on what needs modelling. My general goals with the circular economy stuff was to capture intents, to be able to describe them to people. Transfers could also be important for metrics gathering. 

Is that level of detail needed do you think, of transfer mechanism?

**Comment by elf-pavlik** [comment]
> Is that level of detail needed do you think, of transfer mechanism?

If you don't care about where the actual bike stays located, you may safety ignore the transportation information.

When it comes to intents, I think agreement on transportation may matter. Especially if someone has a broken bike in a basement and recycling centre can only get it if they arrange picking it up. Some recycling centres might require to drop it off.

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/valueflows/-/issues/94.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
