### ISSUE TITLE
Circular economy as focus for VF?

### ISSUE THREAD

**Issue by fosterlynn** [valueflows/valueflows#97]
I am thinking about @pmackay 's and @djwesto 's work with the circular economy.  I like focusing on these use cases because 1) I think that's where we need to go in all economic work ultimately; and 2) it will challenge the model to be as complete as possible because it creates cycles, which are more difficult to work with in directed graphs.  ( @bhaugen has more experience in dealing with cycles in the logic of following value flows, so he can explain this better than I can, if needed.)

So this issue is to start a discussion / brainstorming / get people's thoughts.  

And at some point (if you're willing, Paul and Chris), I'd be very interested to hear more about what you have going in your local work and if/how it might make sense to use that in developing VF, and if that VF work can help develop what you are doing now.  (I know you are trying to figure that out, and I feel like I haven't understood enough to be necessarily on target.  And I haven't even looked at what you have in code now, which I am willing to do if it would be helpful and if you can give some direction into the code.  And no worries if this is premature or otherwise unwelcome, let us know and I'll back off!)

**Comment by pmackay** [comment]
@fosterlynn thanks very much for posting this and other discussions! We're still quite early so I'll come back to this when I have more specifics I could add :)

**Comment by fosterlynn** [comment]
@pmackay cool, no worries! :)

**Comment by elf-pavlik** [comment]
:+1: to emphasis on circular economy

I would like that everyone can have possibility to make it a major factor in evaluating discovered offers #118

**Comment by bhaugen** [comment]
Where's @pmackay ? It's good to have people around who are immersed in the domain.

**Comment by elf-pavlik** [comment]
I would like in our examples, wherever we describe producing something that needs to get recycled later, to already create responsibility, commitment, planned service for that recycling. Once ownership over material resource gets transferred, also the responsibility for recycling it would get transferred or stay with manufacturer.

**Comment by pmackay** [comment]
>to already create responsibility, commitment, planned service for that recycling

Is this something that is possible with where the VF spec has got to so far, @elf-pavlik, or more a future intention?

**Comment by bhaugen** [comment]
Near-future intention. @pmackay you could help if you had some good examples we could work from.

**Comment by elf-pavlik** [comment]
We had quite a bit of conversations about agent <-> resource relationships. Just with that we could define for example 3 relationships in lines of: *creator*, *maintainer*, *destroyer* (bit like [Trimuti](https://en.wikipedia.org/wiki/Trimurti)).

We also touched possibility of 'planned resources' which already can have various relationships to agents and planned processes. If the 'destruction/transformation' of certain resource requires some more specific service, the existing resource could already reference planned process which provides that planned service.

Currently I would prefer to focus on 0.0 milestone and try to narrow the scope for it so that we can have less moving pieces and reach more consensus withing this narrower scope. Comment about just served as big 👍 to always keeping 'circular economy' in mind. Maybe we should even add it to https://github.com/valueflows/valueflows/blob/master/PRINCIPLES.md

**Comment by bhaugen** [comment]
>  Maybe we should even add it to https://github.com/valueflows/valueflows/blob/master/PRINCIPLES.md

Yes, please do.

**Comment by fosterlynn** [comment]
I added it, please improve if you feel the need.

**Comment by pmackay** [comment]
@fosterlynn looks good :)

**Comment by TiberiusB** [comment]
We discussed re-production and care at DeepDive:rethinking value. These
seem to be two theams that will drive medium-term development.

I see recycling or the circular economy as tied into that. We need to move
away from production, as linear process. We need to think of economic
systems as regenerative systems, systems that recreate themselves at every
step of the way, that contain mechanisms to maintain themselves. We also
nee to include the underlying support structures in our thinking about the
economy, to have reproduction, education, health, etc., not as
externalities. This last idea is a feminist idea.

I am going to introduce some of these insights to Sensorica to see how they
can be integrated into the OVN model.

**Comment by bhaugen** [comment]
> We also nee to include the underlying support structures in our thinking
about the economy, to have reproduction, education, health, etc., not as
externalities. This last idea is a feminist idea.

Yes! If you get some use cases going in Sensorica or wherever, please start another thread here on one or all of those topics. Or ping me about a Sensorica use case and I'll add it here.

**Comment by bhaugen** [comment]
Does this overlap? https://github.com/schemaorg/schemaorg/issues/1337

(See also [the list of equivalencies in this comment on that issue](https://github.com/schemaorg/schemaorg/issues/1337#issuecomment-244339641))

**Comment by pmackay** [comment]
@bhaugen thanks! (apols for late reply, been away) 

The waste management models are useful, definite overlaps with the [specs I developed](http://communitiesuk.github.io/waste-service-standards/models/index.html) on a project that finished in March. More fields on their container model but less models overall.

And yes worth looking at the Civic extension stuff. How important/useful are schema.org types to VF though? I guess a general mapping similar to that list of equivalent types?

**Comment by bhaugen** [comment]
> How important/useful are schema.org types to VF though? I guess a general mapping similar to that list of equivalent types?

@elf-pavlik @fosterlynn as you get closer to a "release", where are we at on using other vocabs in general, and schema.org in particular?

**Comment by bhaugen** [comment]
> the [specs I developed](http://communitiesuk.github.io/waste-service-standards/models/index.html) on a project that finished in March. 

We should try to map that to VF, too.

**Comment by elf-pavlik** [comment]
https://www.valueflo.ws/introduction/principles.html already includes

> The model must be able to support circular economies, value flows where resources come full cycle to be fed into the same set or other processes so that recycling, re-use, and other ways to encourage resources not becoming waste.
